import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase.js'
import {canAccessModule,isReadOnlyRole,moduleFromOpenDetail,ROLE_LABEL} from './erp-access-control.js'

const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const MUTATION_WORDS=['guardar','crear','nuevo','nueva','agregar','añadir','eliminar','borrar','anular','revocar','autorizar','aprobar','rechazar','emitir','facturar','cobrar','pagar','registrar','actualizar','editar','modificar','enviar invitación','procesar']
const SAFE_WORDS=['cerrar','volver','cancelar','buscar','filtrar','ver','detalle','detalles','actualizar lista','refrescar','descargar','imprimir']
const deniedCache=new Map()

export default function AccessControlRuntime(){
 const [access,setAccess]=useState({role:'',session:null,companyId:''})
 const {role,session,companyId}=access
 useEffect(()=>{let live=true;if(!supabase)return;const applySession=async next=>{if(!next){if(live)setAccess({role:'',session:null,companyId:''});return}const {data,error}=await supabase.from('company_members').select('company_id,role').eq('user_id',next.user.id).limit(1).maybeSingle();if(live&&!error)setAccess({role:String(data?.role||'').toLowerCase(),session:next,companyId:String(data?.company_id||'')})};supabase.auth.getSession().then(({data})=>applySession(data.session));const {data:l}=supabase.auth.onAuthStateChange((_event,next)=>{void applySession(next)});return()=>{live=false;l.subscription.unsubscribe()}},[])
 useEffect(()=>{if(!role)return;const guardOpen=e=>{const module=moduleFromOpenDetail(e.detail||{});if(!module||canAccessModule(role,module))return;e.stopImmediatePropagation();e.preventDefault?.();const message=`Acceso restringido: ${ROLE_LABEL[role]||role} no tiene permiso para ${module}.`;notify(message);void logDenied({session,companyId,module,reason:message,action:'ACCESS_DENIED'})};const guardChange=e=>{const module=typeof e.detail==='string'?e.detail:null;if(!module||canAccessModule(role,module))return;e.stopImmediatePropagation();e.preventDefault?.();const message=`Acceso restringido: ${ROLE_LABEL[role]||role} no tiene permiso para ${module}.`;notify(message);void logDenied({session,companyId,module,reason:message,action:'ACCESS_DENIED'})};window.addEventListener('idealo-open-module',guardOpen,true);window.addEventListener('idealo-module-change',guardChange,true);return()=>{window.removeEventListener('idealo-open-module',guardOpen,true);window.removeEventListener('idealo-module-change',guardChange,true)}},[role,session?.access_token,companyId])
 useEffect(()=>{if(!role)return;document.documentElement.dataset.erpRole=role;if(!isReadOnlyRole(role))return()=>{delete document.documentElement.dataset.erpRole};const block=reason=>{notify(reason);void logDenied({session,companyId,module:'ERP',reason,action:'READ_ONLY_BLOCKED'})};const onSubmit=e=>{if(!insideErp(e.target))return;e.preventDefault();e.stopImmediatePropagation();block('Modo Solo lectura: no podés guardar ni modificar información.')};const onClick=e=>{const button=e.target.closest?.('button,[role="button"]');if(!button||!insideErp(button)||button.closest('.idealo-main-menu'))return;const text=(button.innerText||button.getAttribute('aria-label')||'').trim().toLowerCase();if(!text||SAFE_WORDS.some(x=>text.includes(x)))return;if(MUTATION_WORDS.some(x=>text.includes(x))){e.preventDefault();e.stopImmediatePropagation();block(`Modo Solo lectura: la acción "${text.slice(0,80)}" requiere permiso de edición.`)}};document.addEventListener('submit',onSubmit,true);document.addEventListener('click',onClick,true);return()=>{delete document.documentElement.dataset.erpRole;document.removeEventListener('submit',onSubmit,true);document.removeEventListener('click',onClick,true)}},[role,session?.access_token,companyId])
 return null
}
function insideErp(node){return Boolean(node?.closest?.('.erp-shell,.erp-modal-panel,.clients-module,.invoice-form,.admin-users-panel'))}
async function logDenied({session,companyId,module,reason,action}){if(!API||!session?.access_token||!companyId)return;const key=`${action}:${module}:${reason}`;const now=Date.now();if(now-(deniedCache.get(key)||0)<10000)return;deniedCache.set(key,now);try{await fetch(`${API}/api/security/audit`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({company_id:companyId,action,module,reason,control:'frontend_role_guard'})})}catch{}}
function notify(message){window.dispatchEvent(new CustomEvent('idealo-access-denied',{detail:{message}}));let box=document.getElementById('idealo-access-toast');if(!box){box=document.createElement('div');box.id='idealo-access-toast';box.setAttribute('role','status');document.body.appendChild(box)}box.textContent=message;box.classList.add('show');window.clearTimeout(box._t);box._t=window.setTimeout(()=>box.classList.remove('show'),3200)}
