import {useEffect,useMemo,useState} from 'react'
import {supabase} from './lib/supabase.js'

export default function AccountSecurityPanel({session,audit=[]}){
 const [factors,setFactors]=useState([]),[aal,setAal]=useState(null),[setup,setSetup]=useState(null),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const activity=useMemo(()=>audit.filter(x=>x.action==='SESSION_ACTIVE'&&x.actor_user_id===session?.user?.id).slice(0,8),[audit,session?.user?.id])
 const verified=factors.filter(x=>x.status==='verified')
 const load=async()=>{if(!supabase)return;setError('');const [{data:f,error:fe},{data:a,error:ae}]=await Promise.all([supabase.auth.mfa.listFactors(),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);if(fe||ae){setError(fe?.message||ae?.message||'No se pudo consultar la seguridad de la cuenta.');return}setFactors([...(f?.totp||[]),...(f?.phone||[])]);setAal(a||null)}
 useEffect(()=>{load()},[session?.user?.id])
 const start=async()=>{setBusy(true);setMessage('');setError('');try{const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'IDEALO SV'});if(error)throw error;setSetup({id:data.id,qr:data.totp?.qr_code,secret:data.totp?.secret});setCode('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const cancel=async()=>{if(setup?.id)await supabase.auth.mfa.unenroll({factorId:setup.id}).catch(()=>{});setSetup(null);setCode('')}
 const verify=async()=>{if(!setup?.id||code.trim().length<6)return;setBusy(true);setMessage('');setError('');try{const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:setup.id,code:code.trim()});if(error)throw error;setSetup(null);setCode('');setMessage('Autenticación de dos pasos activada. Las otras sesiones anteriores fueron cerradas por seguridad.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const remove=async factor=>{if(!window.confirm('¿Desactivar este método de autenticación de dos pasos?'))return;setBusy(true);setError('');try{const {error}=await supabase.auth.mfa.unenroll({factorId:factor.id});if(error)throw error;setMessage('Método de autenticación eliminado.');await supabase.auth.refreshSession();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const closeOthers=async()=>{if(!window.confirm('¿Cerrar todas las demás sesiones y conservar solamente esta?'))return;setBusy(true);setError('');setMessage('');try{const {error}=await supabase.auth.signOut({scope:'others'});if(error)throw error;setMessage('Las demás sesiones fueron cerradas. Esta sesión continúa activa.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="account-security-advanced">
  {error&&<div className="feedback error">{error}</div>}{message&&<div className="feedback success">{message}</div>}
  <div className="advanced-security-grid">
   <article><div><small>Autenticación de dos pasos</small><strong>{verified.length?'Activada':'No activada'}</strong><p>{verified.length?`${verified.length} método(s) verificado(s). Nivel actual: ${aal?.currentLevel||'—'}.`:'Protegé la cuenta con una aplicación autenticadora.'}</p></div>{verified.length?<button className="btn secondary" onClick={()=>remove(verified[0])} disabled={busy}>Desactivar 2FA</button>:<button className="btn primary" onClick={start} disabled={busy||Boolean(setup)}>Activar 2FA</button>}</article>
   <article><div><small>Sesiones de la cuenta</small><strong>Cierre remoto disponible</strong><p>Cierra los accesos de otros dispositivos sin cerrar esta sesión.</p></div><button className="btn secondary" onClick={closeOthers} disabled={busy}>Cerrar otras sesiones</button></article>
  </div>
  {setup&&<section className="mfa-setup"><div><h4>Configurar aplicación autenticadora</h4><p>Escaneá este código con Google Authenticator, Microsoft Authenticator, 1Password u otra app TOTP. Después escribí el código de 6 dígitos.</p>{setup.qr&&<img src={setup.qr} alt="Código QR para configurar autenticación de dos pasos"/>}<small>Clave manual</small><code>{setup.secret}</code></div><div className="mfa-verify"><label>Código de verificación<input inputMode="numeric" autoComplete="one-time-code" maxLength={8} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label><button className="btn primary" onClick={verify} disabled={busy||code.length<6}>Verificar y activar</button><button className="btn secondary" onClick={cancel} disabled={busy}>Cancelar</button></div></section>}
  <section className="security-devices"><div className="admin-section-head"><div><h4>Actividad reciente de esta cuenta</h4><p>Dispositivos observados por la auditoría del ERP. Una actividad no equivale necesariamente a una sesión distinta.</p></div></div>{activity.length?<div className="security-device-list">{activity.map(row=><article key={row.id}><span>●</span><div><strong>{row.detail?.device||'Dispositivo web'} · {row.detail?.browser||'Navegador'}</strong><small>{new Date(row.created_at).toLocaleString('es-SV')} · IP {row.detail?.ip||'no disponible'}</small></div></article>)}</div>:<div className="empty-state compact"><strong>Sin actividad reciente registrada.</strong></div>}</section>
 </div>
}
