import {useEffect,useMemo,useState} from 'react'
const dateKey=v=>String(v||'').slice(0,10)
const today=()=>new Date().toISOString().slice(0,10)
const addDays=n=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
export default function AgendaControlCenter({company,supabase}){
 const [events,setEvents]=useState([]),[deliveries,setDeliveries]=useState([]),[orders,setOrders]=useState([]),[receivables,setReceivables]=useState([]),[msg,setMsg]=useState('')
 useEffect(()=>{let live=true;(async()=>{const r=await Promise.all([
  supabase.from('production_schedule_events').select('id,event_type,title,scheduled_start,status,priority').eq('company_id',company.id),
  supabase.from('deliveries').select('id,scheduled_at,status,delivery_method').eq('company_id',company.id).not('scheduled_at','is',null),
  supabase.from('work_orders').select('id,due_at,status').eq('company_id',company.id),
  supabase.from('accounts_receivable').select('id,due_date,status,amount_total,amount_paid').eq('company_id',company.id)
 ]);if(!live)return;const e=r.find(x=>x.error)?.error;if(e)setMsg(e.message);else{setEvents(r[0].data||[]);setDeliveries(r[1].data||[]);setOrders(r[2].data||[]);setReceivables(r[3].data||[])}})();return()=>{live=false}},[company.id,supabase])
 const k=useMemo(()=>{const t=today(),next=addDays(7);const overdueOrders=orders.filter(x=>x.due_at&&dateKey(x.due_at)<t&&!['DELIVERED','COMPLETED','CANCELLED'].includes(x.status));const upcoming=events.filter(x=>dateKey(x.scheduled_start)>=t&&dateKey(x.scheduled_start)<=next&&x.status!=='COMPLETED');const urgent=upcoming.filter(x=>x.priority==='URGENT');const deliveries7=deliveries.filter(x=>dateKey(x.scheduled_at)>=t&&dateKey(x.scheduled_at)<=next&&!['DELIVERED','CANCELLED'].includes(x.status));const collections=receivables.filter(x=>x.due_date&&x.due_date>=t&&x.due_date<=next&&!['PAID','CANCELLED'].includes(x.status));const overdueCollections=receivables.filter(x=>x.due_date&&x.due_date<t&&!['PAID','CANCELLED'].includes(x.status));return{overdueOrders,upcoming,urgent,deliveries7,collections,overdueCollections}},[events,deliveries,orders,receivables])
 return <section className="panel"><div className="panel-heading"><div><p className="form-kicker">CONTROL DE AGENDA</p><h3>Próximos 7 días</h3><p>Producción, entregas y cobros que requieren atención.</p></div><span className={k.overdueOrders.length||k.overdueCollections.length?'status dte-pending':'status dte-ready'}>{k.overdueOrders.length+k.overdueCollections.length} vencidos</span></div><div className="metrics-grid"><article className="metric-card"><span>Actividades próximas</span><strong>{k.upcoming.length}</strong><small>{k.urgent.length} urgentes</small></article><article className="metric-card"><span>Entregas</span><strong>{k.deliveries7.length}</strong><small>Próximos 7 días</small></article><article className="metric-card"><span>Cobros por vencer</span><strong>{k.collections.length}</strong><small>{k.overdueCollections.length} ya vencidos</small></article><article className="metric-card"><span>OT atrasadas</span><strong>{k.overdueOrders.length}</strong><small>Requieren reprogramación</small></article></div>{msg&&<p className="feedback error">{msg}</p>}</section>
}
