import { useEffect, useMemo, useState } from 'react'
import QRCode from 'qrcode'
import { billingComplianceMetrics, inspectDte, mhEnvironmentLabel } from './billingCompliance.js'

const apiUrl=import.meta.env.VITE_API_URL||'http://localhost:4000'
const mhConsultUrl='https://portaldgii.mh.gob.sv/ssc/consulta/fe'
const money=(value)=>`$${Number(value||0).toFixed(2)}`
const safe=(value)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))
const statusLabel={DRAFT:'Borrador',SIGNING:'Firmando',SIGNED:'Firmado',TRANSMITTING:'Transmitiendo',PROCESSED:'Procesado',REJECTED:'Rechazado',INVALIDATED:'Invalidado'}
function mhBody(row){return row.mh_response?.body||row.mh_response||{}}
function receiptSeal(row){const mh=mhBody(row);return row.mh_receipt_seal||mh.selloRecibido||mh.sello||''}
function isAccepted(row){return row.status==='PROCESSED'&&Boolean(receiptSeal(row))}
function downloadEvidence(row){if(!isAccepted(row))return;const evidence={schema:'IDEALO-SV-DTE-EVIDENCE-1',exportedAt:new Date().toISOString(),fiscalState:'PROCESSED',environment:row.environment,dteType:row.dte_type,controlNumber:row.control_number,generationCode:String(row.generation_code||'').toUpperCase(),mhReceiptSeal:receiptSeal(row),mhProcessedAt:row.mh_processed_at||mhBody(row).fhProcesamiento||null,dte:row.dte_payload,signedDocument:row.signed_document||null,mhResponse:row.mh_response||null};const blob=new Blob([JSON.stringify(evidence,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${String(row.generation_code||row.control_number||'DTE').toUpperCase()}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
async function openReadableVersion(row,company){if(!isAccepted(row))return;const payload=row.dte_payload||{},id=payload.identificacion||{},emisor=payload.emisor||{},receptor=payload.receptor||{},resumen=payload.resumen||{},items=Array.isArray(payload.cuerpoDocumento)?payload.cuerpoDocumento:[],qr=await QRCode.toDataURL(mhConsultUrl,{errorCorrectionLevel:'M',margin:1,width:190}),popup=window.open('','_blank','width=980,height=900');if(!popup)return;const rows=items.map(item=>`<tr><td>${safe(item.numItem)}</td><td>${safe(item.descripcion)}</td><td>${safe(item.cantidad)}</td><td>${money(item.precioUni)}</td></tr>`).join('');popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${safe(row.control_number)}</title><style>body{font-family:Arial,sans-serif;color:#151515;max-width:900px;margin:30px auto;padding:0 24px}header{border-bottom:4px solid #f97316;padding-bottom:14px}h1{margin:0}.ok{display:inline-block;margin-top:8px;padding:5px 9px;border:1px solid #166534;border-radius:6px}section{border:1px solid #ddd;border-radius:8px;padding:12px;margin-top:12px}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.qr{display:flex;gap:16px;align-items:center}.qr img{width:150px}button{padding:9px 14px}@media print{button{display:none}}</style></head><body><header><h1>IDEALO SV</h1><strong>${row.dte_type==='03'?'Comprobante de Crédito Fiscal DTE-03':'Factura Consumidor Final DTE-01'}</strong><br><span class="ok">ACEPTADO MH</span></header><section><b>Número de control:</b> ${safe(row.control_number)}<br><b>Código de generación:</b> ${safe(String(row.generation_code||id.codigoGeneracion||'').toUpperCase())}<br><b>Sello MH:</b> ${safe(receiptSeal(row))}</section><section><b>Emisor:</b> ${safe(emisor.nombre||company.name)}<br><b>Receptor:</b> ${safe(receptor.nombre||'Consumidor final')}</section><section><table><thead><tr><th>#</th><th>Descripción</th><th>Cant.</th><th>Precio</th></tr></thead><tbody>${rows}</tbody></table><p><b>Total:</b> ${money(resumen.totalPagar??resumen.montoTotalOperacion)}</p></section><section class="qr"><img src="${qr}" alt="QR consulta DTE"><div><b>Consulta oficial MH</b><p>El QR abre el portal oficial de consulta de documentos electrónicos.</p></div></section><button onclick="window.print()">Imprimir / Guardar PDF</button></body></html>`);popup.document.close()}

export default function Billing360Dashboard({supabase,company,onOpenNewInvoice}){
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('ALL')
  const [actionId,setActionId]=useState(''),[actionMessage,setActionMessage]=useState({type:'',text:''})
  const load=async(initial=false)=>{if(refreshing)return;if(initial)setLoading(true);else setRefreshing(true);setError('');try{const {data,error:queryError}=await supabase.from('dte_documents').select('id,dte_type,status,environment,control_number,generation_code,created_at,dte_payload,signed_document,mh_response,mh_receipt_seal,mh_processed_at,mh_message_code,mh_message').eq('company_id',company.id).order('created_at',{ascending:false}).limit(300);if(queryError)throw queryError;setRows(data||[])}catch(cause){setError('No se pudo actualizar el centro fiscal. Conservamos la información anterior.')}finally{setLoading(false);setRefreshing(false)}}
  useEffect(()=>{load(true)},[company.id])
  const stats=useMemo(()=>billingComplianceMetrics(rows),[rows])
  const visible=useMemo(()=>rows.filter(row=>{const c=inspectDte(row);if(filter==='CRITICAL')return c.issues.length>0;if(filter==='PROD')return c.environment==='01';if(filter==='TEST')return c.environment==='00';if(filter==='REJECTED')return row.status==='REJECTED';if(filter==='ACCEPTED')return c.accepted;return true}),[rows,filter])
  const controlled=rows.find(row=>inspectDte(row).environment==='00'&&!['PROCESSED','REJECTED','INVALIDATED'].includes(row.status))
  const apiAction=async(path,documentId)=>{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('La sesión venció. Volvé a iniciar sesión.');const response=await fetch(`${apiUrl}${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({documentId})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||`La operación respondió HTTP ${response.status}.`);return payload}
  const testGmail=async()=>{if(actionId)return;setActionId('gmail-test');setActionMessage({type:'neutral',text:'Probando autenticación y envío real por Gmail…'});try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('La sesión venció. Volvé a iniciar sesión.');const response=await fetch(`${apiUrl}/api/dte/gmail-test`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({companyId:company.id})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||`La prueba respondió HTTP ${response.status}.`);setActionMessage({type:'success',text:`Gmail conectado. Correo de prueba enviado a ${payload.recipient}. No se generó ni transmitió ningún DTE.`})}catch(cause){setActionMessage({type:'error',text:`Prueba de Gmail falló: ${cause.message}`})}finally{setActionId('')}}
  const signControlled=async(row)=>{if(actionId)return;setActionId(row.id);setActionMessage({type:'neutral',text:'Comprobando firmador antes de firmar…'});try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;const diagnosticResponse=await fetch(`${apiUrl}/api/dte/signer-diagnostic?companyId=${encodeURIComponent(company.id)}`,{headers:{Authorization:`Bearer ${token}`}});const diagnostic=await diagnosticResponse.json().catch(()=>({}));if(!diagnosticResponse.ok)throw new Error(diagnostic.message||'No se pudo validar el firmador.');if(!['READY','READY_FOR_SINGLE_RETRY'].includes(diagnostic.overall)||!diagnostic.cryptoSelfTest?.valid)throw new Error('El firmador no está validado. Abrí Hacienda y comprobá certificado/RS512 antes de firmar.');setActionMessage({type:'neutral',text:'Firmando DTE en TEST…'});const result=await apiAction('/api/dte/sign-test',row.id);setActionMessage({type:'success',text:`${result.control_number} firmado con JWS. Todavía no se ha enviado a Hacienda.`});await load(false)}catch(cause){setActionMessage({type:'error',text:`No se firmó: ${cause.message}`})}finally{setActionId('')}}
  const transmitControlled=async(row)=>{if(actionId)return;const confirmed=window.confirm(`PRUEBA CONTROLADA MH TEST\n\nSe enviará UNA VEZ ${row.control_number} al ambiente 00 de Hacienda. Producción permanece bloqueada.\n\n¿Continuar?`);if(!confirmed)return;setActionId(row.id);setActionMessage({type:'neutral',text:'Transmitiendo una sola vez a Hacienda TEST…'});try{const result=await apiAction('/api/dte/transmit-test',row.id);setActionMessage(result.status==='PROCESSED'?{type:'success',text:`PROCESADO por Hacienda TEST: ${result.control_number}. Revisá el sello de recepción en el tablero.`}:{type:'error',text:`Hacienda respondió ${result.status}. No se hará reenvío automático; revisá el mensaje guardado.`});await load(false)}catch(cause){setActionMessage({type:'error',text:`Transmisión detenida: ${cause.message}`});await load(false)}finally{setActionId('')}}
  if(loading)return <section className="billing360"><div className="empty-state"><strong>Preparando centro de facturación…</strong><small>Estamos verificando documentos, estados y evidencia de Hacienda.</small></div></section>
  return <section className="billing360">
    <div className="billing360-head"><div><p className="form-kicker">FACTURACIÓN 360 · CONTROL MH</p><h2>Centro de control fiscal</h2><p>Supervisa identidad DTE, ambiente, respuesta de Hacienda, sello de recepción y coherencia del documento.</p></div><div className="billing360-head-actions"><button type="button" onClick={onOpenNewInvoice} disabled={Boolean(actionId)}>+ Nueva factura</button><button type="button" className="secondary-button" onClick={testGmail} disabled={Boolean(actionId)}>Probar Gmail</button><button type="button" className="secondary-button" onClick={()=>load(false)} disabled={refreshing||Boolean(actionId)}>{refreshing?'Actualizando…':'Actualizar'}</button></div></div>
    {error&&<p className="feedback error" role="status">{error}</p>}{actionMessage.text&&<p className={`feedback ${actionMessage.type==='neutral'?'':actionMessage.type}`} role="status">{actionMessage.text}</p>}
    <div className="billing360-kpis"><Kpi label="DTE registrados" value={stats.total}/><Kpi label="Aceptados con sello" value={stats.accepted}/><Kpi label="Rechazados" value={stats.rejected}/><Kpi label="Pruebas" value={stats.test}/><Kpi label="Producción" value={stats.production}/><Kpi label="Alertas críticas" value={stats.critical}/><Kpi label="Con sello MH" value={stats.withSeal}/><Kpi label="Facturación aceptada" value={money(stats.amountAccepted)}/></div>
    <div className="dte-note"><strong>Control fiscal:</strong> los DTE aceptados quedan protegidos; los rechazados no se reenvían automáticamente. <strong>Producción permanece bloqueada.</strong></div>
    <div className="form-actions" style={{justifyContent:'flex-start',flexWrap:'wrap'}}>{[['ALL','Todos'],['CRITICAL','Alertas'],['ACCEPTED','Aceptados'],['REJECTED','Rechazados'],['TEST','TEST'],['PROD','PRODUCCIÓN']].map(([key,label])=><button type="button" key={key} disabled={refreshing} className={filter===key?'':'secondary-button'} onClick={()=>setFilter(key)}>{label}</button>)}</div>
    <div className="billing360-table-wrap"><table className="billing360-table"><thead><tr><th>Fecha</th><th>Tipo / ambiente</th><th>Identidad DTE</th><th>Estado</th><th>MH</th><th>Cumplimiento</th><th>Total</th><th>Control</th></tr></thead><tbody>{visible.slice(0,50).map(row=>{const check=inspectDte(row),isControlled=controlled?.id===row.id,accepted=isAccepted(row);return <tr key={row.id}><td>{row.created_at?new Date(row.created_at).toLocaleString('es-SV'):'—'}</td><td><strong>DTE-{check.type||'—'}</strong><small>{mhEnvironmentLabel(check.environment)}</small></td><td><strong>{row.control_number||'Pendiente'}</strong><small>{check.generation||'Sin código de generación'}</small></td><td><span className={`billing-status ${String(row.status||'').toLowerCase()}`}>{statusLabel[row.status]||row.status||'—'}</span><small>{check.immutable?'Documento fiscal protegido':'Editable según estado'}</small></td><td>{row.mh_message||row.mh_response?.descripcionMsg||(row.mh_receipt_seal?'Sello recibido':'Sin confirmación MH')}<small>{row.mh_receipt_seal?`Sello: ${row.mh_receipt_seal}`:''}</small></td><td>{check.issues.length?<><strong>⚠ {check.issues.length} alerta(s)</strong><small>{check.issues[0]}</small></>:check.warnings.length?<><strong>Revisar</strong><small>{check.warnings[0]}</small></>:<><strong>Consistente</strong><small>{check.accepted?'Aceptado con evidencia MH':'Sin inconsistencias locales'}</small></>}</td><td>{money(check.total)}</td><td>{accepted?<div className="form-actions" style={{gap:6,flexWrap:'wrap'}}><button type="button" className="secondary-button" onClick={()=>openReadableVersion(row,company)}>Versión legible + QR</button><button type="button" className="secondary-button" onClick={()=>downloadEvidence(row)}>Evidencia JSON</button></div>:isControlled&&row.status==='DRAFT'?<button type="button" onClick={()=>signControlled(row)} disabled={Boolean(actionId)}>Validar y firmar TEST</button>:isControlled&&row.status==='SIGNED'?<button type="button" onClick={()=>transmitControlled(row)} disabled={Boolean(actionId)}>Enviar 1 vez a MH TEST</button>:row.status==='PROCESSED'?<strong>✓ Finalizado</strong>:<small>{isControlled?'Esperando estado':'—'}</small>}</td></tr>})}{!visible.length&&<tr><td colSpan="8"><div className="empty-state"><strong>{rows.length?'No hay DTE para este filtro.':'Todavía no hay documentos electrónicos.'}</strong><small>{rows.length?'Elegí otro estado para continuar la revisión.':'Usá “Nueva factura” para iniciar el primer documento del recorrido fiscal.'}</small></div></td></tr>}</tbody></table></div>
  </section>
}
function Kpi({label,value}){return <article className="billing360-kpi"><small>{label}</small><strong>{value}</strong></article>}
