import {useEffect,useMemo,useState} from 'react'
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))
const day=()=>new Date().toISOString().slice(0,10)
export default function CashControlCenter({company,supabase,onOpenReports}){
 const [accounts,setAccounts]=useState([]),[moves,setMoves]=useState([]),[recs,setRecs]=useState([]),[msg,setMsg]=useState('')
 useEffect(()=>{let live=true;(async()=>{const [a,m,r]=await Promise.all([
  supabase.from('cash_account_balances').select('cash_account_id,name,account_type,active,current_balance,income_today,expense_today').eq('company_id',company.id),
  supabase.from('cash_movements').select('id,movement_date,movement_type,amount,concept,cash_account_id').eq('company_id',company.id).order('movement_date',{ascending:false}).limit(250),
  supabase.from('cash_reconciliations').select('id,cash_account_id,status,difference,reconciliation_date').eq('company_id',company.id).order('reconciliation_date',{ascending:false}).limit(100)
 ]);if(!live)return;const e=a.error||m.error||r.error;if(e)setMsg(e.message);else{setAccounts(a.data||[]);setMoves(m.data||[]);setRecs(r.data||[])}})();return()=>{live=false}},[company.id,supabase])
 const k=useMemo(()=>{const t=day(),today=moves.filter(x=>String(x.movement_date||'').startsWith(t)),ins=today.filter(x=>['INCOME','TRANSFER_IN'].includes(x.movement_type)).reduce((s,x)=>s+Number(x.amount||0),0),outs=today.filter(x=>['EXPENSE','TRANSFER_OUT'].includes(x.movement_type)).reduce((s,x)=>s+Number(x.amount||0),0),total=accounts.filter(x=>x.active!==false).reduce((s,x)=>s+Number(x.current_balance||0),0),negative=accounts.filter(x=>Number(x.current_balance||0)<0),diff=recs.filter(x=>Math.abs(Number(x.difference||0))>.009);return{ins,outs,total,negative,diff,today}},[accounts,moves,recs])
 return <section className="cash-control"><div className="clients-titlebar"><div><p className="form-kicker">CONTROL DIARIO</p><h2>Caja y bancos</h2><p>Saldos, movimiento del día y diferencias que requieren atención.</p></div><span className={k.negative.length||k.diff.length?'status dte-pending':'status dte-ready'}>{k.negative.length+k.diff.length} alertas</span></div>{msg&&<p className="feedback error">{msg}</p>}
 <div className="cash-control-summary"><article><small>Disponible</small><strong>{money(k.total)}</strong></article><article><small>Ingresos hoy</small><strong>{money(k.ins)}</strong></article><article><small>Salidas hoy</small><strong>{money(k.outs)}</strong></article><article><small>Neto hoy</small><strong>{money(k.ins-k.outs)}</strong></article></div>
 <div className="cash-control-grid"><article className={k.negative.length?'cash-risk active':'cash-risk'}><span>Cuentas negativas</span><strong>{k.negative.length}</strong><small>{k.negative.map(x=>x.name).slice(0,3).join(' · ')||'Sin saldos negativos'}</small></article><button type="button" className={k.diff.length?'cash-risk active':'cash-risk'} onClick={onOpenReports}><span>Diferencias de conciliación</span><strong>{k.diff.length}</strong><small>Abrir conciliación y reportes</small></button><article className="cash-risk"><span>Movimientos hoy</span><strong>{k.today.length}</strong><small>Ingresos y egresos registrados</small></article></div>
 </section>
}
