import {useEffect,useMemo,useState} from 'react'
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))
const day=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const methodLabel=value=>({CASH:'Efectivo',TRANSFER:'Transferencia',CARD:'Tarjeta',CHECK:'Cheque',OTHER:'Otro'}[value]||value||'Pago')
export default function CashControlCenter({company,supabase,onOpenReports}){
 const [accounts,setAccounts]=useState([]),[moves,setMoves]=useState([]),[recs,setRecs]=useState([]),[clients,setClients]=useState([]),[quotes,setQuotes]=useState([]),[advances,setAdvances]=useState([]),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false)
 const [form,setForm]=useState({client_id:'',quote_id:'',cash_account_id:'',amount:'',received_at:day(),payment_method:'CASH',reference:'',notes:''})
 const load=async()=>{const [a,m,r,c,q,ad]=await Promise.all([
  supabase.from('cash_account_balances').select('cash_account_id,name,account_type,active,current_balance,income_today,expense_today').eq('company_id',company.id),
  supabase.from('cash_movements').select('id,movement_date,movement_type,amount,concept,cash_account_id').eq('company_id',company.id).order('movement_date',{ascending:false}).limit(250),
  supabase.from('cash_reconciliations').select('id,cash_account_id,status,difference,reconciliation_date').eq('company_id',company.id).order('reconciliation_date',{ascending:false}).limit(100),
  supabase.from('clients').select('id,name').eq('company_id',company.id).eq('status','active').order('name'),
  supabase.from('quotes').select('id,number,prefix,client_id,project_name,total,status').eq('company_id',company.id).in('status',['APPROVED','PARTIALLY_CONVERTED','CONVERTED']).order('created_at',{ascending:false}).limit(100),
  supabase.from('customer_advances').select('id,client_id,quote_id,received_at,amount,applied_amount,status,payment_method,reference,clients(name),quotes(number,prefix,project_name)').eq('company_id',company.id).neq('status','CANCELLED').order('received_at',{ascending:false}).limit(100)
 ]);const e=a.error||m.error||r.error||c.error||q.error||ad.error;if(e)setMsg(e.message);else{setAccounts(a.data||[]);setMoves(m.data||[]);setRecs(r.data||[]);setClients(c.data||[]);setQuotes(q.data||[]);setAdvances(ad.data||[]);setForm(f=>({...f,cash_account_id:f.cash_account_id||(a.data||[]).find(x=>x.active!==false)?.cash_account_id||''}))}}
 useEffect(()=>{load()},[company.id,supabase])
 const k=useMemo(()=>{const t=day(),today=moves.filter(x=>x.movement_date&&day(new Date(x.movement_date))===t),ins=today.filter(x=>['INCOME','TRANSFER_IN'].includes(x.movement_type)).reduce((s,x)=>s+Number(x.amount||0),0),outs=today.filter(x=>['EXPENSE','TRANSFER_OUT'].includes(x.movement_type)).reduce((s,x)=>s+Number(x.amount||0),0),total=accounts.filter(x=>x.active!==false).reduce((s,x)=>s+Number(x.current_balance||0),0),negative=accounts.filter(x=>Number(x.current_balance||0)<0),diff=recs.filter(x=>Math.abs(Number(x.difference||0))>.009),pending=advances.filter(x=>['OPEN','PARTIAL'].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0)-Number(x.applied_amount||0),0);return{ins,outs,total,negative,diff,today,pending}},[accounts,moves,recs,advances])
 const availableQuotes=quotes.filter(q=>!form.client_id||q.client_id===form.client_id)
 const pendingAdvances=advances.filter(x=>['OPEN','PARTIAL'].includes(x.status))
 const saveAdvance=async e=>{e.preventDefault();setMsg('');if(!form.client_id||!form.cash_account_id||Number(form.amount)<=0){setMsg('Selecciona cliente, cuenta y un monto mayor que cero.');return}setSaving(true);const {error}=await supabase.rpc('register_customer_advance',{p_company_id:company.id,p_client_id:form.client_id,p_quote_id:form.quote_id||null,p_work_order_id:null,p_cash_account_id:form.cash_account_id,p_amount:Number(form.amount),p_received_at:`${form.received_at}T12:00:00`,p_payment_method:form.payment_method,p_reference:form.reference||null,p_notes:form.notes||null});if(error)setMsg(error.message);else{setMsg(`Anticipo de ${money(form.amount)} registrado.`);setForm(f=>({...f,amount:'',reference:'',notes:''}));await load()}setSaving(false)}
 const alerts=k.negative.length+k.diff.length
 return <section className="cash-control">
  <div className="clients-titlebar cash-simple-title"><div><p className="form-kicker">CAJA</p><h2>Caja y bancos</h2><p>Lo esencial para controlar entradas, salidas y anticipos.</p></div>{alerts>0&&<button type="button" className="cash-alert-button" onClick={onOpenReports}>{alerts} alerta{alerts===1?'':'s'}</button>}</div>
  {msg&&<p className={msg.includes('registrado')?'feedback success':'feedback error'}>{msg}</p>}
  <div className="cash-control-summary simple"><article><small>Disponible</small><strong>{money(k.total)}</strong></article><article><small>Entradas hoy</small><strong>{money(k.ins)}</strong></article><article><small>Salidas hoy</small><strong>{money(k.outs)}</strong></article></div>
  <form onSubmit={saveAdvance} className="form-card cash-advance-card"><div className="cash-section-heading"><div><p className="form-kicker">ANTICIPO</p><h3>Registrar cobro antes de facturar</h3></div><span className="cash-pending-pill">Pendiente de aplicar: {money(k.pending)}</span></div>
   <div className="cash-advance-grid">
    <label>Cliente *<select required value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value,quote_id:''})}><option value="">Seleccionar cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <label>Proyecto<select value={form.quote_id} onChange={e=>setForm({...form,quote_id:e.target.value})}><option value="">Sin vincular</option>{availableQuotes.map(q=><option key={q.id} value={q.id}>{q.prefix||'COT'}-{q.number} · {q.project_name||'Proyecto'} · {money(q.total)}</option>)}</select></label>
    <label>Monto *<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0.00"/></label>
    <label>Forma de pago<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia</option><option value="CARD">Tarjeta</option><option value="CHECK">Cheque</option><option value="OTHER">Otro</option></select></label>
    <label>Recibir en<select value={form.cash_account_id} onChange={e=>setForm({...form,cash_account_id:e.target.value})}>{accounts.filter(a=>a.active!==false).map(a=><option key={a.cash_account_id} value={a.cash_account_id}>{a.name}</option>)}</select></label>
   </div>
   <details className="cash-more-data"><summary>Más datos opcionales</summary><div className="cash-extra-grid"><label>Fecha<input type="date" value={form.received_at} onChange={e=>setForm({...form,received_at:e.target.value})}/></label><label>Referencia<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Comprobante / referencia"/></label><label>Nota<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Nota opcional"/></label></div></details>
   <div className="cash-submit-row"><button type="submit" disabled={saving}>{saving?'Registrando…':'Registrar anticipo'}</button></div>
  </form>
  <section className="form-card cash-pending-card"><div className="cash-section-heading"><div><p className="form-kicker">POR APLICAR</p><h3>Anticipos pendientes</h3></div><strong>{money(k.pending)}</strong></div>
   {pendingAdvances.length?<div className="cash-advance-list">{pendingAdvances.map(a=>{const pending=Number(a.amount||0)-Number(a.applied_amount||0);return <article key={a.id}><div><strong>{a.clients?.name||'Cliente'}</strong><small>{a.quotes?`${a.quotes.prefix||'COT'}-${a.quotes.number} · ${a.quotes.project_name||'Proyecto'}`:'Sin proyecto'} · {methodLabel(a.payment_method)} · {a.received_at?new Date(a.received_at).toLocaleDateString('es-SV'):'—'}</small></div><div><small>Pendiente</small><strong>{money(pending)}</strong></div></article>})}</div>:<p className="cash-empty">No hay anticipos pendientes.</p>}
  </section>
  {(alerts>0)&&<section className="cash-alert-strip"><strong>Revisión necesaria</strong><span>{k.negative.length>0?`${k.negative.length} cuenta(s) con saldo negativo. `:''}{k.diff.length>0?`${k.diff.length} diferencia(s) de conciliación.`:''}</span><button type="button" onClick={onOpenReports}>Revisar</button></section>}
 </section>
}
