import { useEffect,useMemo,useState } from 'react'
import FinancialReportsPanel from './FinancialReportsPanel.jsx'

const money=(v)=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}

export default function CashReconciliationPanel({company,supabase}){
  const [accounts,setAccounts]=useState([]),[rows,setRows]=useState([]),[closures,setClosures]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const [form,setForm]=useState({cash_account_id:'',statement_balance:'',reconciliation_date:today(),reference:'',notes:''})
  const [transfer,setTransfer]=useState({from:'',to:'',amount:'',reference:''})
  const [adjustment,setAdjustment]=useState({account:'',direction:'INCREASE',amount:'',reason:''})
  const load=async()=>{const [a,r,c]=await Promise.all([supabase.from('cash_account_balances').select('*').eq('company_id',company.id).eq('active',true).order('name'),supabase.from('cash_reconciliations').select('*,cash_accounts(name,account_type)').eq('company_id',company.id).order('reconciliation_date',{ascending:false}).limit(30),supabase.from('cash_daily_closures').select('*,cash_accounts(name)').eq('company_id',company.id).order('closure_date',{ascending:false}).limit(20)]);if(a.error||r.error||c.error)setMessage(a.error?.message||r.error?.message||c.error?.message);else{const list=a.data||[];setAccounts(list);setRows(r.data||[]);setClosures(c.data||[]);const first=list[0]?.cash_account_id||'';setForm(v=>({...v,cash_account_id:v.cash_account_id||first}));setTransfer(v=>({...v,from:v.from||first}));setAdjustment(v=>({...v,account:v.account||first}))}}
  useEffect(()=>{load()},[company.id])
  const selected=accounts.find(a=>a.cash_account_id===form.cash_account_id)
  const diff=form.statement_balance===''?null:Number(form.statement_balance)-Number(selected?.current_balance||0)
  const totals=useMemo(()=>accounts.reduce((acc,a)=>({balance:acc.balance+Number(a.current_balance||0),income:acc.income+Number(a.income_today||0),expense:acc.expense+Number(a.expense_today||0)}),{balance:0,income:0,expense:0}),[accounts])
  const run=async(fn,success)=>{setBusy(true);setMessage('');try{const {error}=await fn();if(error)throw error;setMessage(success);await load()}catch(e){setMessage(e.message||'No se pudo completar la operación.')}finally{setBusy(false)}}
  const reconcile=e=>{e.preventDefault();if(!selected)return setMessage('Seleccioná una cuenta.');return run(()=>supabase.rpc('reconcile_cash_account',{p_cash_account:selected.cash_account_id,p_statement_balance:Number(form.statement_balance||0),p_date:form.reconciliation_date,p_reference:form.reference||null,p_notes:form.notes||null}),'Conciliación guardada.')}
  const doTransfer=e=>{e.preventDefault();return run(()=>supabase.rpc('register_cash_transfer',{p_from:transfer.from,p_to:transfer.to,p_amount:Number(transfer.amount),p_reference:transfer.reference||null,p_notes:null}),'Transferencia registrada.').then(()=>setTransfer(v=>({...v,amount:'',reference:''})))}
  const doAdjustment=e=>{e.preventDefault();return run(()=>supabase.rpc('register_cash_adjustment',{p_cash_account:adjustment.account,p_direction:adjustment.direction,p_amount:Number(adjustment.amount),p_reason:adjustment.reason}),'Ajuste registrado.').then(()=>setAdjustment(v=>({...v,amount:'',reason:''})))}
  const closeDay=account=>run(()=>supabase.rpc('close_cash_day',{p_cash_account:account.cash_account_id,p_date:today(),p_notes:null}),`Cierre diario de ${account.name} registrado.`)
  const closeRec=row=>{const note=Math.abs(Number(row.difference||0))>=.01?window.prompt('Explicá la diferencia antes de cerrar:',''):null;if(note!==null&&Math.abs(Number(row.difference||0))>=.01&&!String(note).trim())return;return run(()=>supabase.rpc('close_cash_reconciliation',{p_reconciliation:row.id,p_notes:note}),`Conciliación de ${row.cash_accounts?.name||'cuenta'} cerrada.`)}
  return <><section className="panel"><div className="panel-heading"><div><p className="form-kicker">CAJA Y BANCOS</p><h3>Control financiero diario</h3><p>Transferencias, ajustes, cierres y conciliación con trazabilidad.</p></div></div><div className="metrics-grid"><article className="metric-card"><span>Saldo total</span><strong>{money(totals.balance)}</strong></article><article className="metric-card"><span>Entradas hoy</span><strong>{money(totals.income)}</strong></article><article className="metric-card"><span>Salidas hoy</span><strong>{money(totals.expense)}</strong></article><article className="metric-card"><span>Flujo neto hoy</span><strong>{money(totals.income-totals.expense)}</strong></article></div>{message&&<p className={/registrad|guardad|cerrad/i.test(message)?'feedback success':'feedback error'}>{message}</p>}
  <div className="module-grid two-column"><form onSubmit={doTransfer} className="panel"><div className="panel-heading"><div><p className="form-kicker">TRANSFERENCIA</p><h3>Entre cuentas</h3></div></div><div className="form-grid"><label className="field"><span>Desde *</span><select required value={transfer.from} onChange={e=>setTransfer({...transfer,from:e.target.value})}>{accounts.map(a=><option key={a.cash_account_id} value={a.cash_account_id}>{a.name} · {money(a.current_balance)}</option>)}</select></label><label className="field"><span>Hacia *</span><select required value={transfer.to} onChange={e=>setTransfer({...transfer,to:e.target.value})}><option value="">Seleccionar</option>{accounts.filter(a=>a.cash_account_id!==transfer.from).map(a=><option key={a.cash_account_id} value={a.cash_account_id}>{a.name}</option>)}</select></label><label className="field"><span>Monto *</span><input type="number" min="0.01" step="0.01" required value={transfer.amount} onChange={e=>setTransfer({...transfer,amount:e.target.value})}/></label><label className="field"><span>Referencia</span><input value={transfer.reference} onChange={e=>setTransfer({...transfer,reference:e.target.value})}/></label></div><div className="form-actions end"><button disabled={busy||!transfer.to}>Transferir</button></div></form>
  <form onSubmit={doAdjustment} className="panel"><div className="panel-heading"><div><p className="form-kicker">AJUSTE CONTROLADO</p><h3>Corregir diferencia</h3></div></div><div className="form-grid"><label className="field"><span>Cuenta *</span><select required value={adjustment.account} onChange={e=>setAdjustment({...adjustment,account:e.target.value})}>{accounts.map(a=><option key={a.cash_account_id} value={a.cash_account_id}>{a.name}</option>)}</select></label><label className="field"><span>Tipo *</span><select value={adjustment.direction} onChange={e=>setAdjustment({...adjustment,direction:e.target.value})}><option value="INCREASE">Aumentar saldo</option><option value="DECREASE">Disminuir saldo</option></select></label><label className="field"><span>Monto *</span><input type="number" min="0.01" step="0.01" required value={adjustment.amount} onChange={e=>setAdjustment({...adjustment,amount:e.target.value})}/></label><label className="field"><span>Motivo *</span><input minLength="4" required value={adjustment.reason} onChange={e=>setAdjustment({...adjustment,reason:e.target.value})}/></label></div><div className="form-actions end"><button disabled={busy}>Registrar ajuste</button></div></form></div>
  <div className="module-grid two-column"><form onSubmit={reconcile} className="panel"><div className="panel-heading"><div><p className="form-kicker">CONCILIACIÓN</p><h3>Comparar contra banco/caja</h3></div></div><div className="form-grid"><label className="field"><span>Cuenta *</span><select required value={form.cash_account_id} onChange={e=>setForm({...form,cash_account_id:e.target.value})}><option value="">Seleccionar cuenta</option>{accounts.map(a=><option key={a.cash_account_id} value={a.cash_account_id}>{a.name} · {money(a.current_balance)}</option>)}</select></label><label className="field"><span>Fecha *</span><input type="date" required value={form.reconciliation_date} onChange={e=>setForm({...form,reconciliation_date:e.target.value})}/></label><label className="field"><span>Saldo ERP</span><input readOnly value={selected?money(selected.current_balance):''}/></label><label className="field"><span>Saldo contado / banco *</span><input type="number" step="0.01" required value={form.statement_balance} onChange={e=>setForm({...form,statement_balance:e.target.value})}/></label><label className="field"><span>Diferencia</span><input readOnly value={diff===null?'':money(diff)}/></label><label className="field"><span>Referencia</span><input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label className="field form-span-2"><span>Notas</span><textarea rows="2" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="form-actions end"><button disabled={busy}>{busy?'Procesando…':'Guardar conciliación'}</button></div></form><section className="panel"><div className="panel-heading"><div><p className="form-kicker">CIERRE DIARIO</p><h3>Por cuenta</h3></div></div>{accounts.length?<div className="client-list">{accounts.map(a=><div className="client-row" key={a.cash_account_id}><div><strong>{a.name}</strong><small>{a.account_type} · saldo {money(a.current_balance)}</small></div><button type="button" className="secondary-button" disabled={busy} onClick={()=>closeDay(a)}>Cerrar hoy</button></div>)}</div>:<div className="empty-state"><strong>Sin cuentas activas</strong></div>}{closures.length>0&&<small>Último cierre: {closures[0].closure_date} · {closures[0].cash_accounts?.name||'Cuenta'} · {money(closures[0].closing_balance)}</small>}</section></div>
  {rows.length>0&&<div className="client-table-wrap"><table className="client-table"><thead><tr><th>Fecha</th><th>Cuenta</th><th>ERP</th><th>Contado/Banco</th><th>Diferencia</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.reconciliation_date}</td><td>{r.cash_accounts?.name||'Cuenta'}</td><td>{money(r.system_balance)}</td><td>{money(r.statement_balance)}</td><td>{money(r.difference)}</td><td><span className={r.status==='CLOSED'||r.status==='MATCHED'?'status dte-ready':'status dte-pending'}>{r.status}</span></td><td>{r.status!=='CLOSED'&&r.status!=='CANCELLED'?<button type="button" className="secondary-button" disabled={busy} onClick={()=>closeRec(r)}>Cerrar</button>:'—'}</td></tr>)}</tbody></table></div>}</section><FinancialReportsPanel company={company} supabase={supabase}/></>
}
