import {useMemo,useState} from 'react'
import './CashPaymentHistory.css'

const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))
const methodLabel=v=>({CASH:'Efectivo',TRANSFER:'Transferencia',CARD:'Tarjeta',CHECK:'Cheque',OTHER:'Otro'}[v]||v||'Pago')
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))

export default function CashPaymentHistory({company,records=[],clients=[],quotes=[]}){
 const [search,setSearch]=useState(''),[date,setDate]=useState('')
 const paidByQuote=useMemo(()=>{const map=new Map();for(const r of records){if(!r.quote_id)continue;map.set(r.quote_id,(map.get(r.quote_id)||0)+Number(r.amount||0))}return map},[records])
 const rows=useMemo(()=>records.map(r=>{const client=clients.find(c=>c.id===r.client_id),quote=quotes.find(q=>q.id===r.quote_id),paid=quote?paidByQuote.get(quote.id)||0:0,pending=quote?Math.max(0,Number(quote.total||0)-paid):null;return{...r,client_name:client?.name||'Cliente',quote,paid,pending}}),[records,clients,quotes,paidByQuote])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>{const receipt=`CP-${String(r.receipt_no||0).padStart(6,'0')}`,quote=r.quote?`${r.quote.prefix||'COT'}-${r.quote.number}`:'';const text=`${receipt} ${r.client_name} ${quote} ${r.concept||''} ${r.reference||''}`.toLowerCase();const matchText=!q||text.includes(q);const matchDate=!date||(r.received_at&&String(r.received_at).slice(0,10)===date);return matchText&&matchDate})},[rows,search,date])
 const printRecord=r=>{const receipt=`CP-${String(r.receipt_no||0).padStart(6,'0')}`,quoteLabel=r.quote?`${r.quote.prefix||'COT'}-${r.quote.number}`:'',w=window.open('','_blank','width=820,height=900');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${receipt}</title><style>body{font-family:Arial,sans-serif;color:#1f2937;padding:36px}.box{max-width:720px;margin:auto;border:1px solid #d1d5db;border-radius:14px;padding:28px}h1{margin:0 0 4px;font-size:24px}.tag{display:inline-block;border:1px solid #f59e0b;border-radius:999px;padding:6px 10px;font-weight:700;font-size:12px;margin:10px 0 22px}.row{display:flex;justify-content:space-between;gap:24px;border-top:1px solid #e5e7eb;padding:11px 0}.row span:first-child{color:#6b7280}.amount{font-size:28px;font-weight:800}.note{margin-top:22px;padding:14px;background:#f9fafb;border-radius:10px;font-size:12px;line-height:1.45}.foot{margin-top:26px;font-size:11px;color:#6b7280}@media print{body{padding:0}.box{border:none}}</style></head><body><div class="box"><h1>${esc(company?.name||'IDEALO SV')}</h1><div><strong>COMPROBANTE DE PAGO</strong></div><div class="tag">NO ES FACTURA · NO ES DTE</div><div class="row"><span>Comprobante</span><strong>${receipt}</strong></div><div class="row"><span>Fecha</span><strong>${esc(r.received_at?new Date(r.received_at).toLocaleDateString('es-SV'):'—')}</strong></div><div class="row"><span>Cliente</span><strong>${esc(r.client_name)}</strong></div>${quoteLabel?`<div class="row"><span>Cotización</span><strong>${esc(quoteLabel)}</strong></div>`:''}<div class="row"><span>Concepto</span><strong>${esc(r.concept||r.quote?.project_name||'Pago de trabajo')}</strong></div><div class="row"><span>Forma de pago</span><strong>${esc(methodLabel(r.payment_method))}</strong></div><div class="row"><span>Monto recibido</span><strong class="amount">${money(r.amount)}</strong></div>${r.pending!==null?`<div class="row"><span>Saldo actual</span><strong>${money(r.pending)}</strong></div>`:''}${r.reference?`<div class="row"><span>Referencia</span><strong>${esc(r.reference)}</strong></div>`:''}<div class="note">Constancia interna de dinero recibido. No constituye factura, crédito fiscal ni Documento Tributario Electrónico.</div><div class="foot">Generado por IDEALO SV</div></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
 return <details className="cash-pending-compact" open>
  <summary><span><strong>Historial de pagos y comprobantes</strong><small>{records.length} comprobante{records.length===1?'':'s'} archivado{records.length===1?'':'s'}</small></span><b>{money(records.reduce((s,r)=>s+Number(r.amount||0),0))}</b></summary>
  <div className="cash-history-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, comprobante o cotización"/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/>{(search||date)&&<button type="button" className="secondary" onClick={()=>{setSearch('');setDate('')}}>Limpiar</button>}</div>
  {filtered.length>0?<div className="cash-advance-list">{filtered.map(r=>{const receipt=`CP-${String(r.receipt_no||0).padStart(6,'0')}`,quote=r.quote?`${r.quote.prefix||'COT'}-${r.quote.number}`:'Sin cotización';return <article key={r.id}><div><strong>{receipt} · {r.client_name}</strong><small>{r.received_at?new Date(r.received_at).toLocaleDateString('es-SV'):'—'} · {quote} · {methodLabel(r.payment_method)}</small></div><div><small>Pagado</small><strong>{money(r.amount)}</strong>{r.pending!==null&&<small>Saldo actual {money(r.pending)}</small>}<button type="button" className="secondary" onClick={()=>printRecord(r)}>Ver / PDF</button></div></article>})}</div>:<div className="cash-shift-message">No hay comprobantes que coincidan con la búsqueda.</div>}
 </details>
}
