import { useEffect,useMemo,useState } from 'react'
import { createPortal } from 'react-dom'
import { supabase as s } from './lib/supabase.js'

const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const stages=[['PROSPECT','Prospecto',10],['QUOTED','Cotizado',35],['NEGOTIATION','Negociación',70],['WON','Ganado',100],['LOST','Perdido',0]]

export default function ClientCrmPipeline(){
 const [module,setModule]=useState(''),[company,setCompany]=useState(null),[clients,setClients]=useState([]),[rows,setRows]=useState([]),[forecast,setForecast]=useState([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[form,setForm]=useState({client_id:'',title:'',stage:'PROSPECT',probability:10,amount:0,expected_close_date:'',notes:'',lost_reason:''})
 useEffect(()=>{const sync=v=>setModule(typeof v==='string'?v:(document.querySelector('.erp-header h1')?.textContent?.trim()||''));sync();const onModule=e=>sync(e.detail);window.addEventListener('idealo-module-change',onModule);return()=>window.removeEventListener('idealo-module-change',onModule)},[])
 useEffect(()=>{(async()=>{const {data,error:e}=await s.rpc('get_my_companies');if(e)setError(e.message);else setCompany(data?.[0]?.id||null)})()},[])
 const load=async()=>{if(!company)return;setError('');const sync=await s.rpc('sync_crm_opportunities_from_quotes',{p_company_id:company});const [c,o,f]=await Promise.all([s.from('clients').select('id,name').eq('company_id',company).order('name'),s.from('crm_opportunities').select('id,client_id,source_quote_id,title,stage,probability,amount,expected_close_date,lost_reason,notes,created_at,clients(name)').eq('company_id',company).order('created_at',{ascending:false}),s.from('crm_pipeline_forecast').select('*').eq('company_id',company)]);const e=sync.error||c.error||o.error||f.error;if(e)setError(e.message);setClients(c.data||[]);setRows(o.data||[]);setForecast(f.data||[])}
 useEffect(()=>{if(company)load()},[company])
 const visible=['Clientes','Dashboard'].includes(module)
 const summary=useMemo(()=>({open:rows.filter(x=>!['WON','LOST'].includes(x.stage)).reduce((a,x)=>a+Number(x.amount||0),0),weighted:rows.filter(x=>!['WON','LOST'].includes(x.stage)).reduce((a,x)=>a+Number(x.amount||0)*Number(x.probability||0)/100,0),won:rows.filter(x=>x.stage==='WON').reduce((a,x)=>a+Number(x.amount||0),0),lost:rows.filter(x=>x.stage==='LOST').reduce((a,x)=>a+Number(x.amount||0),0)}),[rows])
 const save=async()=>{if(!form.client_id||!form.title.trim())return;setBusy('new');const {error:e}=await s.from('crm_opportunities').insert({company_id:company,client_id:form.client_id,title:form.title.trim(),stage:form.stage,probability:Number(form.probability),amount:Number(form.amount||0),expected_close_date:form.expected_close_date||null,notes:form.notes||null});setBusy('');if(e){setError(e.message);return}setForm({client_id:'',title:'',stage:'PROSPECT',probability:10,amount:0,expected_close_date:'',notes:'',lost_reason:''});await load()}
 const move=async(row,stage)=>{let lostReason=null;if(stage==='LOST'){lostReason=prompt('Motivo de pérdida de esta oportunidad:',row.lost_reason||'');if(!lostReason?.trim())return}setBusy(row.id);const def=stages.find(x=>x[0]===stage)?.[2]??row.probability;const {error:e}=await s.from('crm_opportunities').update({stage,probability:def,lost_reason:stage==='LOST'?lostReason.trim():null,won_at:stage==='WON'?new Date().toISOString():null,lost_at:stage==='LOST'?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',row.id).eq('company_id',company);setBusy('');if(e)setError(e.message);else await load()}
 const setProbability=async(row,value)=>{const probability=Math.max(0,Math.min(100,Number(value||0)));setRows(rs=>rs.map(x=>x.id===row.id?{...x,probability}:x));const {error:e}=await s.from('crm_opportunities').update({probability,updated_at:new Date().toISOString()}).eq('id',row.id).eq('company_id',company);if(e)setError(e.message);else await load()}
 if(!visible)return null
 const board=<section className="crm360"><header><div><small>CRM · CLIENTE 360</small><h3>Pipeline comercial</h3></div><div className="crm360-kpis"><b>{money(summary.open)}<small>Pipeline abierto</small></b><b>{money(summary.weighted)}<small>Pronóstico ponderado</small></b><b>{money(summary.won)}<small>Ganado</small></b><b>{money(summary.lost)}<small>Perdido</small></b></div></header>{error&&<div className="feedback error">{error}</div>}{module==='Clientes'&&<div className="crm360-new"><select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Cliente…</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Oportunidad" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Valor" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input type="date" value={form.expected_close_date} onChange={e=>setForm({...form,expected_close_date:e.target.value})}/><button type="button" disabled={busy==='new'} onClick={save}>Nueva oportunidad</button></div>}<div className="crm360-board">{stages.map(([code,label])=><div className="crm360-col" key={code}><h4>{label}<span>{rows.filter(x=>x.stage===code).length}</span></h4>{rows.filter(x=>x.stage===code).map(r=><article key={r.id}><strong>{r.title}</strong><small>{r.clients?.name||'Cliente'}</small><b>{money(r.amount)}</b><label className="crm360-prob">Probabilidad<input type="number" min="0" max="100" value={r.probability} onBlur={e=>setProbability(r,e.target.value)} onChange={e=>setRows(rs=>rs.map(x=>x.id===r.id?{...x,probability:e.target.value}:x))}/>%</label><small>Cierre esperado: {r.expected_close_date||'—'}</small>{r.source_quote_id&&<em>Origen: Cotización</em>}{r.stage==='LOST'&&r.lost_reason&&<p>Motivo: {r.lost_reason}</p>}<select disabled={busy===r.id} value={r.stage} onChange={e=>move(r,e.target.value)}>{stages.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></article>)}</div>)}</div>{module==='Dashboard'&&<div className="crm360-forecast"><h4>Pronóstico por etapa</h4>{forecast.map(x=><p key={x.stage}><b>{stages.find(s=>s[0]===x.stage)?.[1]||x.stage}</b><span>{x.opportunity_count} oportunidades · {money(x.pipeline_amount)} · ponderado {money(x.weighted_forecast)}</span></p>)}</div>}</section>
 return createPortal(board,document.querySelector('.erp-content')||document.body)
}
