import { useEffect,useMemo,useState } from 'react'
import { createPortal } from 'react-dom'
import { supabase } from './lib/supabase.js'

const DTE03_REQUIRED=[['name','nombre'],['tax_id','NIT'],['nrc','NRC'],['activity_code','actividad'],['business_activity','giro'],['department_code','departamento'],['municipality_code','municipio'],['district_code','distrito'],['address','dirección'],['phone','teléfono'],['email','correo']]
const norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')
const day=value=>value?new Date(value).toLocaleDateString('es-SV'):'—'

function duplicateGroups(rows,key){const map=new Map();for(const row of rows){const value=norm(row[key]);if(!value)continue;const group=map.get(value)||[];group.push(row);map.set(value,group)}return [...map.values()].filter(group=>group.length>1)}

export default function ClientIntegrityCenter(){
 const [visible,setVisible]=useState(false),[companyId,setCompanyId]=useState(''),[clients,setClients]=useState([]),[credits,setCredits]=useState([]),[receivables,setReceivables]=useState([]),[interactions,setInteractions]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
 useEffect(()=>{const sync=value=>setVisible((typeof value==='string'?value:document.querySelector('.erp-header h1')?.textContent?.trim())==='Clientes');sync();const h=e=>sync(e.detail);window.addEventListener('idealo-module-change',h);return()=>window.removeEventListener('idealo-module-change',h)},[])
 const load=async()=>{if(!visible)return;setLoading(true);setError('');const {data:companies,error:companyError}=await supabase.rpc('get_my_companies');if(companyError){setError(companyError.message);setLoading(false);return}const id=companies?.[0]?.id;if(!id){setLoading(false);return}setCompanyId(id);const [c,cr,ar,i]=await Promise.all([
  supabase.from('clients').select('id,name,trade_name,status,preferred_dte_type,tax_id,nrc,document_number,email,phone,whatsapp,activity_code,business_activity,department_code,municipality_code,district_code,address,blocked_for_debt').eq('company_id',id).order('name'),
  supabase.from('client_credit_profiles').select('client_id,blocked,credit_enabled,risk_level').eq('company_id',id),
  supabase.from('accounts_receivable').select('client_id,amount_total,amount_paid,due_date,status').eq('company_id',id).not('status','in','(PAID,CANCELLED)'),
  supabase.from('client_interactions').select('client_id,next_follow_up_at,subject').eq('company_id',id).not('next_follow_up_at','is',null)
 ]);const issue=c.error||cr.error||ar.error||i.error;if(issue)setError(issue.message);setClients(c.data||[]);setCredits(cr.data||[]);setReceivables(ar.data||[]);setInteractions(i.data||[]);setLoading(false)}
 useEffect(()=>{if(visible)load()},[visible])
 const audit=useMemo(()=>{const now=new Date(),byId=new Map(clients.map(c=>[c.id,c]));const fiscal=clients.filter(c=>c.preferred_dte_type==='03').map(c=>({client:c,missing:DTE03_REQUIRED.filter(([key])=>!String(c[key]||'').trim()).map(([,label])=>label)})).filter(x=>x.missing.length);const duplicates=[['tax_id','NIT'],['nrc','NRC'],['email','correo'],['phone','teléfono'],['whatsapp','WhatsApp']].flatMap(([key,label])=>duplicateGroups(clients,key).map(group=>({label,group})));const creditMismatch=credits.filter(p=>Boolean(p.blocked)!==Boolean(byId.get(p.client_id)?.blocked_for_debt)).map(p=>({profile:p,client:byId.get(p.client_id)})).filter(x=>x.client);const overdue=receivables.filter(r=>r.due_date&&new Date(`${r.due_date}T23:59:59`)<now&&Number(r.amount_total||0)>Number(r.amount_paid||0)).map(r=>({...r,client:byId.get(r.client_id)}));const followups=interactions.filter(x=>x.next_follow_up_at&&new Date(x.next_follow_up_at)<now).map(x=>({...x,client:byId.get(x.client_id)}));return{fiscal,duplicates,creditMismatch,overdue,followups}},[clients,credits,receivables,interactions])
 if(!visible)return null
 const host=document.querySelector('.erp-content')||document.body,total=audit.fiscal.length+audit.duplicates.length+audit.creditMismatch.length+audit.overdue.length+audit.followups.length
 return createPortal(<section className="client-integrity-center" aria-label="Control de integridad de clientes"><header><div><small>CONTROL DE CALIDAD · CLIENTES</small><strong>Integridad del expediente</strong><p>Revisión automática de DTE, duplicados, crédito, CxC y seguimientos.</p></div><button type="button" onClick={load} disabled={loading}>{loading?'Revisando…':'Actualizar'}</button></header>{error&&<div className="client-integrity-error">{error}</div>}<div className="client-integrity-kpis"><Kpi label="Clientes" value={clients.length}/><Kpi label="DTE-03 incompletos" value={audit.fiscal.length} bad={audit.fiscal.length>0}/><Kpi label="Duplicados" value={audit.duplicates.length} bad={audit.duplicates.length>0}/><Kpi label="Mora" value={audit.overdue.length} bad={audit.overdue.length>0}/><Kpi label="Seguimientos vencidos" value={audit.followups.length} bad={audit.followups.length>0}/></div>{!loading&&total===0?<div className="client-integrity-ok">✓ No se detectaron inconsistencias operativas en Clientes.</div>:<div className="client-integrity-grid">{audit.fiscal.length>0&&<Bucket title="Expedientes DTE-03 incompletos" count={audit.fiscal.length}>{audit.fiscal.slice(0,8).map(x=><Row key={x.client.id} title={x.client.name} text={`Falta: ${x.missing.join(', ')}`}/>)}</Bucket>}{audit.duplicates.length>0&&<Bucket title="Posibles duplicados" count={audit.duplicates.length}>{audit.duplicates.slice(0,8).map((x,index)=><Row key={`${x.label}-${index}`} title={`${x.label} repetido`} text={x.group.map(c=>c.name).join(' · ')}/>)}</Bucket>}{audit.creditMismatch.length>0&&<Bucket title="Crédito desincronizado" count={audit.creditMismatch.length}>{audit.creditMismatch.slice(0,8).map(x=><Row key={x.client.id} title={x.client.name} text={`Cliente: ${x.client.blocked_for_debt?'bloqueado':'habilitado'} · perfil: ${x.profile.blocked?'bloqueado':'habilitado'}`}/>)}</Bucket>}{audit.overdue.length>0&&<Bucket title="CxC vencida" count={audit.overdue.length}>{audit.overdue.slice(0,8).map((x,index)=><Row key={`${x.client_id}-${index}`} title={x.client?.name||'Cliente'} text={`Venció ${day(x.due_date)} · saldo $${Math.max(0,Number(x.amount_total||0)-Number(x.amount_paid||0)).toFixed(2)}`}/>)}</Bucket>}{audit.followups.length>0&&<Bucket title="Seguimientos vencidos" count={audit.followups.length}>{audit.followups.slice(0,8).map((x,index)=><Row key={`${x.client_id}-${index}`} title={x.client?.name||'Cliente'} text={`${x.subject||'Seguimiento'} · ${day(x.next_follow_up_at)}`}/>)}</Bucket>}</div>}<footer>Empresa auditada: <code>{companyId||'—'}</code>. Los avisos no modifican datos automáticamente.</footer></section>,host)
}
function Kpi({label,value,bad=false}){return <article className={bad?'bad':''}><strong>{value}</strong><span>{label}</span></article>}
function Bucket({title,count,children}){return <article className="client-integrity-bucket"><h3>{title}<span>{count}</span></h3>{children}</article>}
function Row({title,text}){return <div className="client-integrity-row"><strong>{title}</strong><small>{text}</small></div>}
