import { createClient } from '@supabase/supabase-js'
import { useEffect,useMemo,useState } from 'react'
import { createPortal } from 'react-dom'

const s=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY,{auth:{persistSession:true}})
const stages=['PROSPECT','QUOTED','NEGOTIATION','WON','LOST']
const labels={PROSPECT:'Prospecto',QUOTED:'Cotizado',NEGOTIATION:'Negociación',WON:'Ganado',LOST:'Perdido'}
const defaults={PROSPECT:10,QUOTED:35,NEGOTIATION:70,WON:100,LOST:0}
const money=n=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(n||0))

export default function CrmPipelineCenter(){
 const [show,setShow]=useState(false),[company,setCompany]=useState(null),[clients,setClients]=useState([]),[rows,setRows]=useState([]),[forecast,setForecast]=useState([]),[busy,setBusy]=useState(''),[msg,setMsg]=useState('')
 const [form,setForm]=useState({client_id:'',title:'',amount:'',probability:10,expected_close_date:'',notes:''})
 useEffect(()=>{const sync=()=>setShow(document.querySelector('.erp-header h1')?.textContent?.trim()==='Clientes');sync();const t=setInterval(sync,500);return()=>clearInterval(t)},[])
 useEffect(()=>{if(!show)return;(async()=>{const {data:c}=await s.rpc('get_my_companies');const id=c?.[0]?.id;if(!id)return;setCompany(id);const {data:cl}=await s.from('clients').select('id,name').eq('company_id',id).order('name');setClients(cl||[])})()},[show])
 const load=async()=>{if(!company)return;await s.rpc('sync_crm_opportunities_from_quotes',{p_company_id:company});const [{data:r},{data:f}]=await Promise.all([s.from('crm_opportunities').select('id,client_id,source_quote_id,title,stage,probability,amount,expected_close_date,lost_reason,notes,updated_at,clients(name)').eq('company_id',company).order('updated_at',{ascending:false}),s.from('crm_pipeline_forecast').select('*').eq('company_id',company)]);setRows(r||[]);setForecast(f||[])}
 useEffect(()=>{if(company)load()},[company])
 const totals=useMemo(()=>({open:rows.filter(x=>!['WON','LOST'].includes(x.stage)).reduce((a,x)=>a+Number(x.amount||0),0),weighted:rows.filter(x=>!['WON','LOST'].includes(x.stage)).reduce((a,x)=>a+Number(x.amount||0)*Number(x.probability||0)/100,0),won:rows.filter(x=>x.stage==='WON').reduce((a,x)=>a+Number(x.amount||0),0),lost:rows.filter(x=>x.stage==='LOST').length}),[rows])
 const create=async()=>{setMsg('');if(!form.client_id||!form.title.trim())return setMsg('Seleccioná cliente y escribí el negocio.');setBusy('new');const {error}=await s.from('crm_opportunities').insert({company_id:company,client_id:form.client_id,title:form.title.trim(),stage:'PROSPECT',probability:Number(form.probability||10),amount:Number(form.amount||0),expected_close_date:form.expected_close_date||null,notes:form.notes||null});setBusy('');if(error)return setMsg(error.message);setForm({client_id:'',title:'',amount:'',probability:10,expected_close_date:'',notes:''});setMsg('Oportunidad creada.');await load()}
 const move=async(o,stage)=>{let lost_reason=null;if(stage==='LOST'){lost_reason=prompt('Motivo de pérdida','Precio / no respondió / competencia / canceló')||'';if(!lost_reason.trim())return}setBusy(o.id);const patch={stage,probability:defaults[stage],updated_at:new Date().toISOString(),lost_reason:stage==='LOST'?lost_reason:null,won_at:stage==='WON'?new Date().toISOString():null,lost_at:stage==='LOST'?new Date().toISOString():null};if(stage!=='WON')patch.won_at=null;if(stage!=='LOST')patch.lost_at=null;const {error}=await s.from('crm_opportunities').update(patch).eq('id',o.id).eq('company_id',company);setBusy('');if(error)setMsg(error.message);else await load()}
 if(!show)return null
 return createPortal(<section className="crm360"><header><div><small>CLIENTE 360 · CRM</small><h2>Pipeline comercial</h2></div><div className="crm360kpis"><b>{money(totals.open)}<small>Pipeline abierto</small></b><b>{money(totals.weighted)}<small>Pronóstico ponderado</small></b><b>{money(totals.won)}<small>Ganado</small></b><b>{totals.lost}<small>Perdidos</small></b></div></header>
 <div className="crm360new"><select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Cliente…</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Oportunidad / trabajo" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input type="number" min="0" step="0.01" placeholder="Valor $" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input type="date" value={form.expected_close_date} onChange={e=>setForm({...form,expected_close_date:e.target.value})}/><button disabled={busy==='new'} onClick={create}>+ Prospecto</button></div>{msg&&<div className="crm360msg">{msg}</div>}
 <div className="crm360forecast">{stages.map(st=>{const f=forecast.find(x=>x.stage===st);return <span key={st}><b>{labels[st]}</b> {f?.opportunity_count||0} · {money(f?.pipeline_amount||0)} · pronóstico {money(f?.weighted_forecast||0)}</span>})}</div>
 <div className="crm360board">{stages.map(st=><section key={st}><h3>{labels[st]} <span>{rows.filter(x=>x.stage===st).length}</span></h3>{rows.filter(x=>x.stage===st).map(o=><article key={o.id}><strong>{o.title}</strong><small>{o.clients?.name||'Cliente'}{o.source_quote_id?' · desde cotización':''}</small><b>{money(o.amount)} · {o.probability}%</b><small>Cierre: {o.expected_close_date||'Sin fecha'}</small>{o.lost_reason&&<em>{o.lost_reason}</em>}<select disabled={busy===o.id} value={o.stage} onChange={e=>move(o,e.target.value)}>{stages.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></article>)}</section>)}</div>
 </section>,document.querySelector('.erp-content')||document.body)
}
