import { useEffect,useState } from 'react'

const apiUrl=import.meta.env.VITE_API_URL||'http://localhost:4000'
const TYPES=[['1','No disponibilidad del sistema MH'],['2','No disponibilidad de internet'],['3','Falla en suministro eléctrico'],['4','Falla del equipo o sistema del emisor'],['5','Otro motivo']]

export default function DteContingencyPreparation({supabase,company,session,controlNumber}){
 const [document,setDocument]=useState(null),[type,setType]=useState('1'),[motive,setMotive]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{if(!controlNumber||!company?.id){setDocument(null);return}const {data,error}=await supabase.from('dte_documents').select('id,company_id,control_number,environment,status,signed_document,dte_payload').eq('company_id',company.id).eq('control_number',controlNumber).maybeSingle();if(error){setError(error.message);return}setDocument(data||null)}
 useEffect(()=>{setMessage('');setError('');setMotive('');void load()},[controlNumber,company?.id])
 if(!document)return null
 const ident=document.dte_payload?.identificacion||{}
 const prepared=Number(ident.tipoModelo)===2&&Number(ident.tipoOperacion)===2&&Number(ident.tipoContingencia)>0
 if(prepared)return <section className="billing-document-detail"><div className="billing-document-detail-head"><div><span>Modo de contingencia</span><strong>Preparado</strong><small>Este DTE se firmará como documento generado en contingencia.</small></div><span className="billing-document-status signed">CONTINGENCIA</span></div><div className="billing-document-detail-grid"><Info label="Tipo" value={String(ident.tipoContingencia)}/><Info label="Motivo" value={ident.motivoContin||'—'}/><Info label="Modelo / operación" value={`${ident.tipoModelo} / ${ident.tipoOperacion}`}/></div></section>
 if(document.status!=='DRAFT'||document.signed_document)return null
 const prepare=async()=>{if(!session?.access_token||busy)return;const clean=motive.trim();if(clean.length<5){setError('Escribe un motivo de al menos 5 caracteres.');return}let confirmation=null;if(document.environment==='production'){const expected=`PREPARAR CONTINGENCIA ${document.control_number}`;confirmation=window.prompt(`Producción: escribe exactamente\n${expected}`,'')||'';if(confirmation!==expected){setError('Confirmación de PRODUCCIÓN cancelada o incorrecta.');return}}setBusy(true);setError('');setMessage('');try{const response=await fetch(`${apiUrl}/api/dte/prepare-contingency`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({documentId:document.id,tipoContingencia:Number(type),motivoContin:clean,confirmation})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||`HTTP ${response.status}`);setMessage('DTE preparado en modo contingencia. Ahora puede firmarse con el flujo correspondiente.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="billing-document-detail"><div className="billing-document-detail-head"><div><span>Contingencia</span><strong>Preparar este borrador para emisión en contingencia</strong><small>Úsalo solo cuando exista una contingencia real. El documento debe prepararse antes de firmarlo.</small></div><span className="billing-document-status draft">BORRADOR</span></div>{error&&<div className="billing-documents-alert error" style={{marginTop:12}}>{error}</div>}{message&&<div className="billing-documents-alert success" style={{marginTop:12}}>{message}</div>}<div className="form-grid two" style={{marginTop:12}}><label className="field"><span>Tipo de contingencia</span><select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(([v,l])=><option key={v} value={v}>{v} · {l}</option>)}</select></label><label className="field"><span>Motivo</span><input value={motive} onChange={e=>setMotive(e.target.value)} placeholder="Describe brevemente la contingencia real"/></label></div><div className="billing-document-actions"><button type="button" onClick={prepare} disabled={busy}>{busy?'Preparando…':'Preparar contingencia'}</button></div><small className="billing-document-safety">No transmite nada a Hacienda. Solo cambia el modelo/operación del borrador a contingencia y conserva los controles de firma y transmisión existentes.</small></section>
}
function Info({label,value}){return <div className="billing-document-info"><span>{label}</span><strong>{value||'—'}</strong></div>}
