import { useEffect, useState } from 'react'
const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const today=()=>new Date().toISOString().slice(0,10)
export default function EmployeeCommissions({company,supabase}){
  const [employees,setEmployees]=useState([]),[orders,setOrders]=useState([]),[rows,setRows]=useState([]),[message,setMessage]=useState('')
  const [form,setForm]=useState({employee_id:'',work_order_id:'',commission_date:today(),concept:'Comisión por venta / trabajo',base_amount:'',rate:'',amount:'',notes:''})
  const load=async()=>{const r=await Promise.all([supabase.from('employees').select('*').eq('company_id',company.id).eq('active',true).order('full_name'),supabase.from('work_orders').select('id,number,title,total,clients(name)').eq('company_id',company.id).order('created_at',{ascending:false}).limit(100),supabase.from('employee_commissions').select('*,employees(full_name),work_orders(number,title)').eq('company_id',company.id).order('commission_date',{ascending:false}).limit(150)]);const err=r.find(x=>x.error)?.error;if(err)setMessage(err.message);else{setEmployees(r[0].data||[]);setOrders(r[1].data||[]);setRows(r[2].data||[])}}
  useEffect(()=>{load()},[company.id])
  const chooseEmployee=id=>{const e=employees.find(x=>x.id===id);setForm(v=>({...v,employee_id:id,rate:e?.commission_rate||''}))}
  const chooseOrder=id=>{const o=orders.find(x=>x.id===id);setForm(v=>({...v,work_order_id:id,base_amount:o?.total||''}))}
  const calc=()=>{const base=Number(form.base_amount||0),rate=Number(form.rate||0);return base*rate/100}
  const save=async e=>{e.preventDefault();const amount=Number(form.amount||0)||calc();const {error}=await supabase.from('employee_commissions').insert({...form,company_id:company.id,work_order_id:form.work_order_id||null,base_amount:Number(form.base_amount||0),rate:Number(form.rate||0),amount});if(error)setMessage(error.message);else{setMessage('Comisión registrada y disponible para la próxima planilla.');setForm({employee_id:'',work_order_id:'',commission_date:today(),concept:'Comisión por venta / trabajo',base_amount:'',rate:'',amount:'',notes:''});await load()}}
  return <section className="clients-module"><div className="clients-titlebar"><div><p className="form-kicker">INCENTIVOS</p><h2>Comisiones</h2><p>Registra comisiones de ventas o trabajos; las pendientes se proponen automáticamente al agregar el empleado a una planilla.</p></div></div>{message&&<p className="feedback success">{message}</p>}
    <form className="panel" onSubmit={save}><div className="form-grid three"><label className="field"><span>Empleado *</span><select required value={form.employee_id} onChange={e=>chooseEmployee(e.target.value)}><option value="">Seleccionar</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label className="field form-span-2"><span>Orden relacionada</span><select value={form.work_order_id} onChange={e=>chooseOrder(e.target.value)}><option value="">Sin orden</option>{orders.map(o=><option key={o.id} value={o.id}>OT-{String(o.number).padStart(5,'0')} · {o.clients?.name||'Cliente'} · {money(o.total)}</option>)}</select></label><label className="field"><span>Fecha</span><input type="date" value={form.commission_date} onChange={e=>setForm({...form,commission_date:e.target.value})}/></label><label className="field"><span>Base</span><input type="number" min="0" step="0.01" value={form.base_amount} onChange={e=>setForm({...form,base_amount:e.target.value})}/></label><label className="field"><span>Tasa %</span><input type="number" min="0" step="0.01" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/></label><label className="field"><span>Monto</span><input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder={`Calculado ${money(calc())}`}/></label><label className="field form-span-2"><span>Concepto *</span><input required value={form.concept} onChange={e=>setForm({...form,concept:e.target.value})}/></label></div><div className="form-actions end"><button>Registrar comisión</button></div></form>
    <section className="panel"><div className="panel-heading"><div><p className="form-kicker">HISTORIAL</p><h3>Comisiones registradas</h3></div></div>{rows.length?<div className="client-list">{rows.map(r=><div className="client-row" key={r.id}><div><strong>{r.employees?.full_name}</strong><small>{r.commission_date} · {r.concept} · {r.work_orders?.number?`OT-${String(r.work_orders.number).padStart(5,'0')}`:'Sin OT'}</small></div><div><strong>{money(r.amount)}</strong><small>{r.status}</small></div></div>)}</div>:<div className="empty-state"><strong>Sin comisiones</strong></div>}</section>
  </section>
}
