import { useEffect,useMemo,useState } from 'react'

const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const pct=v=>`${Number(v||0).toFixed(1)}%`
const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const today=()=>localDay(),monthStart=()=>`${today().slice(0,7)}-01`
const startOfDay=d=>`${d}T00:00:00`,endOfDay=d=>`${d}T23:59:59`
const sum=(rows,key)=>rows.reduce((s,r)=>s+Number(r?.[key]||0),0)
const openBalance=r=>Math.max(0,Number(r.amount_total||0)-Number(r.amount_paid||0))
const isOpen=r=>!['PAID','CANCELLED','VOID'].includes(String(r.status||'').toUpperCase())
const liveExpense=r=>!['VOID','CANCELLED'].includes(String(r.status||'ACTIVE').toUpperCase())
const liveOrder=r=>!['VOID','CANCELLED'].includes(String(r.status||'').toUpperCase())
const livePurchase=r=>!['VOID','CANCELLED'].includes(String(r.procurement_status||'').toUpperCase())
const nonMaterialCost=r=>!['MATERIAL','MATERIALS','INVENTORY'].includes(String(r.cost_type||'').toUpperCase())
const STATUS_LABELS={PENDING:'Pendiente',DESIGN:'Diseño',APPROVAL:'Aprobación',PRODUCTION:'Producción',READY:'Listo',DELIVERED:'Entregado'}

function openMainModule(name){[...document.querySelectorAll('.idealo-main-menu-item')].find(b=>b.textContent.trim().startsWith(name))?.click()}

export default function ExecutiveDashboard({company,supabase}){
 const [from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[data,setData]=useState({clients:[],quotes:[],orders:[],receivables:[],payments:[],reversals:[],purchases:[],expenses:[],payables:[],supplierPayments:[],cashAccounts:[],cashMoves:[],inventoryItems:[],inventoryMoves:[],orderCosts:[],dtes:[]})
 const load=async()=>{setLoading(true);setMessage('');const start=startOfDay(from),end=endOfDay(to);const q=[
  supabase.from('clients').select('id,name,status,created_at').eq('company_id',company.id),
  supabase.from('quotes').select('id,number,status,total,created_at').eq('company_id',company.id).gte('created_at',start).lte('created_at',end),
  supabase.from('work_orders').select('id,number,title,total,status,due_at,created_at,client_id,clients(name)').eq('company_id',company.id).order('created_at',{ascending:false}),
  supabase.from('accounts_receivable').select('id,amount_total,amount_paid,status,due_date').eq('company_id',company.id),
  supabase.from('customer_payments').select('id,amount,paid_at').eq('company_id',company.id).gte('paid_at',start).lte('paid_at',end),
  supabase.from('customer_payment_reversals').select('id,amount,reversed_at').eq('company_id',company.id).gte('reversed_at',start).lte('reversed_at',end),
  supabase.from('purchases').select('id,total,purchase_date,procurement_status').eq('company_id',company.id).gte('purchase_date',from).lte('purchase_date',to),
  supabase.from('expenses').select('id,amount,expense_date,category,status').eq('company_id',company.id).gte('expense_date',from).lte('expense_date',to),
  supabase.from('accounts_payable').select('id,amount_total,amount_paid,status,due_date').eq('company_id',company.id),
  supabase.from('supplier_payments').select('id,amount,paid_at').eq('company_id',company.id).gte('paid_at',start).lte('paid_at',end),
  supabase.from('cash_accounts').select('id,name,account_type,opening_balance,active').eq('company_id',company.id).eq('active',true),
  supabase.from('cash_movements').select('id,cash_account_id,movement_type,source_type,amount,movement_date').eq('company_id',company.id),
  supabase.from('inventory_items').select('id,name,unit,current_stock,average_cost,minimum_stock,active').eq('company_id',company.id).eq('active',true),
  supabase.from('inventory_movements').select('id,work_order_id,movement_type,quantity,unit_cost,created_at').eq('company_id',company.id).eq('movement_type','CONSUMPTION').gte('created_at',start).lte('created_at',end),
  supabase.from('work_order_costs').select('id,work_order_id,cost_type,amount,incurred_at').eq('company_id',company.id).gte('incurred_at',from).lte('incurred_at',to),
  supabase.from('dte_documents').select('id,status,environment,control_number,updated_at').eq('company_id',company.id).order('updated_at',{ascending:false}).limit(50)
 ];const r=await Promise.all(q);const errors=r.map((x,i)=>x.error?i:null).filter(i=>i!==null);if(errors.length){setMessage('Algunos indicadores no pudieron cargarse. Revisá permisos o conexión.')}setData({clients:r[0].data||[],quotes:r[1].data||[],orders:r[2].data||[],receivables:r[3].data||[],payments:r[4].data||[],reversals:r[5].data||[],purchases:r[6].data||[],expenses:r[7].data||[],payables:r[8].data||[],supplierPayments:r[9].data||[],cashAccounts:r[10].data||[],cashMoves:r[11].data||[],inventoryItems:r[12].data||[],inventoryMoves:r[13].data||[],orderCosts:r[14].data||[],dtes:r[15].data||[]});setLoading(false)}
 useEffect(()=>{load()},[company.id,from,to])

 const metrics=useMemo(()=>{const start=startOfDay(from),end=endOfDay(to),periodOrders=data.orders.filter(o=>liveOrder(o)&&o.created_at>=start&&o.created_at<=end),sales=sum(periodOrders,'total'),grossCollections=sum(data.payments,'amount'),reversed=sum(data.reversals,'amount'),collections=Math.max(0,grossCollections-reversed),purchases=sum(data.purchases.filter(livePurchase),'total'),expenses=sum(data.expenses.filter(liveExpense),'amount'),materialCost=data.inventoryMoves.reduce((s,m)=>s+Number(m.quantity||0)*Number(m.unit_cost||0),0),directCosts=sum(data.orderCosts.filter(nonMaterialCost),'amount'),grossProfit=sales-materialCost-directCosts,operatingProfit=grossProfit-expenses,margin=sales?operatingProfit/sales*100:0,arOpen=data.receivables.filter(isOpen).reduce((s,r)=>s+openBalance(r),0),apOpen=data.payables.filter(isOpen).reduce((s,r)=>s+openBalance(r),0),overdueAr=data.receivables.filter(r=>isOpen(r)&&r.due_date&&r.due_date<today()).reduce((s,r)=>s+openBalance(r),0),overdueAp=data.payables.filter(r=>isOpen(r)&&r.due_date&&r.due_date<today()).reduce((s,r)=>s+openBalance(r),0),cash=data.cashAccounts.reduce((t,a)=>t+Number(a.opening_balance||0)+data.cashMoves.filter(m=>m.cash_account_id===a.id).reduce((s,m)=>s+(['INCOME','TRANSFER_IN'].includes(m.movement_type)?Number(m.amount||0):-Number(m.amount||0)),0),0),activeOrders=data.orders.filter(o=>liveOrder(o)&&o.status!=='DELIVERED'),lateOrders=data.orders.filter(o=>liveOrder(o)&&o.status!=='DELIVERED'&&o.due_at&&new Date(o.due_at)<new Date()),lowStock=data.inventoryItems.filter(i=>Number(i.current_stock||0)<=Number(i.minimum_stock||0)),stockValue=data.inventoryItems.reduce((s,i)=>s+Number(i.current_stock||0)*Number(i.average_cost||0),0);return{periodOrders,sales,collections,reversed,purchases,expenses,materialCost,directCosts,grossProfit,operatingProfit,margin,arOpen,apOpen,overdueAr,overdueAp,cash,activeOrders,lateOrders,lowStock,stockValue}},[data,from,to])
 const production=useMemo(()=>Object.keys(STATUS_LABELS).map(status=>({status,count:data.orders.filter(o=>liveOrder(o)&&o.status===status).length})),[data.orders])
 const expenseGroups=useMemo(()=>Object.entries(data.expenses.filter(liveExpense).reduce((a,r)=>{a[r.category||'Otros']=(a[r.category||'Otros']||0)+Number(r.amount||0);return a},{})).sort((a,b)=>b[1]-a[1]),[data.expenses])
 const topOrders=useMemo(()=>metrics.periodOrders.map(o=>{const material=data.inventoryMoves.filter(m=>m.work_order_id===o.id).reduce((s,m)=>s+Number(m.quantity||0)*Number(m.unit_cost||0),0),direct=data.orderCosts.filter(c=>c.work_order_id===o.id&&nonMaterialCost(c)).reduce((s,c)=>s+Number(c.amount||0),0),cost=material+direct,profit=Number(o.total||0)-cost;return{...o,cost,profit,margin:Number(o.total||0)?profit/Number(o.total)*100:0}}).sort((a,b)=>b.profit-a.profit).slice(0,8),[data,metrics.periodOrders])
 const quoteStats=useMemo(()=>({total:data.quotes.length,amount:sum(data.quotes,'total'),approved:data.quotes.filter(q=>['APPROVED','CONVERTED'].includes(q.status)).length,pending:data.quotes.filter(q=>['DRAFT','SENT'].includes(q.status)).length}),[data.quotes])
 const dteStats=useMemo(()=>({processed:data.dtes.filter(d=>['PROCESSED','RECEIVED'].includes(d.status)).length,rejected:data.dtes.filter(d=>d.status==='REJECTED').length,pending:data.dtes.filter(d=>!['PROCESSED','RECEIVED','REJECTED','INVALIDATED'].includes(d.status)).length,latest:data.dtes[0]}),[data.dtes])
 if(loading)return <section className="loading-card"><span className="spinner"/><p>Preparando el tablero ejecutivo…</p></section>
 return <section className="executive-dashboard">
  <div className="exec-head"><div><p className="form-kicker">CENTRO DE CONTROL · {company.name}</p><h2>Dashboard</h2><p>Datos reales del ERP, alineados con Finanzas, Caja, Producción e Inventario.</p></div><div className="exec-head-actions"><button type="button" className="exec-refresh" onClick={load}>Actualizar</button></div></div>
  <section className="panel exec-filter"><div className="exec-presets"><button onClick={()=>{const d=today();setFrom(d);setTo(d)}}>Hoy</button><button onClick={()=>{setFrom(monthStart());setTo(today())}}>Mes</button></div><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></section>
  {message&&<p className="feedback error">{message}</p>}
  <div className="exec-kpis"><Kpi label="Ventas" value={money(metrics.sales)} note={`${metrics.periodOrders.length} órdenes válidas`}/><Kpi label="Cobrado neto" value={money(metrics.collections)} note={`Reversado ${money(metrics.reversed)}`}/><Kpi label="Por cobrar" value={money(metrics.arOpen)} note={`${money(metrics.overdueAr)} vencido`}/><Kpi label="Caja + bancos" value={money(metrics.cash)} note={`${data.cashAccounts.length} cuentas activas`}/><Kpi label="Utilidad operativa" value={money(metrics.operatingProfit)} note={`Margen ${pct(metrics.margin)}`} tone={metrics.operatingProfit<0?'bad':'good'}/><Kpi label="Órdenes activas" value={metrics.activeOrders.length} note={`${metrics.lateOrders.length} atrasadas`} tone={metrics.lateOrders.length?'bad':''}/></div>
  <div className="exec-grid two"><Panel title="Resultado del período" kicker="FINANZAS"><div className="exec-statement"><Row label="Ventas" value={money(metrics.sales)}/><Row label="Material consumido" value={`- ${money(metrics.materialCost)}`}/><Row label="Otros costos directos" value={`- ${money(metrics.directCosts)}`}/><Row label="Gastos activos" value={`- ${money(metrics.expenses)}`}/><Row label="Utilidad operativa" value={money(metrics.operatingProfit)} strong/><Row label="Margen" value={pct(metrics.margin)} strong/></div></Panel><Panel title="Estado de producción" kicker="ÓRDENES DE TRABAJO"><div className="status-bars">{production.map(p=><div key={p.status}><span>{STATUS_LABELS[p.status]}</span><div><i style={{width:`${Math.min(100,p.count/Math.max(1,data.orders.filter(liveOrder).length)*100)}%`}}/></div><strong>{p.count}</strong></div>)}</div><button className="link-action" onClick={()=>openMainModule('Producción')}>Abrir Producción</button></Panel></div>
  <div className="exec-grid three"><Panel title="Liquidez" kicker="CAJA Y BANCOS"><Big value={money(metrics.cash)}/><SmallLine label="CxC abierta" value={money(metrics.arOpen)}/><SmallLine label="CxP abierta" value={money(metrics.apOpen)}/></Panel><Panel title="Inventario" kicker="ALMACÉN"><Big value={money(metrics.stockValue)}/><SmallLine label="Stock bajo / agotado" value={metrics.lowStock.length} danger={metrics.lowStock.length>0}/><SmallLine label="Materiales activos" value={data.inventoryItems.length}/></Panel><Panel title="Cotizaciones" kicker="COMERCIAL"><Big value={money(quoteStats.amount)}/><SmallLine label="Cotizaciones del período" value={quoteStats.total}/><SmallLine label="Aprobadas" value={quoteStats.approved}/></Panel></div>
  <div className="exec-grid two"><Panel title="Compras y gastos" kicker="CONTROL"><div className="exec-statement"><Row label="Compras válidas" value={money(metrics.purchases)}/><Row label="Gastos activos" value={money(metrics.expenses)}/><Row label="Pagos a proveedores" value={money(sum(data.supplierPayments,'amount'))}/><Row label="CxP pendiente" value={money(metrics.apOpen)} strong/></div></Panel><Panel title="Facturación electrónica" kicker="DTE"><div className="mini-kpis"><Mini label="Procesados" value={dteStats.processed}/><Mini label="Pendientes" value={dteStats.pending}/><Mini label="Rechazados" value={dteStats.rejected}/><Mini label="Total" value={data.dtes.length}/></div><div className="dte-health"><span>Ambiente</span><strong>{(dteStats.latest?.environment||'—').toUpperCase()}</strong><span>Último DTE</span><strong>{dteStats.latest?.control_number||'Sin documentos'}</strong></div></Panel></div>
  <Panel title="Rentabilidad por orden" kicker="TRABAJOS DEL PERÍODO">{topOrders.length?<div className="exec-table-wrap"><table className="exec-table"><thead><tr><th>Orden</th><th>Cliente</th><th>Venta</th><th>Costo real</th><th>Utilidad</th><th>Margen</th></tr></thead><tbody>{topOrders.map(o=><tr key={o.id}><td>OT-{String(o.number).padStart(5,'0')}</td><td>{o.clients?.name||'Cliente'}</td><td>{money(o.total)}</td><td>{money(o.cost)}</td><td className={o.profit<0?'negative':''}>{money(o.profit)}</td><td><span className={`margin-pill ${o.margin>=30?'good':o.margin>=0?'warn':'bad'}`}>{pct(o.margin)}</span></td></tr>)}</tbody></table></div>:<div className="exec-empty"><span>Sin órdenes válidas en el período.</span></div>}</Panel>
  <div className="exec-grid two"><Panel title="Gastos por categoría" kicker="OPERACIÓN">{expenseGroups.length?<div className="expense-list">{expenseGroups.slice(0,8).map(([name,value])=><div key={name}><span>{name}</span><div><i style={{width:`${Math.min(100,value/Math.max(1,expenseGroups[0][1])*100)}%`}}/></div><strong>{money(value)}</strong></div>)}</div>:<div className="exec-empty"><span>Sin gastos activos en el período.</span></div>}</Panel><Panel title="Estado general" kicker="CONTROL"><div className="system-list"><SmallLine label="Clientes" value={data.clients.filter(c=>!['INACTIVE','DELETED'].includes(String(c.status||'ACTIVE').toUpperCase())).length}/><SmallLine label="Cotizaciones pendientes" value={quoteStats.pending}/><SmallLine label="Órdenes atrasadas" value={metrics.lateOrders.length} danger={metrics.lateOrders.length>0}/><SmallLine label="DTE rechazados" value={dteStats.rejected} danger={dteStats.rejected>0}/></div></Panel></div>
  <Panel title="Acciones rápidas" kicker="OPERAR"><div className="quick-actions">{['Clientes','Cotizaciones','Producción','Inventario','Compras','Caja','Facturación','Reportes'].map(name=><button key={name} onClick={()=>openMainModule(name)}>{name}</button>)}</div></Panel>
 </section>
}
function Kpi({label,value,note,tone=''}){return <article className={`exec-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Panel({title,kicker,children}){return <section className="panel exec-panel"><div className="exec-panel-head"><div><p className="form-kicker">{kicker}</p><h3>{title}</h3></div></div>{children}</section>}
function Row({label,value,strong}){return <div className={strong?'strong':''}><span>{label}</span><b>{value}</b></div>}
function Mini({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Big({value}){return <div className="big-number">{value}</div>}
function SmallLine({label,value,danger}){return <div className="small-line"><span>{label}</span><strong className={danger?'danger':''}>{value}</strong></div>}
