import {useEffect,useState} from 'react'
const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const monthStart=()=>{const d=new Date();d.setDate(1);return localDate(d)}
export default function FinancialReportsPanel({company,supabase}){
 const [range,setRange]=useState({from:monthStart(),to:localDate()}),[data,setData]=useState(null),[alerts,setAlerts]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{setBusy(true);setMsg('');const [r,a]=await Promise.all([supabase.rpc('financial_report_summary',{p_company:company.id,p_from:range.from,p_to:range.to}),supabase.from('financial_integrity_alerts').select('*').eq('company_id',company.id).limit(100)]);if(r.error||a.error)setMsg(r.error?.message||a.error?.message);else{setData(r.data?.[0]||null);setAlerts(a.data||[])}setBusy(false)}
 useEffect(()=>{load()},[company.id])
 const exportCsv=()=>{if(!data)return;const rows=[['Indicador','Valor'],['Ventas',data.sales],['Compras',data.purchases],['Ingresos de caja',data.cash_income],['Salidas de caja',data.cash_expense],['Flujo neto',data.cash_net],['CxC pendiente',data.receivable_balance],['CxP pendiente',data.payable_balance],['Disponible',data.available_cash],['Conciliaciones con diferencia',data.reconciliations_with_difference],['Cierres diarios',data.closed_days]];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`reporte-financiero-${range.from}-${range.to}.csv`;a.click();URL.revokeObjectURL(url)}
 return <section className="panel"><div className="panel-heading"><div><p className="form-kicker">REPORTES Y FINANZAS</p><h3>Resumen financiero consolidado</h3><p>Ventas, compras, caja, cartera, obligaciones y alertas de integridad en un solo corte.</p></div><button type="button" className="secondary-button" onClick={exportCsv} disabled={!data}>Exportar CSV</button></div>
 <div className="form-grid three"><label className="field"><span>Desde</span><input type="date" value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/></label><label className="field"><span>Hasta</span><input type="date" value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/></label><div className="form-actions end"><button type="button" onClick={load} disabled={busy}>{busy?'Calculando…':'Actualizar reporte'}</button></div></div>
 {msg&&<p className="feedback error">{msg}</p>}{data&&<><div className="metrics-grid"><article className="metric-card"><span>Ventas</span><strong>{money(data.sales)}</strong></article><article className="metric-card"><span>Compras</span><strong>{money(data.purchases)}</strong></article><article className="metric-card"><span>Flujo neto</span><strong>{money(data.cash_net)}</strong></article><article className="metric-card"><span>Disponible</span><strong>{money(data.available_cash)}</strong></article></div><div className="metrics-grid"><article className="metric-card"><span>CxC pendiente</span><strong>{money(data.receivable_balance)}</strong></article><article className="metric-card"><span>CxP pendiente</span><strong>{money(data.payable_balance)}</strong></article><article className="metric-card"><span>Diferencias</span><strong>{data.reconciliations_with_difference||0}</strong></article><article className="metric-card"><span>Cierres diarios</span><strong>{data.closed_days||0}</strong></article></div></>}
 <div className="panel-heading"><div><p className="form-kicker">AUDITORÍA AUTOMÁTICA</p><h3>Alertas financieras</h3></div><span className={alerts.length?'status dte-pending':'status dte-ready'}>{alerts.length} alertas</span></div>{alerts.length?<div className="client-list">{alerts.map((a,i)=><div className="client-row" key={`${a.alert_type}-${a.source_id}-${i}`}><div><strong>{a.detail}</strong><small>{a.alert_type.replaceAll('_',' ')}</small></div><strong>{money(a.amount)}</strong></div>)}</div>:<div className="empty-state"><strong>Sin inconsistencias financieras detectadas</strong></div>}
 </section>
}
