import { useEffect,useMemo,useState } from 'react'
const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const pct=v=>`${Number(v||0).toFixed(1)}%`
const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const today=()=>localDay(),monthStart=()=>`${today().slice(0,7)}-01`
const csvCell=v=>`"${String(v??'').replaceAll('"','""')}"`
export default function FinancialDashboard({company,supabase,view='Resultados'}){
 const [from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 const [data,setData]=useState({orders:[],receivables:[],customerPayments:[],reversals:[],purchases:[],expenses:[],payables:[],supplierPayments:[],cashAccounts:[],cashMoves:[],inventoryMoves:[],orderCosts:[]})
 useEffect(()=>{(async()=>{setLoading(true);setMessage('');const start=`${from}T00:00:00`,end=`${to}T23:59:59`,r=await Promise.all([
  supabase.from('work_orders').select('id,number,title,total,status,created_at,client_id,clients(name)').eq('company_id',company.id).gte('created_at',start).lte('created_at',end),
  supabase.from('accounts_receivable').select('id,amount_total,amount_paid,status,due_date,created_at').eq('company_id',company.id),
  supabase.from('customer_payments').select('id,amount,paid_at,payment_method').eq('company_id',company.id).gte('paid_at',start).lte('paid_at',end),
  supabase.from('customer_payment_reversals').select('id,amount,reversed_at').eq('company_id',company.id).gte('reversed_at',start).lte('reversed_at',end),
  supabase.from('purchases').select('id,total,purchase_date,payment_status').eq('company_id',company.id).gte('purchase_date',from).lte('purchase_date',to),
  supabase.from('expenses').select('id,amount,expense_date,category').eq('company_id',company.id).gte('expense_date',from).lte('expense_date',to),
  supabase.from('accounts_payable').select('id,amount_total,amount_paid,status,due_date,created_at').eq('company_id',company.id),
  supabase.from('supplier_payments').select('id,amount,paid_at,payment_method').eq('company_id',company.id).gte('paid_at',start).lte('paid_at',end),
  supabase.from('cash_accounts').select('id,name,account_type,opening_balance,active').eq('company_id',company.id).eq('active',true),
  supabase.from('cash_movements').select('id,cash_account_id,movement_type,source_type,amount,movement_date,concept').eq('company_id',company.id),
  supabase.from('inventory_movements').select('id,work_order_id,movement_type,quantity,unit_cost,created_at').eq('company_id',company.id).eq('movement_type','CONSUMPTION').gte('created_at',start).lte('created_at',end),
  supabase.from('work_order_costs').select('id,work_order_id,cost_type,amount,incurred_at').eq('company_id',company.id).gte('incurred_at',from).lte('incurred_at',to)
 ]);const err=r.find(x=>x.error)?.error;if(err)setMessage(err.message);else setData({orders:r[0].data||[],receivables:r[1].data||[],customerPayments:r[2].data||[],reversals:r[3].data||[],purchases:r[4].data||[],expenses:r[5].data||[],payables:r[6].data||[],supplierPayments:r[7].data||[],cashAccounts:r[8].data||[],cashMoves:r[9].data||[],inventoryMoves:r[10].data||[],orderCosts:r[11].data||[]});setLoading(false)})()},[company.id,from,to,supabase])
 const m=useMemo(()=>{const sales=data.orders.reduce((s,r)=>s+Number(r.total||0),0),grossCollections=data.customerPayments.reduce((s,r)=>s+Number(r.amount||0),0),reversed=data.reversals.reduce((s,r)=>s+Number(r.amount||0),0),collections=grossCollections-reversed,purchases=data.purchases.reduce((s,r)=>s+Number(r.total||0),0),expenses=data.expenses.reduce((s,r)=>s+Number(r.amount||0),0),supplierPaid=data.supplierPayments.reduce((s,r)=>s+Number(r.amount||0),0),materialCost=data.inventoryMoves.reduce((s,r)=>s+Number(r.quantity||0)*Number(r.unit_cost||0),0),directCosts=data.orderCosts.reduce((s,r)=>s+Number(r.amount||0),0),realCost=materialCost+directCosts,grossProfit=sales-realCost,operatingProfit=grossProfit-expenses,margin=sales?operatingProfit/sales*100:0,arOpen=data.receivables.filter(r=>!['PAID','CANCELLED','VOID'].includes(r.status)).reduce((s,r)=>s+Math.max(0,Number(r.amount_total||0)-Number(r.amount_paid||0)),0),apOpen=data.payables.filter(r=>!['PAID','CANCELLED','VOID'].includes(r.status)).reduce((s,r)=>s+Math.max(0,Number(r.amount_total||0)-Number(r.amount_paid||0)),0),overdueAr=data.receivables.filter(r=>r.due_date&&r.due_date<today()&&!['PAID','CANCELLED','VOID'].includes(r.status)).reduce((s,r)=>s+Math.max(0,Number(r.amount_total||0)-Number(r.amount_paid||0)),0),overdueAp=data.payables.filter(r=>r.due_date&&r.due_date<today()&&!['PAID','CANCELLED','VOID'].includes(r.status)).reduce((s,r)=>s+Math.max(0,Number(r.amount_total||0)-Number(r.amount_paid||0)),0),cash=data.cashAccounts.reduce((t,a)=>t+Number(a.opening_balance||0)+data.cashMoves.filter(x=>x.cash_account_id===a.id).reduce((s,x)=>s+(['INCOME','TRANSFER_IN'].includes(x.movement_type)?Number(x.amount||0):-Number(x.amount||0)),0),0),periodMoves=data.cashMoves.filter(x=>{const d=localDay(new Date(x.movement_date));return d>=from&&d<=to}),cashIn=periodMoves.filter(x=>x.movement_type==='INCOME').reduce((s,x)=>s+Number(x.amount||0),0),cashOut=periodMoves.filter(x=>x.movement_type==='EXPENSE').reduce((s,x)=>s+Number(x.amount||0),0),netCash=cashIn-cashOut;return{sales,collections,reversed,purchases,expenses,supplierPaid,materialCost,directCosts,grossProfit,operatingProfit,margin,arOpen,apOpen,overdueAr,overdueAp,cash,cashIn,cashOut,netCash}},[data,from,to])
 const orders=useMemo(()=>data.orders.map(o=>{const cost=data.inventoryMoves.filter(x=>x.work_order_id===o.id).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.unit_cost||0),0)+data.orderCosts.filter(x=>x.work_order_id===o.id).reduce((s,x)=>s+Number(x.amount||0),0),profit=Number(o.total||0)-cost;return{...o,cost,profit,margin:Number(o.total||0)?profit/Number(o.total)*100:0}}).sort((a,b)=>b.profit-a.profit),[data])
 const exportCsv=()=>{const rows=[['IDEALO SV - Reporte financiero'],['Empresa',company.name],['Periodo',from,to],[],['Indicador','Valor'],['Ventas',m.sales],['Cobros netos',m.collections],['Reversiones de cobros',m.reversed],['Compras',m.purchases],['Gastos',m.expenses],['Utilidad operativa',m.operatingProfit],['Caja y bancos',m.cash],['CxC abierta',m.arOpen],['CxP abierta',m.apOpen],['Entradas de efectivo',m.cashIn],['Salidas de efectivo',m.cashOut],['Flujo neto',m.netCash],[],['Orden','Cliente','Venta','Costo','Utilidad','Margen %'],...orders.map(o=>[`OT-${String(o.number).padStart(5,'0')}`,o.clients?.name||'',o.total,o.cost,o.profit,o.margin.toFixed(2)])];const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`idealo-reporte-${from}-${to}.csv`;a.click();URL.revokeObjectURL(url)}
 if(loading)return <section className="loading-card"><span className="spinner"/><p>Calculando reportes…</p></section>
 return <section className="clients-module financial-dashboard"><div className="clients-titlebar"><div><p className="form-kicker">REPORTES</p><h2>{view}</h2><p>Información financiera separada por objetivo para facilitar decisiones.</p></div><div className="client-actions"><button type="button" className="secondary-button" onClick={exportCsv}>Exportar CSV</button><button type="button" className="secondary-button" onClick={()=>window.print()}>Imprimir / PDF</button></div></div><section className="panel finance-filter"><div className="form-grid three"><label className="field"><span>Desde</span><input type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label className="field"><span>Hasta</span><input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><div className="field"><span>Periodo</span><strong>{from} → {to}</strong></div></div></section>{message&&<p className="feedback error">{message}</p>}
 {view==='Resultados'&&<><div className="metrics-grid finance-kpis"><article className="metric-card"><span>Ventas</span><strong>{money(m.sales)}</strong></article><article className="metric-card"><span>Cobros netos</span><strong>{money(m.collections)}</strong><small>Reversado {money(m.reversed)}</small></article><article className="metric-card"><span>Utilidad operativa</span><strong>{money(m.operatingProfit)}</strong><small>Margen {pct(m.margin)}</small></article><article className="metric-card"><span>Gastos</span><strong>{money(m.expenses)}</strong></article></div><section className="panel"><div className="finance-statement"><div><span>Ventas</span><strong>{money(m.sales)}</strong></div><div><span>(-) Materiales</span><strong>{money(m.materialCost)}</strong></div><div><span>(-) Costos directos</span><strong>{money(m.directCosts)}</strong></div><div><span>(-) Gastos</span><strong>{money(m.expenses)}</strong></div><div className="total"><span>UTILIDAD OPERATIVA</span><strong>{money(m.operatingProfit)}</strong></div></div></section></>}
 {view==='Liquidez'&&<><div className="metrics-grid finance-kpis"><article className="metric-card"><span>Caja + bancos</span><strong>{money(m.cash)}</strong></article><article className="metric-card"><span>CxC</span><strong>{money(m.arOpen)}</strong></article><article className="metric-card"><span>CxP</span><strong>{money(m.apOpen)}</strong></article><article className="metric-card"><span>Liquidez neta</span><strong>{money(m.cash+m.arOpen-m.apOpen)}</strong></article></div><section className="panel"><div className="finance-statement"><div><span>CxC vencidas</span><strong>{money(m.overdueAr)}</strong></div><div><span>CxP vencidas</span><strong>{money(m.overdueAp)}</strong></div><div><span>Compras del periodo</span><strong>{money(m.purchases)}</strong></div><div><span>Pagos a proveedores</span><strong>{money(m.supplierPaid)}</strong></div></div></section><section className="panel"><div className="panel-heading"><div><p className="form-kicker">FLUJO DE EFECTIVO</p><h3>Movimiento real del periodo</h3></div></div><div className="finance-statement"><div><span>Entradas</span><strong>{money(m.cashIn)}</strong></div><div><span>Salidas</span><strong>{money(m.cashOut)}</strong></div><div className="total"><span>FLUJO NETO</span><strong>{money(m.netCash)}</strong></div></div></section></>}
 {view==='Rentabilidad'&&<section className="panel"><div className="panel-heading"><div><p className="form-kicker">POR ORDEN</p><h3>Rentabilidad de trabajos</h3></div></div>{orders.length?<div className="client-table-wrap"><table className="client-table"><thead><tr><th>Orden</th><th>Venta</th><th>Costo real</th><th>Utilidad</th><th>Margen</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>OT-{String(o.number).padStart(5,'0')} · {o.clients?.name||'Cliente'}</td><td>{money(o.total)}</td><td>{money(o.cost)}</td><td>{money(o.profit)}</td><td><span className={o.margin>=30?'status dte-ready':o.margin>=0?'status':'status dte-pending'}>{pct(o.margin)}</span></td></tr>)}</tbody></table></div>:<div className="empty-state"><strong>Sin órdenes en el periodo</strong></div>}</section>}
 </section>
}
