import { useEffect, useMemo, useState } from 'react'

const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const today=()=>new Date().toISOString().slice(0,10)
const monthStart=()=>`${today().slice(0,7)}-01`

export function EmployeesModule({company,supabase}){
  const [rows,setRows]=useState([]),[message,setMessage]=useState('')
  const [form,setForm]=useState({employee_code:'',full_name:'',document_number:'',phone:'',email:'',position:'PRODUCTION',employment_type:'EMPLOYEE',salary_type:'MONTHLY',base_salary:'',hourly_cost:'',commission_rate:'',hire_date:today(),notes:''})
  const load=async()=>{const {data,error}=await supabase.from('employees').select('*').eq('company_id',company.id).order('full_name');if(error)setMessage(error.message);else setRows(data||[])}
  useEffect(()=>{load()},[company.id])
  const save=async e=>{e.preventDefault();const payload={...form,company_id:company.id,employee_code:form.employee_code.trim()||null,base_salary:Number(form.base_salary||0),hourly_cost:Number(form.hourly_cost||0),commission_rate:Number(form.commission_rate||0),hire_date:form.hire_date||null};const {error}=await supabase.from('employees').insert(payload);if(error)setMessage(error.message);else{setMessage('Empleado registrado.');setForm({employee_code:'',full_name:'',document_number:'',phone:'',email:'',position:'PRODUCTION',employment_type:'EMPLOYEE',salary_type:'MONTHLY',base_salary:'',hourly_cost:'',commission_rate:'',hire_date:today(),notes:''});await load()}}
  const toggle=async r=>{const {error}=await supabase.from('employees').update({active:!r.active,updated_at:new Date().toISOString()}).eq('id',r.id);setMessage(error?error.message:'Estado actualizado.');if(!error)await load()}
  return <section className="clients-module"><div className="clients-titlebar"><div><p className="form-kicker">PERSONAL</p><h2>Empleados y colaboradores</h2><p>Personal de diseño, impresión, sublimación, producción, instalación, ventas y administración.</p></div><span className="status dte-ready">{rows.filter(r=>r.active).length} activos</span></div>
    {message&&<p className="feedback success">{message}</p>}
    <form className="panel" onSubmit={save}><div className="form-grid three"><label className="field"><span>Código</span><input value={form.employee_code} onChange={e=>setForm({...form,employee_code:e.target.value})}/></label><label className="field form-span-2"><span>Nombre completo *</span><input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label className="field"><span>DUI / documento</span><input value={form.document_number} onChange={e=>setForm({...form,document_number:e.target.value})}/></label><label className="field"><span>Teléfono</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="field"><span>Correo</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field"><span>Área / cargo</span><select value={form.position} onChange={e=>setForm({...form,position:e.target.value})}><option value="PRODUCTION">Producción</option><option value="DESIGN">Diseño</option><option value="PRINTING">Impresión</option><option value="SUBLIMATION">Sublimación</option><option value="INSTALLATION">Instalación</option><option value="SALES">Ventas</option><option value="ADMIN">Administración</option><option value="OTHER">Otro</option></select></label><label className="field"><span>Vinculación</span><select value={form.employment_type} onChange={e=>setForm({...form,employment_type:e.target.value})}><option value="EMPLOYEE">Empleado</option><option value="CONTRACTOR">Contratista</option></select></label><label className="field"><span>Tipo salario</span><select value={form.salary_type} onChange={e=>setForm({...form,salary_type:e.target.value})}><option value="MONTHLY">Mensual</option><option value="DAILY">Diario</option><option value="HOURLY">Por hora</option></select></label><label className="field"><span>Salario base</span><input type="number" min="0" step="0.01" value={form.base_salary} onChange={e=>setForm({...form,base_salary:e.target.value})}/></label><label className="field"><span>Costo interno por hora</span><input type="number" min="0" step="0.01" value={form.hourly_cost} onChange={e=>setForm({...form,hourly_cost:e.target.value})}/></label><label className="field"><span>Comisión %</span><input type="number" min="0" step="0.01" value={form.commission_rate} onChange={e=>setForm({...form,commission_rate:e.target.value})}/></label><label className="field"><span>Ingreso</span><input type="date" value={form.hire_date} onChange={e=>setForm({...form,hire_date:e.target.value})}/></label></div><div className="form-actions end"><button>Guardar empleado</button></div></form>
    <section className="panel"><div className="panel-heading"><div><p className="form-kicker">EQUIPO</p><h3>Personal registrado</h3></div></div>{rows.length?<div className="client-list">{rows.map(r=><div className="client-row" key={r.id}><div><strong>{r.full_name}</strong><small>{r.position} · {r.salary_type} · costo/h {money(r.hourly_cost)}</small></div><div><strong>{r.active?'ACTIVO':'INACTIVO'}</strong><button onClick={()=>toggle(r)}>{r.active?'Desactivar':'Activar'}</button></div></div>)}</div>:<div className="empty-state"><strong>Sin empleados registrados</strong></div>}</section>
  </section>
}

export function AttendanceLaborModule({company,supabase}){
  const [employees,setEmployees]=useState([]),[orders,setOrders]=useState([]),[attendance,setAttendance]=useState([]),[allocations,setAllocations]=useState([]),[message,setMessage]=useState('')
  const [att,setAtt]=useState({employee_id:'',work_date:today(),check_in:'08:00',check_out:'17:00',break_minutes:'60',status:'PRESENT',notes:''})
  const [labor,setLabor]=useState({employee_id:'',work_order_id:'',work_date:today(),hours:'',hourly_cost:'',notes:''})
  const load=async()=>{const r=await Promise.all([supabase.from('employees').select('*').eq('company_id',company.id).eq('active',true).order('full_name'),supabase.from('work_orders').select('id,number,title,clients(name)').eq('company_id',company.id).order('created_at',{ascending:false}).limit(100),supabase.from('attendance_records').select('*,employees(full_name)').eq('company_id',company.id).order('work_date',{ascending:false}).limit(100),supabase.from('labor_allocations').select('*,employees(full_name),work_orders(number,title)').eq('company_id',company.id).order('work_date',{ascending:false}).limit(100)]);const err=r.find(x=>x.error)?.error;if(err)setMessage(err.message);else{setEmployees(r[0].data||[]);setOrders(r[1].data||[]);setAttendance(r[2].data||[]);setAllocations(r[3].data||[])}}
  useEffect(()=>{load()},[company.id])
  const saveAttendance=async e=>{e.preventDefault();const {error}=await supabase.from('attendance_records').upsert({...att,company_id:company.id,break_minutes:Number(att.break_minutes||0),check_in:att.check_in||null,check_out:att.check_out||null},{onConflict:'company_id,employee_id,work_date'});if(error)setMessage(error.message);else{setMessage('Asistencia guardada.');await load()}}
  const chooseEmployee=id=>{const emp=employees.find(x=>x.id===id);setLabor(v=>({...v,employee_id:id,hourly_cost:emp?.hourly_cost||''}))}
  const saveLabor=async e=>{e.preventDefault();const {error}=await supabase.from('labor_allocations').insert({...labor,company_id:company.id,hours:Number(labor.hours||0),hourly_cost:Number(labor.hourly_cost||0)});if(error)setMessage(error.message);else{setMessage('Horas cargadas a la orden y costo de mano de obra actualizado.');setLabor({employee_id:'',work_order_id:'',work_date:today(),hours:'',hourly_cost:'',notes:''});await load()}}
  const totalHours=useMemo(()=>allocations.reduce((s,r)=>s+Number(r.hours||0),0),[allocations]);const totalLabor=useMemo(()=>allocations.reduce((s,r)=>s+Number(r.amount||0),0),[allocations])
  return <section className="clients-module"><div className="clients-titlebar"><div><p className="form-kicker">TIEMPO Y PRODUCCIÓN</p><h2>Asistencia y mano de obra</h2><p>Registra presencia y carga horas reales a cada orden para conocer su costo verdadero.</p></div></div><div className="metrics-grid"><article className="metric-card"><span>Horas cargadas</span><strong>{totalHours.toFixed(1)}</strong></article><article className="metric-card"><span>Costo mano de obra</span><strong>{money(totalLabor)}</strong></article><article className="metric-card"><span>Registros asistencia</span><strong>{attendance.length}</strong></article></div>{message&&<p className="feedback success">{message}</p>}
    <div className="module-grid two-column"><form className="panel" onSubmit={saveAttendance}><div className="panel-heading"><div><p className="form-kicker">ASISTENCIA</p><h3>Entrada / salida</h3></div></div><div className="form-grid"><label className="field form-span-2"><span>Empleado *</span><select required value={att.employee_id} onChange={e=>setAtt({...att,employee_id:e.target.value})}><option value="">Seleccionar</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label className="field"><span>Fecha</span><input type="date" value={att.work_date} onChange={e=>setAtt({...att,work_date:e.target.value})}/></label><label className="field"><span>Estado</span><select value={att.status} onChange={e=>setAtt({...att,status:e.target.value})}><option value="PRESENT">Presente</option><option value="ABSENT">Ausente</option><option value="LEAVE">Permiso</option><option value="REST">Descanso</option></select></label><label className="field"><span>Entrada</span><input type="time" value={att.check_in} onChange={e=>setAtt({...att,check_in:e.target.value})}/></label><label className="field"><span>Salida</span><input type="time" value={att.check_out} onChange={e=>setAtt({...att,check_out:e.target.value})}/></label><label className="field"><span>Descanso min.</span><input type="number" min="0" value={att.break_minutes} onChange={e=>setAtt({...att,break_minutes:e.target.value})}/></label></div><div className="form-actions end"><button>Guardar asistencia</button></div></form>
      <form className="panel" onSubmit={saveLabor}><div className="panel-heading"><div><p className="form-kicker">COSTEO POR ORDEN</p><h3>Cargar horas trabajadas</h3></div></div><div className="form-grid"><label className="field form-span-2"><span>Empleado *</span><select required value={labor.employee_id} onChange={e=>chooseEmployee(e.target.value)}><option value="">Seleccionar</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label className="field form-span-2"><span>Orden *</span><select required value={labor.work_order_id} onChange={e=>setLabor({...labor,work_order_id:e.target.value})}><option value="">Seleccionar</option>{orders.map(o=><option key={o.id} value={o.id}>OT-{String(o.number).padStart(5,'0')} · {o.clients?.name||'Cliente'} · {o.title}</option>)}</select></label><label className="field"><span>Fecha</span><input type="date" value={labor.work_date} onChange={e=>setLabor({...labor,work_date:e.target.value})}/></label><label className="field"><span>Horas *</span><input required type="number" min="0.01" step="0.25" value={labor.hours} onChange={e=>setLabor({...labor,hours:e.target.value})}/></label><label className="field"><span>Costo/hora *</span><input required type="number" min="0" step="0.01" value={labor.hourly_cost} onChange={e=>setLabor({...labor,hourly_cost:e.target.value})}/></label></div><div className="form-actions end"><button>Cargar a la orden</button></div></form></div>
    <section className="panel"><div className="panel-heading"><div><p className="form-kicker">ÚLTIMAS HORAS</p><h3>Mano de obra por OT</h3></div></div>{allocations.length?<div className="client-list">{allocations.slice(0,30).map(r=><div className="client-row" key={r.id}><div><strong>{r.employees?.full_name} · OT-{String(r.work_orders?.number||0).padStart(5,'0')}</strong><small>{r.work_date} · {r.hours} h · {r.work_orders?.title}</small></div><div><strong>{money(r.amount)}</strong></div></div>)}</div>:<div className="empty-state"><strong>Sin horas asignadas</strong></div>}</section>
  </section>
}

export function PayrollModule({company,supabase}){
  const [employees,setEmployees]=useState([]),[runs,setRuns]=useState([]),[items,setItems]=useState([]),[accounts,setAccounts]=useState([]),[commissions,setCommissions]=useState([]),[selected,setSelected]=useState(''),[message,setMessage]=useState('')
  const [runForm,setRunForm]=useState({period_start:monthStart(),period_end:today(),notes:''});const [item,setItem]=useState({employee_id:'',base_pay:'',overtime_pay:'0',commissions:'0',bonuses:'0',deductions:'0',notes:''});const [cashAccount,setCashAccount]=useState('')
  const load=async()=>{const r=await Promise.all([supabase.from('employees').select('*').eq('company_id',company.id).eq('active',true).order('full_name'),supabase.from('payroll_runs').select('*').eq('company_id',company.id).order('period_end',{ascending:false}),supabase.from('payroll_items').select('*,employees(full_name)').eq('company_id',company.id).order('created_at',{ascending:false}),supabase.from('cash_accounts').select('*').eq('company_id',company.id).eq('active',true).order('name'),supabase.from('employee_commissions').select('*').eq('company_id',company.id).eq('status','PENDING')]);const err=r.find(x=>x.error)?.error;if(err)setMessage(err.message);else{setEmployees(r[0].data||[]);setRuns(r[1].data||[]);setItems(r[2].data||[]);setAccounts(r[3].data||[]);setCommissions(r[4].data||[]);setCashAccount(v=>v||r[3].data?.[0]?.id||'');setSelected(v=>v||r[1].data?.[0]?.id||'')}}
  useEffect(()=>{load()},[company.id]);const current=runs.find(x=>x.id===selected);const currentItems=items.filter(x=>x.payroll_run_id===selected)
  const createRun=async e=>{e.preventDefault();const {data,error}=await supabase.from('payroll_runs').insert({...runForm,company_id:company.id}).select().single();if(error)setMessage(error.message);else{setMessage('Planilla creada.');setSelected(data.id);await load()}}
  const chooseEmployee=id=>{const emp=employees.find(x=>x.id===id);const comm=commissions.filter(c=>c.employee_id===id&&(!current||c.commission_date>=current.period_start&&c.commission_date<=current.period_end)).reduce((s,c)=>s+Number(c.amount||0),0);setItem(v=>({...v,employee_id:id,base_pay:emp?.base_salary||'',commissions:comm.toFixed(2)}))}
  const addItem=async e=>{e.preventDefault();if(!selected)return setMessage('Crea o selecciona una planilla.');const payload={...item,company_id:company.id,payroll_run_id:selected,base_pay:Number(item.base_pay||0),overtime_pay:Number(item.overtime_pay||0),commissions:Number(item.commissions||0),bonuses:Number(item.bonuses||0),deductions:Number(item.deductions||0)};const {error}=await supabase.from('payroll_items').upsert(payload,{onConflict:'payroll_run_id,employee_id'});if(error)setMessage(error.message);else{setMessage('Empleado agregado a planilla.');setItem({employee_id:'',base_pay:'',overtime_pay:'0',commissions:'0',bonuses:'0',deductions:'0',notes:''});await load()}}
  const pay=async()=>{if(!selected||!cashAccount)return setMessage('Selecciona planilla y caja/banco.');const {error}=await supabase.rpc('pay_payroll_run',{target_run_id:selected,target_cash_account_id:cashAccount});if(error)setMessage(error.message);else{setMessage('Planilla pagada y salida registrada en Caja/Banco.');await load()}}
  return <section className="clients-module"><div className="clients-titlebar"><div><p className="form-kicker">PLANILLA OPERATIVA</p><h2>Planilla, comisiones y pago</h2><p>Consolida salario, horas extra, comisiones, bonos y deducciones internas; el pago sale de Caja/Banco.</p></div><span className="status">No sustituye cálculo legal de ISSS/AFP/renta</span></div>{message&&<p className="feedback success">{message}</p>}
    <div className="module-grid two-column"><form className="panel" onSubmit={createRun}><div className="panel-heading"><div><p className="form-kicker">PERIODO</p><h3>Nueva planilla</h3></div></div><div className="form-grid"><label className="field"><span>Desde</span><input type="date" value={runForm.period_start} onChange={e=>setRunForm({...runForm,period_start:e.target.value})}/></label><label className="field"><span>Hasta</span><input type="date" value={runForm.period_end} onChange={e=>setRunForm({...runForm,period_end:e.target.value})}/></label></div><div className="form-actions end"><button>Crear planilla</button></div></form>
      <section className="panel"><div className="panel-heading"><div><p className="form-kicker">PLANILLAS</p><h3>Seleccionar periodo</h3></div></div><label className="field"><span>Planilla</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Seleccionar</option>{runs.map(r=><option key={r.id} value={r.id}>{r.period_start} → {r.period_end} · {r.status} · {money(r.net_total)}</option>)}</select></label>{current&&<div className="metrics-grid"><article className="metric-card"><span>Bruto</span><strong>{money(current.gross_total)}</strong></article><article className="metric-card"><span>Deducciones</span><strong>{money(current.deductions_total)}</strong></article><article className="metric-card"><span>Neto</span><strong>{money(current.net_total)}</strong></article></div>}</section></div>
    <form className="panel" onSubmit={addItem}><div className="panel-heading"><div><p className="form-kicker">DETALLE</p><h3>Agregar empleado a planilla</h3></div></div><div className="form-grid three"><label className="field form-span-2"><span>Empleado *</span><select required value={item.employee_id} onChange={e=>chooseEmployee(e.target.value)}><option value="">Seleccionar</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label><label className="field"><span>Salario base</span><input type="number" min="0" step="0.01" value={item.base_pay} onChange={e=>setItem({...item,base_pay:e.target.value})}/></label><label className="field"><span>Horas extra $</span><input type="number" min="0" step="0.01" value={item.overtime_pay} onChange={e=>setItem({...item,overtime_pay:e.target.value})}/></label><label className="field"><span>Comisiones</span><input type="number" min="0" step="0.01" value={item.commissions} onChange={e=>setItem({...item,commissions:e.target.value})}/></label><label className="field"><span>Bonos</span><input type="number" min="0" step="0.01" value={item.bonuses} onChange={e=>setItem({...item,bonuses:e.target.value})}/></label><label className="field"><span>Deducciones</span><input type="number" min="0" step="0.01" value={item.deductions} onChange={e=>setItem({...item,deductions:e.target.value})}/></label></div><div className="form-actions end"><button>Agregar / actualizar</button></div></form>
    {current&&current.status!=='PAID'&&<section className="panel payroll-pay"><div><p className="form-kicker">PAGO</p><h3>Pagar planilla {money(current.net_total)}</h3><p>Genera una salida única en Caja/Banco y marca las comisiones incluidas como pagadas.</p></div><label className="field"><span>Sale de</span><select value={cashAccount} onChange={e=>setCashAccount(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button type="button" onClick={pay}>Pagar planilla</button></section>}
    <section className="panel"><div className="panel-heading"><div><p className="form-kicker">PERSONAL EN PLANILLA</p><h3>Detalle del periodo</h3></div></div>{currentItems.length?<div className="client-list">{currentItems.map(r=><div className="client-row" key={r.id}><div><strong>{r.employees?.full_name}</strong><small>Base {money(r.base_pay)} · extra {money(r.overtime_pay)} · comisiones {money(r.commissions)} · deducciones {money(r.deductions)}</small></div><div><strong>{money(r.net_pay)}</strong><small>Neto</small></div></div>)}</div>:<div className="empty-state"><strong>Sin empleados agregados</strong></div>}</section>
  </section>
}
