import {useCallback,useEffect,useMemo,useState} from 'react'
import './idealo-bar-advanced.css'

const money=new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'})
const fmt=value=>value?new Intl.DateTimeFormat('es-SV',{timeZone:'America/El_Salvador',dateStyle:'short',timeStyle:'short'}).format(new Date(value)):''
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/El_Salvador'}).format(new Date())
const TABS=[['Dividir cuenta','◫'],['Propinas','★'],['Ubicaciones','⌖'],['Presentaciones','▣'],['Compras','🛒'],['Anulaciones','⚠'],['Delivery','⌁'],['Tickets','▤'],['DTE','⚡'],['Rentabilidad','📈']]

export default function IdealoBarAdvancedCenter({company,supabase,access}){
 const companyId=company?.id
 const permissions=access?.permissions||[]
 const can=p=>permissions.includes('*')||permissions.includes(p)
 const [tab,setTab]=useState('Dividir cuenta'),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const [orders,setOrders]=useState([]),[items,setItems]=useState([]),[splits,setSplits]=useState([]),[splitItems,setSplitItems]=useState([]),[tips,setTips]=useState([]),[staff,setStaff]=useState([])
 const [inventory,setInventory]=useState([]),[warehouses,setWarehouses]=useState([]),[locations,setLocations]=useState([]),[stock,setStock]=useState([]),[presentations,setPresentations]=useState([]),[suppliers,setSuppliers]=useState([]),[purchases,setPurchases]=useState([])
 const [deliveryEvents,setDeliveryEvents]=useState([]),[printJobs,setPrintJobs]=useState([]),[dtes,setDtes]=useState([]),[clients,setClients]=useState([]),[profit,setProfit]=useState({})
 const [selectedOrderId,setSelectedOrderId]=useState(''),[parts,setParts]=useState('2'),[itemSelection,setItemSelection]=useState({}),[splitMethod,setSplitMethod]=useState('cash')
 const [locForm,setLocForm]=useState({itemId:'',warehouseId:'',locationId:'',kind:'BAR',qty:'0'}),[transfer,setTransfer]=useState({from:'',to:'',qty:'1',reason:''})
 const [presentation,setPresentation]=useState({itemId:'',name:'Caja 24',code:'CAJA24',units:'24',cost:'',sale:'',supplierId:''}),[buy,setBuy]=useState({presentationId:'',qty:'1'})
 const [dteForm,setDteForm]=useState({orderId:'',clientId:'',type:'01',environment:'test'})
 const [range,setRange]=useState(()=>({from:today(),to:today()}))

 const allowedTabs=useMemo(()=>TABS.filter(([name])=>{
  if(['Dividir cuenta','Propinas'].includes(name))return can('payment.take')||can('bill.request')||can('admin.manage')
  if(['Ubicaciones','Presentaciones','Compras'].includes(name))return can('inventory.view')||can('inventory.manage')||can('admin.manage')
  if(name==='DTE')return can('payment.take')||can('admin.manage')
  if(name==='Rentabilidad')return can('admin.manage')
  if(name==='Tickets')return can('order.send')||can('kitchen.view')||can('bar.view')||can('admin.manage')
  return can('admin.manage')||can('delivery.view')
 }),[permissions])
 useEffect(()=>{if(allowedTabs.length&&!allowedTabs.some(([n])=>n===tab))setTab(allowedTabs[0][0])},[allowedTabs,tab])

 const load=useCallback(async()=>{
  if(!companyId)return
  setLoading(true);setError('')
  const calls=[
   supabase.from('bar_orders').select('*').eq('company_id',companyId).order('created_at',{ascending:false}).limit(300),
   supabase.from('bar_order_items').select('*').eq('company_id',companyId).order('created_at',{ascending:false}).limit(1500),
   supabase.from('bar_bill_splits').select('*').eq('company_id',companyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('bar_bill_split_items').select('*').eq('company_id',companyId).limit(1200),
   supabase.from('bar_tip_allocations').select('*').eq('company_id',companyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('bar_staff_assignments').select('user_id,display_name,bar_role').eq('company_id',companyId),
   supabase.from('inventory_items').select('id,name,unit,current_stock,average_cost,reorder_point,target_stock,supplier_id,warehouse_id,location_id').eq('company_id',companyId).eq('active',true).is('deleted_at',null).order('name'),
   supabase.from('inventory_warehouses').select('*').eq('company_id',companyId).eq('active',true).order('name'),
   supabase.from('inventory_locations').select('*').eq('company_id',companyId).eq('active',true).order('code'),
   supabase.from('bar_inventory_location_stock').select('*').eq('company_id',companyId).order('updated_at',{ascending:false}),
   supabase.from('bar_inventory_presentations').select('*').eq('company_id',companyId).order('created_at',{ascending:false}),
   supabase.from('suppliers').select('id,name').eq('company_id',companyId).eq('active',true).order('name'),
   supabase.from('purchases').select('id,number,concept,total,procurement_status,supplier_id,created_at').eq('company_id',companyId).order('created_at',{ascending:false}).limit(100),
   supabase.from('bar_delivery_events').select('*').eq('company_id',companyId).order('created_at',{ascending:false}).limit(300),
   supabase.from('bar_print_jobs').select('*').eq('company_id',companyId).order('created_at',{ascending:false}).limit(300),
   supabase.from('dte_documents').select('id,bar_order_id,dte_type,environment,status,control_number,mh_receipt_seal,created_at').eq('company_id',companyId).not('bar_order_id','is',null).order('created_at',{ascending:false}).limit(200),
   supabase.from('clients').select('id,name,nit,nrc,preferred_dte_type').eq('company_id',companyId).eq('status','active').order('name').limit(300),
   supabase.rpc('bar_advanced_profitability',{p_company_id:companyId,p_from:range.from,p_to:range.to}),
  ]
  const r=await Promise.all(calls);const e=r.find(x=>x.error)?.error
  if(e)setError(e.message);else{setOrders(r[0].data||[]);setItems(r[1].data||[]);setSplits(r[2].data||[]);setSplitItems(r[3].data||[]);setTips(r[4].data||[]);setStaff(r[5].data||[]);setInventory(r[6].data||[]);setWarehouses(r[7].data||[]);setLocations(r[8].data||[]);setStock(r[9].data||[]);setPresentations(r[10].data||[]);setSuppliers(r[11].data||[]);setPurchases(r[12].data||[]);setDeliveryEvents(r[13].data||[]);setPrintJobs(r[14].data||[]);setDtes(r[15].data||[]);setClients(r[16].data||[]);setProfit(r[17].data||{})}
  setLoading(false)
 },[companyId,supabase,range.from,range.to])
 useEffect(()=>{load()},[load])
 const run=async(fn,msg)=>{setWorking(true);setError('');setNotice('');try{await fn();setNotice(msg);await load()}catch(e){setError(e.message||String(e))}finally{setWorking(false)}}
 const openOrders=orders.filter(o=>!['paid','cancelled'].includes(o.status))
 const paidOrders=orders.filter(o=>o.status==='paid')
 const selectedOrder=orders.find(o=>o.id===selectedOrderId)
 const selectedItems=items.filter(i=>i.order_id===selectedOrderId&&i.status!=='cancelled')
 const staffMap=useMemo(()=>new Map(staff.map(x=>[x.user_id,x.display_name])),[staff]);const itemMap=useMemo(()=>new Map(inventory.map(x=>[x.id,x])),[inventory]);const whMap=useMemo(()=>new Map(warehouses.map(x=>[x.id,x.name])),[warehouses]);const locMap=useMemo(()=>new Map(locations.map(x=>[x.id,x.code])),[locations])
 const createEqual=()=>run(async()=>{if(!selectedOrderId)throw new Error('Selecciona un pedido.');const {error:e}=await supabase.rpc('bar_create_equal_splits',{p_order_id:selectedOrderId,p_parts:Number(parts)});if(e)throw e},'Cuenta dividida por personas.')
 const createItems=()=>run(async()=>{if(!selectedOrderId)throw new Error('Selecciona un pedido.');const allocations=selectedItems.filter(i=>itemSelection[i.id]).map(i=>({order_item_id:i.id,quantity:Number(itemSelection[i.id])}));if(!allocations.length)throw new Error('Selecciona productos.');const {error:e}=await supabase.rpc('bar_create_item_split',{p_order_id:selectedOrderId,p_label:'Cuenta por productos',p_allocations:allocations});if(e)throw e},'Cuenta por productos creada.')
 const paySplit=split=>run(async()=>{const {error:e}=await supabase.rpc('bar_take_split_payment',{p_split_id:split.id,p_method:splitMethod,p_reference:`${split.label} · IDEALO BAR`});if(e)throw e},`${split.label} cobrada.`)
 const initLocation=()=>run(async()=>{const {error:e}=await supabase.rpc('bar_initialize_location_stock',{p_inventory_item_id:locForm.itemId,p_warehouse_id:locForm.warehouseId||null,p_location_id:locForm.locationId||null,p_location_kind:locForm.kind,p_quantity:Number(locForm.qty)});if(e)throw e},'Existencia asignada a ubicación.')
 const moveStock=()=>run(async()=>{const {error:e}=await supabase.rpc('bar_transfer_location_stock',{p_from_stock_id:transfer.from,p_to_stock_id:transfer.to,p_quantity:Number(transfer.qty),p_reason:transfer.reason||null});if(e)throw e},'Traslado interno registrado sin cambiar el stock total.')
 const createPresentation=()=>run(async()=>{if(!presentation.itemId||!presentation.name||!(Number(presentation.units)>0))throw new Error('Completa insumo, nombre y unidades.');const {error:e}=await supabase.from('bar_inventory_presentations').insert({company_id:companyId,inventory_item_id:presentation.itemId,name:presentation.name,code:presentation.code||null,units_per_presentation:Number(presentation.units),purchase_cost:presentation.cost?Number(presentation.cost):null,sale_price:presentation.sale?Number(presentation.sale):null,preferred_supplier_id:presentation.supplierId||null,is_purchase_default:true});if(e)throw e},'Presentación creada.')
 const preparePurchase=()=>run(async()=>{if(!buy.presentationId)throw new Error('Selecciona una presentación.');const {data,error:e}=await supabase.rpc('bar_prepare_purchase_by_presentation',{p_presentation_id:buy.presentationId,p_presentations:Number(buy.qty)});if(e)throw e;setNotice(`Compra preparada: ${data}`)},'Compra preparada.')
 const markPrinted=job=>run(async()=>{const {error:e}=await supabase.from('bar_print_jobs').update({status:'PRINTED',printed_at:new Date().toISOString(),attempts:Number(job.attempts||0)+1}).eq('id',job.id);if(e)throw e},'Ticket marcado como impreso.')
 const reprint=job=>run(async()=>{const {error:e}=await supabase.from('bar_print_jobs').insert({company_id:companyId,order_id:job.order_id,station:job.station,ticket_type:'REPRINT',payload:job.payload,printer_name:job.printer_name});if(e)throw e},'Reimpresión enviada a cola.')
 const generateDte=()=>run(async()=>{if(!dteForm.orderId)throw new Error('Selecciona una venta pagada.');const {data,error:e}=await supabase.rpc('bar_generate_dte_draft',{p_order_id:dteForm.orderId,p_client_id:dteForm.clientId||null,p_dte_type:dteForm.type,p_environment:dteForm.environment});if(e)throw e;setNotice(`DTE preparado: ${data}`)},'DTE preparado.')

 if(loading)return <div className="baradv-load">Cargando Control avanzado…</div>
 return <section className="baradv"><header><div><small>IDEALO BAR · OPERACIÓN AVANZADA</small><h2>Control avanzado</h2><p>Cuenta, inventario, compras, despacho, fiscalidad y rentabilidad en un solo lugar.</p></div><button onClick={load}>↻ Actualizar</button></header>{error&&<div className="baradv-alert error">{error}</div>}{notice&&<div className="baradv-alert ok">✓ {notice}</div>}
  <nav>{allowedTabs.map(([n,i])=><button key={n} className={tab===n?'active':''} onClick={()=>setTab(n)}>{i} {n}</button>)}</nav>
  {tab==='Dividir cuenta'&&<div className="baradv-grid two"><Panel title="Cuenta a dividir"><select value={selectedOrderId} onChange={e=>{setSelectedOrderId(e.target.value);setItemSelection({})}}><option value="">Pedido abierto…</option>{openOrders.map(o=><option key={o.id} value={o.id}>{o.order_code} · {money.format(Number(o.total||0))}</option>)}</select>{selectedOrder&&<><div className="baradv-total">Total <b>{money.format(Number(selectedOrder.total||0))}</b></div><label>Partes iguales<input type="number" min="2" max="50" value={parts} onChange={e=>setParts(e.target.value)}/></label><button disabled={working} onClick={createEqual}>Dividir por personas</button><h4>O dividir por productos</h4>{selectedItems.map(i=><label className="baradv-check" key={i.id}><span>{i.item_name} · {i.quantity} · {money.format(Number(i.line_total||0))}</span><input type="number" min="0" max={Number(i.quantity)} step="1" value={itemSelection[i.id]||''} onChange={e=>setItemSelection(v=>({...v,[i.id]:e.target.value}))}/></label>)}<button disabled={working} onClick={createItems}>Crear cuenta por productos</button></>}</Panel><Panel title="Partes abiertas"><label>Método<select value={splitMethod} onChange={e=>setSplitMethod(e.target.value)}><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option><option value="other">Otro</option></select></label>{splits.filter(s=>!selectedOrderId||s.order_id===selectedOrderId).slice(0,20).map(s=><article key={s.id}><div><b>{s.label}</b><small>{s.split_type} · {s.status}</small></div><strong>{money.format(Number(s.amount))}</strong>{s.status==='OPEN'&&can('payment.take')&&<button onClick={()=>paySplit(s)}>Cobrar</button>}</article>)}</Panel></div>}
  {tab==='Propinas'&&<Panel title="Propinas por mesero y método"><div className="baradv-kpis"><Kpi label="Ganadas" value={money.format(tips.filter(t=>t.status==='EARNED').reduce((a,b)=>a+Number(b.amount),0))}/><Kpi label="Efectivo" value={money.format(tips.filter(t=>t.method==='cash').reduce((a,b)=>a+Number(b.amount),0))}/><Kpi label="Tarjeta" value={money.format(tips.filter(t=>t.method==='card').reduce((a,b)=>a+Number(b.amount),0))}/></div>{tips.slice(0,80).map(t=><article key={t.id}><div><b>{staffMap.get(t.recipient_user_id)||'Sin mesero'}</b><small>{t.method} · {fmt(t.created_at)}</small></div><strong>{money.format(Number(t.amount))}</strong></article>)}</Panel>}
  {tab==='Ubicaciones'&&<div className="baradv-grid two"><Panel title="Asignar stock inicial"><select value={locForm.itemId} onChange={e=>setLocForm(v=>({...v,itemId:e.target.value}))}><option value="">Insumo…</option>{inventory.map(i=><option value={i.id} key={i.id}>{i.name} · total {i.current_stock}</option>)}</select><select value={locForm.warehouseId} onChange={e=>setLocForm(v=>({...v,warehouseId:e.target.value,locationId:''}))}><option value="">Bodega…</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select value={locForm.locationId} onChange={e=>setLocForm(v=>({...v,locationId:e.target.value}))}><option value="">Ubicación…</option>{locations.filter(l=>!locForm.warehouseId||l.warehouse_id===locForm.warehouseId).map(l=><option key={l.id} value={l.id}>{l.code} · {l.zone||''}</option>)}</select><select value={locForm.kind} onChange={e=>setLocForm(v=>({...v,kind:e.target.value}))}><option>WAREHOUSE</option><option>FRIDGE</option><option>BAR</option><option>OTHER</option></select><input type="number" min="0" step="0.001" value={locForm.qty} onChange={e=>setLocForm(v=>({...v,qty:e.target.value}))}/><button onClick={initLocation}>Asignar existencia</button></Panel><Panel title="Trasladar Bodega / Refrigerador / Barra"><select value={transfer.from} onChange={e=>setTransfer(v=>({...v,from:e.target.value}))}><option value="">Origen…</option>{stock.map(s=><option key={s.id} value={s.id}>{itemMap.get(s.inventory_item_id)?.name} · {s.location_kind} · {s.quantity}</option>)}</select><select value={transfer.to} onChange={e=>setTransfer(v=>({...v,to:e.target.value}))}><option value="">Destino…</option>{stock.filter(s=>!transfer.from||s.inventory_item_id===stock.find(x=>x.id===transfer.from)?.inventory_item_id).map(s=><option key={s.id} value={s.id}>{s.location_kind} · {whMap.get(s.warehouse_id)||''} · {locMap.get(s.location_id)||''} · {s.quantity}</option>)}</select><input type="number" min="0.001" step="0.001" value={transfer.qty} onChange={e=>setTransfer(v=>({...v,qty:e.target.value}))}/><input placeholder="Motivo" value={transfer.reason} onChange={e=>setTransfer(v=>({...v,reason:e.target.value}))}/><button onClick={moveStock}>Trasladar sin cambiar total</button></Panel></div>}
  {tab==='Presentaciones'&&<div className="baradv-grid two"><Panel title="Caja, pack, six-pack o unidad"><select value={presentation.itemId} onChange={e=>setPresentation(v=>({...v,itemId:e.target.value}))}><option value="">Insumo…</option>{inventory.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select><input value={presentation.name} onChange={e=>setPresentation(v=>({...v,name:e.target.value}))} placeholder="Ej. Caja 24"/><input value={presentation.code} onChange={e=>setPresentation(v=>({...v,code:e.target.value}))} placeholder="Código"/><input type="number" min="0.001" value={presentation.units} onChange={e=>setPresentation(v=>({...v,units:e.target.value}))} placeholder="Unidades base"/><input type="number" step="0.01" value={presentation.cost} onChange={e=>setPresentation(v=>({...v,cost:e.target.value}))} placeholder="Costo presentación"/><select value={presentation.supplierId} onChange={e=>setPresentation(v=>({...v,supplierId:e.target.value}))}><option value="">Proveedor preferido…</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={createPresentation}>Guardar presentación</button></Panel><Panel title="Presentaciones configuradas">{presentations.map(p=><article key={p.id}><div><b>{itemMap.get(p.inventory_item_id)?.name}</b><small>{p.name} = {p.units_per_presentation} unidades</small></div><strong>{p.purchase_cost?money.format(Number(p.purchase_cost)):'—'}</strong></article>)}</Panel></div>}
  {tab==='Compras'&&<div className="baradv-grid two"><Panel title="Preparar reposición"><select value={buy.presentationId} onChange={e=>setBuy(v=>({...v,presentationId:e.target.value}))}><option value="">Presentación…</option>{presentations.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{itemMap.get(p.inventory_item_id)?.name} · {p.name}</option>)}</select><input type="number" min="1" step="1" value={buy.qty} onChange={e=>setBuy(v=>({...v,qty:e.target.value}))}/><button onClick={preparePurchase}>Preparar compra en IDEALO SV</button><p className="baradv-note">La compra se crea en el motor central de Compras; recepción y cuentas por pagar siguen siendo únicas.</p></Panel><Panel title="Compras preparadas">{purchases.slice(0,30).map(p=><article key={p.id}><div><b>Compra #{p.number}</b><small>{p.concept} · {p.procurement_status}</small></div><strong>{money.format(Number(p.total||0))}</strong></article>)}</Panel></div>}
  {tab==='Anulaciones'&&<Panel title="Control de anulaciones y autorizaciones">{items.filter(i=>i.status==='cancelled').slice(0,60).map(i=><article key={i.id}><div><b>{i.item_name}</b><small>{i.void_reason||'Sin motivo'} · {fmt(i.voided_at)}</small></div><span>Anuló: {staffMap.get(i.voided_by)||'Usuario'}</span></article>)}{!items.some(i=>i.status==='cancelled')&&<Empty>Sin anulaciones registradas.</Empty>}</Panel>}
  {tab==='Delivery'&&<Panel title="Trazabilidad Delivery">{orders.filter(o=>o.order_type==='delivery').slice(0,50).map(o=><article className="vertical" key={o.id}><div><b>{o.order_code} · {o.customer_name||'Cliente'}</b><small>{o.delivery_address||'Sin dirección'} · {o.driver_name||'Sin motorista'}</small></div><div className="baradv-timeline">{deliveryEvents.filter(e=>e.order_id===o.id).slice().reverse().map(e=><span key={e.id}><b>{e.status}</b>{fmt(e.created_at)}</span>)}</div></article>)}</Panel>}
  {tab==='Tickets'&&<Panel title="Cola Cocina / Barra">{printJobs.map(j=><article key={j.id}><div><b>{j.station==='kitchen'?'Cocina':'Barra'} · {j.ticket_type}</b><small>{j.status} · {fmt(j.created_at)} · {j.printer_name||'Impresora no asignada'}</small></div><div className="baradv-actions">{j.status==='PENDING'&&<button onClick={()=>markPrinted(j)}>Marcar impreso</button>}<button onClick={()=>reprint(j)}>Reimprimir</button></div></article>)}</Panel>}
  {tab==='DTE'&&<div className="baradv-grid two"><Panel title="DTE automático de venta"><select value={dteForm.orderId} onChange={e=>setDteForm(v=>({...v,orderId:e.target.value}))}><option value="">Venta pagada…</option>{paidOrders.map(o=><option key={o.id} value={o.id}>{o.order_code} · {money.format(Number(o.total||0))}</option>)}</select><select value={dteForm.type} onChange={e=>setDteForm(v=>({...v,type:e.target.value}))}><option value="01">Factura electrónica 01</option><option value="03">CCF 03</option></select>{dteForm.type==='03'&&<select value={dteForm.clientId} onChange={e=>setDteForm(v=>({...v,clientId:e.target.value}))}><option value="">Cliente fiscal…</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.nit||c.nrc||''}</option>)}</select>}<select value={dteForm.environment} onChange={e=>setDteForm(v=>({...v,environment:e.target.value}))}><option value="test">Pruebas</option><option value="production">Producción</option></select><button onClick={generateDte}>Generar / recuperar borrador</button><p className="baradv-note">La venta queda enlazada al DTE y marcada como ya cobrada. Firmado y transmisión usan el motor DTE existente.</p></Panel><Panel title="DTE del bar">{dtes.map(d=><article key={d.id}><div><b>{d.dte_type} · {d.control_number}</b><small>{d.environment} · {d.status} · {fmt(d.created_at)}</small></div><span>{d.mh_receipt_seal?'Sello MH recibido':'Sin sello MH'}</span></article>)}</Panel></div>}
  {tab==='Rentabilidad'&&<Panel title="Rentabilidad avanzada"><div className="baradv-range"><input type="date" value={range.from} onChange={e=>setRange(v=>({...v,from:e.target.value}))}/><input type="date" value={range.to} onChange={e=>setRange(v=>({...v,to:e.target.value}))}/><button onClick={load}>Calcular</button></div><div className="baradv-kpis"><Kpi label="Ventas" value={money.format(Number(profit.summary?.sales||0))}/><Kpi label="Pedidos" value={profit.summary?.orders||0}/><Kpi label="Ticket promedio" value={money.format(Number(profit.summary?.avg_ticket||0))}/><Kpi label="Descuentos" value={money.format(Number(profit.summary?.discounts||0))}/><Kpi label="Propinas" value={money.format(Number(profit.summary?.tips||0))}/><Kpi label="Mermas" value={money.format(Number(profit.losses||0))}/><Kpi label="Cortesías" value={money.format(Number(profit.courtesies||0))}/></div><h4>Venta por hora</h4><div className="baradv-bars">{(profit.by_hour||[]).map(h=><div key={h.hour}><span>{String(h.hour).padStart(2,'0')}:00</span><b>{money.format(Number(h.sales||0))}</b><small>{h.orders} pedidos</small></div>)}</div></Panel>}
 </section>
}

function Panel({title,children}){return <div className="baradv-panel"><h3>{title}</h3>{children}</div>}
function Kpi({label,value}){return <div className="baradv-kpi"><span>{label}</span><b>{value}</b></div>}
function Empty({children}){return <div className="baradv-empty">{children}</div>}
