import {useEffect,useMemo,useState} from 'react'

const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))
const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const methodLabel=v=>({CASH:'Efectivo',TRANSFER:'Transferencia',CARD:'Tarjeta',CHECK:'Cheque',OTHER:'Otro'}[v]||v||'Pago')
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))

export default function InternalIncomeCard({company,supabase,accounts=[],clients=[],onSaved}){
 const activeAccounts=useMemo(()=>accounts.filter(a=>a.active!==false),[accounts])
 const [mode,setMode]=useState('WORK'),[quotes,setQuotes]=useState([]),[orders,setOrders]=useState([]),[payments,setPayments]=useState([])
 const [form,setForm]=useState({client_id:'',quote_id:'',work_order_id:'',cash_account_id:'',amount:'',concept:'',received_at:day(),payment_method:'CASH',reference:'',notes:''})
 const [saving,setSaving]=useState(false),[message,setMessage]=useState(''),[receipt,setReceipt]=useState(null)
 const loadWork=async()=>{if(!company?.id)return;const [q,w,p]=await Promise.all([
  supabase.from('quotes').select('id,number,prefix,client_id,project_name,total,status').eq('company_id',company.id).order('created_at',{ascending:false}).limit(150),
  supabase.from('work_orders').select('id,number,quote_id,client_id,total,status').eq('company_id',company.id).order('created_at',{ascending:false}).limit(150),
  supabase.from('internal_income_records').select('id,quote_id,work_order_id,amount,receipt_no').eq('company_id',company.id)
 ]);setQuotes(q.data||[]);setOrders(w.data||[]);setPayments(p.data||[])}
 useEffect(()=>{loadWork()},[company?.id])
 useEffect(()=>{if(!form.cash_account_id&&activeAccounts.length)setForm(f=>({...f,cash_account_id:activeAccounts[0].cash_account_id}))},[activeAccounts,form.cash_account_id])
 const selectedOrder=orders.find(x=>x.id===form.work_order_id),selectedQuote=quotes.find(x=>x.id===(selectedOrder?.quote_id||form.quote_id))
 const selectedClient=clients.find(x=>x.id===(selectedOrder?.client_id||selectedQuote?.client_id||form.client_id))
 const total=Number(selectedOrder?.total||selectedQuote?.total||0)
 const paid=payments.filter(p=>selectedOrder?p.work_order_id===selectedOrder.id:(!p.work_order_id&&p.quote_id===form.quote_id)).reduce((s,p)=>s+Number(p.amount||0),0)
 const pending=Math.max(0,total-paid),percent=total>0?Math.min(100,(paid/total)*100):0
 const filteredQuotes=quotes.filter(q=>!form.client_id||q.client_id===form.client_id)
 const filteredOrders=orders.filter(o=>(!form.client_id||o.client_id===form.client_id)&&(!form.quote_id||o.quote_id===form.quote_id))
 const chooseQuote=id=>{const q=quotes.find(x=>x.id===id);const matching=orders.filter(o=>o.quote_id===id);const autoOrder=matching.length===1?matching[0]:null;setForm(f=>({...f,quote_id:id,work_order_id:autoOrder?.id||'',client_id:q?.client_id||f.client_id,concept:q?.project_name?.trim()||'Trabajo'}));setReceipt(null)}
 const chooseOrder=id=>{const o=orders.find(x=>x.id===id),q=quotes.find(x=>x.id===o?.quote_id);setForm(f=>({...f,work_order_id:id,quote_id:o?.quote_id||f.quote_id,client_id:o?.client_id||f.client_id,concept:q?.project_name?.trim()||'Trabajo'}));setReceipt(null)}
 const setPercent=n=>{if(pending>0)setForm(f=>({...f,amount:(pending*n/100).toFixed(2)}))}
 const printReceipt=()=>{if(!receipt)return;const w=window.open('','_blank','width=820,height=900');if(!w){setMessage('El navegador bloqueó la ventana del comprobante. Habilita ventanas emergentes e inténtalo de nuevo.');return}const number=`CP-${String(receipt.receipt_no||0).padStart(6,'0')}`;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${number}</title><style>body{font-family:Arial,sans-serif;color:#1f2937;padding:36px}.box{max-width:720px;margin:auto;border:1px solid #d1d5db;border-radius:14px;padding:28px}h1{margin:0 0 4px;font-size:24px}.tag{display:inline-block;border:1px solid #f59e0b;border-radius:999px;padding:6px 10px;font-weight:700;font-size:12px;margin:10px 0 22px}.row{display:flex;justify-content:space-between;gap:24px;border-top:1px solid #e5e7eb;padding:11px 0}.row span:first-child{color:#6b7280}.amount{font-size:28px;font-weight:800}.note{margin-top:22px;padding:14px;background:#f9fafb;border-radius:10px;font-size:12px;line-height:1.45}.foot{margin-top:26px;font-size:11px;color:#6b7280}@media print{body{padding:0}.box{border:none}}</style></head><body><div class="box"><h1>${esc(company?.name||'IDEALO SV')}</h1><div><strong>COMPROBANTE DE PAGO</strong></div><div class="tag">NO ES FACTURA · NO ES DTE</div><div class="row"><span>Comprobante</span><strong>${number}</strong></div><div class="row"><span>Fecha</span><strong>${esc(new Date(receipt.received_at).toLocaleDateString('es-SV'))}</strong></div><div class="row"><span>Cliente</span><strong>${esc(receipt.client_name||'Cliente')}</strong></div><div class="row"><span>Concepto</span><strong>${esc(receipt.concept)}</strong></div>${receipt.quote_label?`<div class="row"><span>Cotización</span><strong>${esc(receipt.quote_label)}</strong></div>`:''}${receipt.ot_label?`<div class="row"><span>OT</span><strong>${esc(receipt.ot_label)}</strong></div>`:''}<div class="row"><span>Forma de pago</span><strong>${esc(methodLabel(receipt.payment_method))}</strong></div><div class="row"><span>Monto recibido</span><strong class="amount">${money(receipt.amount)}</strong></div>${receipt.total>0?`<div class="row"><span>Total del trabajo</span><strong>${money(receipt.total)}</strong></div><div class="row"><span>Total recibido</span><strong>${money(receipt.paid_after)}</strong></div><div class="row"><span>Saldo pendiente</span><strong>${money(receipt.pending_after)}</strong></div>`:''}<div class="note">Este comprobante es únicamente una constancia de dinero recibido. No constituye factura, crédito fiscal ni Documento Tributario Electrónico y no sustituye el documento tributario que corresponda legalmente.</div><div class="foot">Generado por IDEALO SV</div></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
 const save=async e=>{e.preventDefault();setMessage('');setReceipt(null);const amount=Number(form.amount);const concept=mode==='WORK'?(selectedQuote?.project_name?.trim()||'Pago de trabajo'):form.concept.trim();if(!form.cash_account_id||!concept||!Number.isFinite(amount)||amount<=0){setMessage('Selecciona dónde recibir el dinero y un monto mayor que cero.');return}if(mode==='WORK'&&!form.quote_id&&!form.work_order_id){setMessage('Selecciona la Cotización u OT que estás cobrando.');return}if(mode==='WORK'&&pending>0&&amount>pending+.009){setMessage(`El pago supera el saldo pendiente de ${money(pending)}.`);return}setSaving(true);const {data,error}=await supabase.rpc('register_internal_income',{p_company_id:company.id,p_cash_account_id:form.cash_account_id,p_amount:amount,p_concept:concept,p_received_at:`${form.received_at}T12:00:00`,p_payment_method:form.payment_method,p_client_id:(selectedClient?.id||form.client_id)||null,p_reference:form.reference||null,p_notes:form.notes||null,p_quote_id:mode==='WORK'?(form.quote_id||null):null,p_work_order_id:mode==='WORK'?(form.work_order_id||null):null});if(error)setMessage(error.message);else{const r=Array.isArray(data)?data[0]:data;const paidAfter=paid+amount;setReceipt({...r,amount,concept,client_name:selectedClient?.name||'Cliente',quote_label:selectedQuote?`${selectedQuote.prefix||'COT'}-${selectedQuote.number}`:'',ot_label:selectedOrder?`OT-${selectedOrder.number}`:'',payment_method:form.payment_method,total,paid_after:paidAfter,pending_after:Math.max(0,total-paidAfter),received_at:r?.received_at||`${form.received_at}T12:00:00`});setMessage(`Pago de ${money(amount)} registrado correctamente. El comprobante ya está listo.`);setForm(f=>({...f,amount:'',reference:'',notes:''}));await loadWork();await onSaved?.()}setSaving(false)}
 return <form onSubmit={save} className="form-card cash-advance-card internal-income-card">
  <div className="cash-section-heading compact"><div><p className="form-kicker">REGISTRO INTERNO</p><h3>Registrar dinero recibido</h3><small>Control de Caja/Banco. No crea, firma ni transmite DTE automáticamente.</small></div><span className="cash-pending-pill">SIN DTE</span></div>
  <div className="cash-form-footer"><div><button type="button" className={mode==='WORK'?'confirm':'secondary'} onClick={()=>{setMode('WORK');setReceipt(null)}}>Pago de trabajo</button> <button type="button" className={mode==='OTHER'?'confirm':'secondary'} onClick={()=>{setMode('OTHER');setReceipt(null)}}>Otro ingreso</button></div></div>
  {message&&<p className={message.includes('correctamente')?'feedback success':'feedback error'}>{message}</p>}
  {receipt&&<div className="cash-shift-message"><strong>Comprobante CP-{String(receipt.receipt_no||0).padStart(6,'0')} listo.</strong> <button type="button" className="secondary" onClick={printReceipt}>Ver / Imprimir / Guardar PDF</button></div>}
  {mode==='WORK'&&<><div className="cash-advance-grid"><label>Cliente<select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value,quote_id:'',work_order_id:'',concept:''})}><option value="">Seleccionar cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Cotización<select value={form.quote_id} onChange={e=>chooseQuote(e.target.value)}><option value="">Seleccionar</option>{filteredQuotes.map(q=><option key={q.id} value={q.id}>{q.prefix||'COT'}-{q.number} · {q.project_name||'Trabajo'} · {money(q.total)}</option>)}</select></label><label>OT<select value={form.work_order_id} onChange={e=>chooseOrder(e.target.value)}><option value="">Sin OT / usar cotización</option>{filteredOrders.map(o=><option key={o.id} value={o.id}>OT-{o.number} · {money(o.total)}</option>)}</select></label></div>{selectedQuote&&<div className="cash-shift-message"><strong>{selectedClient?.name||'Cliente'}</strong> · {selectedQuote.prefix||'COT'}-{selectedQuote.number}{selectedOrder?` · OT-${selectedOrder.number}`:''} · {selectedQuote.project_name||'Trabajo'}</div>}{total>0&&<div className="cash-shift-summary"><article><small>Total trabajo</small><strong>{money(total)}</strong></article><article><small>Recibido</small><strong>{money(paid)}</strong></article><article className="expected"><small>Pendiente</small><strong>{money(pending)}</strong></article><article><small>Pagado</small><strong>{percent.toFixed(0)}%</strong></article></div>}<div className="cash-form-footer"><span>Pago rápido:</span><div><button type="button" className="secondary" onClick={()=>setPercent(25)}>25%</button> <button type="button" className="secondary" onClick={()=>setPercent(50)}>50%</button> <button type="button" className="secondary" onClick={()=>setPercent(100)}>Saldo completo</button></div></div></>}
  <div className="cash-advance-grid">{mode==='OTHER'&&<label>Concepto *<input required maxLength="160" value={form.concept} onChange={e=>setForm({...form,concept:e.target.value})} placeholder="Ej. aporte, reintegro u otro ingreso"/></label>}{mode==='OTHER'&&<label>Cliente <span>(opcional)</span><select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Sin identificar</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>Monto recibido *<input required type="number" min="0.01" step="0.01" inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0.00"/></label><label>Forma de ingreso<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia</option><option value="CARD">Tarjeta</option><option value="CHECK">Cheque</option><option value="OTHER">Otro</option></select></label><label>Recibir en<select required value={form.cash_account_id} onChange={e=>setForm({...form,cash_account_id:e.target.value})}><option value="">Seleccionar</option>{activeAccounts.map(a=><option key={a.cash_account_id} value={a.cash_account_id}>{a.name}</option>)}</select></label></div>
  <div className="cash-form-footer"><details className="cash-more-data"><summary>Más datos</summary><div className="cash-extra-grid"><label>Fecha<input type="date" value={form.received_at} onChange={e=>setForm({...form,received_at:e.target.value})}/></label><label>Referencia<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Referencia interna"/></label><label>Nota<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Observación opcional"/></label></div></details><button type="submit" disabled={saving}>{saving?'Registrando…':mode==='WORK'?'Registrar pago':'Registrar otro ingreso'}</button></div>
  <p className="cash-shift-message">Después de registrar el pago aparecerá el botón para ver, imprimir o guardar el comprobante como PDF.</p>
 </form>
}
