export const INVENTORY_IN_TYPES=['PURCHASE_IN','ADJUST_IN','RETURN','PRODUCTION_IN','TRANSFER_IN','INITIAL']
export const INVENTORY_OUT_TYPES=['CONSUMPTION','ADJUST_OUT','SALE_OUT','TRANSFER_OUT','DAMAGE','LOSS','EXPIRY','SUPPLIER_RETURN','PRODUCTION_OUT','INSTALLATION_OUT']
export function availableStock(item={}){return Math.max(0,Number(item.current_stock||0)-Number(item.reserved_stock||0)-Number(item.blocked_stock||0)-Number(item.damaged_stock||0))}
export function stockStatus(item={}){const stock=Number(item.current_stock||0),min=Number(item.minimum_stock||0),max=Number(item.maximum_stock||0);if(stock<=0)return 'OUT';if(min>0&&stock<=min)return 'LOW';if(max>0&&stock>max)return 'OVER';return 'OK'}
export function inventoryValue(items=[]){return items.reduce((s,i)=>s+Number(i.current_stock||0)*Number(i.average_cost||0),0)}
export function movementImpact(type,quantity){const q=Math.abs(Number(quantity||0));return INVENTORY_OUT_TYPES.includes(type)?-q:q}
export function reorderSuggestion(item={}){const target=Math.max(Number(item.target_stock||0),Number(item.maximum_stock||0),Number(item.minimum_stock||0));const projected=Number(item.current_stock||0)+Number(item.in_transit_stock||0)-Number(item.reserved_stock||0)-Number(item.committed_stock||0);return Math.max(0,target-projected)}
export function abcClass(value,total){const share=total>0?Number(value||0)/total:0;return share>=0.1?'A':share>=0.03?'B':'C'}
export function inventoryMetrics(items=[]){const value=inventoryValue(items);return{items:items.length,active:items.filter(i=>i.active).length,out:items.filter(i=>stockStatus(i)==='OUT').length,low:items.filter(i=>stockStatus(i)==='LOW').length,over:items.filter(i=>stockStatus(i)==='OVER').length,value,availableValue:items.reduce((s,i)=>s+availableStock(i)*Number(i.average_cost||0),0),reservedValue:items.reduce((s,i)=>s+Number(i.reserved_stock||0)*Number(i.average_cost||0),0)}}
export function canMove(item,type,quantity){const q=Number(quantity||0);if(!item)return{ok:false,reason:'Seleccioná un artículo.'};if(q<=0)return{ok:false,reason:'La cantidad debe ser mayor a cero.'};if(INVENTORY_OUT_TYPES.includes(type)&&q>availableStock(item))return{ok:false,reason:`Stock disponible insuficiente (${availableStock(item)}).`};return{ok:true}}
