import {useEffect,useMemo,useState} from 'react'
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))
const qty=v=>new Intl.NumberFormat('es-SV',{maximumFractionDigits:3}).format(Number(v||0))
export default function InventoryControlCenter({company,supabase}){
 const[items,setItems]=useState([]),[reservations,setReservations]=useState([]),[counts,setCounts]=useState([]),[moves,setMoves]=useState([]),[message,setMessage]=useState('')
 const load=async()=>{const [i,r,c,m]=await Promise.all([
  supabase.from('inventory_items').select('id,name,sku,current_stock,reserved_stock,minimum_stock,reorder_point,target_stock,maximum_stock,average_cost,replacement_cost,active,deleted_at').eq('company_id',company.id).is('deleted_at',null),
  supabase.from('inventory_reservations').select('id,inventory_item_id,quantity,status,priority,expires_at,work_order_id,inventory_items(name,unit),work_orders(number,title,status)').eq('company_id',company.id).order('created_at',{ascending:false}).limit(300),
  supabase.from('inventory_counts').select('id,code,status,created_at,completed_at').eq('company_id',company.id).order('created_at',{ascending:false}).limit(50),
  supabase.from('inventory_movements').select('id,inventory_item_id,movement_type,quantity,unit_cost,movement_at').eq('company_id',company.id).order('movement_at',{ascending:false}).limit(500)
 ]);const e=[i,r,c,m].find(x=>x.error)?.error;if(e)setMessage(e.message);else{setItems(i.data||[]);setReservations(r.data||[]);setCounts(c.data||[]);setMoves(m.data||[])}}
 useEffect(()=>{load()},[company.id])
 const data=useMemo(()=>{const active=items.filter(x=>x.active!==false);const critical=active.filter(x=>Number(x.current_stock||0)<=Number(x.minimum_stock||0));const out=active.filter(x=>Number(x.current_stock||0)<=0);const blocked=active.filter(x=>Number(x.reserved_stock||0)>Number(x.current_stock||0));const over=active.filter(x=>Number(x.maximum_stock||0)>0&&Number(x.current_stock||0)>Number(x.maximum_stock||0));const stale=active.filter(x=>{const lm=moves.find(m=>m.inventory_item_id===x.id);if(!lm)return Number(x.current_stock||0)>0;return Date.now()-new Date(lm.movement_at).getTime()>60*86400000&&Number(x.current_stock||0)>0});const openReservations=reservations.filter(r=>!['RELEASED','CONSUMED','CANCELLED'].includes(r.status));const expiredReservations=openReservations.filter(r=>r.expires_at&&new Date(r.expires_at)<new Date());const openCounts=counts.filter(c=>!['COMPLETED','CANCELLED'].includes(c.status));const inventoryValue=active.reduce((s,x)=>s+Number(x.current_stock||0)*Number(x.average_cost||x.replacement_cost||0),0);return{critical,out,blocked,over,stale,openReservations,expiredReservations,openCounts,inventoryValue}},[items,reservations,counts,moves])
 const openProcurement=()=>window.dispatchEvent(new CustomEvent('idealo-open-module',{detail:{target:'procurement',tab:'Reposición'}}))
 return <section className="inventory-control-center"><div className="inventory-control-head"><div><p className="form-kicker">CONTROL DE INVENTARIO</p><h3>Riesgos que requieren atención</h3><p>Prioriza faltantes, reservas problemáticas, sobrestock y conteos pendientes.</p></div><button type="button" onClick={openProcurement}>Abrir reposición</button></div>{message&&<p className="feedback error">{message}</p>}<div className="inventory-control-kpis"><article><small>Agotados</small><strong>{data.out.length}</strong></article><article><small>Bajo mínimo</small><strong>{data.critical.length}</strong></article><article><small>Reservas bloqueadas</small><strong>{data.blocked.length}</strong></article><article><small>Reservas vencidas</small><strong>{data.expiredReservations.length}</strong></article><article><small>Conteos abiertos</small><strong>{data.openCounts.length}</strong></article><article><small>Valor inventario</small><strong>{money(data.inventoryValue)}</strong></article></div><div className="inventory-control-grid"><section><h4>Faltantes y bloqueos</h4>{[...data.out,...data.blocked.filter(x=>!data.out.some(o=>o.id===x.id)),...data.critical.filter(x=>!data.out.some(o=>o.id===x.id)&&!data.blocked.some(b=>b.id===x.id))].slice(0,8).map(x=><div className="inventory-control-row" key={x.id}><div><strong>{x.name}</strong><small>{x.sku||'Sin SKU'}</small></div><div><span>{qty(x.current_stock)} stock</span><small>{qty(x.reserved_stock)} reservado · mínimo {qty(x.minimum_stock)}</small></div></div>)}{!data.out.length&&!data.blocked.length&&!data.critical.length&&<p className="inventory-control-empty">Sin faltantes críticos.</p>}</section><section><h4>Capital inmovilizado</h4>{[...data.over,...data.stale.filter(x=>!data.over.some(o=>o.id===x.id))].slice(0,8).map(x=><div className="inventory-control-row" key={x.id}><div><strong>{x.name}</strong><small>{data.over.some(o=>o.id===x.id)?'Sobrestock':'Sin movimiento >60 días'}</small></div><div><span>{qty(x.current_stock)}</span><small>{money(Number(x.current_stock||0)*Number(x.average_cost||x.replacement_cost||0))}</small></div></div>)}{!data.over.length&&!data.stale.length&&<p className="inventory-control-empty">Sin sobrestock relevante.</p>}</section></div></section>
}
