import { useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { supabase } from './lib/supabase.js'
import { canAccessModule, ERP_MODULES, ROLE_LABEL } from './erp-access-control.js'

const openDirectModule = (target, tab) => {
 if(target==='workspace'&&tab){const buttons=[...document.querySelectorAll('.erp-sidebar nav .nav-item')];const button=buttons.find(node=>node.textContent?.trim().endsWith(tab));button?.click()}
 const detail={target,tab}
 ;[0,120,400,800].forEach(delay=>window.setTimeout(()=>window.dispatchEvent(new CustomEvent('idealo-open-module',{detail})),delay))
 return true
}

export default function MainMenuController() {
 const [sidebar,setSidebar]=useState(null),[active,setActive]=useState('Dashboard'),[query,setQuery]=useState(''),[role,setRole]=useState('')
 const searchRef=useRef(null)
 useEffect(()=>{let cancelled=false,attempts=0;const findSidebar=()=>{if(cancelled)return;const node=document.querySelector('.erp-sidebar');if(node)return setSidebar(node);attempts+=1;if(attempts<20)window.setTimeout(findSidebar,100)};findSidebar();return()=>{cancelled=true}},[])
 useEffect(()=>{let live=true;if(!supabase)return;const applySession=async session=>{if(!session){if(live)setRole('');return}const {data:companies,error:companyError}=await supabase.rpc('get_my_companies');if(companyError||!companies?.[0]?.id){if(live)setRole('');return}const {data,error}=await supabase.from('company_members').select('role').eq('company_id',companies[0].id).eq('user_id',session.user.id).maybeSingle();if(live&&!error)setRole(String(data?.role||'').toLowerCase())};supabase.auth.getSession().then(({data})=>void applySession(data.session));const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{void applySession(session)});return()=>{live=false;listener.subscription.unsubscribe()}},[])
 useEffect(()=>{const syncActive=event=>{if(ERP_MODULES.includes(event.detail))setActive(event.detail)};window.addEventListener('idealo-module-change',syncActive);return()=>window.removeEventListener('idealo-module-change',syncActive)},[])
 useEffect(()=>{const shortcut=event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();searchRef.current?.focus()}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut)},[])
 const openModule=name=>{if(role&&!canAccessModule(role,name)){window.dispatchEvent(new CustomEvent('idealo-access-denied',{detail:{message:`${ROLE_LABEL[role]||role} no tiene permiso para ${name}.`}}));return false}setQuery('');if(name==='Dashboard'){openDirectModule('workspace','Resumen');setActive(name);window.dispatchEvent(new CustomEvent('idealo-module-change',{detail:name}));return true}if(name==='App móviles'){setActive(name);window.dispatchEvent(new CustomEvent('idealo-module-change',{detail:name}));return true}if(name==='Clientes'){openDirectModule('workspace','Clientes');setActive(name);window.dispatchEvent(new CustomEvent('idealo-module-change',{detail:name}));return true}const map={Productos:['commercial','Productos y trabajos'],Cotizaciones:['commercial','Cotizaciones'],Producción:['commercial','Producción'],Inventario:['inventory','Inventario'],Facturación:['billing','resumen'],'Cuentas por cobrar':['billing','cobros'],Proveedores:['procurement','Proveedores'],Compras:['procurement','Compras y gastos'],Caja:['procurement','Caja'],'Asistente IA':['assistant'],Agenda:['planning'],Reportes:['financial'],Seguridad:['security']};const destination=map[name];if(!destination)return false;openDirectModule(destination[0],destination[1]);setActive(name);window.dispatchEvent(new CustomEvent('idealo-module-change',{detail:name}));return true}
 const filteredModules=useMemo(()=>{const normalized=query.trim().toLowerCase();return normalized?ERP_MODULES.filter(name=>name.toLowerCase().includes(normalized)):ERP_MODULES},[query])
 if(!sidebar)return null
 return createPortal(<nav className="idealo-main-menu" aria-label="Módulos principales IDEALO SV"><div className="idealo-menu-search-wrap"><input ref={searchRef} className="idealo-menu-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar módulo…" aria-label="Buscar módulo" />{query&&<button type="button" className="idealo-menu-search-clear" onClick={()=>setQuery('')} aria-label="Limpiar búsqueda">×</button>}</div>{role&&<div className="idealo-role-strip"><span>Perfil</span><strong>{ROLE_LABEL[role]||role}</strong></div>}<div className="idealo-menu-list">{filteredModules.map(name=>{const allowed=!role||canAccessModule(role,name);return <button type="button" key={name} aria-disabled={!allowed} className={`${active===name?'idealo-main-menu-item active':'idealo-main-menu-item'}${allowed?'':' locked'}`} onClick={()=>openModule(name)}>{name}{!allowed&&<small>Sin acceso</small>}</button>})}</div>{filteredModules.length===0&&<div className="idealo-menu-empty">No hay módulos con ese nombre.</div>}</nav>,sidebar)
}
