import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import FacturacionLauncher from './FacturacionLauncher.jsx'
import CommercialLauncher from './CommercialLauncher.jsx'
import OperationsFinanceLauncher from './OperationsFinanceLauncher.jsx'
import InventoryCostLauncher from './InventoryCostLauncher.jsx'
import FinancialDashboardLauncher from './FinancialDashboardLauncher.jsx'
import HrPayrollLauncher from './HrPayrollLauncher.jsx'
import ProductionCalendarLauncher from './ProductionCalendarLauncher.jsx'
import QualityControlLauncher from './QualityControlLauncher.jsx'
import MainMenuController from './MainMenuController.jsx'
import ExecutiveDashboardHost from './ExecutiveDashboardHost.jsx'
import MobileAppHost from './MobileAppHost.jsx'
import MobileFieldTools from './MobileFieldTools.jsx'
import MobileSalesFieldBlock from './MobileSalesFieldBlock.jsx'
import MobileClient360 from './MobileClient360.jsx'
import Client360Enhancer from './Client360Enhancer.jsx'
import CommercialAutomationCenter from './CommercialAutomationCenter.jsx'
import ClientCrmPipeline from './ClientCrmPipeline.jsx'
import ClientModuleOrganizer from './ClientModuleOrganizer.jsx'
import Client360TimelineHost from './Client360TimelineHost.jsx'
import ClientVatCardScannerHost from './ClientVatCardScannerHost.jsx'
import './styles.css'
import './premium.css'
import './executive.css'
import './idealo-brand.css'
import './idealo-reference.css'
import './facturacion-feedback.css'
import './sidebar-modules.css'
import './accounts-payable.css'
import './financial-dashboard.css'
import './hr-payroll.css'
import './production-calendar.css'
import './quality-control.css'
import './main-menu.css'
import './executive-dashboard-main.css'
import './dashboard-intelligence.css'
import './dashboard-advanced-insights.css'
import './dashboard-owner-daily.css'
import './mobile-app.css'
import './mobile-field-tools.css'
import './mobile-next-block.css'
import './mobile-client-360.css'
import './client-360.css'
import './commercial-automation.css'
import './client-crm-pipeline.css'
import './client-module-organizer.css'
import './global-contrast.css'
import './client-360-timeline.css'
import './client-button-balance.css'
import './corporate-premium-global.css'
import './corporate-gray-dark.css'
import './orange-button-clean.css'
import './solid-button-clean.css'
import './client-vat-card-scanner.css'
import './less-orange-global.css'
import './enterprise-theme-final.css'
import './enterprise-ui-v2.css'
import './enterprise-ui-v3-hotfix.css'
const nativeScrollIntoView=Element.prototype.scrollIntoView
Element.prototype.scrollIntoView=function(options){if(this.classList?.contains('invoice-form'))return;return nativeScrollIntoView.call(this,options)}
if('serviceWorker'in navigator&&import.meta.env.PROD)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>null))
createRoot(document.getElementById('root')).render(<StrictMode><App/><CommercialLauncher/><OperationsFinanceLauncher/><InventoryCostLauncher/><FinancialDashboardLauncher/><HrPayrollLauncher/><ProductionCalendarLauncher/><QualityControlLauncher/><FacturacionLauncher/><MainMenuController/><ExecutiveDashboardHost/><MobileAppHost/><MobileFieldTools/><MobileSalesFieldBlock/><MobileClient360/><Client360Enhancer/><CommercialAutomationCenter/><ClientCrmPipeline/><ClientModuleOrganizer/><Client360TimelineHost/><ClientVatCardScannerHost/></StrictMode>)