import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import FacturacionLauncher from './FacturacionLauncher.jsx'
import CommercialLauncher from './CommercialLauncher.jsx'
import OperationsFinanceLauncher from './OperationsFinanceLauncher.jsx'
import InventoryCostLauncher from './InventoryCostLauncher.jsx'
import FinancialDashboardLauncher from './FinancialDashboardLauncher.jsx'
import HrPayrollLauncher from './HrPayrollLauncher.jsx'
import ProductionCalendarLauncher from './ProductionCalendarLauncher.jsx'
import QualityControlLauncher from './QualityControlLauncher.jsx'
import AssistantLauncher from './AssistantLauncher.jsx'
import SecurityLauncher from './SecurityLauncher.jsx'
import WorkspaceNavigationBridge from './WorkspaceNavigationBridge.jsx'
import MainMenuController from './MainMenuController.jsx'
import ErpUxCoordinator from './ErpUxCoordinator.jsx'
import FormAccordionManager from './FormAccordionManager.jsx'
import FormSimplificationManager from './FormSimplificationManager.jsx'
import RuntimeBoundary from './RuntimeBoundary.jsx'
import ModuleRuntime from './ModuleRuntime.jsx'
import MobileRuntimeGuard from './MobileRuntimeGuard.jsx'
import MobileAppHost from './MobileAppHost.jsx'
import MobileDteHost from './MobileDteHost.jsx'
import MobileDteEnvironmentGuard from './MobileDteEnvironmentGuard.jsx'
import MobileHealthGuard from './MobileHealthGuard.jsx'
import MobileUpdateNotice from './MobileUpdateNotice.jsx'
import ClientIntegrityCenter from './ClientIntegrityCenter.jsx'
import ClientAdditionalActivitiesHost from './ClientAdditionalActivitiesHost.jsx'
import SaasMasterPanelHost from './SaasMasterPanelHost.jsx'
import AgencyDemoGuard from './AgencyDemoGuard.jsx'
import PurchaseTaxAssistant from './PurchaseTaxAssistant.jsx'
import './styles.css'
import './facturacion-feedback.css'
import './sidebar-modules.css'
import './accounts-payable.css'
import './financial-dashboard.css'
import './financial-alerts-dashboard.css'
import './hr-payroll.css'
import './production-calendar.css'
import './production-control-center.css'
import './production-simple.css'
import './quality-control.css'
import './main-menu.css'
import './executive-dashboard-main.css'
import './dashboard-intelligence.css'
import './dashboard-advanced-insights.css'
import './dashboard-owner-daily.css'
import './mobile-app.css'
import './mobile-field-tools.css'
import './mobile-next-block.css'
import './mobile-client-360.css'
import './mobile-dte.css'
import './mobile-dte-environment.css'
import './mobile-health.css'
import './mobile-owner-hub.css'
import './mobile-simple-navigation.css'
import './client-360.css'
import './client-integrity-center.css'
import './commercial-automation.css'
import './client-crm-pipeline.css'
import './client-module-organizer.css'
import './client-360-timeline.css'
import './client-button-balance.css'
import './client-vat-card-scanner.css'
import './client-additional-activities.css'
import './products-360.css'
import './products-360-simple.css'
import './quotes-360.css'
import './quotes-simple.css'
import './quotes-quick.css'
import './inventory-360.css'
import './inventory-control-center.css'
import './procurement-control-center.css'
import './purchases-expenses-clean.css'
import './purchase-tax-assistant.css'
import './cash-control-center.css'
import './billing-simplification.css'
import './billing-classic-layout.css'
import './billing-documents.css'
import './billing-tax-mode.css'
import './billing-reorganization.css'
import './modal-structure.css'
import './erp-corporate-master.css'
import './module-action-hierarchy.css'
import './form-simplification.css'
import './mobile-android-polish.css'
import './agency-demo.css'
const nativeScrollIntoView=Element.prototype.scrollIntoView
Element.prototype.scrollIntoView=function(options){if(this.classList?.contains('invoice-form'))return;return nativeScrollIntoView.call(this,options)}
if('serviceWorker'in navigator&&import.meta.env.PROD){window.addEventListener('load',async()=>{try{const registration=await navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'});await registration.update().catch(()=>null);navigator.serviceWorker.addEventListener('controllerchange',()=>{const key='idealo-sw-controller-reload';if(sessionStorage.getItem(key)==='1')return;sessionStorage.setItem(key,'1');window.location.reload()});sessionStorage.removeItem('idealo-sw-controller-reload')}catch{}})}
const Safe=({label,children,fatal=false})=><RuntimeBoundary label={label} fatal={fatal}>{children}</RuntimeBoundary>
createRoot(document.getElementById('root')).render(<StrictMode><Safe label="ERP principal" fatal><App/></Safe><Safe label="Comercial"><CommercialLauncher/></Safe><Safe label="Compras y finanzas"><OperationsFinanceLauncher/></Safe><Safe label="Inventario"><InventoryCostLauncher/></Safe><Safe label="Reportes financieros"><FinancialDashboardLauncher/></Safe><Safe label="RRHH"><HrPayrollLauncher/></Safe><Safe label="Agenda de producción"><ProductionCalendarLauncher/></Safe><Safe label="Control de calidad"><QualityControlLauncher/></Safe><Safe label="Facturación"><FacturacionLauncher/></Safe><Safe label="Asistente IA"><AssistantLauncher/></Safe><Safe label="Seguridad"><SecurityLauncher/></Safe><Safe label="Compatibilidad Workspace"><WorkspaceNavigationBridge/></Safe><Safe label="Menú principal"><MainMenuController/></Safe><Safe label="Coordinación UX"><ErpUxCoordinator/></Safe><Safe label="Formularios"><FormAccordionManager/></Safe><Safe label="Simplificación de formularios"><FormSimplificationManager/></Safe><Safe label="Runtime móvil"><MobileRuntimeGuard/></Safe><Safe label="App móvil"><MobileAppHost/></Safe><Safe label="DTE móvil"><MobileDteHost/></Safe><Safe label="Ambiente DTE móvil"><MobileDteEnvironmentGuard/></Safe><Safe label="Salud móvil"><MobileHealthGuard/></Safe><Safe label="Actualizaciones Android"><MobileUpdateNotice/></Safe><Safe label="Integridad clientes"><ClientIntegrityCenter/></Safe><Safe label="Giros adicionales clientes"><ClientAdditionalActivitiesHost/></Safe><Safe label="Panel Maestro SaaS"><SaasMasterPanelHost/></Safe><Safe label="Entorno demo"><AgencyDemoGuard/></Safe><Safe label="Asistente IVA compras"><PurchaseTaxAssistant/></Safe><Safe label="Runtime por módulo"><ModuleRuntime/></Safe></StrictMode>)