import { createClient } from '@supabase/supabase-js'
import { useEffect,useMemo,useState } from 'react'
import { createPortal } from 'react-dom'

const url=import.meta.env.VITE_SUPABASE_URL
const key=import.meta.env.VITE_SUPABASE_ANON_KEY
const supabase=url&&key?createClient(url,key,{auth:{persistSession:true}}):null
const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const cleanPhone=v=>String(v||'').replace(/\D/g,'').replace(/^0+/,'')
const svPhone=v=>{const p=cleanPhone(v);return p.startsWith('503')?p:`503${p}`}
const isoDay=()=>new Date().toISOString().slice(0,10)
const vapidKey=import.meta.env.VITE_VAPID_PUBLIC_KEY||''
function b64(s){const pad='='.repeat((4-s.length%4)%4),raw=atob((s+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}

export default function MobileSalesFieldBlock(){
 const [show,setShow]=useState(false),[open,setOpen]=useState(false),[tab,setTab]=useState('Rápido'),[company,setCompany]=useState(null),[role,setRole]=useState(null)
 const [clients,setClients]=useState([]),[orders,setOrders]=useState([]),[deliveries,setDeliveries]=useState([]),[products,setProducts]=useState([]),[quotes,setQuotes]=useState([]),[receivables,setReceivables]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const [form,setForm]=useState({kind:'quote',client_id:'',title:'',description:'',quantity:1,unit_price:0,due_at:'',valid_until:'',priority:'NORMAL',notes:''})
 const [clientForm,setClientForm]=useState({name:'',phone:'',whatsapp:'',email:'',address:''}),[payment,setPayment]=useState({receivable_id:'',amount:'',method:'CASH',reference:'',notes:''})
 useEffect(()=>{const sync=()=>setShow(location.pathname==='/mobile'||!!document.querySelector('.mobile-app-shell'));sync();const t=setInterval(sync,500);return()=>clearInterval(t)},[])
 useEffect(()=>{if(!show||!supabase)return;(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data:cs}=await supabase.rpc('get_my_companies');const id=cs?.[0]?.id;if(!id)return;const [{data:c},{data:m}]=await Promise.all([supabase.from('companies').select('id,name').eq('id',id).single(),supabase.from('company_members').select('role').eq('company_id',id).eq('user_id',session.user.id).single()]);setCompany(c);setRole(m?.role||'viewer')})()},[show])
 const load=async()=>{if(!company)return;const from=`${isoDay()}T00:00:00`,to=`${isoDay()}T23:59:59`;const [c,o,d,p,q,r]=await Promise.all([
  supabase.from('clients').select('id,name,phone,whatsapp,email,address').eq('company_id',company.id).eq('status','active').order('name'),
  supabase.from('work_orders').select('id,number,title,status,design_status,clients(name,phone,whatsapp)').eq('company_id',company.id).in('status',['DESIGN','APPROVAL']).order('updated_at',{ascending:false}).limit(30),
  supabase.from('deliveries').select('id,number,status,delivery_method,scheduled_at,delivery_address,work_order_id,clients(name,phone,whatsapp,address),work_orders(number,title)').eq('company_id',company.id).gte('scheduled_at',from).lte('scheduled_at',to).order('scheduled_at'),
  supabase.from('finished_products').select('id,name,category,description,unit,sale_price,estimated_minutes').eq('company_id',company.id).eq('active',true).order('name'),
  supabase.from('quotes').select('id,number,status,total,valid_until,created_at,clients(name,phone,whatsapp)').eq('company_id',company.id).in('status',['SENT','APPROVED']).order('created_at',{ascending:false}).limit(40),
  supabase.from('accounts_receivable').select('id,number,concept,amount_total,amount_paid,due_date,status,clients(name,phone,whatsapp)').eq('company_id',company.id).not('status','in','(PAID,CANCELLED)').order('due_date',{ascending:true}).limit(60)
 ]);setClients(c.data||[]);setOrders(o.data||[]);setDeliveries(d.data||[]);setProducts(p.data||[]);setQuotes(q.data||[]);setReceivables(r.data||[])}
 useEffect(()=>{if(company)load()},[company])
 const canWrite=['owner','admin','staff'].includes(role),canCollect=['owner','admin'].includes(role)
 const selectedClient=useMemo(()=>clients.find(x=>x.id===form.client_id),[clients,form.client_id])
 const saveQuick=async()=>{if(!canWrite)return;setBusy(true);setMsg('');try{if(!form.client_id||!form.description.trim())throw new Error('Seleccioná cliente y escribí el trabajo.');if(form.kind==='quote'){const {error}=await supabase.rpc('mobile_create_quick_quote',{p_company_id:company.id,p_client_id:form.client_id,p_description:form.description.trim(),p_quantity:Number(form.quantity),p_unit_price:Number(form.unit_price),p_valid_until:form.valid_until||null,p_notes:form.notes||null});if(error)throw error;setMsg('Cotización creada correctamente.')}else{const {error}=await supabase.rpc('mobile_create_quick_work_order',{p_company_id:company.id,p_client_id:form.client_id,p_title:(form.title||form.description).trim(),p_description:form.description.trim(),p_quantity:Number(form.quantity),p_unit_price:Number(form.unit_price),p_due_at:form.due_at?new Date(form.due_at).toISOString():null,p_priority:form.priority});if(error)throw error;setMsg('Orden de trabajo creada correctamente.')}setForm(x=>({...x,title:'',description:'',quantity:1,unit_price:0,notes:''}));await load()}catch(e){setMsg(e.message||'No se pudo guardar.')}finally{setBusy(false)}}
 const saveClient=async()=>{setBusy(true);setMsg('');try{const {error}=await supabase.rpc('mobile_create_client',{p_company_id:company.id,p_name:clientForm.name,p_phone:clientForm.phone||null,p_whatsapp:clientForm.whatsapp||null,p_email:clientForm.email||null,p_address:clientForm.address||null});if(error)throw error;setClientForm({name:'',phone:'',whatsapp:'',email:'',address:''});setMsg('Cliente creado correctamente.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const useProduct=p=>{setForm(x=>({...x,description:p.name,unit_price:Number(p.sale_price||0)}));setTab('Rápido');setMsg(`${p.name} cargado en trabajo rápido.`)}
 const convertQuote=async q=>{const due=prompt('Fecha/hora estimada de entrega (opcional, YYYY-MM-DD HH:MM)','');setBusy(true);setMsg('');const {error}=await supabase.rpc('mobile_convert_quote_to_work_order',{p_quote_id:q.id,p_due_at:due?new Date(due).toISOString():null,p_priority:'NORMAL'});setBusy(false);if(error)setMsg(error.message);else{setMsg(`COT-${q.number} convertida a orden de trabajo.`);await load()}}
 const registerPayment=async()=>{setBusy(true);setMsg('');try{if(!canCollect)throw new Error('Solo Propietario/Administrador puede registrar cobros.');const {error}=await supabase.rpc('mobile_register_customer_payment',{p_receivable_id:payment.receivable_id,p_amount:Number(payment.amount),p_method:payment.method,p_reference:payment.reference||null,p_notes:payment.notes||null});if(error)throw error;const r=receivables.find(x=>x.id===payment.receivable_id);const text=`IDEALO SV\nComprobante de abono\nCliente: ${r?.clients?.name||'Cliente'}\nConcepto: ${r?.concept||''}\nMonto recibido: ${money(payment.amount)}\nMétodo: ${payment.method}\nFecha: ${new Date().toLocaleString('es-SV')}`;if(navigator.share)await navigator.share({title:'Comprobante de abono IDEALO SV',text}).catch(()=>{});else await navigator.clipboard?.writeText(text).catch(()=>{});setPayment({receivable_id:'',amount:'',method:'CASH',reference:'',notes:''});setMsg('Abono registrado y comprobante preparado.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const whatsapp=(client,text)=>{const p=svPhone(client?.whatsapp||client?.phone);if(!p||p==='503')return setMsg('Este cliente no tiene WhatsApp/teléfono registrado.');window.open(`https://wa.me/${p}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}
 const decide=async(o,decision)=>{setBusy(true);const comments=decision==='CHANGES_REQUESTED'?prompt('¿Qué cambios necesita el diseño?','')||'Cambios solicitados desde móvil':null;const {error}=await supabase.rpc('mobile_set_design_decision',{p_work_order_id:o.id,p_decision:decision,p_comments:comments});setBusy(false);if(error)setMsg(error.message);else{setMsg(decision==='APPROVED'?'Diseño aprobado.':'Cambios solicitados.');await load()}}
 const navigate=d=>{const q=d.delivery_address||d.clients?.address;if(!q)return setMsg('No hay dirección registrada.');window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`,'_blank','noopener,noreferrer')}
 const enablePush=async()=>{setMsg('');if(!('serviceWorker'in navigator)&&!('PushManager'in window))return setMsg('Este dispositivo no soporta Push.');if(!vapidKey)return setMsg('Push preparado, pero falta configurar VITE_VAPID_PUBLIC_KEY en el despliegue.');try{const reg=await navigator.serviceWorker.ready;const perm=await Notification.requestPermission();if(perm!=='granted')throw new Error('Permiso de notificaciones no concedido.');let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(vapidKey)});const j=sub.toJSON(),{data:{session}}=await supabase.auth.getSession();const {error}=await supabase.from('mobile_push_subscriptions').upsert({company_id:company.id,user_id:session.user.id,endpoint:j.endpoint,p256dh:j.keys?.p256dh,auth_key:j.keys?.auth,user_agent:navigator.userAgent,active:true},{onConflict:'user_id,endpoint'});if(error)throw error;setMsg('Dispositivo suscrito a notificaciones Push.')}catch(e){setMsg(e.message||'No se pudo activar Push.')}}
 if(!show||!company)return null
 const tabs=['Rápido','Clientes','Catálogo','Cotizaciones','Cobros','Diseños','Entregas','Push']
 return createPortal(<><button className="mobile-next-fab" onClick={()=>setOpen(true)}>＋</button>{open&&<div className="mobile-next-backdrop" onMouseDown={()=>setOpen(false)}><section className="mobile-next-panel" onMouseDown={e=>e.stopPropagation()}><header><div><small>IDEALO SV · APP MÓVIL</small><strong>Ventas y campo</strong></div><button onClick={()=>setOpen(false)}>×</button></header><nav>{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><main>{msg&&<div className="mobile-next-msg">{msg}</div>}
 {tab==='Rápido'&&<div className="mobile-next-form"><div className="mobile-kind"><button className={form.kind==='quote'?'active':''} onClick={()=>setForm({...form,kind:'quote'})}>Cotización</button><button className={form.kind==='order'?'active':''} onClick={()=>setForm({...form,kind:'order'})}>Orden de trabajo</button></div><label>Cliente<select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Seleccionar…</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{selectedClient&&<button className="mobile-wa" onClick={()=>whatsapp(selectedClient,`Hola ${selectedClient.name}, te escribimos de IDEALO SV.`)}>WhatsApp al cliente</button>}{form.kind==='order'&&<label>Título<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>}<label>Trabajo / descripción<textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="mobile-next-grid"><label>Cantidad<input type="number" min="0.01" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Precio unitario<input type="number" min="0" step="0.01" value={form.unit_price} onChange={e=>setForm({...form,unit_price:e.target.value})}/></label></div><strong className="mobile-next-total">Total: {money(Number(form.quantity)*Number(form.unit_price))}</strong>{form.kind==='quote'?<label>Válida hasta<input type="date" value={form.valid_until} onChange={e=>setForm({...form,valid_until:e.target.value})}/></label>:<><label>Entrega estimada<input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>Prioridad<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>NORMAL</option><option>HIGH</option><option>URGENT</option><option>LOW</option></select></label></>}<label>Notas<textarea rows="2" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="mobile-next-primary" disabled={busy||!canWrite} onClick={saveQuick}>{busy?'Guardando…':form.kind==='quote'?'Crear cotización':'Crear OT'}</button></div>}
 {tab==='Clientes'&&<div className="mobile-next-form"><h3>Nuevo cliente</h3><label>Nombre<input value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})}/></label><div className="mobile-next-grid"><label>Teléfono<input value={clientForm.phone} onChange={e=>setClientForm({...clientForm,phone:e.target.value})}/></label><label>WhatsApp<input value={clientForm.whatsapp} onChange={e=>setClientForm({...clientForm,whatsapp:e.target.value})}/></label></div><label>Correo<input type="email" value={clientForm.email} onChange={e=>setClientForm({...clientForm,email:e.target.value})}/></label><label>Dirección<textarea rows="2" value={clientForm.address} onChange={e=>setClientForm({...clientForm,address:e.target.value})}/></label><button className="mobile-next-primary" disabled={busy||!canWrite||!clientForm.name.trim()} onClick={saveClient}>Guardar cliente</button></div>}
 {tab==='Catálogo'&&<div>{products.length?products.map(p=><article className="mobile-next-row" key={p.id}><div><strong>{p.name}</strong><small>{p.category||'Trabajo terminado'} · {p.unit} · {money(p.sale_price)}</small><small>{p.description||''}</small></div><div className="mobile-next-actions"><button onClick={()=>useProduct(p)}>Usar</button></div></article>):<div className="mobile-next-empty">No hay productos terminados activos.</div>}</div>}
 {tab==='Cotizaciones'&&<div>{quotes.length?quotes.map(q=><article className="mobile-next-row" key={q.id}><div><strong>COT-{q.number} · {q.clients?.name||'Cliente'}</strong><small>{q.status} · {money(q.total)} · válida {q.valid_until||'—'}</small></div><div className="mobile-next-actions"><button onClick={()=>whatsapp(q.clients,`Hola ${q.clients?.name||''}. Te contactamos por la cotización COT-${q.number} de IDEALO SV.`)}>WhatsApp</button><button className="ok" disabled={busy} onClick={()=>convertQuote(q)}>Convertir a OT</button></div></article>):<div className="mobile-next-empty">No hay cotizaciones enviadas/aprobadas.</div>}</div>}
 {tab==='Cobros'&&<div className="mobile-next-form"><h3>Registrar abono</h3><label>Cuenta por cobrar<select value={payment.receivable_id} onChange={e=>setPayment({...payment,receivable_id:e.target.value})}><option value="">Seleccionar…</option>{receivables.map(r=><option key={r.id} value={r.id}>{r.clients?.name||'Cliente'} · {money(Number(r.amount_total)-Number(r.amount_paid))} · {r.concept}</option>)}</select></label><div className="mobile-next-grid"><label>Monto<input type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>Método<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>CASH</option><option>TRANSFER</option><option>CARD</option><option>CHECK</option><option>OTHER</option></select></label></div><label>Referencia<input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><label>Notas<textarea rows="2" value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})}/></label><button className="mobile-next-primary" disabled={busy||!canCollect||!payment.receivable_id||Number(payment.amount)<=0} onClick={registerPayment}>Registrar y compartir comprobante</button>{!canCollect&&<small>Solo Propietario/Administrador puede registrar cobros.</small>}</div>}
 {tab==='Diseños'&&<div>{orders.length?orders.map(o=><article className="mobile-next-row" key={o.id}><div><strong>OT-{o.number} · {o.clients?.name||'Cliente'}</strong><small>{o.title} · Diseño: {o.design_status}</small></div><div className="mobile-next-actions"><button onClick={()=>whatsapp(o.clients,`Hola ${o.clients?.name||''}. Tenemos listo el diseño de la OT-${o.number} para revisión.`)}>WhatsApp</button><button className="ok" disabled={busy} onClick={()=>decide(o,'APPROVED')}>Aprobar</button><button className="change" disabled={busy} onClick={()=>decide(o,'CHANGES_REQUESTED')}>Cambios</button></div></article>):<div className="mobile-next-empty">No hay diseños pendientes.</div>}</div>}
 {tab==='Entregas'&&<div>{deliveries.length?deliveries.map(d=><article className="mobile-next-row" key={d.id}><div><strong>{d.delivery_method==='INSTALLATION'?'Instalación':d.delivery_method==='DELIVERY'?'Entrega':'Retiro'} · OT-{d.work_orders?.number||'—'}</strong><small>{d.work_orders?.title||''} · {d.scheduled_at?new Date(d.scheduled_at).toLocaleTimeString('es-SV',{hour:'2-digit',minute:'2-digit'}):'Sin hora'} · {d.clients?.name||'Cliente'}</small><small>{d.delivery_address||d.clients?.address||'Sin dirección'}</small></div><div className="mobile-next-actions"><button onClick={()=>navigate(d)}>Navegar</button><button onClick={()=>whatsapp(d.clients,`Hola ${d.clients?.name||''}. Te contactamos por la ${d.delivery_method==='INSTALLATION'?'instalación':'entrega'} programada para hoy de IDEALO SV.`)}>WhatsApp</button></div></article>):<div className="mobile-next-empty">No hay entregas o instalaciones programadas para hoy.</div>}</div>}
 {tab==='Push'&&<div className="mobile-push-box"><h3>Notificaciones Push</h3><p>Permiten recibir avisos aunque la app no esté abierta.</p><button className="mobile-next-primary" onClick={enablePush}>Activar Push en este teléfono</button>{!vapidKey&&<small>Falta configurar la clave pública VAPID en el despliegue.</small>}</div>}
 </main></section></div>}</>,document.body)
}
