import { useEffect,useMemo,useState } from 'react'
import { createPortal } from 'react-dom'
import { supabase } from './lib/supabase.js'
import MobileEvidenceSheet from './MobileEvidenceSheet.jsx'
import { enqueueOffline,listOffline,removeOffline,offlineCount } from './mobileOffline.js'

const today=()=>new Date().toISOString().slice(0,10)
const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const closedOrder=s=>['DELIVERED','CANCELLED'].includes(s)
const nextStatus={PENDING:'DESIGN',DESIGN:'APPROVAL',APPROVAL:'PRODUCTION',PRODUCTION:'READY',READY:'DELIVERED'}
const roleLabel={owner:'Propietario',admin:'Administrador',staff:'Empleado',viewer:'Solo lectura'}

export default function MobileAppHost(){
 const [visible,setVisible]=useState(window.location.pathname==='/mobile')
 const [session,setSession]=useState(null),[company,setCompany]=useState(null),[role,setRole]=useState(null),[employee,setEmployee]=useState(null)
 const [tab,setTab]=useState('Inicio'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const [login,setLogin]=useState({email:'',password:''}),[data,setData]=useState({orders:[],agenda:[],clients:[],quotes:[],alerts:[],evidence:[]})
 const [online,setOnline]=useState(navigator.onLine),[pending,setPending]=useState(0),[evidenceOrder,setEvidenceOrder]=useState(null)

 useEffect(()=>{const h=e=>{if(e.detail==='App móviles')setVisible(true);else if(window.location.pathname!=='/mobile')setVisible(false)};window.addEventListener('idealo-module-change',h);return()=>window.removeEventListener('idealo-module-change',h)},[])
 useEffect(()=>{const up=()=>setOnline(true),down=()=>setOnline(false);window.addEventListener('online',up);window.addEventListener('offline',down);offlineCount().then(setPending).catch(()=>{});return()=>{window.removeEventListener('online',up);window.removeEventListener('offline',down)}},[])
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session||null));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[])
 useEffect(()=>{if(!session){setCompany(null);setRole(null);setEmployee(null);setLoading(false);return}let alive=true;(async()=>{setLoading(true);const {data:list}=await supabase.rpc('get_my_companies');const id=list?.[0]?.id;if(!id){setError('Tu usuario no tiene empresa asignada.');setLoading(false);return}const [{data:c},{data:m},{data:e}]=await Promise.all([supabase.from('companies').select('id,name').eq('id',id).single(),supabase.from('company_members').select('role').eq('company_id',id).eq('user_id',session.user.id).single(),supabase.from('employees').select('id,full_name,position,user_id').eq('company_id',id).eq('user_id',session.user.id).maybeSingle()]);if(alive){setCompany(c||null);setRole(m?.role||'viewer');setEmployee(e||null);setLoading(false)}})();return()=>{alive=false}},[session])

 const loadData=async()=>{if(!company||!online){setLoading(false);return}setLoading(true);setError('');let eventIds=null,workIds=null;if(role==='staff'&&employee){const {data:as}=await supabase.from('production_schedule_assignments').select('event_id,production_schedule_events(work_order_id)').eq('company_id',company.id).eq('employee_id',employee.id);eventIds=(as||[]).map(x=>x.event_id);workIds=[...new Set((as||[]).map(x=>x.production_schedule_events?.work_order_id).filter(Boolean))]}
 const oq=supabase.from('work_orders').select('id,number,title,status,priority,due_at,total,clients(name)').eq('company_id',company.id).order('due_at',{ascending:true}).limit(60);if(role==='staff')workIds?.length?oq.in('id',workIds):oq.eq('id','00000000-0000-0000-0000-000000000000')
 const aq=supabase.from('production_schedule_events').select('id,title,event_type,status,priority,scheduled_start,location,work_order_id').eq('company_id',company.id).gte('scheduled_start',`${today()}T00:00:00`).order('scheduled_start',{ascending:true}).limit(50);if(role==='staff')eventIds?.length?aq.in('id',eventIds):aq.eq('id','00000000-0000-0000-0000-000000000000')
 const [o,a,c,q,ar,ap,inv,ev]=await Promise.all([oq,aq,supabase.from('clients').select('id,name,phone,email,status').eq('company_id',company.id).order('created_at',{ascending:false}).limit(50),supabase.from('quotes').select('id,number,status,total,valid_until,created_at,clients(name)').eq('company_id',company.id).order('created_at',{ascending:false}).limit(50),supabase.from('accounts_receivable').select('id,amount_total,amount_paid,status,due_date,clients(name)').eq('company_id',company.id),supabase.from('accounts_payable').select('id,amount_total,amount_paid,status,due_date,suppliers(name)').eq('company_id',company.id),supabase.from('inventory_items').select('id,name,current_stock,minimum_stock,unit').eq('company_id',company.id).eq('active',true),supabase.from('work_order_evidence').select('id,work_order_id,evidence_type,created_at').eq('company_id',company.id).order('created_at',{ascending:false}).limit(200)])
 const alerts=[],now=today();(o.data||[]).filter(x=>!closedOrder(x.status)&&x.due_at&&x.due_at<new Date().toISOString()).slice(0,4).forEach(x=>alerts.push({id:`ot-${x.id}`,level:'critical',text:`OT-${x.number} atrasada: ${x.title}`}));if(role!=='staff'){(ar.data||[]).filter(x=>!['PAID','CANCELLED'].includes(x.status)&&x.due_date&&x.due_date<now).slice(0,3).forEach(x=>alerts.push({id:`ar-${x.id}`,level:'critical',text:`Cobro vencido: ${x.clients?.name||'Cliente'}`}));(ap.data||[]).filter(x=>!['PAID','CANCELLED'].includes(x.status)&&x.due_date&&x.due_date<now).slice(0,3).forEach(x=>alerts.push({id:`ap-${x.id}`,level:'important',text:`Pago vencido: ${x.suppliers?.name||'Proveedor'}`}));(inv.data||[]).filter(x=>Number(x.current_stock||0)<=Number(x.minimum_stock||0)).slice(0,4).forEach(x=>alerts.push({id:`inv-${x.id}`,level:'important',text:`Stock bajo: ${x.name}`}))}setData({orders:o.data||[],agenda:a.data||[],clients:c.data||[],quotes:q.data||[],alerts,evidence:ev.data||[]});setLoading(false)}
 useEffect(()=>{if(company)loadData()},[company,role,employee?.id,online])
 useEffect(()=>{if(!visible||!data.alerts.length||typeof Notification==='undefined'||Notification.permission!=='granted')return;const key='idealo-mobile-notified';const seen=new Set(JSON.parse(localStorage.getItem(key)||'[]'));const fresh=data.alerts.filter(x=>!seen.has(x.id)).slice(0,2);fresh.forEach(x=>new Notification('IDEALO SV',{body:x.text,tag:x.id}));fresh.forEach(x=>seen.add(x.id));localStorage.setItem(key,JSON.stringify([...seen].slice(-100)))},[data.alerts,visible])

 const syncOffline=async()=>{if(!online||!session)return;setBusy('sync');setError('');try{const items=await listOffline();for(const item of items){try{if(item.kind==='order_status'){const {error:e}=await supabase.rpc('mobile_set_work_order_status',item.payload);if(e)throw e}else if(item.kind==='event_complete'){const {error:e}=await supabase.rpc('mobile_complete_schedule_event',item.payload);if(e)throw e}else if(item.kind==='evidence'){const {error:u}=await supabase.storage.from('work-order-evidence').upload(item.meta.storage_path,item.blob,{contentType:item.meta.mime_type,upsert:false});if(u)throw u;const {error:i}=await supabase.from('work_order_evidence').insert(item.meta);if(i)throw i}await removeOffline(item.id)}catch(e){console.warn('Pendiente móvil no sincronizado',e)}}setPending(await offlineCount());await loadData()}finally{setBusy('')}}
 useEffect(()=>{if(online&&session)syncOffline()},[online,session?.user?.id])

 const home=useMemo(()=>{const active=data.orders.filter(x=>!closedOrder(x.status));return {active,late:active.filter(x=>x.due_at&&x.due_at<new Date().toISOString()),todayAgenda:data.agenda.filter(x=>x.scheduled_start?.slice(0,10)===today()),openQuotes:data.quotes.filter(x=>!['REJECTED','EXPIRED','CONVERTED'].includes(x.status))}},[data])
 const signIn=async e=>{e.preventDefault();setBusy('login');setError('');const {error:er}=await supabase.auth.signInWithPassword(login);if(er)setError(er.message);setBusy('')}
 const signOut=()=>supabase.auth.signOut()
 const advanceOrder=async o=>{const next=nextStatus[o.status];if(!next)return;if(!online){await enqueueOffline({kind:'order_status',payload:{p_work_order_id:o.id,p_status:next}});setPending(await offlineCount());setData(d=>({...d,orders:d.orders.map(x=>x.id===o.id?{...x,status:next}:x)}));return}setBusy(o.id);const {error:er}=await supabase.rpc('mobile_set_work_order_status',{p_work_order_id:o.id,p_status:next});if(er)setError(er.message);else await loadData();setBusy('')}
 const completeEvent=async e=>{if(!online){await enqueueOffline({kind:'event_complete',payload:{p_event_id:e.id}});setPending(await offlineCount());setData(d=>({...d,agenda:d.agenda.map(x=>x.id===e.id?{...x,status:'COMPLETED'}:x)}));return}setBusy(e.id);const {error:er}=await supabase.rpc('mobile_complete_schedule_event',{p_event_id:e.id});if(er)setError(er.message);else await loadData();setBusy('')}
 const enableNotifications=async()=>{if(typeof Notification==='undefined'){setError('Este dispositivo no admite avisos del navegador.');return}const p=await Notification.requestPermission();if(p==='granted')new Notification('IDEALO SV',{body:'Alertas móviles activadas.'})}
 if(!visible)return null
 const close=()=>{if(window.location.pathname==='/mobile')window.history.back();else setVisible(false)}
 const canWrite=role&&role!=='viewer',ownerMode=['owner','admin'].includes(role)
 const tabs=ownerMode?['Inicio','Producción','Agenda','Clientes','Cotizaciones','Perfil']:['Inicio','Producción','Agenda','Perfil']
 const evidenceCount=id=>data.evidence.filter(x=>x.work_order_id===id).length
 return createPortal(<div className="mobile-app-shell">
  <header className="mobile-topbar"><div><span className="mobile-brand-mark">I</span><div><strong>IDEALO SV</strong><small>{company?.name||'App móvil'}</small></div></div><div className="mobile-top-actions"><span className={online?'mobile-online':'mobile-offline'}>{online?'En línea':'Sin señal'}</span>{pending>0&&<button className="mobile-sync" onClick={syncOffline} disabled={!online||busy==='sync'}>{busy==='sync'?'…':`↻ ${pending}`}</button>}<button type="button" onClick={close}>×</button></div></header>
  {!session?<main className="mobile-login"><section><p>ACCESO MÓVIL</p><h1>Iniciar sesión</h1><form onSubmit={signIn}><label>Correo<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required autoComplete="email"/></label><label>Contraseña<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required autoComplete="current-password"/></label>{error&&<div className="mobile-error">{error}</div>}<button type="submit" disabled={busy==='login'}>{busy==='login'?'Ingresando…':'Entrar a IDEALO'}</button></form></section></main>:<>
  <main className="mobile-content">{!online&&<div className="mobile-offline-banner">Modo sin conexión activo. Los cambios se guardarán en este dispositivo y se sincronizarán al recuperar señal.</div>}{error&&<div className="mobile-error">{error}<button onClick={()=>setError('')}>×</button></div>}{loading?<div className="mobile-empty">Sincronizando información…</div>:<>
   {tab==='Inicio'&&<><section className="mobile-hero"><p>{ownerMode?'VISTA PROPIETARIO':'MI JORNADA'}</p><h1>{ownerMode?'Control desde tu teléfono':employee?.full_name||'Trabajo asignado'}</h1><small className="mobile-role">{roleLabel[role]||role}{employee?.position?` · ${employee.position}`:''}</small><div className="mobile-kpis"><Kpi t="OT activas" v={home.active.length}/><Kpi t="Atrasadas" v={home.late.length}/><Kpi t="Agenda hoy" v={home.todayAgenda.length}/><Kpi t={ownerMode?'Cotizaciones':'Alertas'} v={ownerMode?home.openQuotes.length:data.alerts.length}/></div></section>{data.alerts.length>0&&<section className="mobile-card"><h3>Necesita atención</h3>{data.alerts.map(x=><div className={`mobile-alert ${x.level}`} key={x.id}>{x.text}</div>)}</section>}<section className="mobile-card"><h3>{ownerMode?'Próximos trabajos':'Mis trabajos'}</h3><OrderList rows={home.active.slice(0,8)} canWrite={canWrite} busy={busy} onAdvance={advanceOrder} onEvidence={setEvidenceOrder} evidenceCount={evidenceCount}/></section></>}
   {tab==='Producción'&&<section className="mobile-card mobile-full"><h2>Producción</h2><p className="mobile-muted">{ownerMode?'Órdenes activas de la empresa.':'Solo órdenes vinculadas a tus actividades asignadas.'}</p><OrderList rows={home.active} canWrite={canWrite} busy={busy} onAdvance={advanceOrder} onEvidence={setEvidenceOrder} evidenceCount={evidenceCount}/></section>}
   {tab==='Agenda'&&<section className="mobile-card mobile-full"><h2>Agenda</h2>{data.agenda.length?data.agenda.map(x=><div className="mobile-row mobile-action-row" key={x.id}><div><strong>{x.title}</strong><small>{new Date(x.scheduled_start).toLocaleString('es-SV')} · {x.event_type}{x.location?` · ${x.location}`:''}</small></div><div className="mobile-row-actions"><span>{x.status}</span>{canWrite&&x.status!=='COMPLETED'&&<button disabled={busy===x.id} onClick={()=>completeEvent(x)}>Completar</button>}</div></div>):<div className="mobile-empty">No hay actividades próximas.</div>}</section>}
   {tab==='Clientes'&&<section className="mobile-card mobile-full"><h2>Clientes</h2>{data.clients.length?data.clients.map(x=><div className="mobile-row" key={x.id}><div><strong>{x.name}</strong><small>{x.phone||x.email||'Sin contacto registrado'}</small></div><span>{x.status||'ACTIVO'}</span></div>):<div className="mobile-empty">No hay clientes registrados.</div>}</section>}
   {tab==='Cotizaciones'&&<section className="mobile-card mobile-full"><h2>Cotizaciones</h2>{data.quotes.length?data.quotes.map(x=><div className="mobile-row" key={x.id}><div><strong>COT-{x.number} · {x.clients?.name||'Cliente'}</strong><small>{money(x.total)} · válida hasta {x.valid_until||'—'}</small></div><span>{x.status}</span></div>):<div className="mobile-empty">No hay cotizaciones registradas.</div>}</section>}
   {tab==='Perfil'&&<section className="mobile-card mobile-full mobile-profile"><h2>Mi acceso</h2><div className="mobile-profile-line"><span>Usuario</span><strong>{session.user.email}</strong></div><div className="mobile-profile-line"><span>Rol</span><strong>{roleLabel[role]||role}</strong></div><div className="mobile-profile-line"><span>Empleado vinculado</span><strong>{employee?.full_name||'No vinculado'}</strong></div><div className="mobile-profile-line"><span>Estado</span><strong>{online?'En línea':'Modo offline'}</strong></div><div className="mobile-profile-line"><span>Pendientes por sincronizar</span><strong>{pending}</strong></div>{pending>0&&<button disabled={!online||busy==='sync'} onClick={syncOffline}>Sincronizar ahora</button>}<button onClick={enableNotifications}>Activar alertas móviles</button><button className="mobile-secondary" onClick={signOut}>Cerrar sesión</button></section>}
  </>}</main>
  <nav className="mobile-bottom-nav" style={{gridTemplateColumns:`repeat(${tabs.length},1fr)`}}>{tabs.map(name=><button type="button" key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><span>{name==='Inicio'?'⌂':name==='Producción'?'▣':name==='Agenda'?'◷':name==='Clientes'?'◎':name==='Cotizaciones'?'$':'●'}</span><small>{name}</small></button>)}</nav></>}
  {evidenceOrder&&company&&<MobileEvidenceSheet supabase={supabase} company={company} order={evidenceOrder} onClose={()=>setEvidenceOrder(null)} onSaved={async()=>{setPending(await offlineCount());if(online)await loadData()}}/>}
 </div>,document.body)
}

function Kpi({t,v}){return <article><strong>{v}</strong><span>{t}</span></article>}
function OrderList({rows,canWrite,busy,onAdvance,onEvidence,evidenceCount}){return rows.length?rows.map(x=><div className="mobile-row mobile-action-row" key={x.id}><div><strong>OT-{x.number} · {x.clients?.name||'Cliente'}</strong><small>{x.title} · {x.due_at?new Date(x.due_at).toLocaleDateString('es-SV'):'Sin fecha'} · {x.priority}</small><small>{evidenceCount(x.id)} evidencia(s)</small></div><div className="mobile-row-actions"><span>{x.status}</span>{canWrite&&<button className="mobile-evidence-button" onClick={()=>onEvidence(x)}>📷 Evidencia</button>}{canWrite&&nextStatus[x.status]&&<button disabled={busy===x.id} onClick={()=>onAdvance(x)}>{busy===x.id?'…':`→ ${nextStatus[x.status]}`}</button>}</div></div>):<div className="mobile-empty">No hay órdenes activas.</div>}
