import { useEffect,useState } from 'react'

const typeLabel={PRODUCTION:'Producción',INSTALLATION:'Instalación',DELIVERY:'Entrega',SIGNATURE:'Firma',OTHER:'Otra'}
const fmt=d=>d?new Date(d).toLocaleString('es-SV'):'—'

export default function MobileEvidenceGallery({supabase,company,order,onClose}){
 const [rows,setRows]=useState([]),[urls,setUrls]=useState({}),[busy,setBusy]=useState(true),[msg,setMsg]=useState('')
 useEffect(()=>{let alive=true;(async()=>{setBusy(true);const {data,error}=await supabase.from('work_order_evidence').select('id,evidence_type,storage_path,file_name,mime_type,notes,latitude,longitude,accuracy_m,recipient_name,created_at').eq('company_id',company.id).eq('work_order_id',order.id).order('created_at',{ascending:false});if(!alive)return;if(error){setMsg(error.message);setRows([])}else{setRows(data||[]);const map={};for(const r of data||[]){const {data:s}=await supabase.storage.from('work-order-evidence').createSignedUrl(r.storage_path,900);if(s?.signedUrl)map[r.id]=s.signedUrl}setUrls(map)}setBusy(false)})();return()=>{alive=false}},[company.id,order.id])
 const navigate=r=>{const q=r.latitude&&r.longitude?`${r.latitude},${r.longitude}`:null;if(q)window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(q)}`,'_blank','noopener,noreferrer')}
 const share=async()=>{const delivery=rows.find(r=>r.evidence_type==='DELIVERY')||rows.find(r=>r.evidence_type==='INSTALLATION')||rows[0];const signature=rows.find(r=>r.evidence_type==='SIGNATURE');const text=[`IDEALO SV · Comprobante de trabajo`,`OT-${order.number} · ${order.title}`,order.clients?.name?`Cliente: ${order.clients.name}`:null,`Estado: ${order.status}`,delivery?.recipient_name?`Recibido por: ${delivery.recipient_name}`:null,delivery?.created_at?`Fecha: ${fmt(delivery.created_at)}`:null,delivery?.latitude?`Ubicación: ${delivery.latitude}, ${delivery.longitude}`:null,`Evidencias registradas: ${rows.length}`,signature?'Firma del cliente registrada.':null].filter(Boolean).join('\n');const url=delivery?urls[delivery.id]:null;try{if(navigator.share)await navigator.share({title:`Comprobante OT-${order.number}`,text,url:url||undefined});else{await navigator.clipboard.writeText(url?`${text}\n${url}`:text);setMsg('Comprobante copiado al portapapeles.')}}catch(e){if(e?.name!=='AbortError')setMsg('No se pudo compartir el comprobante.') }}
 return <div className="mobile-sheet-backdrop" onMouseDown={onClose}><section className="mobile-sheet mobile-gallery-sheet" onMouseDown={e=>e.stopPropagation()}><header><div><small>GALERÍA OT-{order.number}</small><strong>{order.title}</strong></div><button onClick={onClose}>×</button></header><div className="mobile-sheet-body"><button className="mobile-primary-action" onClick={share} disabled={!rows.length}>Compartir comprobante de entrega</button>{msg&&<div className="mobile-evidence-msg">{msg}</div>}{busy?<div className="mobile-empty">Abriendo evidencias…</div>:rows.length?<div className="mobile-evidence-grid">{rows.map(r=><article key={r.id} className="mobile-evidence-card"><button className="mobile-evidence-preview" onClick={()=>urls[r.id]&&window.open(urls[r.id],'_blank','noopener,noreferrer')}>{urls[r.id]?<img src={urls[r.id]} alt={typeLabel[r.evidence_type]||'Evidencia'}/>:<span>Imagen privada</span>}</button><div><strong>{typeLabel[r.evidence_type]||r.evidence_type}</strong><small>{fmt(r.created_at)}</small>{r.recipient_name&&<small>Recibe: {r.recipient_name}</small>}{r.notes&&<p>{r.notes}</p>}<div className="mobile-evidence-actions"><button onClick={()=>urls[r.id]&&window.open(urls[r.id],'_blank','noopener,noreferrer')}>Abrir</button>{r.latitude&&r.longitude&&<button onClick={()=>navigate(r)}>Navegar</button>}</div></div></article>)}</div>:<div className="mobile-empty">Esta OT todavía no tiene evidencias.</div>}</div></section></div>
}
