import { useEffect,useMemo,useState } from 'react'
import { createPortal } from 'react-dom'
import { supabase } from './lib/supabase.js'

const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const phone=v=>String(v||'').replace(/\D/g,'')
const actionLabel=v=>({COBRAR_SALDO_VENCIDO:'Cobrar saldo vencido',DAR_SEGUIMIENTO_HOY:'Dar seguimiento hoy',SEGUIR_COTIZACION:'Mover cotización a cierre',REACTIVAR_CLIENTE:'Reactivar cliente',FIDELIZAR_Y_PEDIR_REFERIDOS:'Fidelizar y pedir referidos',GENERAR_PRIMERA_VENTA:'Convertir primera venta',PROPONER_RECOMPRA:'Proponer recompra'}[v]||'Mantener seguimiento')

export default function MobileClient360(){
 const [visible,setVisible]=useState(location.pathname==='/mobile'),[open,setOpen]=useState(false),[company,setCompany]=useState(null),[role,setRole]=useState('viewer')
 const [clients,setClients]=useState([]),[selected,setSelected]=useState(''),[q,setQ]=useState(''),[intel,setIntel]=useState(null),[contacts,setContacts]=useState([]),[addresses,setAddresses]=useState([]),[interactions,setInteractions]=useState([]),[receivables,setReceivables]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const [follow,setFollow]=useState({interaction_type:'FOLLOW_UP',channel:'WHATSAPP',subject:'',details:'',next_follow_up_at:''})
 useEffect(()=>{const h=e=>{if(e.detail==='App móviles')setVisible(true);else if(location.pathname!=='/mobile')setVisible(false)};window.addEventListener('idealo-module-change',h);return()=>window.removeEventListener('idealo-module-change',h)},[])
 useEffect(()=>{if(!visible)return;(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data:cs}=await supabase.rpc('get_my_companies');const id=cs?.[0]?.id;if(!id)return;const [{data:c},{data:m},{data:list}]=await Promise.all([supabase.from('companies').select('id,name').eq('id',id).single(),supabase.from('company_members').select('role').eq('company_id',id).eq('user_id',session.user.id).single(),supabase.from('clients').select('id,name,trade_name,phone,whatsapp,email,status').eq('company_id',id).order('name')]);setCompany(c);setRole(m?.role||'viewer');setClients(list||[])})()},[visible])
 const loadClient=async id=>{if(!company||!id)return;setBusy(true);setMsg('');const [i,c,a,x,r]=await Promise.all([
   supabase.from('client_commercial_intelligence').select('*').eq('company_id',company.id).eq('client_id',id).maybeSingle(),
   supabase.from('client_contacts').select('id,name,position,phone,whatsapp,email,is_primary').eq('company_id',company.id).eq('client_id',id).order('is_primary',{ascending:false}),
   supabase.from('client_addresses').select('id,address_type,label,department,municipality,address,is_primary').eq('company_id',company.id).eq('client_id',id).order('is_primary',{ascending:false}),
   supabase.from('client_interactions').select('id,interaction_type,channel,subject,details,occurred_at,next_follow_up_at,outcome').eq('company_id',company.id).eq('client_id',id).order('occurred_at',{ascending:false}).limit(20),
   supabase.from('accounts_receivable').select('id,number,concept,amount_total,amount_paid,due_date,status').eq('company_id',company.id).eq('client_id',id).not('status','in','(PAID,CANCELLED)').order('due_date',{ascending:true})
 ]);const e=i.error||c.error||a.error||x.error||r.error;if(e)setMsg(e.message);setIntel(i.data||null);setContacts(c.data||[]);setAddresses(a.data||[]);setInteractions(x.data||[]);setReceivables(r.data||[]);setBusy(false)}
 useEffect(()=>{if(selected)loadClient(selected)},[selected,company?.id])
 const client=clients.find(x=>x.id===selected)
 const filtered=useMemo(()=>clients.filter(x=>[x.name,x.trade_name,x.phone,x.whatsapp,x.email].join(' ').toLowerCase().includes(q.toLowerCase())),[clients,q])
 const canWrite=['owner','admin','staff'].includes(role)
 const saveFollow=async()=>{if(!canWrite||!selected)return;setBusy(true);setMsg('');const {error}=await supabase.from('client_interactions').insert({company_id:company.id,client_id:selected,interaction_type:follow.interaction_type,channel:follow.channel,subject:follow.subject||null,details:follow.details.trim(),next_follow_up_at:follow.next_follow_up_at?new Date(follow.next_follow_up_at).toISOString():null,occurred_at:new Date().toISOString()});if(error)setMsg(error.message);else{setMsg('Seguimiento registrado.');setFollow({interaction_type:'FOLLOW_UP',channel:'WHATSAPP',subject:'',details:'',next_follow_up_at:''});await loadClient(selected)}setBusy(false)}
 const whatsapp=()=>{const p=phone(client?.whatsapp||client?.phone);if(!p)return setMsg('El cliente no tiene teléfono o WhatsApp.');const n=p.startsWith('503')?p:`503${p}`;window.open(`https://wa.me/${n}?text=${encodeURIComponent(`Hola ${client?.name||''}, te escribimos de IDEALO SV.`)}`,'_blank','noopener,noreferrer')}
 if(!visible||!company)return null
 return createPortal(<><button type="button" className="mobile-c360-fab" onClick={()=>setOpen(true)}>360</button>{open&&<div className="mobile-c360-backdrop" onMouseDown={()=>setOpen(false)}><section className="mobile-c360-panel" onMouseDown={e=>e.stopPropagation()}><header><div><small>IDEALO SV · CLIENTE 360</small><strong>Inteligencia y seguimiento</strong></div><button type="button" onClick={()=>setOpen(false)}>×</button></header><main><input className="mobile-c360-search" placeholder="Buscar cliente…" value={q} onChange={e=>setQ(e.target.value)}/><select className="mobile-c360-select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Seleccionar cliente…</option>{filtered.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{busy&&<div className="mobile-c360-note">Cargando…</div>}{msg&&<div className="mobile-c360-note">{msg}</div>}{client&&<><section className="mobile-c360-hero"><div><h2>{client.name}</h2><p>{client.trade_name||'Sin nombre comercial'}</p></div>{intel&&<div className="mobile-c360-score"><strong>{intel.commercial_score}</strong><small>/100</small><span>{intel.commercial_segment}</span></div>}</section>{intel&&<><div className="mobile-c360-kpis"><b>{money(intel.lifetime_sales)}<small>Valor de vida</small></b><b>{money(intel.outstanding_balance)}<small>Por cobrar</small></b><b>{money(intel.overdue_balance)}<small>Vencido</small></b><b>{Number(intel.estimated_margin_pct||0).toFixed(1)}%<small>Margen</small></b></div><section className="mobile-c360-action"><small>PRÓXIMA MEJOR ACCIÓN</small><strong>{actionLabel(intel.next_best_action)}</strong><p>{intel.recommendation}</p></section></>}
 <div className="mobile-c360-actions"><button type="button" onClick={whatsapp}>WhatsApp</button>{client.phone&&<a href={`tel:${client.phone}`}>Llamar</a>}</div>
 <section className="mobile-c360-card"><h3>Crédito y cobros</h3><p>Conversión: {Number(intel?.conversion_rate||0).toFixed(1)}% · Ticket: {money(intel?.avg_ticket)}</p><p>Retraso promedio: {Math.round(Number(intel?.avg_payment_delay_days||0))} días · Vencidas: {intel?.overdue_count||0}</p>{receivables.slice(0,4).map(r=><div className="mobile-c360-row" key={r.id}><div><strong>CxC-{r.number}</strong><small>{r.concept}</small></div><b>{money(Number(r.amount_total)-Number(r.amount_paid))}</b></div>)}</section>
 <section className="mobile-c360-card"><h3>Contactos y ubicaciones</h3>{contacts.slice(0,4).map(x=><div className="mobile-c360-row" key={x.id}><div><strong>{x.name}{x.is_primary?' · Principal':''}</strong><small>{x.position||''} {x.whatsapp||x.phone||x.email||''}</small></div></div>)}{addresses.slice(0,3).map(x=><div className="mobile-c360-row" key={x.id}><div><strong>{x.label||x.address_type}{x.is_primary?' · Principal':''}</strong><small>{x.address}</small></div></div>)}</section>
 <section className="mobile-c360-card"><h3>Seguimiento comercial</h3>{interactions.slice(0,5).map(x=><div className="mobile-c360-row" key={x.id}><div><strong>{x.subject||x.interaction_type}</strong><small>{new Date(x.occurred_at).toLocaleString('es-SV')} · {x.channel||'Sin canal'}</small></div></div>)}{canWrite&&<div className="mobile-c360-follow"><select value={follow.interaction_type} onChange={e=>setFollow({...follow,interaction_type:e.target.value})}><option>FOLLOW_UP</option><option>CALL</option><option>VISIT</option><option>QUOTE</option><option>COLLECTION</option></select><select value={follow.channel} onChange={e=>setFollow({...follow,channel:e.target.value})}><option>WHATSAPP</option><option>PHONE</option><option>EMAIL</option><option>IN_PERSON</option><option>OTHER</option></select><input placeholder="Asunto" value={follow.subject} onChange={e=>setFollow({...follow,subject:e.target.value})}/><textarea rows="3" placeholder="Detalle del seguimiento" value={follow.details} onChange={e=>setFollow({...follow,details:e.target.value})}/><label>Próximo seguimiento<input type="datetime-local" value={follow.next_follow_up_at} onChange={e=>setFollow({...follow,next_follow_up_at:e.target.value})}/></label><button type="button" disabled={busy||!follow.details.trim()} onClick={saveFollow}>Registrar seguimiento</button></div>}</section></>}</main></section></div>}</>,document.body)
}
