const DB='idealo-mobile-offline-v1',QUEUE='queue',SNAPSHOTS='snapshots'
const openDb=()=>new Promise((resolve,reject)=>{const req=indexedDB.open(DB,2);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(QUEUE))db.createObjectStore(QUEUE,{keyPath:'id'});if(!db.objectStoreNames.contains(SNAPSHOTS))db.createObjectStore(SNAPSHOTS,{keyPath:'userId'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})
export const enqueueOffline=async item=>{const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(QUEUE,'readwrite');tx.objectStore(QUEUE).put({...item,id:item.id||crypto.randomUUID(),queuedAt:new Date().toISOString()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export const listOffline=async()=>{const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(QUEUE).objectStore(QUEUE).getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>{const byTime=String(a.queuedAt||'').localeCompare(String(b.queuedAt||''));if(byTime)return byTime;if(a.kind===b.kind)return String(a.id||'').localeCompare(String(b.id||''));if(a.kind==='delivery_confirm')return 1;if(b.kind==='delivery_confirm')return -1;return String(a.id||'').localeCompare(String(b.id||''))}));req.onerror=()=>reject(req.error)})}
export const removeOffline=async id=>{const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(QUEUE,'readwrite');tx.objectStore(QUEUE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export const offlineCount=async()=>{const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(QUEUE).objectStore(QUEUE).count();req.onsuccess=()=>resolve(req.result||0);req.onerror=()=>reject(req.error)})}
export const saveMobileSnapshot=async snapshot=>{if(!snapshot?.userId)return;const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(SNAPSHOTS,'readwrite');tx.objectStore(SNAPSHOTS).put({...snapshot,savedAt:new Date().toISOString()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export const getMobileSnapshot=async userId=>{if(!userId)return null;const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(SNAPSHOTS).objectStore(SNAPSHOTS).get(userId);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}
export const clearMobileSnapshot=async userId=>{if(!userId)return;const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(SNAPSHOTS,'readwrite');tx.objectStore(SNAPSHOTS).delete(userId);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
