import {useEffect,useMemo,useState} from 'react'
import {createPortal} from 'react-dom'
import {supabase} from './lib/supabase.js'
import MobileEvidenceSheet from './MobileEvidenceSheet.jsx'
import MobileOwnerHub from './MobileOwnerHub.jsx'
import {enqueueOffline,listOffline,removeOffline,offlineCount,saveMobileSnapshot,getMobileSnapshot,clearMobileSnapshot} from './mobileOffline.js'

const today=()=>new Date().toISOString().slice(0,10)
const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))
const closed=s=>['DELIVERED','CANCELLED'].includes(s)
const nextStatus={PENDING:'DESIGN',DESIGN:'APPROVAL',APPROVAL:'PRODUCTION',PRODUCTION:'READY',READY:'DELIVERED'}
const roleLabel={owner:'Propietario',admin:'Administrador',staff:'Empleado',viewer:'Solo lectura'}
const tabs=['Inicio','Trabajo','Clientes','Más']
const emptyData=()=>({orders:[],agenda:[],clients:[],quotes:[],alerts:[],evidence:[]})

export default function MobileAppHost(){
 const [visible,setVisible]=useState(location.pathname==='/mobile'),[session,setSession]=useState(null),[company,setCompany]=useState(null),[role,setRole]=useState(null),[employee,setEmployee]=useState(null)
 const [tab,setTab]=useState('Inicio'),[workView,setWorkView]=useState('Producción'),[clientView,setClientView]=useState('Clientes'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const [login,setLogin]=useState({email:'',password:''}),[data,setData]=useState(emptyData),[online,setOnline]=useState(navigator.onLine),[pending,setPending]=useState(0),[evidenceOrder,setEvidenceOrder]=useState(null),[cachedAt,setCachedAt]=useState(null)

 useEffect(()=>{const h=e=>{if(e.detail==='App móviles')setVisible(true);else if(location.pathname!=='/mobile')setVisible(false)};window.addEventListener('idealo-module-change',h);return()=>window.removeEventListener('idealo-module-change',h)},[])
 useEffect(()=>{const up=()=>setOnline(true),down=()=>setOnline(false);addEventListener('online',up);addEventListener('offline',down);offlineCount().then(setPending).catch(()=>{});return()=>{removeEventListener('online',up);removeEventListener('offline',down)}},[])
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session||null));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[])

 useEffect(()=>{let alive=true;if(!session){setCompany(null);setRole(null);setEmployee(null);setData(emptyData());setCachedAt(null);setLoading(false);return()=>{alive=false}}
  ;(async()=>{setLoading(true);const cached=await getMobileSnapshot(session.user.id).catch(()=>null);if(cached&&alive){setCompany(cached.company||null);setRole(cached.role||'viewer');setEmployee(cached.employee||null);setData(cached.data||emptyData());setCachedAt(cached.savedAt||null);setLoading(false)}if(!navigator.onLine){if(!cached&&alive)setError('No hay datos guardados todavía. Conectate una vez para preparar el modo sin internet.');if(alive)setLoading(false);return}
   const {data:list,error:listError}=await supabase.rpc('get_my_companies');if(listError){if(!cached&&alive)setError(listError.message);if(alive)setLoading(false);return}const id=list?.[0]?.id;if(!id){if(alive){setError('Tu usuario no tiene empresa asignada.');setLoading(false)}return}
   const [{data:c,error:ce},{data:m,error:me},{data:e,error:ee}]=await Promise.all([supabase.from('companies').select('id,name').eq('id',id).single(),supabase.from('company_members').select('role').eq('company_id',id).eq('user_id',session.user.id).single(),supabase.from('employees').select('id,full_name,position,user_id').eq('company_id',id).eq('user_id',session.user.id).maybeSingle()]);if(!alive)return;if(ce||me||ee){if(!cached)setError((ce||me||ee)?.message||'No se pudo cargar el perfil móvil.');setLoading(false);return}setCompany(c||null);setRole(m?.role||'viewer');setEmployee(e||null);setLoading(false)
  })();return()=>{alive=false}},[session?.user?.id])

 const persistSnapshot=async(nextData,nextCompany=company,nextRole=role,nextEmployee=employee)=>{if(!session?.user?.id||!nextCompany?.id)return;await saveMobileSnapshot({userId:session.user.id,company:nextCompany,role:nextRole||'viewer',employee:nextEmployee||null,data:nextData}).catch(()=>{});setCachedAt(new Date().toISOString())}
 const loadData=async()=>{if(!company){setLoading(false);return}if(!online){const cached=await getMobileSnapshot(session?.user?.id).catch(()=>null);if(cached){setData(cached.data||emptyData());setCachedAt(cached.savedAt||null)}setLoading(false);return}setLoading(true);setError('');let eventIds=null,workIds=null;if(role==='staff'&&employee){const {data:as}=await supabase.from('production_schedule_assignments').select('event_id,production_schedule_events(work_order_id)').eq('company_id',company.id).eq('employee_id',employee.id);eventIds=(as||[]).map(x=>x.event_id);workIds=[...new Set((as||[]).map(x=>x.production_schedule_events?.work_order_id).filter(Boolean))]}
  const oq=supabase.from('work_orders').select('id,number,title,status,priority,due_at,total,clients(name)').eq('company_id',company.id).order('due_at',{ascending:true}).limit(60);if(role==='staff')workIds?.length?oq.in('id',workIds):oq.eq('id','00000000-0000-0000-0000-000000000000')
  const aq=supabase.from('production_schedule_events').select('id,title,event_type,status,priority,scheduled_start,location,work_order_id').eq('company_id',company.id).gte('scheduled_start',`${today()}T00:00:00`).order('scheduled_start',{ascending:true}).limit(50);if(role==='staff')eventIds?.length?aq.in('id',eventIds):aq.eq('id','00000000-0000-0000-0000-000000000000')
  const [o,a,c,q,ar,ap,inv,ev]=await Promise.all([oq,aq,supabase.from('clients').select('id,name,phone,email,status').eq('company_id',company.id).order('created_at',{ascending:false}).limit(50),supabase.from('quotes').select('id,number,status,total,valid_until,created_at,clients(name)').eq('company_id',company.id).order('created_at',{ascending:false}).limit(50),supabase.from('accounts_receivable').select('id,status,due_date,clients(name)').eq('company_id',company.id),supabase.from('accounts_payable').select('id,status,due_date,suppliers(name)').eq('company_id',company.id),supabase.from('inventory_items').select('id,name,current_stock,minimum_stock').eq('company_id',company.id).eq('active',true),supabase.from('work_order_evidence').select('id,work_order_id').eq('company_id',company.id).limit(200)])
  const queryError=[o,a,c,q,ar,ap,inv,ev].find(x=>x.error)?.error;if(queryError){setError(`No se pudo actualizar todo. Se conservan los últimos datos guardados. ${queryError.message||''}`.trim());const cached=await getMobileSnapshot(session?.user?.id).catch(()=>null);if(cached)setData(cached.data||emptyData());setLoading(false);return}
  const alerts=[],now=today();(o.data||[]).filter(x=>!closed(x.status)&&x.due_at&&x.due_at<new Date().toISOString()).slice(0,3).forEach(x=>alerts.push({id:`ot-${x.id}`,text:`OT-${x.number} atrasada · ${x.title}`}));if(role!=='staff'){(ar.data||[]).filter(x=>!['PAID','CANCELLED'].includes(x.status)&&x.due_date&&x.due_date<now).slice(0,2).forEach(x=>alerts.push({id:`ar-${x.id}`,text:`Cobro vencido · ${x.clients?.name||'Cliente'}`}));(ap.data||[]).filter(x=>!['PAID','CANCELLED'].includes(x.status)&&x.due_date&&x.due_date<now).slice(0,2).forEach(x=>alerts.push({id:`ap-${x.id}`,text:`Pago vencido · ${x.suppliers?.name||'Proveedor'}`}));(inv.data||[]).filter(x=>Number(x.current_stock||0)<=Number(x.minimum_stock||0)).slice(0,2).forEach(x=>alerts.push({id:`inv-${x.id}`,text:`Stock bajo · ${x.name}`}))}
  const nextData={orders:o.data||[],agenda:a.data||[],clients:c.data||[],quotes:q.data||[],alerts,evidence:ev.data||[]};setData(nextData);await persistSnapshot(nextData);setLoading(false)}
 useEffect(()=>{if(company)loadData()},[company?.id,role,employee?.id,online])

 const updateCachedData=async updater=>{let next;setData(current=>{next=updater(current);return next});setTimeout(()=>{if(next)persistSnapshot(next)},0)}
 const syncOffline=async()=>{if(!online||!session)return;setBusy('sync');let failed=0;try{for(const item of await listOffline()){try{if(item.kind==='order_status'){const {error:e}=await supabase.rpc('mobile_set_work_order_status',item.payload);if(e)throw e}else if(item.kind==='event_complete'){const {error:e}=await supabase.rpc('mobile_complete_schedule_event',item.payload);if(e)throw e}else if(item.kind==='evidence'){const {error:u}=await supabase.storage.from('work-order-evidence').upload(item.meta.storage_path,item.blob,{contentType:item.meta.mime_type,upsert:false});if(u)throw u;const {error:i}=await supabase.from('work_order_evidence').insert(item.meta);if(i)throw i}await removeOffline(item.id)}catch{failed++}}setPending(await offlineCount());await loadData();if(failed)setError(`${failed} cambio(s) siguen pendientes de sincronizar.`)}finally{setBusy('')}}
 useEffect(()=>{if(online&&session)syncOffline()},[online,session?.user?.id])
 const home=useMemo(()=>{const active=data.orders.filter(x=>!closed(x.status));return{active,late:active.filter(x=>x.due_at&&x.due_at<new Date().toISOString()),todayAgenda:data.agenda.filter(x=>x.scheduled_start?.slice(0,10)===today())}},[data])
 const canWrite=role&&role!=='viewer',ownerMode=['owner','admin'].includes(role)
 const advanceOrder=async o=>{const next=nextStatus[o.status];if(!next)return;if(!online){await enqueueOffline({kind:'order_status',payload:{p_work_order_id:o.id,p_status:next}});setPending(await offlineCount());await updateCachedData(d=>({...d,orders:d.orders.map(x=>x.id===o.id?{...x,status:next}:x)}));return}setBusy(o.id);const {error:e}=await supabase.rpc('mobile_set_work_order_status',{p_work_order_id:o.id,p_status:next});if(e)setError(e.message);else await loadData();setBusy('')}
 const completeEvent=async e=>{if(!online){await enqueueOffline({kind:'event_complete',payload:{p_event_id:e.id}});setPending(await offlineCount());await updateCachedData(d=>({...d,agenda:d.agenda.map(x=>x.id===e.id?{...x,status:'COMPLETED'}:x)}));return}setBusy(e.id);const {error:er}=await supabase.rpc('mobile_complete_schedule_event',{p_event_id:e.id});if(er)setError(er.message);else await loadData();setBusy('')}
 const signIn=async e=>{e.preventDefault();setBusy('login');setError('');const {error:er}=await supabase.auth.signInWithPassword(login);if(er)setError(er.message);setBusy('')}
 const signOut=async()=>{const userId=session?.user?.id;await supabase.auth.signOut();if(userId)await clearMobileSnapshot(userId).catch(()=>{});setData(emptyData());setCachedAt(null)}
 const close=()=>location.pathname==='/mobile'?history.back():setVisible(false)
 const notifications=async()=>{if(typeof Notification==='undefined')return;await Notification.requestPermission()}
 if(!visible)return null
 return createPortal(<div className="mobile-app-shell">
  <header className="mobile-topbar"><div><span className="mobile-brand-mark"></span><div><strong>IDEALO SV</strong><small>{company?.name||'App móvil'}</small></div></div><div className="mobile-top-actions"><span className={online?'mobile-online':'mobile-offline'}>{online?'En línea':'Sin señal'}</span>{pending>0&&<button className="mobile-sync" onClick={syncOffline}>{busy==='sync'?'…':`↻ ${pending}`}</button>}<button onClick={close}>×</button></div></header>
  {!session?<main className="mobile-login"><section><p>ACCESO</p><h1>Iniciar sesión</h1><form onSubmit={signIn}><label>Correo<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required/></label><label>Contraseña<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/></label>{error&&<div className="mobile-error">{error}</div>}<button disabled={busy==='login'}>{busy==='login'?'Ingresando…':'Entrar'}</button></form></section></main>:<>
   <main className="mobile-content">{!online&&<div className="mobile-offline-banner">Sin conexión. Estás viendo los últimos datos guardados{cachedAt?` · ${new Date(cachedAt).toLocaleString('es-SV')}`:''}. Los cambios compatibles se sincronizarán al recuperar señal.</div>}{error&&<div className="mobile-error">{error}<button onClick={()=>setError('')}>×</button></div>}{loading?<div className="mobile-empty">Cargando…</div>:<>
    {tab==='Inicio'&&<><section className="mobile-home-clean"><div><p>{ownerMode?'RESUMEN':'MI JORNADA'}</p><h1>{ownerMode?'Hoy en IDEALO SV':employee?.full_name||'Trabajo asignado'}</h1><small>{roleLabel[role]||role}</small></div><div className="mobile-home-stats"><div><strong>{home.active.length}</strong><span>Trabajos activos</span></div><div><strong>{home.todayAgenda.length}</strong><span>Agenda hoy</span></div><div><strong>{home.late.length}</strong><span>Atrasados</span></div></div></section>{data.alerts.length>0&&<section className="mobile-clean-section"><h3>Atención</h3>{data.alerts.slice(0,4).map(x=><div className="mobile-clean-alert" key={x.id}>{x.text}</div>)}</section>}<section className="mobile-clean-section"><h3>Próximos trabajos</h3><OrderList rows={home.active.slice(0,5)} canWrite={canWrite} busy={busy} onAdvance={advanceOrder} onEvidence={setEvidenceOrder}/></section></>}
    {tab==='Trabajo'&&<section className="mobile-screen"><div className="mobile-segment"><button className={workView==='Producción'?'active':''} onClick={()=>setWorkView('Producción')}>Producción</button><button className={workView==='Agenda'?'active':''} onClick={()=>setWorkView('Agenda')}>Agenda</button></div>{workView==='Producción'?<><h2>Producción</h2><OrderList rows={home.active} canWrite={canWrite} busy={busy} onAdvance={advanceOrder} onEvidence={setEvidenceOrder}/></>:<><h2>Agenda</h2>{data.agenda.length?data.agenda.map(x=><div className="mobile-simple-row" key={x.id}><div><strong>{x.title}</strong><small>{new Date(x.scheduled_start).toLocaleString('es-SV')}{x.location?` · ${x.location}`:''}</small></div>{canWrite&&x.status!=='COMPLETED'?<button onClick={()=>completeEvent(x)} disabled={busy===x.id}>Completar</button>:<span>{x.status}</span>}</div>):<div className="mobile-empty">No hay actividades próximas.</div>}</>}</section>}
    {tab==='Clientes'&&<section className="mobile-screen"><div className="mobile-segment"><button className={clientView==='Clientes'?'active':''} onClick={()=>setClientView('Clientes')}>Clientes</button><button className={clientView==='Cotizaciones'?'active':''} onClick={()=>setClientView('Cotizaciones')}>Cotizaciones</button></div>{clientView==='Clientes'?<><h2>Clientes</h2>{data.clients.length?data.clients.map(x=><div className="mobile-simple-row" key={x.id}><div><strong>{x.name}</strong><small>{x.phone||x.email||'Sin contacto'}</small></div><span>{x.status||'ACTIVO'}</span></div>):<div className="mobile-empty">No hay clientes guardados.</div>}</>:<><h2>Cotizaciones</h2>{data.quotes.length?data.quotes.map(x=><div className="mobile-simple-row" key={x.id}><div><strong>COT-{x.number} · {x.clients?.name||'Cliente'}</strong><small>{money(x.total)} · {x.valid_until||'Sin vencimiento'}</small></div><span>{x.status}</span></div>):<div className="mobile-empty">No hay cotizaciones guardadas.</div>}</>}</section>}
    {tab==='Más'&&<section className="mobile-screen mobile-more-screen"><MobileOwnerHub company={company} supabase={supabase} session={session} role={role} online={online} pending={pending} busy={busy} onSync={syncOffline} onSignOut={signOut} onNotifications={notifications}/>{!ownerMode&&<div className="mobile-owner-profile"><button className="danger" onClick={signOut}>Cerrar sesión</button></div>}</section>}
   </>}</main>
   <nav className="mobile-bottom-nav simple-four">{tabs.map((t,i)=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}><span>{['⌂','▣','♙','•••'][i]}</span><small>{t}</small></button>)}</nav>
   {evidenceOrder&&<MobileEvidenceSheet supabase={supabase} company={company} order={evidenceOrder} onClose={()=>setEvidenceOrder(null)} onSaved={loadData}/>}</>}
 </div>,document.body)
}

function OrderList({rows,canWrite,busy,onAdvance,onEvidence}){return rows.length?rows.map(o=><div className="mobile-simple-row order" key={o.id}><div><strong>OT-{o.number} · {o.title}</strong><small>{o.clients?.name||'Sin cliente'} · {o.due_at?new Date(o.due_at).toLocaleDateString('es-SV'):'Sin fecha'}</small></div><div className="mobile-row-actions"><span>{o.status}</span>{canWrite&&nextStatus[o.status]&&<button onClick={()=>onAdvance(o)} disabled={busy===o.id}>Avanzar</button>}<button className="mobile-evidence-button" onClick={()=>onEvidence(o)}>Evidencia</button></div></div>):<div className="mobile-empty">No hay información para mostrar.</div>}
