import { useEffect,useRef,useState } from 'react'
import { supabase } from './lib/supabase.js'
import MobileEvidenceGallery from './MobileEvidenceGallery.jsx'
import MobileEvidenceSheet from './MobileEvidenceSheet.jsx'

export default function MobileFieldTools(){
 const [visible,setVisible]=useState(window.location.pathname==='/mobile'),[open,setOpen]=useState(false),[session,setSession]=useState(null),[company,setCompany]=useState(null),[employee,setEmployee]=useState(null),[attendance,setAttendance]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(''),[scanning,setScanning]=useState(false),[manual,setManual]=useState(''),[order,setOrder]=useState(null),[gallery,setGallery]=useState(false),[evidence,setEvidence]=useState(false)
 const videoRef=useRef(null),streamRef=useRef(null),scanTimer=useRef(null)
 useEffect(()=>{const h=e=>{if(e.detail==='App móviles')setVisible(true);else if(window.location.pathname!=='/mobile')setVisible(false)};window.addEventListener('idealo-module-change',h);return()=>window.removeEventListener('idealo-module-change',h)},[])
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session||null));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[])
 useEffect(()=>{if(!session){setCompany(null);setEmployee(null);return}(async()=>{const {data:list}=await supabase.rpc('get_my_companies');const id=list?.[0]?.id;if(!id)return;const [{data:c},{data:e}]=await Promise.all([supabase.from('companies').select('id,name').eq('id',id).single(),supabase.from('employees').select('id,full_name,position,user_id').eq('company_id',id).eq('user_id',session.user.id).maybeSingle()]);setCompany(c||null);setEmployee(e||null);if(e){const day=new Date().toLocaleDateString('en-CA',{timeZone:'America/El_Salvador'});const {data:a}=await supabase.from('attendance_records').select('id,work_date,check_in,check_out').eq('employee_id',e.id).eq('work_date',day).maybeSingle();setAttendance(a||null)}})()},[session?.user?.id])
 useEffect(()=>()=>stopScanner(),[])
 if(!visible||!session||!company)return null
 const locate=()=>new Promise(resolve=>{if(!navigator.geolocation)return resolve({});navigator.geolocation.getCurrentPosition(p=>resolve({p_lat:p.coords.latitude,p_lng:p.coords.longitude,p_accuracy_m:p.coords.accuracy}),()=>resolve({}),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})})
 const attendanceAction=async action=>{if(!employee){setMsg('Tu usuario todavía no está vinculado a un empleado.');return}setBusy(action);setMsg('');const geo=await locate();const {data,error}=await supabase.rpc('mobile_attendance_action',{p_action:action,...geo});if(error)setMsg(error.message);else{const r=data?.[0];setAttendance({work_date:r?.work_date,check_in:r?.check_in,check_out:r?.check_out});setMsg(action==='CHECK_IN'?'Entrada registrada.':'Salida registrada.')}setBusy('')}
 const parseCode=raw=>{const t=String(raw||'').trim();const id=t.match(/[0-9a-f]{8}-[0-9a-f-]{27,}/i)?.[0];const num=t.match(/(?:OT[-:# ]*)?(\d{1,12})/i)?.[1];return {id,num}}
 const findOrder=async raw=>{const {id,num}=parseCode(raw);if(!id&&!num){setMsg('El QR no contiene una OT válida.');return}setBusy('find');let q=supabase.from('work_orders').select('id,number,title,status,priority,due_at,total,clients(name,address)').eq('company_id',company.id);q=id?q.eq('id',id):q.eq('number',Number(num));const {data,error}=await q.maybeSingle();if(error||!data)setMsg(error?.message||'No se encontró la orden.');else{setOrder(data);setMsg('');setOpen(true)}setBusy('');stopScanner()}
 const stopScanner=()=>{if(scanTimer.current)cancelAnimationFrame(scanTimer.current);scanTimer.current=null;streamRef.current?.getTracks?.().forEach(t=>t.stop());streamRef.current=null;setScanning(false)}
 const startScanner=async()=>{setMsg('');if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){setMsg('Este navegador no admite lector QR automático. Podés escribir el número de OT abajo.');setScanning(false);return}try{const detector=new BarcodeDetector({formats:['qr_code']});const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});streamRef.current=stream;setScanning(true);setTimeout(()=>{if(videoRef.current){videoRef.current.srcObject=stream;videoRef.current.play().catch(()=>{})}},50);const scan=async()=>{if(!streamRef.current)return;try{if(videoRef.current?.readyState>=2){const codes=await detector.detect(videoRef.current);if(codes?.[0]?.rawValue){await findOrder(codes[0].rawValue);return}}}catch{}scanTimer.current=requestAnimationFrame(scan)};scanTimer.current=requestAnimationFrame(scan)}catch(e){setMsg(e.message||'No se pudo abrir la cámara.');stopScanner()}}
 const navigate=()=>{const dest=order?.clients?.address;if(dest)window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(dest)}`,'_blank','noopener,noreferrer');else setMsg('La OT no tiene dirección del cliente registrada.')}
 return <><button type="button" className="mobile-field-fab" onClick={()=>setOpen(v=>!v)}>⌁<span>Campo</span></button>{open&&<div className="mobile-tools-backdrop" onMouseDown={()=>{stopScanner();setOpen(false)}}><section className="mobile-tools-panel" onMouseDown={e=>e.stopPropagation()}><header><div><small>HERRAMIENTAS DE CAMPO</small><strong>IDEALO SV Móvil</strong></div><button type="button" onClick={()=>{stopScanner();setOpen(false)}}>×</button></header><div className="mobile-tools-body"><section className="mobile-tools-card"><h3>Asistencia</h3>{employee?<><p>{employee.full_name} · {employee.position}</p><div className="mobile-attendance-times"><span>Entrada <strong>{attendance?.check_in||'—'}</strong></span><span>Salida <strong>{attendance?.check_out||'—'}</strong></span></div><div className="mobile-tools-actions"><button type="button" disabled={busy||attendance?.check_in} onClick={()=>attendanceAction('CHECK_IN')}>{busy==='CHECK_IN'?'Registrando…':'Marcar entrada'}</button><button type="button" disabled={busy||!attendance?.check_in||attendance?.check_out} onClick={()=>attendanceAction('CHECK_OUT')}>{busy==='CHECK_OUT'?'Registrando…':'Marcar salida'}</button></div></>:<p>Vinculá este usuario a un empleado para habilitar asistencia.</p>}</section><section className="mobile-tools-card"><h3>Escáner QR de OT</h3>{scanning&&<video ref={videoRef} className="mobile-qr-video" muted playsInline/>}<div className="mobile-tools-actions"><button type="button" onClick={scanning?stopScanner:startScanner}>{scanning?'Cerrar cámara':'Escanear QR'}</button></div><div className="mobile-manual-ot"><input value={manual} onChange={e=>setManual(e.target.value)} placeholder="Número OT o código"/><button type="button" onClick={()=>findOrder(manual)} disabled={busy==='find'}>Buscar</button></div></section>{order&&<section className="mobile-tools-card mobile-scanned-order"><h3>OT-{order.number}</h3><strong>{order.title}</strong><p>{order.clients?.name||'Cliente'} · {order.status} · {order.priority}</p><div className="mobile-tools-actions"><button type="button" onClick={()=>setEvidence(true)}>Agregar evidencia</button><button type="button" onClick={()=>setGallery(true)}>Ver galería</button><button type="button" onClick={navigate}>Navegar</button></div></section>}{msg&&<div className="mobile-evidence-msg">{msg}</div>}</div></section></div>}{evidence&&order&&<MobileEvidenceSheet supabase={supabase} company={company} order={order} onClose={()=>setEvidence(false)} onSaved={()=>setGallery(true)}/>} {gallery&&order&&<MobileEvidenceGallery supabase={supabase} company={company} order={order} onClose={()=>setGallery(false)}/>}</>
}
