import { useEffect, useMemo, useState } from 'react'

const money=(v)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))
const today=()=>new Date().toISOString().slice(0,10)

export function SuppliersModule({company,supabase}){
  const [rows,setRows]=useState([]),[message,setMessage]=useState('')
  const [form,setForm]=useState({name:'',trade_name:'',nit:'',nrc:'',contact_name:'',phone:'',email:'',supplier_type:'MATERIALS',notes:''})
  const load=async()=>{const {data,error}=await supabase.from('suppliers').select('*').eq('company_id',company.id).order('name');if(error)setMessage(error.message);else setRows(data||[])}
  useEffect(()=>{load()},[company.id])
  const save=async(e)=>{e.preventDefault();const {error}=await supabase.from('suppliers').insert({...form,company_id:company.id,name:form.name.trim()});if(error)setMessage(error.message);else{setMessage('Proveedor guardado.');setForm({name:'',trade_name:'',nit:'',nrc:'',contact_name:'',phone:'',email:'',supplier_type:'MATERIALS',notes:''});await load()}}
  const toggle=async(r)=>{const {error}=await supabase.from('suppliers').update({active:!r.active,updated_at:new Date().toISOString()}).eq('id',r.id);setMessage(error?error.message:'Estado actualizado.');if(!error)await load()}
  return <section className="clients-module">
    <div className="clients-titlebar"><div><p className="form-kicker">ABASTECIMIENTO</p><h2>Proveedores</h2><p>Registra proveedores de materiales, servicios tercerizados, transporte y gastos operativos.</p></div><span className="status dte-ready">{rows.filter(r=>r.active).length} activos</span></div>
    {message&&<p className="feedback success">{message}</p>}
    <form className="panel client-form-full" onSubmit={save}><div className="form-grid three">
      <label className="field form-span-2"><span>Nombre / razón social *</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
      <label className="field"><span>Tipo</span><select value={form.supplier_type} onChange={e=>setForm({...form,supplier_type:e.target.value})}><option value="MATERIALS">Materiales e insumos</option><option value="OUTSOURCED_SERVICE">Servicio tercerizado</option><option value="TRANSPORT">Transporte</option><option value="UTILITIES">Servicios básicos</option><option value="OTHER">Otro</option></select></label>
      <label className="field"><span>NIT</span><input value={form.nit} onChange={e=>setForm({...form,nit:e.target.value})}/></label><label className="field"><span>NRC</span><input value={form.nrc} onChange={e=>setForm({...form,nrc:e.target.value})}/></label><label className="field"><span>Contacto</span><input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></label>
      <label className="field"><span>Teléfono</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="field"><span>Correo</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field"><span>Nombre comercial</span><input value={form.trade_name} onChange={e=>setForm({...form,trade_name:e.target.value})}/></label>
      <label className="field form-span-3"><span>Notas</span><textarea rows="2" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
    </div><div className="form-actions end"><button>Guardar proveedor</button></div></form>
    <section className="panel"><div className="panel-heading"><div><p className="form-kicker">DIRECTORIO</p><h3>Proveedores registrados</h3></div></div>{rows.length?<div className="client-list">{rows.map(r=><div className="client-row" key={r.id}><div><strong>{r.name}</strong><small>{r.supplier_type} · {r.contact_name||'Sin contacto'} · {r.phone||r.email||'Sin datos de contacto'}</small></div><div><strong>{r.active?'ACTIVO':'INACTIVO'}</strong><button onClick={()=>toggle(r)}>{r.active?'Desactivar':'Activar'}</button></div></div>)}</div>:<div className="empty-state"><strong>Sin proveedores</strong><p>Agrega quien te vende materiales o presta servicios para producir los trabajos finales.</p></div>}</section>
  </section>
}

export function PurchasesExpensesModule({company,supabase}){
  const [suppliers,setSuppliers]=useState([]),[purchases,setPurchases]=useState([]),[expenses,setExpenses]=useState([]),[message,setMessage]=useState('')
  const [purchase,setPurchase]=useState({supplier_id:'',purchase_date:today(),document_type:'INVOICE',document_number:'',concept:'',subtotal:'',tax:'',total:'',payment_status:'PENDING',due_date:'',notes:''})
  const [expense,setExpense]=useState({supplier_id:'',expense_date:today(),category:'OPERATING',concept:'',amount:'',payment_method:'CASH',reference:'',notes:''})
  const load=async()=>{const [s,p,e]=await Promise.all([supabase.from('suppliers').select('id,name,active').eq('company_id',company.id).eq('active',true).order('name'),supabase.from('purchases').select('*,suppliers(name)').eq('company_id',company.id).order('purchase_date',{ascending:false}).limit(100),supabase.from('expenses').select('*,suppliers(name)').eq('company_id',company.id).order('expense_date',{ascending:false}).limit(100)]);if(s.error||p.error||e.error)setMessage(s.error?.message||p.error?.message||e.error?.message);else{setSuppliers(s.data||[]);setPurchases(p.data||[]);setExpenses(e.data||[])}}
  useEffect(()=>{load()},[company.id])
  const savePurchase=async(e)=>{e.preventDefault();const subtotal=Number(purchase.subtotal||0),tax=Number(purchase.tax||0),total=Number(purchase.total||subtotal+tax);const {error}=await supabase.from('purchases').insert({...purchase,company_id:company.id,supplier_id:purchase.supplier_id||null,subtotal,tax,total,due_date:purchase.due_date||null});if(error)setMessage(error.message);else{setMessage('Compra registrada como consumo interno de producción.');setPurchase({supplier_id:'',purchase_date:today(),document_type:'INVOICE',document_number:'',concept:'',subtotal:'',tax:'',total:'',payment_status:'PENDING',due_date:'',notes:''});await load()}}
  const saveExpense=async(e)=>{e.preventDefault();const {error}=await supabase.from('expenses').insert({...expense,company_id:company.id,supplier_id:expense.supplier_id||null,amount:Number(expense.amount||0)});if(error)setMessage(error.message);else{setMessage('Gasto registrado.');setExpense({supplier_id:'',expense_date:today(),category:'OPERATING',concept:'',amount:'',payment_method:'CASH',reference:'',notes:''});await load()}}
  const monthKey=today().slice(0,7);const monthPurchases=useMemo(()=>purchases.filter(r=>r.purchase_date?.startsWith(monthKey)).reduce((s,r)=>s+Number(r.total||0),0),[purchases]);const monthExpenses=useMemo(()=>expenses.filter(r=>r.expense_date?.startsWith(monthKey)).reduce((s,r)=>s+Number(r.amount||0),0),[expenses])
  const supplierOptions=<><option value="">Sin proveedor / ocasional</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</>
  return <section className="clients-module"><div className="clients-titlebar"><div><p className="form-kicker">COSTOS</p><h2>Compras y gastos</h2><p>Controla lo que la empresa compra para producir y los gastos de operación. Los insumos no se publican como productos de venta.</p></div></div>
    <div className="metrics-grid"><article className="metric-card"><span>Compras del mes</span><strong>{money(monthPurchases)}</strong></article><article className="metric-card"><span>Gastos del mes</span><strong>{money(monthExpenses)}</strong></article><article className="metric-card"><span>Compras pendientes</span><strong>{purchases.filter(r=>['PENDING','PARTIAL'].includes(r.payment_status)).length}</strong></article></div>
    {message&&<p className="feedback success">{message}</p>}
    <div className="module-grid two-column">
      <form className="panel" onSubmit={savePurchase}><div className="panel-heading"><div><p className="form-kicker">COMPRA</p><h3>Materiales / tercerización</h3></div></div><div className="form-grid"><label className="field"><span>Proveedor</span><select value={purchase.supplier_id} onChange={e=>setPurchase({...purchase,supplier_id:e.target.value})}>{supplierOptions}</select></label><label className="field"><span>Fecha</span><input type="date" value={purchase.purchase_date} onChange={e=>setPurchase({...purchase,purchase_date:e.target.value})}/></label><label className="field"><span>Documento</span><select value={purchase.document_type} onChange={e=>setPurchase({...purchase,document_type:e.target.value})}><option value="INVOICE">Factura</option><option value="CCF">CCF</option><option value="TICKET">Ticket</option><option value="RECEIPT">Recibo</option><option value="OTHER">Otro</option></select></label><label className="field"><span>Número</span><input value={purchase.document_number} onChange={e=>setPurchase({...purchase,document_number:e.target.value})}/></label><label className="field form-span-2"><span>Concepto *</span><input required placeholder="Ej. vinil para rótulos / camisas para sublimación / corte CNC tercerizado" value={purchase.concept} onChange={e=>setPurchase({...purchase,concept:e.target.value})}/></label><label className="field"><span>Subtotal</span><input type="number" min="0" step="0.01" value={purchase.subtotal} onChange={e=>setPurchase({...purchase,subtotal:e.target.value})}/></label><label className="field"><span>IVA / impuesto</span><input type="number" min="0" step="0.01" value={purchase.tax} onChange={e=>setPurchase({...purchase,tax:e.target.value})}/></label><label className="field"><span>Total *</span><input type="number" min="0" step="0.01" required value={purchase.total} onChange={e=>setPurchase({...purchase,total:e.target.value})}/></label><label className="field"><span>Estado pago</span><select value={purchase.payment_status} onChange={e=>setPurchase({...purchase,payment_status:e.target.value})}><option value="PENDING">Pendiente</option><option value="PARTIAL">Parcial</option><option value="PAID">Pagada</option></select></label><label className="field"><span>Vence</span><input type="date" value={purchase.due_date} onChange={e=>setPurchase({...purchase,due_date:e.target.value})}/></label></div><div className="form-actions end"><button>Registrar compra</button></div></form>
      <form className="panel" onSubmit={saveExpense}><div className="panel-heading"><div><p className="form-kicker">GASTO</p><h3>Operación del negocio</h3></div></div><div className="form-grid"><label className="field"><span>Proveedor</span><select value={expense.supplier_id} onChange={e=>setExpense({...expense,supplier_id:e.target.value})}>{supplierOptions}</select></label><label className="field"><span>Fecha</span><input type="date" value={expense.expense_date} onChange={e=>setExpense({...expense,expense_date:e.target.value})}/></label><label className="field"><span>Categoría</span><select value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}><option value="RENT">Alquiler</option><option value="UTILITIES">Servicios básicos</option><option value="PAYROLL">Planilla</option><option value="TRANSPORT">Transporte</option><option value="MAINTENANCE">Mantenimiento</option><option value="MARKETING">Publicidad</option><option value="TAXES">Impuestos</option><option value="OPERATING">Operativo</option><option value="OTHER">Otro</option></select></label><label className="field"><span>Forma pago</span><select value={expense.payment_method} onChange={e=>setExpense({...expense,payment_method:e.target.value})}><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia</option><option value="CARD">Tarjeta</option><option value="CHECK">Cheque</option><option value="OTHER">Otro</option></select></label><label className="field form-span-2"><span>Concepto *</span><input required value={expense.concept} onChange={e=>setExpense({...expense,concept:e.target.value})}/></label><label className="field"><span>Monto *</span><input type="number" min="0.01" step="0.01" required value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label><label className="field"><span>Referencia</span><input value={expense.reference} onChange={e=>setExpense({...expense,reference:e.target.value})}/></label></div><div className="form-actions end"><button>Registrar gasto</button></div></form>
    </div>
    <section className="panel"><div className="panel-heading"><div><p className="form-kicker">HISTORIAL</p><h3>Compras recientes</h3></div></div>{purchases.length?<div className="client-list">{purchases.slice(0,20).map(r=><div className="client-row" key={r.id}><div><strong>COM-{String(r.number).padStart(5,'0')} · {r.suppliers?.name||'Proveedor ocasional'}</strong><small>{r.purchase_date} · {r.concept} · {r.document_type} {r.document_number||''}</small></div><div><strong>{money(r.total)}</strong><small>{r.payment_status}</small></div></div>)}</div>:<div className="empty-state"><strong>Sin compras</strong></div>}</section>
  </section>
}

export function CashModule({company,supabase}){
  const [accounts,setAccounts]=useState([]),[moves,setMoves]=useState([]),[message,setMessage]=useState('')
  const [account,setAccount]=useState({name:'Caja principal',account_type:'CASH',opening_balance:'0'})
  const [move,setMove]=useState({cash_account_id:'',movement_type:'INCOME',concept:'',amount:'',reference:'',notes:''})
  const load=async()=>{const [a,m]=await Promise.all([supabase.from('cash_accounts').select('*').eq('company_id',company.id).eq('active',true).order('name'),supabase.from('cash_movements').select('*,cash_accounts(name)').eq('company_id',company.id).order('movement_date',{ascending:false}).limit(200)]);if(a.error||m.error)setMessage(a.error?.message||m.error?.message);else{setAccounts(a.data||[]);setMoves(m.data||[]);setMove(v=>({...v,cash_account_id:v.cash_account_id||a.data?.[0]?.id||''}))}}
  useEffect(()=>{load()},[company.id])
  const saveAccount=async(e)=>{e.preventDefault();const {error}=await supabase.from('cash_accounts').insert({...account,company_id:company.id,opening_balance:Number(account.opening_balance||0)});if(error)setMessage(error.message);else{setMessage('Cuenta de caja creada.');setAccount({name:'',account_type:'CASH',opening_balance:'0'});await load()}}
  const saveMove=async(e)=>{e.preventDefault();const {error}=await supabase.from('cash_movements').insert({...move,company_id:company.id,amount:Number(move.amount||0),source_type:'MANUAL'});if(error)setMessage(error.message);else{setMessage('Movimiento registrado.');setMove(v=>({...v,concept:'',amount:'',reference:'',notes:''}));await load()}}
  const balance=(id)=>{const a=accounts.find(x=>x.id===id);return Number(a?.opening_balance||0)+moves.filter(m=>m.cash_account_id===id).reduce((s,m)=>s+(['INCOME','TRANSFER_IN'].includes(m.movement_type)?Number(m.amount):-Number(m.amount)),0)}
  const total=accounts.reduce((s,a)=>s+balance(a.id),0)
  return <section className="clients-module"><div className="clients-titlebar"><div><p className="form-kicker">TESORERÍA</p><h2>Caja</h2><p>Controla efectivo, caja chica y cuentas bancarias con entradas y salidas trazables.</p></div><span className="status dte-ready">Saldo {money(total)}</span></div>{message&&<p className="feedback success">{message}</p>}
    <div className="metrics-grid">{accounts.slice(0,3).map(a=><article className="metric-card" key={a.id}><span>{a.name}</span><strong>{money(balance(a.id))}</strong><small>{a.account_type}</small></article>)}{!accounts.length&&<article className="metric-card"><span>Sin cuentas</span><strong>$0.00</strong></article>}</div>
    <div className="module-grid two-column"><form className="panel" onSubmit={saveAccount}><div className="panel-heading"><div><p className="form-kicker">CONFIGURAR</p><h3>Nueva caja / banco</h3></div></div><div className="form-grid"><label className="field"><span>Nombre *</span><input required value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/></label><label className="field"><span>Tipo</span><select value={account.account_type} onChange={e=>setAccount({...account,account_type:e.target.value})}><option value="CASH">Caja</option><option value="PETTY_CASH">Caja chica</option><option value="BANK">Banco</option></select></label><label className="field"><span>Saldo inicial</span><input type="number" step="0.01" value={account.opening_balance} onChange={e=>setAccount({...account,opening_balance:e.target.value})}/></label></div><div className="form-actions end"><button>Crear cuenta</button></div></form>
    <form className="panel" onSubmit={saveMove}><div className="panel-heading"><div><p className="form-kicker">MOVIMIENTO</p><h3>Entrada / salida</h3></div></div><div className="form-grid"><label className="field"><span>Cuenta *</span><select required value={move.cash_account_id} onChange={e=>setMove({...move,cash_account_id:e.target.value})}><option value="">Seleccionar</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="field"><span>Tipo</span><select value={move.movement_type} onChange={e=>setMove({...move,movement_type:e.target.value})}><option value="INCOME">Entrada</option><option value="EXPENSE">Salida</option><option value="ADJUSTMENT">Ajuste</option></select></label><label className="field form-span-2"><span>Concepto *</span><input required value={move.concept} onChange={e=>setMove({...move,concept:e.target.value})}/></label><label className="field"><span>Monto *</span><input type="number" min="0.01" step="0.01" required value={move.amount} onChange={e=>setMove({...move,amount:e.target.value})}/></label><label className="field"><span>Referencia</span><input value={move.reference} onChange={e=>setMove({...move,reference:e.target.value})}/></label></div><div className="form-actions end"><button disabled={!accounts.length}>Registrar movimiento</button></div></form></div>
    <section className="panel"><div className="panel-heading"><div><p className="form-kicker">LIBRO DE CAJA</p><h3>Movimientos recientes</h3></div></div>{moves.length?<div className="client-list">{moves.slice(0,50).map(r=><div className="client-row" key={r.id}><div><strong>{r.cash_accounts?.name} · {r.concept}</strong><small>{new Date(r.movement_date).toLocaleString('es-SV')} · {r.reference||'Sin referencia'}</small></div><div><strong>{['INCOME','TRANSFER_IN'].includes(r.movement_type)?'+':'-'} {money(r.amount)}</strong><small>{r.movement_type}</small></div></div>)}</div>:<div className="empty-state"><strong>Sin movimientos</strong><p>Crea una caja y registra la primera entrada o salida.</p></div>}</section>
  </section>
}
