import { useEffect,useMemo,useState } from 'react'
import { PRODUCTION_STAGES,NEXT_STAGE,productionMetrics,visibleProductionStatus } from './productionEngine.js'

const label=value=>PRODUCTION_STAGES.find(([code])=>code===visibleProductionStatus(value))?.[1]||value
const isOpen=row=>!['DELIVERED','CANCELLED'].includes(row.status)
const actionLabel=status=>({PENDING:'Iniciar diseño',DESIGN:'Pasar a producción',PRODUCTION:'Marcar listo',READY:'Entregar'}[visibleProductionStatus(status)]||'')

export default function Production360Module({company,supabase,initialClientId=''}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[employees,setEmployees]=useState([])
 const [search,setSearch]=useState(''),[stage,setStage]=useState('OPEN'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[showMore,setShowMore]=useState(false)
 const load=async()=>{const [orders,people]=await Promise.all([supabase.from('work_orders').select('*,clients(name,phone),work_order_items(*)').eq('company_id',company.id).order('created_at',{ascending:false}),supabase.from('employees').select('id,full_name,position').eq('company_id',company.id).eq('active',true).order('full_name')]);if(orders.error)setMessage(orders.error.message);else{setRows(orders.data||[]);if(selected)setSelected((orders.data||[]).find(row=>row.id===selected.id)||null)};setEmployees(people.data||[])}
 useEffect(()=>{load()},[company.id])
 const visible=useMemo(()=>rows.filter(row=>{const simple=visibleProductionStatus(row.status);const clientMatches=!initialClientId||row.client_id===initialClientId;const stageMatches=stage==='ALL'||(stage==='OPEN'?isOpen(row):simple===stage);const text=`${row.number||''} ${row.title||''} ${row.clients?.name||''}`.toLowerCase();return clientMatches&&stageMatches&&text.includes(search.trim().toLowerCase())}),[rows,stage,search,initialClientId])
 const metrics=useMemo(()=>productionMetrics(rows),[rows])
 const save=async patch=>{if(!selected)return;setBusy(true);setMessage('');const payload={...patch,updated_at:new Date().toISOString()};if(patch.status==='PRODUCTION'&&!selected.production_started_at)payload.production_started_at=new Date().toISOString();if(patch.status==='READY'&&!selected.ready_at)payload.ready_at=new Date().toISOString();if(patch.status==='DELIVERED'&&!selected.delivered_at)payload.delivered_at=new Date().toISOString();const old=selected.status;const {error}=await supabase.from('work_orders').update(payload).eq('id',selected.id).eq('company_id',company.id);if(!error&&patch.status&&patch.status!==old)await supabase.from('production_status_history').insert({company_id:company.id,work_order_id:selected.id,from_status:old,to_status:patch.status});if(error)setMessage(error.message);else{setMessage('Orden actualizada.');setSelected({...selected,...payload});await load()}setBusy(false)}
 const advance=async()=>{const next=NEXT_STAGE[visibleProductionStatus(selected.status)];if(!next)return;await save({status:next,progress_percent:next==='DELIVERED'?100:next==='READY'?90:next==='PRODUCTION'?50:20})}
 return <section className="production-suite production-360 production-simple">
  <div className="production-simple-head"><div><p className="form-kicker">PRODUCCIÓN</p><h2>Trabajos por producir</h2><p>Cada cotización aprobada aparece aquí como orden de trabajo. Abrí una orden y avanzala hasta entregarla.</p></div><div className="production-simple-stats"><span><b>{metrics.open}</b> activas</span><span className={metrics.late?'warning':''}><b>{metrics.late}</b> atrasadas</span><span><b>{metrics.ready}</b> listas</span></div></div>
  {message&&<p className="feedback success">{message}</p>}
  <div className="production-toolbar production-simple-toolbar"><input className="production-search" placeholder="Buscar OT, cliente o trabajo" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Estado" value={stage} onChange={e=>setStage(e.target.value)}><option value="OPEN">Activas</option><option value="ALL">Todas</option>{PRODUCTION_STAGES.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></div>
  {visible.length===0?<div className="production-simple-empty"><strong>{rows.length?'No hay trabajos con este filtro':'Todavía no hay trabajos para producir'}</strong><p>{rows.length?'Cambiá el filtro o la búsqueda.':'Cuando una cotización aprobada genere su orden de trabajo, aparecerá aquí automáticamente.'}</p></div>:<div className="production-simple-list production-job-list"><div className="production-job-head"><span>Orden / trabajo</span><span>Cliente</span><span>Cantidad</span><span>Responsable</span><span>Entrega</span><span>Estado</span></div>{visible.map(row=>{const qty=(row.work_order_items||[]).reduce((sum,item)=>sum+Number(item.quantity||0),0);const responsible=employees.find(person=>person.id===row.assigned_employee_id);return <button type="button" className="production-simple-row production-job-row" key={row.id} onClick={()=>{setSelected(row);setShowMore(false)}}><div className="production-simple-order"><small>OT-{String(row.number).padStart(5,'0')}</small><strong>{row.title}</strong></div><span>{row.clients?.name||'Sin cliente'}</span><span>{qty||'—'}</span><span>{responsible?.full_name||'Sin asignar'}</span><span>{row.due_at?new Date(row.due_at).toLocaleDateString('es-SV'):'Sin fecha'}</span><span className="production-stage-badge">{label(row.status)}</span></button>})}</div>}
  {selected&&<div className="production-detail-backdrop" onMouseDown={()=>setSelected(null)}><aside className="production-detail production-detail-wide production-simple-detail" onMouseDown={e=>e.stopPropagation()}><header className="production-detail-head"><div><small>OT-{String(selected.number).padStart(5,'0')} · {label(selected.status)}</small><h3>{selected.title}</h3><p>{selected.clients?.name||'Cliente'} {selected.clients?.phone?`· ${selected.clients.phone}`:''}</p></div><button className="detail-close" onClick={()=>setSelected(null)}>×</button></header><div className="production-detail-body">
   <section className="production-main-info"><div><small>Trabajo</small><strong>{selected.title}</strong></div><div><small>Cantidad</small><strong>{(selected.work_order_items||[]).reduce((sum,item)=>sum+Number(item.quantity||0),0)||'—'}</strong></div><div><small>Entrega</small><strong>{selected.due_at?new Date(selected.due_at).toLocaleDateString('es-SV'):'Sin fecha'}</strong></div><div><small>Estado</small><strong>{label(selected.status)}</strong></div></section>
   <div className="detail-grid"><label><span>Responsable</span><select value={selected.assigned_employee_id||''} onChange={e=>setSelected({...selected,assigned_employee_id:e.target.value||null})}><option value="">Sin asignar</option>{employees.map(person=><option value={person.id} key={person.id}>{person.full_name}</option>)}</select></label><label><span>Fecha de entrega</span><input type="datetime-local" value={selected.due_at?new Date(selected.due_at).toISOString().slice(0,16):''} onChange={e=>setSelected({...selected,due_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label></div>
   <section className="detail-section"><h4>Qué hay que producir</h4>{selected.work_order_items?.length?selected.work_order_items.map(item=><div className="detail-line" key={item.id}><span>{item.quantity} {item.unit}</span><strong>{item.description}</strong></div>):<p className="muted-note">La orden no tiene partidas registradas.</p>}</section>
   <button type="button" className="secondary-button production-more-toggle" onClick={()=>setShowMore(value=>!value)}>{showMore?'Ocultar detalles':'Más detalles'}</button>
   {showMore&&<section className="production-advanced-details"><label className="detail-field"><span>Especificaciones</span><textarea rows="4" value={selected.specifications||''} onChange={e=>setSelected({...selected,specifications:e.target.value})} placeholder="Medidas, colores, acabado y observaciones de producción"/></label><label className="detail-field"><span>Notas internas</span><textarea rows="3" value={selected.internal_notes||''} onChange={e=>setSelected({...selected,internal_notes:e.target.value})}/></label><p className="muted-note">Los controles técnicos, materiales, calidad, incidencias y costos siguen registrados, pero ya no saturan la operación principal.</p></section>}
  </div><footer className="production-detail-actions"><button className="secondary" disabled={busy} onClick={()=>save({assigned_employee_id:selected.assigned_employee_id,due_at:selected.due_at,specifications:selected.specifications,internal_notes:selected.internal_notes})}>Guardar</button>{NEXT_STAGE[visibleProductionStatus(selected.status)]&&<button disabled={busy} onClick={advance}>{actionLabel(selected.status)}</button>}</footer></aside></div>}
 </section>
}
