import { useEffect, useMemo, useState } from 'react'

const fmt=(v)=>new Date(v).toLocaleString('es-SV',{dateStyle:'medium',timeStyle:'short'})
const dateKey=(v)=>String(v||'').slice(0,10)
const monday=()=>{const d=new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d.toISOString().slice(0,10)}

export default function ProductionCalendar({company,supabase}){
 const [events,setEvents]=useState([]),[deliveries,setDeliveries]=useState([]),[orders,setOrders]=useState([]),[employees,setEmployees]=useState([]),[assignments,setAssignments]=useState([]),[week,setWeek]=useState(monday()),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 const [form,setForm]=useState({work_order_id:'',event_type:'PRODUCTION',title:'',scheduled_start:'',scheduled_end:'',estimated_hours:'0',priority:'NORMAL',location:'',notes:'',employee_ids:[]})
 const load=async()=>{setLoading(true);const r=await Promise.all([
  supabase.from('production_schedule_events').select('*').eq('company_id',company.id).order('scheduled_start'),
  supabase.from('production_schedule_assignments').select('*').eq('company_id',company.id),
  supabase.from('work_orders').select('id,number,title,status,due_at,priority').eq('company_id',company.id).order('number',{ascending:false}),
  supabase.from('deliveries').select('id,number,work_order_id,delivery_method,status,scheduled_at,delivery_address').eq('company_id',company.id).not('scheduled_at','is',null).order('scheduled_at'),
  supabase.from('employees').select('id,full_name,position,active').eq('company_id',company.id).eq('active',true).order('full_name')]);
  const err=r.find(x=>x.error)?.error;if(err)setMessage(err.message);else{setEvents(r[0].data||[]);setAssignments(r[1].data||[]);setOrders(r[2].data||[]);setDeliveries(r[3].data||[]);setEmployees(r[4].data||[]);setMessage('')}setLoading(false)}
 useEffect(()=>{load()},[company.id])
 const save=async(e)=>{e.preventDefault();setMessage('');const payload={company_id:company.id,work_order_id:form.work_order_id||null,event_type:form.event_type,title:form.title.trim(),scheduled_start:new Date(form.scheduled_start).toISOString(),scheduled_end:new Date(form.scheduled_end).toISOString(),estimated_hours:Number(form.estimated_hours||0),priority:form.priority,location:form.location||null,notes:form.notes||null};const {data,error}=await supabase.from('production_schedule_events').insert(payload).select().single();if(error){setMessage(error.message);return}if(form.employee_ids.length){const each=Number(form.estimated_hours||0)/(form.employee_ids.length||1);const {error:aerr}=await supabase.from('production_schedule_assignments').insert(form.employee_ids.map(id=>({company_id:company.id,event_id:data.id,employee_id:id,allocated_hours:each})));if(aerr){setMessage(aerr.message);return}}setForm({work_order_id:'',event_type:'PRODUCTION',title:'',scheduled_start:'',scheduled_end:'',estimated_hours:'0',priority:'NORMAL',location:'',notes:'',employee_ids:[]});await load()}
 const setStatus=async(id,status)=>{await supabase.from('production_schedule_events').update({status,updated_at:new Date().toISOString()}).eq('id',id);await load()}
 const weekEnd=useMemo(()=>{const d=new Date(`${week}T00:00:00`);d.setDate(d.getDate()+6);return d.toISOString().slice(0,10)},[week])
 const visible=useMemo(()=>events.filter(e=>dateKey(e.scheduled_start)>=week&&dateKey(e.scheduled_start)<=weekEnd),[events,week,weekEnd])
 const deliveryWeek=useMemo(()=>deliveries.filter(d=>dateKey(d.scheduled_at)>=week&&dateKey(d.scheduled_at)<=weekEnd),[deliveries,week,weekEnd])
 const workload=useMemo(()=>employees.map(emp=>{const ids=assignments.filter(a=>a.employee_id===emp.id&&visible.some(e=>e.id===a.event_id));const hours=ids.reduce((s,a)=>s+Number(a.allocated_hours||0),0);return {...emp,hours,load:Math.round(hours/40*100)}}).sort((a,b)=>b.hours-a.hours),[employees,assignments,visible])
 const overdue=orders.filter(o=>o.due_at&&dateKey(o.due_at)<new Date().toISOString().slice(0,10)&&!['DELIVERED','CANCELLED','COMPLETED'].includes(o.status))
 if(loading)return <section className="loading-card"><span className="spinner"/><p>Cargando planificación…</p></section>
 return <section className="clients-module production-calendar">
  <div className="clients-titlebar"><div><p className="form-kicker">PLANIFICACIÓN OPERATIVA</p><h2>Calendario de producción</h2><p>Órdenes, personal, instalaciones, entregas y carga semanal.</p></div><span className={overdue.length?'status dte-pending':'status dte-ready'}>{overdue.length?`${overdue.length} OT atrasadas`:'Sin atrasos'}</span></div>
  {message&&<p className="feedback error">{message}</p>}
  <section className="panel"><form onSubmit={save}><div className="form-grid three"><label className="field"><span>Orden</span><select value={form.work_order_id} onChange={e=>{const o=orders.find(x=>x.id===e.target.value);setForm(f=>({...f,work_order_id:e.target.value,title:f.title||o?.title||''}))}}><option value="">Sin OT</option>{orders.map(o=><option key={o.id} value={o.id}>OT-{String(o.number).padStart(5,'0')} · {o.title}</option>)}</select></label><label className="field"><span>Tipo</span><select value={form.event_type} onChange={e=>setForm(f=>({...f,event_type:e.target.value}))}>{['DESIGN','PRODUCTION','INSTALLATION','DELIVERY','SITE_VISIT','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Prioridad</span><select value={form.priority} onChange={e=>setForm(f=>({...f,priority:e.target.value}))}>{['LOW','NORMAL','HIGH','URGENT'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field form-span-3"><span>Actividad *</span><input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} required/></label><label className="field"><span>Inicio *</span><input type="datetime-local" value={form.scheduled_start} onChange={e=>setForm(f=>({...f,scheduled_start:e.target.value}))} required/></label><label className="field"><span>Fin *</span><input type="datetime-local" value={form.scheduled_end} onChange={e=>setForm(f=>({...f,scheduled_end:e.target.value}))} required/></label><label className="field"><span>Horas previstas</span><input type="number" min="0" step="0.25" value={form.estimated_hours} onChange={e=>setForm(f=>({...f,estimated_hours:e.target.value}))}/></label><label className="field form-span-2"><span>Personal asignado</span><select multiple value={form.employee_ids} onChange={e=>setForm(f=>({...f,employee_ids:[...e.target.selectedOptions].map(o=>o.value)}))}>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name} · {e.position}</option>)}</select></label><label className="field"><span>Ubicación</span><input value={form.location} onChange={e=>setForm(f=>({...f,location:e.target.value}))}/></label></div><div className="form-actions end"><button type="submit">Programar actividad</button></div></form></section>
  <section className="panel"><div className="panel-heading"><div><p className="form-kicker">SEMANA</p><h3>{week} → {weekEnd}</h3></div><input type="date" value={week} onChange={e=>setWeek(e.target.value)}/></div><div className="schedule-list">{visible.map(ev=>{const names=assignments.filter(a=>a.event_id===ev.id).map(a=>employees.find(e=>e.id===a.employee_id)?.full_name).filter(Boolean);return <article key={ev.id} className="schedule-card"><div><strong>{ev.title}</strong><small>{ev.event_type} · {fmt(ev.scheduled_start)} → {fmt(ev.scheduled_end)}</small><small>{names.length?names.join(', '):'Sin personal asignado'}{ev.location?` · ${ev.location}`:''}</small></div><div><span className={`status ${ev.priority==='URGENT'?'dte-pending':''}`}>{ev.status}</span>{ev.status!=='COMPLETED'&&<button type="button" className="secondary-button" onClick={()=>setStatus(ev.id,'COMPLETED')}>Completar</button>}</div></article>})}{!visible.length&&<div className="empty-state"><strong>Semana sin actividades</strong></div>}</div></section>
  <div className="module-grid two-column"><section className="panel"><div className="panel-heading"><div><p className="form-kicker">CARGA DEL EQUIPO</p><h3>Horas asignadas</h3></div></div>{workload.map(e=><div className="workload-row" key={e.id}><div><strong>{e.full_name}</strong><small>{e.position}</small></div><div><strong>{e.hours.toFixed(1)} h</strong><small>{e.load}% de 40 h</small></div></div>)}</section><section className="panel"><div className="panel-heading"><div><p className="form-kicker">ENTREGAS / INSTALACIONES</p><h3>Agenda existente</h3></div></div>{deliveryWeek.map(d=><div className="workload-row" key={d.id}><div><strong>Entrega #{d.number}</strong><small>{d.delivery_method} · {d.delivery_address||'Sin dirección'}</small></div><div><strong>{fmt(d.scheduled_at)}</strong><small>{d.status}</small></div></div>)}{!deliveryWeek.length&&<div className="empty-state"><strong>Sin entregas programadas</strong></div>}</section></div>
 </section>
}
