import { useEffect,useMemo,useState } from 'react'
import { PRODUCTION_STAGES,NEXT_STAGE,productionMetrics,taskProgress,materialStatus,canAdvanceProduction } from './productionEngine.js'
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))
const label=v=>PRODUCTION_STAGES.find(x=>x[0]===v)?.[1]||v
const blankTask={title:'',process_type:'PRODUCTION',estimated_minutes:0,instructions:''}
const blankMaterial={material_name:'',unit:'unidad',required_qty:1,unit_cost:0}
const isOpen=r=>!['DELIVERED','CANCELLED'].includes(r.status)
export default function Production360Module({company,supabase,initialClientId=''}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[tasks,setTasks]=useState([]),[materials,setMaterials]=useState([]),[checks,setChecks]=useState([]),[incidents,setIncidents]=useState([]),[costs,setCosts]=useState([]),[employees,setEmployees]=useState([])
 const [search,setSearch]=useState(''),[stage,setStage]=useState('OPEN'),[priority,setPriority]=useState('ALL'),[view,setView]=useState('TABLE'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[task,setTask]=useState(blankTask),[material,setMaterial]=useState(blankMaterial)
 const load=async()=>{const [w,e]=await Promise.all([supabase.from('work_orders').select('*,clients(name,phone),work_order_items(*)').eq('company_id',company.id).order('created_at',{ascending:false}),supabase.from('employees').select('id,full_name,position,hourly_cost').eq('company_id',company.id).eq('active',true).order('full_name')]);if(w.error)setMessage(w.error.message);else{setRows(w.data||[]);if(selected)setSelected((w.data||[]).find(x=>x.id===selected.id)||null)};setEmployees(e.data||[])}
 const loadDetail=async o=>{setSelected(o);const [t,m,q,i,c]=await Promise.all([supabase.from('production_tasks').select('*').eq('work_order_id',o.id).order('sequence_no'),supabase.from('production_material_requirements').select('*').eq('work_order_id',o.id),supabase.from('quality_checks').select('*').eq('work_order_id',o.id).order('created_at',{ascending:false}),supabase.from('quality_incidents').select('*').eq('work_order_id',o.id).order('created_at',{ascending:false}),supabase.from('work_order_costs').select('*').eq('work_order_id',o.id).order('created_at',{ascending:false})]);setTasks(t.data||[]);setMaterials(m.data||[]);setChecks(q.data||[]);setIncidents(i.data||[]);setCosts(c.data||[])}
 useEffect(()=>{load()},[company.id])
 const visible=useMemo(()=>rows.filter(r=>{const clientMatches=!initialClientId||r.client_id===initialClientId;const stageMatches=stage==='ALL'||(stage==='OPEN'?isOpen(r):r.status===stage);const priorityMatches=priority==='ALL'||r.priority===priority;const text=`${r.number||''} ${r.title||''} ${r.clients?.name||''}`.toLowerCase();return clientMatches&&stageMatches&&priorityMatches&&text.includes(search.trim().toLowerCase())}),[rows,stage,priority,search,initialClientId])
 const metrics=useMemo(()=>productionMetrics(rows),[rows]); const detailCost=costs.reduce((s,c)=>s+Number(c.amount||0),0); const profit=Number(selected?.total||0)-detailCost
 const kanbanStages=useMemo(()=>PRODUCTION_STAGES.filter(([code])=>code!=='CANCELLED'&&visible.some(r=>r.status===code)),[visible])
 const patch=async p=>{if(!selected)return;setBusy(true);const payload={...p,updated_at:new Date().toISOString()};if(p.status==='PRODUCTION'&&!selected.production_started_at)payload.production_started_at=new Date().toISOString();if(p.status==='READY'&&!selected.ready_at)payload.ready_at=new Date().toISOString();if(p.status==='DELIVERED'&&!selected.delivered_at)payload.delivered_at=new Date().toISOString();const old=selected.status;const {error}=await supabase.from('work_orders').update(payload).eq('id',selected.id);if(!error&&p.status&&p.status!==old)await supabase.from('production_status_history').insert({company_id:company.id,work_order_id:selected.id,from_status:old,to_status:p.status});setMessage(error?.message||'Orden actualizada.');await load();if(!error)await loadDetail({...selected,...payload});setBusy(false)}
 const advance=async()=>{const next=NEXT_STAGE[selected.status];if(!next)return;const gate=canAdvanceProduction(selected,tasks,materials);if(!gate.ok)return setMessage(gate.reason);await patch({status:next,progress_percent:next==='DELIVERED'?100:Math.max(Number(selected.progress_percent||0),taskProgress(tasks))})}
 const addTask=async()=>{if(!task.title.trim())return;await supabase.from('production_tasks').insert({...task,company_id:company.id,work_order_id:selected.id,sequence_no:tasks.length});setTask(blankTask);await loadDetail(selected)}
 const toggleTask=async t=>{await supabase.from('production_tasks').update({status:t.status==='DONE'?'PENDING':'DONE',completed_at:t.status==='DONE'?null:new Date().toISOString()}).eq('id',t.id);await loadDetail(selected)}
 const addMaterial=async()=>{if(!material.material_name.trim())return;await supabase.from('production_material_requirements').insert({...material,company_id:company.id,work_order_id:selected.id});setMaterial(blankMaterial);await loadDetail(selected)}
 const reserveMaterial=async m=>{await supabase.from('production_material_requirements').update({reserved_qty:m.required_qty,status:'READY'}).eq('id',m.id);await loadDetail(selected)}
 const quality=async result=>{await supabase.from('quality_checks').insert({company_id:company.id,work_order_id:selected.id,result,check_stage:'FINAL',checklist:[{name:'Medidas',ok:result==='APPROVED'},{name:'Color y acabado',ok:result==='APPROVED'},{name:'Cantidad',ok:result==='APPROVED'}],approved_at:result==='APPROVED'?new Date().toISOString():null});await patch({quality_status:result,status:result==='REJECTED'?'REWORK':selected.status})}
 const addIncident=async()=>{const title=prompt('Describí la incidencia');if(!title)return;await supabase.from('quality_incidents').insert({company_id:company.id,work_order_id:selected.id,title,description:title,incident_type:'PRODUCTION',severity:'MEDIUM',status:'OPEN'});await loadDetail(selected)}
 const addCost=async()=>{const concept=prompt('Concepto del costo');if(!concept)return;const amount=Number(prompt('Monto')||0);if(amount<=0)return;await supabase.from('work_order_costs').insert({company_id:company.id,work_order_id:selected.id,cost_type:'OTHER',concept,amount,incurred_at:new Date().toISOString().slice(0,10)});await loadDetail(selected)}
 return <section className="production-suite production-360 production-simple">
  <div className="production-simple-head"><div><p className="form-kicker">PRODUCCIÓN</p><h2>Órdenes en producción</h2><p>Revisá únicamente lo que está en proceso y abrí una orden cuando necesités trabajarla.</p></div><div className="production-simple-stats"><span><b>{metrics.open}</b> activas</span><span className={metrics.late?'warning':''}><b>{metrics.late}</b> atrasadas</span><span><b>{metrics.ready}</b> listas</span></div></div>
  {message&&<p className="feedback success">{message}</p>}
  <div className="production-toolbar production-simple-toolbar"><input className="production-search" placeholder="Buscar orden o cliente" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Estado" value={stage} onChange={e=>setStage(e.target.value)}><option value="OPEN">Activas</option><option value="ALL">Todas</option>{PRODUCTION_STAGES.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select><select aria-label="Prioridad" value={priority} onChange={e=>setPriority(e.target.value)}><option value="ALL">Cualquier prioridad</option><option value="NORMAL">Normal</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select><div className="segmented-control"><button type="button" className={view==='TABLE'?'active':''} onClick={()=>setView('TABLE')}>Lista</button><button type="button" className={view==='KANBAN'?'active':''} onClick={()=>setView('KANBAN')}>Etapas</button></div></div>
  {rows.length>0&&<div className="production-simple-kpis"><span>En producción <b>{metrics.production}</b></span><span>Calidad <b>{metrics.quality}</b></span><span>Costo real <b>{money(metrics.actualCost)}</b></span><span>Margen <b>{metrics.margin.toFixed(1)}%</b></span></div>}
  {visible.length===0?<div className="production-simple-empty"><strong>{rows.length?'No hay órdenes con estos filtros':'No hay órdenes activas'}</strong><p>{rows.length?'Cambiá el estado, la prioridad o la búsqueda para ver otras órdenes.':'Cuando una cotización aprobada genere una orden de trabajo, aparecerá aquí automáticamente.'}</p></div>:view==='KANBAN'?<div className="production-board production-simple-board">{kanbanStages.map(([code,name])=><section className="production-column" key={code}><header><span>{name}</span><strong>{visible.filter(r=>r.status===code).length}</strong></header><div className="production-stack">{visible.filter(r=>r.status===code).map(r=><button type="button" className={`production-card priority-${String(r.priority||'NORMAL').toLowerCase()}`} key={r.id} onClick={()=>loadDetail(r)}><div className="production-card-top"><small>OT-{String(r.number).padStart(5,'0')}</small><span>{r.priority||'NORMAL'}</span></div><strong>{r.title}</strong><p>{r.clients?.name||'Cliente'}</p><div className="production-card-meta"><span>{r.due_at?new Date(r.due_at).toLocaleDateString('es-SV'):'Sin fecha'}</span><span>{Number(r.progress_percent||0)}%</span></div></button>)}</div></section>)}</div>:<div className="production-simple-list">{visible.map(r=><button type="button" className="production-simple-row" key={r.id} onClick={()=>loadDetail(r)}><div className="production-simple-order"><small>OT-{String(r.number).padStart(5,'0')}</small><strong>{r.title}</strong><span>{r.clients?.name||'Cliente'}</span></div><span className="production-stage-badge">{label(r.status)}</span><span className={`production-priority priority-${String(r.priority||'NORMAL').toLowerCase()}`}>{r.priority==='URGENT'?'Urgente':r.priority==='HIGH'?'Alta':'Normal'}</span><div className="production-simple-meta"><strong>{Number(r.progress_percent||0)}%</strong><small>{r.due_at?new Date(r.due_at).toLocaleDateString('es-SV'):'Sin fecha'}</small></div></button>)}</div>}
  {selected&&<div className="production-detail-backdrop" onMouseDown={()=>setSelected(null)}><aside className="production-detail production-detail-wide" onMouseDown={e=>e.stopPropagation()}><header className="production-detail-head"><div><small>OT-{String(selected.number).padStart(5,'0')} · {label(selected.status)}</small><h3>{selected.title}</h3><p>{selected.clients?.name||'Cliente'} · {selected.clients?.phone||''}</p></div><button className="detail-close" onClick={()=>setSelected(null)}>×</button></header><div className="production-detail-body">
   <div className="detail-grid"><label><span>Estado</span><select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}>{PRODUCTION_STAGES.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></label><label><span>Prioridad</span><select value={selected.priority||'NORMAL'} onChange={e=>setSelected({...selected,priority:e.target.value})}><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label><span>Responsable</span><select value={selected.assigned_employee_id||''} onChange={e=>setSelected({...selected,assigned_employee_id:e.target.value||null})}><option value="">Sin asignar</option>{employees.map(x=><option value={x.id} key={x.id}>{x.full_name} · {x.position||''}</option>)}</select></label><label><span>Entrega prevista</span><input type="datetime-local" value={selected.due_at?new Date(selected.due_at).toISOString().slice(0,16):''} onChange={e=>setSelected({...selected,due_at:e.target.value?new Date(e.target.value).toISOString():null})}/></label></div>
   <div className="production-kpis detail"><span>Procesos <b>{taskProgress(tasks)}%</b></span><span>Materiales <b>{materialStatus(materials)}</b></span><span>Calidad <b>{selected.quality_status||'PENDING'}</b></span><span>Costo <b>{money(detailCost)}</b></span><span>Utilidad <b>{money(profit)}</b></span></div>
   <section className="detail-section"><h4>Partidas</h4>{selected.work_order_items?.map(i=><div className="detail-line" key={i.id}><span>{i.quantity} {i.unit}</span><strong>{i.description}</strong><small>{money(i.line_total)}</small></div>)}</section>
   <section className="detail-section"><div className="panel-heading"><h4>Ruta y procesos</h4></div>{tasks.map(t=><div className="detail-line" key={t.id}><button className="mini-check" onClick={()=>toggleTask(t)}>{t.status==='DONE'?'✓':'○'}</button><strong>{t.title}</strong><small>{t.process_type} · {t.estimated_minutes} min</small></div>)}<div className="inline-production-form"><input placeholder="Nuevo proceso" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><select value={task.process_type} onChange={e=>setTask({...task,process_type:e.target.value})}><option>DESIGN</option><option>PRINT</option><option>CUT</option><option>PRODUCTION</option><option>FINISHING</option><option>INSTALLATION</option></select><input type="number" placeholder="min" value={task.estimated_minutes} onChange={e=>setTask({...task,estimated_minutes:Number(e.target.value)})}/><button onClick={addTask}>Agregar</button></div></section>
   <section className="detail-section"><h4>Materiales</h4>{materials.map(m=><div className="detail-line" key={m.id}><span>{m.reserved_qty}/{m.required_qty} {m.unit}</span><strong>{m.material_name}</strong><button className="secondary" onClick={()=>reserveMaterial(m)}>Reservar</button></div>)}<div className="inline-production-form"><input placeholder="Material" value={material.material_name} onChange={e=>setMaterial({...material,material_name:e.target.value})}/><input type="number" value={material.required_qty} onChange={e=>setMaterial({...material,required_qty:Number(e.target.value)})}/><input placeholder="Unidad" value={material.unit} onChange={e=>setMaterial({...material,unit:e.target.value})}/><button onClick={addMaterial}>Agregar</button></div></section>
   <section className="detail-section"><h4>Calidad, incidencias y costos</h4><div className="form-actions"><button className="secondary" onClick={()=>quality('APPROVED')}>✓ Aprobar calidad</button><button className="secondary" onClick={()=>quality('REJECTED')}>Rechazar / reproceso</button><button className="secondary" onClick={addIncident}>+ Incidencia</button><button className="secondary" onClick={addCost}>+ Costo real</button></div><small>{checks.length} controles · {incidents.filter(i=>i.status!=='CLOSED').length} incidencias abiertas · {costs.length} costos registrados</small></section>
   <label className="detail-field"><span>Especificaciones</span><textarea rows="3" value={selected.specifications||''} onChange={e=>setSelected({...selected,specifications:e.target.value})}/></label><label className="detail-field"><span>Notas internas</span><textarea rows="3" value={selected.internal_notes||''} onChange={e=>setSelected({...selected,internal_notes:e.target.value})}/></label></div>
   <footer className="production-detail-actions"><button className="secondary" disabled={busy} onClick={()=>patch({status:selected.status,priority:selected.priority,assigned_employee_id:selected.assigned_employee_id,due_at:selected.due_at,specifications:selected.specifications,internal_notes:selected.internal_notes,progress_percent:taskProgress(tasks),materials_status:materialStatus(materials),actual_cost:detailCost})}>Guardar</button>{NEXT_STAGE[selected.status]&&<button disabled={busy} onClick={advance}>Avanzar a {label(NEXT_STAGE[selected.status])}</button>}</footer></aside></div>}
 </section>
}
