import { createClient } from '@supabase/supabase-js'
import { useEffect, useMemo, useState } from 'react'

const supabaseUrl=import.meta.env.VITE_SUPABASE_URL
const supabaseKey=import.meta.env.VITE_SUPABASE_ANON_KEY
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey,{auth:{persistSession:true}}):null
const money=v=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(Number(v||0))

function QualityControl({company}){
  const [orders,setOrders]=useState([]),[employees,setEmployees]=useState([]),[checks,setChecks]=useState([]),[incidents,setIncidents]=useState([]),[message,setMessage]=useState('')
  const [check,setCheck]=useState({work_order_id:'',check_stage:'FINAL',result:'APPROVED',checked_by_employee_id:'',observations:''})
  const [incident,setIncident]=useState({work_order_id:'',incident_type:'PRINT_ERROR',severity:'MEDIUM',title:'',description:'',root_cause:'',corrective_action:'',responsible_employee_id:'',material_cost:'0',labor_cost:'0',outsourced_cost:'0',other_cost:'0'})
  const load=async()=>{const r=await Promise.all([
    supabase.from('work_orders').select('id,number,title,total,status').eq('company_id',company.id).order('created_at',{ascending:false}).limit(100),
    supabase.from('employees').select('id,full_name,position').eq('company_id',company.id).eq('active',true).order('full_name'),
    supabase.from('quality_checks').select('id,work_order_id,check_stage,result,observations,checked_at,work_orders(number,title)').eq('company_id',company.id).order('checked_at',{ascending:false}).limit(100),
    supabase.from('quality_incidents').select('id,work_order_id,incident_type,severity,status,title,material_cost,labor_cost,outsourced_cost,other_cost,created_at,work_orders(number,title)').eq('company_id',company.id).order('created_at',{ascending:false}).limit(100)
  ]);const e=r.find(x=>x.error)?.error;if(e)setMessage(e.message);else{setOrders(r[0].data||[]);setEmployees(r[1].data||[]);setChecks(r[2].data||[]);setIncidents(r[3].data||[])}}
  useEffect(()=>{load()},[company.id])
  const saveCheck=async e=>{e.preventDefault();setMessage('');const payload={...check,company_id:company.id,checked_by_employee_id:check.checked_by_employee_id||null,approved_at:check.result==='APPROVED'?new Date().toISOString():null};const {error}=await supabase.from('quality_checks').insert(payload);if(error)setMessage(error.message);else{setMessage('Control de calidad guardado.');setCheck({...check,observations:''});load()}}
  const saveIncident=async e=>{e.preventDefault();setMessage('');const payload={...incident,company_id:company.id,responsible_employee_id:incident.responsible_employee_id||null,material_cost:Number(incident.material_cost||0),labor_cost:Number(incident.labor_cost||0),outsourced_cost:Number(incident.outsourced_cost||0),other_cost:Number(incident.other_cost||0)};const {error}=await supabase.from('quality_incidents').insert(payload);if(error)setMessage(error.message);else{setMessage('Incidencia registrada y costo enviado a la OT.');setIncident({...incident,title:'',description:'',root_cause:'',corrective_action:'',material_cost:'0',labor_cost:'0',outsourced_cost:'0',other_cost:'0'});load()}}
  const changeStatus=async(id,status)=>{const {error}=await supabase.from('quality_incidents').update({status,resolved_at:status==='RESOLVED'?new Date().toISOString():null}).eq('id',id).eq('company_id',company.id);if(error)setMessage(error.message);else load()}
  const stats=useMemo(()=>{const open=incidents.filter(x=>!['RESOLVED','CANCELLED'].includes(x.status)).length;const rejected=checks.filter(x=>x.result==='REJECTED').length;const cost=incidents.filter(x=>x.status!=='CANCELLED').reduce((s,x)=>s+Number(x.material_cost||0)+Number(x.labor_cost||0)+Number(x.outsourced_cost||0)+Number(x.other_cost||0),0);return{open,rejected,cost}},[checks,incidents])
  return <section className="clients-module quality-module">
    <div className="clients-titlebar"><div><p className="form-kicker">CALIDAD Y MEJORA</p><h2>Control de calidad y retrabajos</h2><p>Inspecciones internas, incidencias, causa raíz, acciones correctivas y costo real de errores por orden.</p></div><span className={stats.open?'status dte-pending':'status dte-ready'}>{stats.open} incidencias abiertas</span></div>
    <div className="metrics-grid three"><article className="metric-card"><span>Incidencias abiertas</span><strong>{stats.open}</strong></article><article className="metric-card"><span>Controles rechazados</span><strong>{stats.rejected}</strong></article><article className="metric-card"><span>Costo de retrabajos</span><strong>{money(stats.cost)}</strong></article></div>
    {message&&<p className="feedback">{message}</p>}
    <div className="module-grid two-column">
      <form className="panel" onSubmit={saveCheck}><div className="panel-heading"><div><p className="form-kicker">APROBACIÓN INTERNA</p><h3>Nuevo control de calidad</h3></div></div><div className="form-grid two"><label className="field"><span>Orden</span><select required value={check.work_order_id} onChange={e=>setCheck({...check,work_order_id:e.target.value})}><option value="">Seleccionar OT</option>{orders.map(o=><option key={o.id} value={o.id}>OT-{o.number} · {o.title}</option>)}</select></label><label className="field"><span>Etapa</span><select value={check.check_stage} onChange={e=>setCheck({...check,check_stage:e.target.value})}>{['DESIGN','PREPRESS','PRODUCTION','FINAL','INSTALLATION','DELIVERY'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Resultado</span><select value={check.result} onChange={e=>setCheck({...check,result:e.target.value})}>{['APPROVED','CONDITIONAL','REJECTED','PENDING'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Revisó</span><select value={check.checked_by_employee_id} onChange={e=>setCheck({...check,checked_by_employee_id:e.target.value})}><option value="">Sin asignar</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label className="field full"><span>Observaciones</span><textarea value={check.observations} onChange={e=>setCheck({...check,observations:e.target.value})}/></label></div><div className="actions"><button className="primary-button">Guardar control</button></div></form>
      <form className="panel" onSubmit={saveIncident}><div className="panel-heading"><div><p className="form-kicker">INCIDENCIA / RETRABAJO</p><h3>Registrar error o repetición</h3></div></div><div className="form-grid two"><label className="field"><span>Orden</span><select required value={incident.work_order_id} onChange={e=>setIncident({...incident,work_order_id:e.target.value})}><option value="">Seleccionar OT</option>{orders.map(o=><option key={o.id} value={o.id}>OT-{o.number} · {o.title}</option>)}</select></label><label className="field"><span>Tipo</span><select value={incident.incident_type} onChange={e=>setIncident({...incident,incident_type:e.target.value})}>{['PRINT_ERROR','MEASUREMENT_ERROR','COLOR_ERROR','DESIGN_ERROR','MATERIAL_DAMAGE','INSTALLATION_ERROR','CLIENT_CHANGE','MACHINE_FAILURE','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Severidad</span><select value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Responsable</span><select value={incident.responsible_employee_id} onChange={e=>setIncident({...incident,responsible_employee_id:e.target.value})}><option value="">No definido</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label className="field full"><span>Título</span><input required value={incident.title} onChange={e=>setIncident({...incident,title:e.target.value})}/></label><label className="field full"><span>Descripción</span><textarea value={incident.description} onChange={e=>setIncident({...incident,description:e.target.value})}/></label><label className="field"><span>Costo material</span><input type="number" step="0.01" min="0" value={incident.material_cost} onChange={e=>setIncident({...incident,material_cost:e.target.value})}/></label><label className="field"><span>Mano de obra</span><input type="number" step="0.01" min="0" value={incident.labor_cost} onChange={e=>setIncident({...incident,labor_cost:e.target.value})}/></label><label className="field"><span>Tercerización</span><input type="number" step="0.01" min="0" value={incident.outsourced_cost} onChange={e=>setIncident({...incident,outsourced_cost:e.target.value})}/></label><label className="field"><span>Otros</span><input type="number" step="0.01" min="0" value={incident.other_cost} onChange={e=>setIncident({...incident,other_cost:e.target.value})}/></label></div><div className="actions"><button className="primary-button">Registrar incidencia</button></div></form>
    </div>
    <section className="panel"><div className="panel-heading"><div><p className="form-kicker">SEGUIMIENTO</p><h3>Incidencias y retrabajos</h3></div></div><div className="client-table-wrap"><table className="client-table"><thead><tr><th>OT</th><th>Incidencia</th><th>Severidad</th><th>Costo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{incidents.map(x=><tr key={x.id}><td>OT-{x.work_orders?.number||'—'}</td><td><strong>{x.title}</strong><small>{x.incident_type}</small></td><td>{x.severity}</td><td>{money(Number(x.material_cost||0)+Number(x.labor_cost||0)+Number(x.outsourced_cost||0)+Number(x.other_cost||0))}</td><td>{x.status}</td><td>{x.status!=='RESOLVED'&&x.status!=='CANCELLED'?<><button type="button" className="secondary-button" onClick={()=>changeStatus(x.id,'IN_REWORK')}>Retrabajo</button> <button type="button" className="secondary-button" onClick={()=>changeStatus(x.id,'RESOLVED')}>Resolver</button></>:<span>—</span>}</td></tr>)}</tbody></table></div></section>
  </section>
}

export default function QualityControlLauncher(){
  const [session,setSession]=useState(null),[company,setCompany]=useState(null),[open,setOpen]=useState(false)
  useEffect(()=>{if(!supabase)return undefined;supabase.auth.getSession().then(({data})=>setSession(data.session||null));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[])
  useEffect(()=>{if(!session||!supabase){setCompany(null);return}supabase.rpc('get_my_companies').then(async({data})=>{const id=data?.[0]?.id;if(!id)return;const {data:row}=await supabase.from('companies').select('*').eq('id',id).single();setCompany(row||null)})},[session])
  if(!session||!company)return null
  return <><button type="button" onClick={()=>setOpen(true)} className="sidebar-module-access quality"><span className="module-glyph">✓</span><span className="module-copy"><span>Calidad y retrabajos</span><small>Aprobaciones · Errores · Costos</small></span></button>{open&&<div className="erp-modal-backdrop" onMouseDown={()=>setOpen(false)}><section className="erp-modal-panel" onMouseDown={e=>e.stopPropagation()}><header className="erp-modal-head"><div><strong>Calidad y retrabajos</strong><small>Control → incidencia → retrabajo → costo real → cierre</small></div><button className="erp-modal-close" onClick={()=>setOpen(false)}>×</button></header><div className="erp-modal-body commercial-module"><QualityControl company={company}/></div></section></div>}</>
}