import {useEffect,useMemo,useState} from 'react'
import {supabase} from './lib/supabase.js'

const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const roleLabel={owner:'Propietario',admin:'Administrador',staff:'Empleado',viewer:'Solo lectura'}
const roleHelp={owner:'Control total de empresa y usuarios.',admin:'Administra operación y usuarios no propietarios.',staff:'Opera módulos de trabajo.',viewer:'Consulta sin cambios.'}

export default function UsersAdministrationCenter({company,session}){
 const [users,setUsers]=useState([]),[actorRole,setActorRole]=useState(''),[audit,setAudit]=useState([]),[tab,setTab]=useState('Usuarios'),[loading,setLoading]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''),[invite,setInvite]=useState({full_name:'',email:'',role:'staff'})
 const request=async(path,options={})=>{const token=session?.access_token;if(!token)throw new Error('Sesión no disponible.');const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'No se pudo completar la operación.');return payload}
 const load=async()=>{if(!company||!session)return;setLoading(true);setError('');try{const [u,a]=await Promise.all([request(`/api/admin/users?company_id=${encodeURIComponent(company.id)}`),request(`/api/admin/audit?company_id=${encodeURIComponent(company.id)}`)]);setUsers(u.users||[]);setActorRole(u.actor_role||'');setAudit(a.rows||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[company?.id,session?.access_token])
 const summary=useMemo(()=>({owners:users.filter(x=>x.role==='owner').length,admins:users.filter(x=>x.role==='admin').length,active:users.filter(x=>x.email_confirmed_at||x.last_sign_in_at).length,pending:users.filter(x=>!x.email_confirmed_at&&!x.last_sign_in_at).length}),[users])
 const inviteUser=async e=>{e.preventDefault();setMsg('');setError('');try{await request('/api/admin/users/invite',{method:'POST',body:JSON.stringify({company_id:company.id,...invite})});setInvite({full_name:'',email:'',role:'staff'});setMsg('Invitación creada correctamente.');await load()}catch(err){setError(err.message)}}
 const changeRole=async(user,role)=>{setMsg('');setError('');try{await request(`/api/admin/users/${user.user_id}`,{method:'PATCH',body:JSON.stringify({company_id:company.id,role})});setMsg('Rol actualizado.');await load()}catch(err){setError(err.message)}}
 const revoke=async user=>{setMsg('');setError('');try{await request(`/api/admin/users/${user.user_id}?company_id=${encodeURIComponent(company.id)}`,{method:'DELETE'});setMsg('Acceso revocado.');await load()}catch(err){setError(err.message)}}
 return <div className="users-admin-center"><section className="admin-users-hero"><div><p className="form-kicker">ADMINISTRACIÓN</p><h2>Control de accesos</h2><p>Gestioná quién entra al ERP y qué nivel de acceso tiene.</p></div><span className="status dte-ready">{roleLabel[actorRole]||'Verificando'}</span></section>{error&&<div className="feedback error">{error}</div>}{msg&&<div className="feedback success">{msg}</div>}<div className="admin-users-metrics"><article><small>Usuarios</small><strong>{users.length}</strong></article><article><small>Propietarios</small><strong>{summary.owners}</strong></article><article><small>Administradores</small><strong>{summary.admins}</strong></article><article><small>Pendientes</small><strong>{summary.pending}</strong></article></div><nav className="admin-users-tabs">{['Usuarios','Invitar','Roles','Auditoría'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>{loading?<div className="empty-state"><strong>Cargando administración…</strong></div>:<>{tab==='Usuarios'&&<Users users={users} actorRole={actorRole} session={session} onRole={changeRole} onRevoke={revoke} onRefresh={load}/>} {tab==='Invitar'&&<Invite invite={invite} setInvite={setInvite} actorRole={actorRole} onSubmit={inviteUser}/>} {tab==='Roles'&&<Roles users={users}/>} {tab==='Auditoría'&&<Audit rows={audit}/>}</>}</div>
}

function Users({users,actorRole,session,onRole,onRevoke,onRefresh}){return <section className="admin-users-panel"><div className="admin-section-head"><div><h3>Usuarios de la empresa</h3><p>Accesos, estado y privilegios actuales.</p></div><button className="btn secondary" onClick={onRefresh}>Actualizar</button></div><div className="admin-user-list">{users.map(user=><article className="admin-user-row" key={user.user_id}><div className="admin-avatar">{(user.full_name||user.email||'?').slice(0,1).toUpperCase()}</div><div className="admin-user-main"><strong>{user.full_name||'Sin nombre'}</strong><small>{user.email||user.user_id}</small><span>{user.last_sign_in_at?`Último acceso ${new Date(user.last_sign_in_at).toLocaleString('es-SV')}`:user.email_confirmed_at?'Cuenta confirmada':'Invitación pendiente'}</span></div><div className="admin-user-role"><select value={user.role} onChange={e=>onRole(user,e.target.value)} disabled={actorRole==='admin'&&['owner','admin'].includes(user.role)}>{['owner','admin','staff','viewer'].map(role=><option key={role} value={role} disabled={actorRole==='admin'&&['owner','admin'].includes(role)}>{roleLabel[role]}</option>)}</select><small>{roleHelp[user.role]}</small></div><button className="admin-revoke" disabled={user.user_id===session?.user?.id||(actorRole==='admin'&&['owner','admin'].includes(user.role))} onClick={()=>onRevoke(user)}>Revocar</button></article>)}</div></section>}
function Invite({invite,setInvite,actorRole,onSubmit}){return <section className="admin-users-panel narrow"><div className="admin-section-head"><div><h3>Invitar usuario</h3><p>El acceso se envía al correo y queda ligado a esta empresa.</p></div></div><form className="admin-invite-form" onSubmit={onSubmit}><label>Nombre completo<input value={invite.full_name} onChange={e=>setInvite({...invite,full_name:e.target.value})}/></label><label>Correo electrónico<input type="email" required value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/></label><label>Rol<select value={invite.role} onChange={e=>setInvite({...invite,role:e.target.value})}>{['owner','admin','staff','viewer'].map(role=><option key={role} value={role} disabled={actorRole==='admin'&&['owner','admin'].includes(role)}>{roleLabel[role]}</option>)}</select><small>{roleHelp[invite.role]}</small></label><button className="btn primary">Enviar invitación</button></form></section>}
function Roles({users}){return <section className="admin-users-panel"><div className="admin-role-grid">{['owner','admin','staff','viewer'].map(role=><article key={role}><span>{roleLabel[role]}</span><h3>{roleLabel[role]}</h3><p>{roleHelp[role]}</p><strong>{users.filter(x=>x.role===role).length} usuario(s)</strong></article>)}</div><div className="admin-rule-note"><strong>Protecciones activas</strong><p>El último propietario no puede ser degradado ni eliminado. Un administrador no puede modificar propietarios ni conceder privilegios altos. Nadie puede revocar su propio acceso desde esta pantalla.</p></div></section>}
function Audit({rows}){return <section className="admin-users-panel"><div className="admin-section-head"><div><h3>Bitácora administrativa</h3><p>Últimos cambios de acceso registrados por la API.</p></div></div><div className="admin-audit-list">{rows.length?rows.map(row=><article key={row.id}><div><strong>{formatAction(row.action)}</strong><small>{new Date(row.created_at).toLocaleString('es-SV')}</small></div><span>{formatDetail(row.detail)}</span></article>):<div className="empty-state"><strong>Aún no hay cambios registrados.</strong></div>}</div></section>}
function formatAction(action){return({USER_INVITED:'Usuario invitado',USER_ROLE_CHANGED:'Rol modificado',USER_ACCESS_REVOKED:'Acceso revocado'})[action]||action}
function formatDetail(detail={}){if(detail.email)return `${detail.email} · ${roleLabel[detail.role]||detail.role}`;if(detail.from||detail.to)return `${roleLabel[detail.from]||detail.from} → ${roleLabel[detail.to]||detail.to}`;if(detail.role)return roleLabel[detail.role]||detail.role;return 'Cambio administrativo'}
