import {useEffect,useMemo,useState} from 'react'
import {supabase} from './lib/supabase.js'

const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const roleLabel={owner:'Propietario',admin:'Administrador',staff:'Empleado',viewer:'Solo lectura'}
const roleHelp={owner:'Control total de empresa, usuarios y seguridad.',admin:'Administra operación y usuarios no propietarios.',staff:'Opera los módulos de trabajo asignados.',viewer:'Consulta información sin realizar cambios.'}
const tabs=['Usuarios','Invitar','Roles','Auditoría','Seguridad']
const permissionRows=[
 ['Clientes',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin','staff'],['owner','admin']],
 ['Cotizaciones',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin','staff'],['owner','admin']],
 ['Producción',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin','staff'],['owner','admin']],
 ['Inventario',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin','staff'],['owner','admin']],
 ['Facturación',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin'],['owner','admin']],
 ['Finanzas',['owner','admin','viewer'],['owner','admin'],['owner','admin'],['owner']],
 ['Usuarios y seguridad',['owner','admin'],['owner','admin'],['owner','admin'],['owner']]
]

export default function UsersAdministrationCenter({company,session}){
 const [users,setUsers]=useState([]),[actorRole,setActorRole]=useState(''),[audit,setAudit]=useState([]),[tab,setTab]=useState('Usuarios'),[loading,setLoading]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''),[invite,setInvite]=useState({full_name:'',email:'',role:'staff'}),[query,setQuery]=useState('')
 const request=async(path,options={})=>{const token=session?.access_token;if(!token)throw new Error('Sesión no disponible.');const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'No se pudo completar la operación.');return payload}
 const load=async()=>{if(!company||!session)return;setLoading(true);setError('');try{const [u,a]=await Promise.all([request(`/api/admin/users?company_id=${encodeURIComponent(company.id)}`),request(`/api/admin/audit?company_id=${encodeURIComponent(company.id)}`)]);setUsers(u.users||[]);setActorRole(u.actor_role||'');setAudit(a.rows||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[company?.id,session?.access_token])
 const summary=useMemo(()=>({owners:users.filter(x=>x.role==='owner').length,admins:users.filter(x=>x.role==='admin').length,active:users.filter(x=>x.email_confirmed_at||x.last_sign_in_at).length,pending:users.filter(x=>!x.email_confirmed_at&&!x.last_sign_in_at).length,today:users.filter(x=>isToday(x.last_sign_in_at)).length}),[users])
 const filteredUsers=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return users;return users.filter(u=>`${u.full_name||''} ${u.email||''} ${roleLabel[u.role]||u.role}`.toLowerCase().includes(q))},[users,query])
 const inviteUser=async e=>{e.preventDefault();setMsg('');setError('');try{await request('/api/admin/users/invite',{method:'POST',body:JSON.stringify({company_id:company.id,...invite})});setInvite({full_name:'',email:'',role:'staff'});setMsg('Invitación creada correctamente.');await load()}catch(err){setError(err.message)}}
 const changeRole=async(user,role)=>{setMsg('');setError('');try{await request(`/api/admin/users/${user.user_id}`,{method:'PATCH',body:JSON.stringify({company_id:company.id,role})});setMsg('Rol actualizado.');await load()}catch(err){setError(err.message)}}
 const revoke=async user=>{setMsg('');setError('');try{await request(`/api/admin/users/${user.user_id}?company_id=${encodeURIComponent(company.id)}`,{method:'DELETE'});setMsg('Acceso revocado.');await load()}catch(err){setError(err.message)}}
 const securityLabel=actorRole?'Sistema protegido':'Verificando acceso'
 return <div className="users-admin-center">
  <section className="admin-users-hero"><div><p className="form-kicker">ADMINISTRACIÓN</p><h2>Usuarios y control de accesos</h2><p>Gestioná personas, roles, permisos y trazabilidad desde un solo lugar.</p></div><div className="admin-security-badge"><span className="admin-security-dot"/><div><strong>{securityLabel}</strong><small>{actorRole?`Sesión con perfil ${roleLabel[actorRole]||actorRole}`:'Validando permisos…'}</small></div></div></section>
  {error&&<div className="feedback error">{error}</div>}{msg&&<div className="feedback success">{msg}</div>}
  <div className="admin-users-metrics"><article><small>Usuarios activos</small><strong>{summary.active}</strong><span>{users.length} registrados</span></article><article><small>Administradores</small><strong>{summary.admins}</strong><span>{summary.owners} propietario(s)</span></article><article><small>Invitaciones pendientes</small><strong>{summary.pending}</strong><span>Por confirmar acceso</span></article><article><small>Accesos hoy</small><strong>{summary.today}</strong><span>Actividad reciente</span></article></div>
  <nav className="admin-users-tabs">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  {loading?<div className="empty-state"><strong>Cargando administración…</strong></div>:<>
   {tab==='Usuarios'&&<Users users={filteredUsers} allUsers={users} actorRole={actorRole} session={session} onRole={changeRole} onRevoke={revoke} onRefresh={load} query={query} setQuery={setQuery}/>} 
   {tab==='Invitar'&&<Invite invite={invite} setInvite={setInvite} actorRole={actorRole} onSubmit={inviteUser} users={users}/>} 
   {tab==='Roles'&&<Roles users={users}/>} 
   {tab==='Auditoría'&&<Audit rows={audit}/>} 
   {tab==='Seguridad'&&<Security users={users} session={session} actorRole={actorRole} summary={summary}/>} 
  </>}
 </div>
}

function Users({users,allUsers,actorRole,session,onRole,onRevoke,onRefresh,query,setQuery}){return <section className="admin-users-panel"><div className="admin-section-head"><div><h3>Usuarios de la empresa</h3><p>Consultá estado, último acceso y privilegios de cada cuenta.</p></div><button className="btn secondary" onClick={onRefresh}>Actualizar</button></div><div className="admin-user-tools"><input aria-label="Buscar usuario" placeholder="Buscar por nombre, correo o rol…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{users.length} de {allUsers.length} usuario(s)</span></div><div className="admin-user-list">{users.length?users.map(user=><article className="admin-user-row" key={user.user_id}><div className="admin-avatar">{(user.full_name||user.email||'?').slice(0,1).toUpperCase()}</div><div className="admin-user-main"><div className="admin-user-name-line"><strong>{user.full_name||'Sin nombre'}</strong><span className={`admin-account-state ${user.email_confirmed_at||user.last_sign_in_at?'active':'pending'}`}>{user.email_confirmed_at||user.last_sign_in_at?'Activo':'Pendiente'}</span></div><small>{user.email||user.user_id}</small><span>{user.last_sign_in_at?`Último acceso ${new Date(user.last_sign_in_at).toLocaleString('es-SV')}`:user.email_confirmed_at?'Cuenta confirmada':'Invitación pendiente'}</span></div><div className="admin-user-role"><select value={user.role} onChange={e=>onRole(user,e.target.value)} disabled={actorRole==='admin'&&['owner','admin'].includes(user.role)}>{['owner','admin','staff','viewer'].map(role=><option key={role} value={role} disabled={actorRole==='admin'&&['owner','admin'].includes(role)}>{roleLabel[role]}</option>)}</select><small>{roleHelp[user.role]}</small></div><button className="admin-revoke" disabled={user.user_id===session?.user?.id||(actorRole==='admin'&&['owner','admin'].includes(user.role))} onClick={()=>onRevoke(user)}>Revocar</button></article>):<div className="empty-state"><strong>No encontramos usuarios con ese criterio.</strong></div>}</div></section>}

function Invite({invite,setInvite,actorRole,onSubmit,users}){const pending=users.filter(x=>!x.email_confirmed_at&&!x.last_sign_in_at);return <section className="admin-users-panel"><div className="admin-invite-layout"><div><div className="admin-section-head"><div><h3>Invitar usuario</h3><p>La persona recibirá un acceso ligado a esta empresa.</p></div></div><form className="admin-invite-form" onSubmit={onSubmit}><label>Nombre completo<input required value={invite.full_name} onChange={e=>setInvite({...invite,full_name:e.target.value})}/></label><label>Correo electrónico<input type="email" required value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/></label><label>Rol<select value={invite.role} onChange={e=>setInvite({...invite,role:e.target.value})}>{['owner','admin','staff','viewer'].map(role=><option key={role} value={role} disabled={actorRole==='admin'&&['owner','admin'].includes(role)}>{roleLabel[role]}</option>)}</select><small>{roleHelp[invite.role]}</small></label><button className="btn primary">Enviar invitación</button></form></div><aside className="admin-pending-box"><h4>Invitaciones pendientes</h4><p>{pending.length?`${pending.length} acceso(s) todavía no han sido activados.`:'No hay invitaciones pendientes.'}</p>{pending.slice(0,5).map(u=><div key={u.user_id}><strong>{u.full_name||u.email}</strong><small>{u.email} · {roleLabel[u.role]}</small></div>)}</aside></div></section>}

function Roles({users}){return <section className="admin-users-panel"><div className="admin-role-grid">{['owner','admin','staff','viewer'].map(role=><article key={role}><span>{roleLabel[role]}</span><h3>{roleLabel[role]}</h3><p>{roleHelp[role]}</p><strong>{users.filter(x=>x.role===role).length} usuario(s)</strong></article>)}</div><div className="admin-permissions-wrap"><div className="admin-section-head"><div><h3>Matriz de permisos</h3><p>Vista de referencia de privilegios por nivel de rol.</p></div></div><div className="admin-permissions-table"><div className="admin-permissions-row header"><span>Módulo</span><span>Ver</span><span>Crear</span><span>Editar</span><span>Autorizar</span></div>{permissionRows.map(([module,...cols])=><div className="admin-permissions-row" key={module}><strong>{module}</strong>{cols.map((roles,i)=><span key={i} title={roles.map(r=>roleLabel[r]).join(', ')}>{roles.length===4?'Todos':roles.map(r=>roleLabel[r]).join(' / ')}</span>)}</div>)}</div></div><div className="admin-rule-note"><strong>Protecciones activas</strong><p>El último propietario no puede ser degradado ni eliminado. Un administrador no puede modificar propietarios ni conceder privilegios de propietario. Nadie puede revocar su propio acceso desde esta pantalla.</p></div></section>}

function Audit({rows}){const [filter,setFilter]=useState('');const visible=rows.filter(r=>`${r.action||''} ${formatDetail(r.detail)}`.toLowerCase().includes(filter.toLowerCase()));return <section className="admin-users-panel"><div className="admin-section-head"><div><h3>Bitácora administrativa</h3><p>Trazabilidad de invitaciones, cambios de rol y revocaciones.</p></div></div><div className="admin-user-tools"><input placeholder="Filtrar actividad…" value={filter} onChange={e=>setFilter(e.target.value)}/><span>{visible.length} evento(s)</span></div><div className="admin-audit-list">{visible.length?visible.map(row=><article key={row.id}><div className="admin-audit-icon">•</div><div><strong>{formatAction(row.action)}</strong><small>{new Date(row.created_at).toLocaleString('es-SV')}</small></div><span>{formatDetail(row.detail)}</span></article>):<div className="empty-state"><strong>Aún no hay cambios registrados.</strong></div>}</div></section>}

function Security({users,session,actorRole,summary}){const me=users.find(u=>u.user_id===session?.user?.id);return <section className="admin-users-panel"><div className="admin-section-head"><div><h3>Seguridad de acceso</h3><p>Resumen de la sesión actual y controles de protección del ERP.</p></div></div><div className="admin-security-grid"><article><span className="security-icon">✓</span><div><strong>Sesión autenticada</strong><p>{me?.email||session?.user?.email||'Usuario autenticado'}</p><small>Perfil: {roleLabel[actorRole]||actorRole||'En verificación'}</small></div></article><article><span className="security-icon">✓</span><div><strong>Protección de privilegios</strong><p>Los roles superiores tienen restricciones contra cambios indebidos.</p><small>{summary.owners} propietario(s) registrado(s)</small></div></article><article><span className="security-icon">✓</span><div><strong>Auditoría administrativa</strong><p>Los cambios críticos quedan registrados para trazabilidad.</p><small>Invitaciones, roles y revocaciones</small></div></article><article className={summary.pending?'attention':''}><span className="security-icon">{summary.pending?'!':'✓'}</span><div><strong>Accesos pendientes</strong><p>{summary.pending?`${summary.pending} invitación(es) requieren activación.`:'No hay accesos pendientes.'}</p><small>Revisá periódicamente usuarios inactivos</small></div></article></div><div className="admin-security-recommendations"><h4>Controles recomendados</h4><div><span>Contraseñas individuales</span><strong>Activo</strong></div><div><span>Registro de cambios administrativos</span><strong>Activo</strong></div><div><span>Protección del propietario</span><strong>Activo</strong></div><div><span>Autenticación de dos pasos</span><strong className="muted">Próxima mejora</strong></div><div><span>Gestión de dispositivos y sesiones</span><strong className="muted">Próxima mejora</strong></div></div></section>}

function isToday(value){if(!value)return false;const d=new Date(value),n=new Date();return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate()}
function formatAction(action){return({USER_INVITED:'Usuario invitado',USER_ROLE_CHANGED:'Rol modificado',USER_ACCESS_REVOKED:'Acceso revocado'})[action]||action}
function formatDetail(detail={}){if(detail.email)return `${detail.email} · ${roleLabel[detail.role]||detail.role}`;if(detail.from||detail.to)return `${roleLabel[detail.from]||detail.from} → ${roleLabel[detail.to]||detail.to}`;if(detail.role)return roleLabel[detail.role]||detail.role;return 'Cambio administrativo'}
