import {useEffect,useMemo,useState} from 'react'

const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const roleLabel={owner:'Propietario',admin:'Administrador',staff:'Empleado',viewer:'Solo lectura'}
const roleHelp={owner:'Control total de empresa, usuarios y seguridad.',admin:'Administra operación y usuarios no propietarios.',staff:'Opera los módulos de trabajo asignados.',viewer:'Consulta información sin realizar cambios.'}
const tabs=['Usuarios','Invitar','Roles','Auditoría','Seguridad']
const permissionRows=[
 ['Clientes',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin','staff'],['owner','admin']],
 ['Cotizaciones',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin','staff'],['owner','admin']],
 ['Producción',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin','staff'],['owner','admin']],
 ['Inventario',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin','staff'],['owner','admin']],
 ['Facturación',['owner','admin','staff','viewer'],['owner','admin','staff'],['owner','admin'],['owner','admin']],
 ['Finanzas',['owner','admin','viewer'],['owner','admin'],['owner','admin'],['owner']],
 ['Usuarios y seguridad',['owner','admin'],['owner','admin'],['owner','admin'],['owner']]
]

export default function UsersAdministrationCenter({company,session}){
 const [users,setUsers]=useState([]),[actorRole,setActorRole]=useState(''),[audit,setAudit]=useState([]),[tab,setTab]=useState('Usuarios'),[loading,setLoading]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''),[invite,setInvite]=useState({full_name:'',email:'',role:'staff',job_title:''}),[query,setQuery]=useState('')
 const request=async(path,options={})=>{const token=session?.access_token;if(!token)throw new Error('Sesión no disponible.');const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'No se pudo completar la operación.');return payload}
 const load=async()=>{if(!company||!session)return;setLoading(true);setError('');try{const [u,a]=await Promise.all([request(`/api/admin/users?company_id=${encodeURIComponent(company.id)}`),request(`/api/admin/audit?company_id=${encodeURIComponent(company.id)}`)]);setUsers(u.users||[]);setActorRole(u.actor_role||'');setAudit(a.rows||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[company?.id,session?.access_token])
 const sessionEvents=useMemo(()=>audit.filter(x=>x.action==='SESSION_ACTIVE'),[audit])
 const todayActors=useMemo(()=>new Set(sessionEvents.filter(x=>isToday(x.created_at)).map(x=>x.actor_user_id)),[sessionEvents])
 const latestActivityByUser=useMemo(()=>{const map=new Map();for(const row of sessionEvents){if(!map.has(row.actor_user_id))map.set(row.actor_user_id,row)}return map},[sessionEvents])
 const summary=useMemo(()=>({owners:users.filter(x=>x.role==='owner').length,admins:users.filter(x=>x.role==='admin').length,active:users.filter(x=>x.email_confirmed_at||x.last_sign_in_at).length,pending:users.filter(x=>!x.email_confirmed_at&&!x.last_sign_in_at).length,today:todayActors.size}),[users,todayActors])
 const lastToday=useMemo(()=>sessionEvents.find(x=>isToday(x.created_at))||null,[sessionEvents])
 const filteredUsers=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return users;return users.filter(u=>`${u.full_name||''} ${u.email||''} ${roleLabel[u.role]||u.role}`.toLowerCase().includes(q))},[users,query])
 const inviteUser=async e=>{e.preventDefault();setMsg('');setError('');try{await request('/api/admin/users/invite',{method:'POST',body:JSON.stringify({company_id:company.id,...invite})});setInvite({full_name:'',email:'',role:'staff',job_title:''});setMsg('Invitación creada correctamente.');await load()}catch(err){setError(err.message)}}
 const changeRole=async(user,role)=>{setMsg('');setError('');try{await request(`/api/admin/users/${user.user_id}`,{method:'PATCH',body:JSON.stringify({company_id:company.id,role})});setMsg('Rol actualizado.');await load()}catch(err){setError(err.message)}}
 const revoke=async user=>{setMsg('');setError('');try{await request(`/api/admin/users/${user.user_id}?company_id=${encodeURIComponent(company.id)}`,{method:'DELETE'});setMsg('Acceso revocado.');await load()}catch(err){setError(err.message)}}
 return <div className="users-admin-center">
  <section className="admin-users-hero"><div><p className="form-kicker">ADMINISTRACIÓN</p><h2>Usuarios y control de accesos</h2><p>Gestioná personas, roles, permisos y trazabilidad desde un solo lugar.</p></div><div className="admin-security-badge"><span className="admin-security-dot"/><div><strong>{actorRole?'Sistema protegido':'Verificando acceso'}</strong><small>{actorRole?`Sesión con perfil ${roleLabel[actorRole]||actorRole}`:'Validando permisos…'}</small></div></div></section>
  {error&&<div className="feedback error">{error}</div>}{msg&&<div className="feedback success">{msg}</div>}
  <div className="admin-users-metrics"><article><small>Usuarios activos</small><strong>{summary.active}</strong><span>{users.length} registrados</span></article><article><small>Propietarios</small><strong>{summary.owners}</strong><span>Control total del ERP</span></article><article><small>Administradores</small><strong>{summary.admins}</strong><span>Gestión operativa</span></article><article><small>Invitaciones pendientes</small><strong>{summary.pending}</strong><span>Por confirmar acceso</span></article><article><small>Accesos hoy</small><strong>{summary.today}</strong><span>{lastToday?`Última actividad: ${new Date(lastToday.created_at).toLocaleTimeString('es-SV',{hour:'2-digit',minute:'2-digit'})}`:'Sin actividad registrada hoy'}</span></article></div>
  <nav className="admin-users-tabs">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  {loading?<div className="empty-state"><strong>Cargando administración…</strong></div>:<>
   {tab==='Usuarios'&&<Users users={filteredUsers} allUsers={users} actorRole={actorRole} session={session} onRole={changeRole} onRevoke={revoke} onRefresh={load} query={query} setQuery={setQuery} latestActivityByUser={latestActivityByUser}/>} 
   {tab==='Invitar'&&<Invite invite={invite} setInvite={setInvite} actorRole={actorRole} onSubmit={inviteUser} users={users}/>} 
   {tab==='Roles'&&<Roles users={users}/>} 
   {tab==='Auditoría'&&<Audit rows={audit} users={users}/>} 
   {tab==='Seguridad'&&<Security users={users} session={session} actorRole={actorRole} summary={summary} audit={audit}/>} 
  </>}
 </div>
}

function Users({users,allUsers,actorRole,session,onRole,onRevoke,onRefresh,query,setQuery,latestActivityByUser}){return <section className="admin-users-panel"><div className="admin-section-head"><div><h3>Usuarios de la empresa</h3><p>Consultá estado, actividad real y privilegios de cada cuenta.</p></div><button className="btn secondary" onClick={onRefresh}>Actualizar</button></div><div className="admin-user-tools"><input aria-label="Buscar usuario" placeholder="Buscar por nombre, correo o rol…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{users.length} de {allUsers.length} usuario(s)</span></div><div className="admin-user-list">{users.length?users.map(user=>{const own=user.user_id===session?.user?.id;const protectedUser=own||(actorRole==='admin'&&['owner','admin'].includes(user.role));const activity=latestActivityByUser.get(user.user_id);return <article className="admin-user-row" key={user.user_id}><div className="admin-avatar">{(user.full_name||user.email||'?').slice(0,1).toUpperCase()}</div><div className="admin-user-main"><div className="admin-user-name-line"><strong>{user.full_name||'Sin nombre'}</strong><span className={`admin-account-state ${user.email_confirmed_at||user.last_sign_in_at?'active':'pending'}`}>{user.email_confirmed_at||user.last_sign_in_at?'Activo':'Pendiente'}</span>{own&&<span className="admin-account-state self">Tu cuenta</span>}</div><small>{user.email||user.user_id}</small><span>{activity?`Actividad ERP ${new Date(activity.created_at).toLocaleString('es-SV')} · ${activity.detail?.device||'Dispositivo web'}`:user.last_sign_in_at?`Último inicio de sesión ${new Date(user.last_sign_in_at).toLocaleString('es-SV')}`:'Sin actividad registrada'}</span></div><div className="admin-user-actions"><div className="admin-user-role"><select value={user.role} onChange={e=>onRole(user,e.target.value)} disabled={actorRole==='admin'&&['owner','admin'].includes(user.role)}>{['owner','admin','staff','viewer'].map(role=><option key={role} value={role} disabled={actorRole==='admin'&&['owner','admin'].includes(role)}>{roleLabel[role]}</option>)}</select><small>{roleHelp[user.role]}</small></div>{protectedUser?<span className="admin-protected" title={own?'No podés revocar tu propia cuenta desde esta pantalla.':'Este usuario está protegido por su nivel de privilegio.'}>Protegido</span>:<button className="admin-revoke" onClick={()=>onRevoke(user)}>Revocar</button>}</div></article>}) :<div className="empty-state compact"><strong>No encontramos usuarios con ese criterio.</strong></div>}</div></section>}

function Invite({invite,setInvite,actorRole,onSubmit,users}){const pending=users.filter(x=>!x.email_confirmed_at&&!x.last_sign_in_at);return <section className="admin-users-panel"><div className="admin-invite-layout"><div><div className="admin-section-head"><div><h3>Invitar usuario</h3><p>La persona recibirá un acceso ligado a esta empresa.</p></div></div><form className="admin-invite-form" onSubmit={onSubmit}><label>Nombre completo<input required value={invite.full_name} onChange={e=>setInvite({...invite,full_name:e.target.value})}/></label><label>Correo electrónico<input type="email" required value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})}/></label><label>Cargo o función<input placeholder="Ej. Ventas, Caja, Producción" value={invite.job_title||''} onChange={e=>setInvite({...invite,job_title:e.target.value})}/></label><label>Rol<select value={invite.role} onChange={e=>setInvite({...invite,role:e.target.value})}>{['owner','admin','staff','viewer'].map(role=><option key={role} value={role} disabled={actorRole==='admin'&&['owner','admin'].includes(role)}>{roleLabel[role]}</option>)}</select><small>{roleHelp[invite.role]}</small></label><button className="btn primary">Enviar invitación</button></form></div><aside className="admin-pending-box"><h4>Invitaciones pendientes</h4><p>{pending.length?`${pending.length} acceso(s) todavía no han sido activados.`:'No hay invitaciones pendientes.'}</p>{pending.slice(0,5).map(u=><div key={u.user_id}><strong>{u.full_name||u.email}</strong><small>{u.email} · {roleLabel[u.role]}</small></div>)}</aside></div></section>}

function Roles({users}){return <section className="admin-users-panel compact-panel"><div className="admin-section-head"><div><h3>Roles y permisos</h3><p>Definición clara de quién puede ver, crear, editar y autorizar dentro del ERP.</p></div></div><div className="admin-role-grid compact-roles">{['owner','admin','staff','viewer'].map(role=><article key={role}><span>{roleLabel[role]}</span><h3>{roleLabel[role]}</h3><p>{roleHelp[role]}</p><strong>{users.filter(x=>x.role===role).length} usuario(s)</strong></article>)}</div><div className="admin-permissions-wrap"><div className="admin-section-head"><div><h3>Matriz de permisos</h3><p>Vista de referencia de privilegios por nivel de rol.</p></div></div><div className="admin-permissions-table"><div className="admin-permissions-row header"><span>Módulo</span><span>Ver</span><span>Crear</span><span>Editar</span><span>Autorizar</span></div>{permissionRows.map(([module,...cols])=><div className="admin-permissions-row" key={module}><strong>{module}</strong>{cols.map((roles,i)=><span key={i} title={roles.map(r=>roleLabel[r]).join(', ')}>{roles.length===4?'Todos':roles.map(r=>roleLabel[r]).join(' / ')}</span>)}</div>)}</div></div><div className="admin-rule-note"><strong>Protecciones activas</strong><p>El último propietario no puede ser degradado ni eliminado. Un administrador no puede modificar propietarios ni conceder privilegios de propietario. Nadie puede revocar su propio acceso desde esta pantalla.</p></div></section>}

function Audit({rows,users}){
 const [filter,setFilter]=useState(''),[module,setModule]=useState('Todos'),[action,setAction]=useState('Todos'),[actor,setActor]=useState('Todos'),[date,setDate]=useState('')
 const modules=useMemo(()=>['Todos',...new Set(rows.map(r=>r.detail?.module).filter(Boolean))],[rows])
 const actions=useMemo(()=>['Todos',...new Set(rows.map(r=>r.action).filter(Boolean))],[rows])
 const actors=useMemo(()=>{const map=new Map();for(const row of rows){if(row.actor_user_id)map.set(row.actor_user_id,row.actor?.name||row.actor?.email||row.actor_user_id)}for(const user of users||[]){if(user.user_id&&!map.has(user.user_id))map.set(user.user_id,user.full_name||user.email||user.user_id)}return [...map.entries()]},[rows,users])
 const visible=useMemo(()=>rows.filter(r=>{const text=`${r.action||''} ${formatAction(r.action)} ${r.actor?.name||''} ${r.actor?.email||''} ${r.detail?.module||''} ${formatDetail(r.detail)}`.toLowerCase();if(filter&& !text.includes(filter.toLowerCase()))return false;if(module!=='Todos'&&r.detail?.module!==module)return false;if(action!=='Todos'&&r.action!==action)return false;if(actor!=='Todos'&&r.actor_user_id!==actor)return false;if(date&&localDateKey(r.created_at)!==date)return false;return true}),[rows,filter,module,action,actor,date])
 const stats=useMemo(()=>({changes:visible.filter(r=>String(r.action||'').startsWith('ERP_RECORD_')).length,blocked:visible.filter(r=>['ACCESS_DENIED','READ_ONLY_BLOCKED','DTE_ACCESS_DENIED'].includes(r.action)).length,sessions:visible.filter(r=>r.action==='SESSION_ACTIVE').length,users:new Set(visible.map(r=>r.actor_user_id).filter(Boolean)).size}),[visible])
 const clear=()=>{setFilter('');setModule('Todos');setAction('Todos');setActor('Todos');setDate('')}
 return <section className="admin-users-panel audit-panel"><div className="admin-section-head"><div><h3>Auditoría global del ERP</h3><p>Actividad administrativa, operaciones de negocio y accesos bloqueados en un solo registro.</p></div><button className="btn secondary" onClick={clear}>Limpiar filtros</button></div><div className="audit-summary"><article><small>Eventos visibles</small><strong>{visible.length}</strong></article><article><small>Cambios ERP</small><strong>{stats.changes}</strong></article><article><small>Bloqueos</small><strong>{stats.blocked}</strong></article><article><small>Sesiones</small><strong>{stats.sessions}</strong></article><article><small>Usuarios</small><strong>{stats.users}</strong></article></div><div className="audit-filters"><input placeholder="Buscar acción, usuario, módulo o detalle…" value={filter} onChange={e=>setFilter(e.target.value)}/><select value={module} onChange={e=>setModule(e.target.value)}>{modules.map(x=><option key={x}>{x}</option>)}</select><select value={action} onChange={e=>setAction(e.target.value)}>{actions.map(x=><option key={x} value={x}>{x==='Todos'?'Todas las acciones':formatAction(x)}</option>)}</select><select value={actor} onChange={e=>setActor(e.target.value)}><option value="Todos">Todos los usuarios</option>{actors.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="admin-audit-list global-audit-list">{visible.length?visible.map(row=><article key={row.id} className={`audit-event ${auditTone(row.action)}`}><div className="admin-audit-icon">{auditIcon(row.action)}</div><div className="audit-event-main"><div className="audit-event-title"><strong>{formatAction(row.action)}</strong>{row.detail?.module&&<span>{row.detail.module}</span>}</div><small>{row.actor?.name||row.actor?.email||'Usuario'} · {new Date(row.created_at).toLocaleString('es-SV')}</small><p>{formatDetail(row.detail)}</p></div></article>):<div className="empty-state compact"><strong>No hay eventos con esos filtros.</strong><p>Probá otro módulo, usuario, acción o fecha.</p></div>}</div><div className="admin-rule-note"><strong>Trazabilidad activa</strong><p>IDEALO SV registra sesiones, invitaciones, cambios de rol, accesos denegados y cambios de negocio en Clientes, Cotizaciones, Producción, Inventario, Proveedores, Compras, Caja, Finanzas y Facturación.</p></div></section>}

function Security({users,session,actorRole,summary,audit}){const me=users.find(u=>u.user_id===session?.user?.id);const current=audit.find(x=>x.action==='SESSION_ACTIVE'&&x.actor_user_id===session?.user?.id);const signedAt=current?.created_at||me?.last_sign_in_at||session?.user?.last_sign_in_at;return <section className="admin-users-panel"><div className="admin-section-head"><div><h3>Seguridad de acceso</h3><p>Sesión actual, dispositivo, red y protección de privilegios.</p></div></div><div className="admin-session-strip five"><div><small>Cuenta actual</small><strong>{me?.email||session?.user?.email||'Usuario autenticado'}</strong></div><div><small>Dispositivo</small><strong>{current?.detail?.device||browserDeviceFallback()}</strong></div><div><small>Navegador</small><strong>{current?.detail?.browser||browserName()}</strong></div><div><small>IP registrada</small><strong>{current?.detail?.ip||'Pendiente de próxima actividad'}</strong></div><div><small>Actividad ERP</small><strong>{signedAt?new Date(signedAt).toLocaleString('es-SV'):'No disponible'}</strong></div></div><div className="admin-security-grid"><article><span className="security-icon">✓</span><div><strong>Sesión autenticada</strong><p>La cuenta actual mantiene actividad válida en IDEALO SV.</p><small>Perfil: {roleLabel[actorRole]||actorRole||'En verificación'}</small></div></article><article><span className="security-icon">✓</span><div><strong>Actividad real</strong><p>El ERP registra presencia mientras la sesión está abierta o vuelve a primer plano.</p><small>{summary.today} usuario(s) con actividad hoy</small></div></article><article><span className="security-icon">✓</span><div><strong>Auditoría administrativa</strong><p>Los cambios críticos de usuarios quedan registrados para trazabilidad.</p><small>Sesiones, invitaciones, roles y revocaciones</small></div></article><article className={summary.pending?'attention':''}><span className="security-icon">{summary.pending?'!':'✓'}</span><div><strong>Accesos pendientes</strong><p>{summary.pending?`${summary.pending} invitación(es) requieren activación.`:'No hay accesos pendientes.'}</p><small>Revisá periódicamente usuarios inactivos</small></div></article></div><div className="admin-security-recommendations"><h4>Estado de controles</h4><div><span>Contraseñas individuales</span><strong>Activo</strong></div><div><span>Registro de actividad de sesión</span><strong>Activo</strong></div><div><span>Dispositivo y navegador</span><strong>Activo</strong></div><div><span>IP enmascarada para auditoría</span><strong>Activo</strong></div><div><span>Protección del propietario</span><strong>Activo</strong></div><div><span>Autenticación de dos pasos</span><strong className="muted">Pendiente de activar</strong></div><div><span>Cierre remoto de otras sesiones</span><strong className="muted">Pendiente de API</strong></div></div></section>}

function browserName(){if(typeof navigator==='undefined')return 'No disponible';const u=navigator.userAgent;if(/Edg\//.test(u))return 'Microsoft Edge';if(/Chrome\//.test(u))return 'Google Chrome';if(/Firefox\//.test(u))return 'Mozilla Firefox';if(/Safari\//.test(u))return 'Safari';return 'Navegador web'}
function browserDeviceFallback(){if(typeof navigator==='undefined')return 'No disponible';const u=navigator.userAgent;if(/Android/i.test(u))return 'Android';if(/iPhone|iPad|iPod/i.test(u))return 'iPhone / iPad';if(/Windows/i.test(u))return 'Windows';if(/Macintosh|Mac OS X/i.test(u))return 'Mac';return 'Dispositivo web'}
function isToday(value){if(!value)return false;const d=new Date(value),n=new Date();return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate()}
function localDateKey(value){if(!value)return '';const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function formatAction(action){return({SESSION_ACTIVE:'Actividad de sesión',USER_INVITED:'Usuario invitado',USER_ROLE_CHANGED:'Rol modificado',USER_ACCESS_REVOKED:'Acceso revocado',ERP_RECORD_CREATED:'Registro creado',ERP_RECORD_UPDATED:'Registro modificado',ERP_RECORD_DELETED:'Registro eliminado',ACCESS_DENIED:'Acceso a módulo bloqueado',READ_ONLY_BLOCKED:'Modificación bloqueada',DTE_ACCESS_DENIED:'Operación DTE bloqueada'})[action]||action}
function formatDetail(detail={}){if(detail.module&&detail.operation){const verb={INSERT:'Creación',UPDATE:'Modificación',DELETE:'Eliminación'}[detail.operation]||detail.operation;const fields=Array.isArray(detail.changed_fields)&&detail.changed_fields.length?` · Campos: ${detail.changed_fields.join(', ')}`:'';return `${verb} en ${detail.module}${detail.record_id?` · Registro ${String(detail.record_id).slice(0,12)}`:''}${fields}`};if(detail.reason||detail.action){return `${detail.module?`${detail.module} · `:''}${detail.action||'Acción'}${detail.reason?` · ${detail.reason}`:''}`};if(detail.operation&&detail.allowed_roles)return `${detail.operation} · Roles permitidos: ${(detail.allowed_roles||[]).map(r=>roleLabel[r]||r).join(', ')}`;if(detail.event)return `${detail.email||'Usuario'} · ${detail.device||'Dispositivo'} · ${detail.browser||'Navegador'}${detail.ip?` · IP ${detail.ip}`:''}`;if(detail.from||detail.to)return `${detail.email?`${detail.email} · `:''}${roleLabel[detail.from]||detail.from||'—'} → ${roleLabel[detail.to]||detail.to||'—'}`;if(detail.email)return `${detail.email} · ${roleLabel[detail.role]||detail.role||'Sin rol'}${detail.job_title?` · ${detail.job_title}`:''}`;if(detail.role)return roleLabel[detail.role]||detail.role;return 'Cambio administrativo'}
function auditIcon(action){if(action==='SESSION_ACTIVE')return '↗';if(String(action||'').includes('DENIED')||action==='READ_ONLY_BLOCKED')return '!';if(action==='ERP_RECORD_CREATED')return '+';if(action==='ERP_RECORD_UPDATED')return '↻';if(action==='ERP_RECORD_DELETED')return '−';return '•'}
function auditTone(action){if(String(action||'').includes('DENIED')||action==='READ_ONLY_BLOCKED')return 'blocked';if(String(action||'').startsWith('ERP_RECORD_'))return 'business';if(action==='SESSION_ACTIVE')return 'session';return 'admin'}
