create table if not exists accounts_payable (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  supplier_id uuid references suppliers(id) on delete set null,
  purchase_id uuid references purchases(id) on delete cascade,
  number bigint generated by default as identity,
  concept text not null,
  amount_total numeric(12,2) not null default 0 check (amount_total >= 0),
  amount_paid numeric(12,2) not null default 0 check (amount_paid >= 0),
  due_date date,
  status text not null default 'OPEN' check (status in ('OPEN','PARTIAL','PAID','OVERDUE','CANCELLED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists accounts_payable_purchase_uidx on accounts_payable(purchase_id) where purchase_id is not null;
create index if not exists accounts_payable_company_idx on accounts_payable(company_id,status,due_date);
create index if not exists accounts_payable_supplier_idx on accounts_payable(supplier_id) where supplier_id is not null;

create table if not exists supplier_payments (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  payable_id uuid not null references accounts_payable(id) on delete cascade,
  supplier_id uuid references suppliers(id) on delete set null,
  cash_account_id uuid not null references cash_accounts(id) on delete restrict,
  amount numeric(12,2) not null check (amount > 0),
  payment_method text not null default 'CASH' check (payment_method in ('CASH','TRANSFER','CARD','CHECK','OTHER')),
  reference text,
  notes text,
  paid_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists supplier_payments_payable_idx on supplier_payments(payable_id,paid_at desc);
create index if not exists supplier_payments_company_idx on supplier_payments(company_id,paid_at desc);
create index if not exists supplier_payments_supplier_idx on supplier_payments(supplier_id) where supplier_id is not null;
create index if not exists supplier_payments_cash_account_idx on supplier_payments(cash_account_id);

alter table accounts_payable enable row level security;
alter table supplier_payments enable row level security;

create policy "members manage accounts payable" on accounts_payable
for all to authenticated
using (exists(select 1 from company_members cm where cm.company_id=accounts_payable.company_id and cm.user_id=(select auth.uid())))
with check (
  exists(select 1 from company_members cm where cm.company_id=accounts_payable.company_id and cm.user_id=(select auth.uid()))
  and (accounts_payable.supplier_id is null or exists(select 1 from suppliers s where s.id=accounts_payable.supplier_id and s.company_id=accounts_payable.company_id))
  and (accounts_payable.purchase_id is null or exists(select 1 from purchases p where p.id=accounts_payable.purchase_id and p.company_id=accounts_payable.company_id))
);

create policy "members manage supplier payments" on supplier_payments
for all to authenticated
using (exists(select 1 from company_members cm where cm.company_id=supplier_payments.company_id and cm.user_id=(select auth.uid())))
with check (
  exists(select 1 from company_members cm where cm.company_id=supplier_payments.company_id and cm.user_id=(select auth.uid()))
  and exists(select 1 from accounts_payable ap where ap.id=supplier_payments.payable_id and ap.company_id=supplier_payments.company_id)
  and exists(select 1 from cash_accounts ca where ca.id=supplier_payments.cash_account_id and ca.company_id=supplier_payments.company_id)
  and (supplier_payments.supplier_id is null or exists(select 1 from suppliers s where s.id=supplier_payments.supplier_id and s.company_id=supplier_payments.company_id))
);

create or replace function sync_purchase_to_payable() returns trigger
language plpgsql
security invoker
set search_path=public
as $$
begin
  if new.payment_status in ('PENDING','PARTIAL') and new.total > 0 then
    insert into accounts_payable(company_id,supplier_id,purchase_id,concept,amount_total,due_date,status)
    values(new.company_id,new.supplier_id,new.id,new.concept,new.total,new.due_date,
      case when new.due_date is not null and new.due_date < current_date then 'OVERDUE' else 'OPEN' end)
    on conflict (purchase_id) where purchase_id is not null do update
      set supplier_id=excluded.supplier_id,
          concept=excluded.concept,
          amount_total=excluded.amount_total,
          due_date=excluded.due_date,
          updated_at=now();
  elsif new.payment_status='PAID' then
    update accounts_payable set amount_paid=amount_total,status='PAID',updated_at=now() where purchase_id=new.id;
  end if;
  return new;
end;
$$;

revoke all on function sync_purchase_to_payable() from public, anon, authenticated;

drop trigger if exists trg_sync_purchase_to_payable on purchases;
create trigger trg_sync_purchase_to_payable
after insert or update of payment_status,total,due_date,supplier_id,concept on purchases
for each row execute function sync_purchase_to_payable();

create or replace function apply_supplier_payment() returns trigger
language plpgsql
security invoker
set search_path=public
as $$
declare
  v_total numeric(12,2);
  v_paid numeric(12,2);
  v_purchase uuid;
  v_due date;
  v_supplier uuid;
begin
  select amount_total, purchase_id, due_date, supplier_id into v_total,v_purchase,v_due,v_supplier
  from accounts_payable where id=new.payable_id and company_id=new.company_id for update;

  if not found then raise exception 'Payable does not belong to this company'; end if;

  select coalesce(sum(amount),0) into v_paid from supplier_payments where payable_id=new.payable_id;
  if v_paid > v_total + 0.001 then raise exception 'Payment exceeds payable balance'; end if;

  update accounts_payable set amount_paid=v_paid,
    status=case when v_paid>=v_total then 'PAID' when v_paid>0 then 'PARTIAL' when v_due is not null and v_due<current_date then 'OVERDUE' else 'OPEN' end,
    updated_at=now()
  where id=new.payable_id;

  if v_purchase is not null then
    update purchases set payment_status=case when v_paid>=v_total then 'PAID' when v_paid>0 then 'PARTIAL' else 'PENDING' end,updated_at=now()
    where id=v_purchase and company_id=new.company_id;
  end if;

  insert into cash_movements(company_id,cash_account_id,movement_date,movement_type,source_type,source_id,concept,amount,reference,notes)
  values(new.company_id,new.cash_account_id,new.paid_at,'EXPENSE','SUPPLIER_PAYMENT',new.id,
    'Pago a proveedor' || case when v_supplier is not null then '' else '' end,
    new.amount,new.reference,new.notes);

  return new;
end;
$$;

revoke all on function apply_supplier_payment() from public, anon, authenticated;

drop trigger if exists trg_apply_supplier_payment on supplier_payments;
create trigger trg_apply_supplier_payment
after insert on supplier_payments
for each row execute function apply_supplier_payment();

insert into accounts_payable(company_id,supplier_id,purchase_id,concept,amount_total,due_date,status)
select p.company_id,p.supplier_id,p.id,p.concept,p.total,p.due_date,
  case when p.due_date is not null and p.due_date<current_date then 'OVERDUE' else 'OPEN' end
from purchases p
where p.payment_status in ('PENDING','PARTIAL') and p.total>0
on conflict (purchase_id) where purchase_id is not null do nothing;

grant select,insert,update,delete on accounts_payable to authenticated;
grant select,insert on supplier_payments to authenticated;
