create table if not exists suppliers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  name text not null,
  trade_name text,
  nit text,
  nrc text,
  contact_name text,
  phone text,
  email text,
  address text,
  supplier_type text not null default 'MATERIALS' check (supplier_type in ('MATERIALS','OUTSOURCED_SERVICE','TRANSPORT','UTILITIES','OTHER')),
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists suppliers_company_idx on suppliers(company_id,active,name);

create table if not exists purchases (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  supplier_id uuid references suppliers(id) on delete set null,
  number bigint generated by default as identity,
  purchase_date date not null default current_date,
  document_type text not null default 'INVOICE' check (document_type in ('INVOICE','CCF','TICKET','RECEIPT','OTHER')),
  document_number text,
  concept text not null,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  tax numeric(12,2) not null default 0 check (tax >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  payment_status text not null default 'PENDING' check (payment_status in ('PENDING','PARTIAL','PAID','CANCELLED')),
  due_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists purchases_company_idx on purchases(company_id,purchase_date desc,payment_status);

create table if not exists purchase_items (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  purchase_id uuid not null references purchases(id) on delete cascade,
  description text not null,
  category text not null default 'MATERIAL' check (category in ('MATERIAL','OUTSOURCED_SERVICE','FREIGHT','OTHER')),
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  unit_cost numeric(12,4) not null default 0 check (unit_cost >= 0),
  line_total numeric(12,2) generated always as (round((quantity * unit_cost)::numeric,2)) stored,
  internal_use boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists purchase_items_purchase_idx on purchase_items(purchase_id);

create table if not exists expenses (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  supplier_id uuid references suppliers(id) on delete set null,
  number bigint generated by default as identity,
  expense_date date not null default current_date,
  category text not null default 'OPERATING' check (category in ('RENT','UTILITIES','PAYROLL','TRANSPORT','MAINTENANCE','MARKETING','TAXES','OPERATING','OTHER')),
  concept text not null,
  amount numeric(12,2) not null check (amount > 0),
  payment_method text not null default 'CASH' check (payment_method in ('CASH','TRANSFER','CARD','CHECK','OTHER')),
  reference text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists expenses_company_idx on expenses(company_id,expense_date desc,category);

create table if not exists cash_accounts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  name text not null,
  account_type text not null default 'CASH' check (account_type in ('CASH','BANK','PETTY_CASH')),
  opening_balance numeric(12,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id,name)
);

create table if not exists cash_movements (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  cash_account_id uuid not null references cash_accounts(id) on delete cascade,
  movement_date timestamptz not null default now(),
  movement_type text not null check (movement_type in ('INCOME','EXPENSE','TRANSFER_IN','TRANSFER_OUT','ADJUSTMENT')),
  source_type text not null default 'MANUAL' check (source_type in ('MANUAL','CUSTOMER_PAYMENT','PURCHASE','EXPENSE','OTHER')),
  source_id uuid,
  concept text not null,
  amount numeric(12,2) not null check (amount > 0),
  reference text,
  notes text,
  created_at timestamptz not null default now()
);
create index if not exists cash_movements_company_idx on cash_movements(company_id,movement_date desc);
create index if not exists cash_movements_account_idx on cash_movements(cash_account_id,movement_date desc);

alter table suppliers enable row level security;
alter table purchases enable row level security;
alter table purchase_items enable row level security;
alter table expenses enable row level security;
alter table cash_accounts enable row level security;
alter table cash_movements enable row level security;

create policy "members manage suppliers" on suppliers for all to authenticated
using (exists(select 1 from company_members cm where cm.company_id=suppliers.company_id and cm.user_id=(select auth.uid())))
with check (exists(select 1 from company_members cm where cm.company_id=suppliers.company_id and cm.user_id=(select auth.uid())));
create policy "members manage purchases" on purchases for all to authenticated
using (exists(select 1 from company_members cm where cm.company_id=purchases.company_id and cm.user_id=(select auth.uid())))
with check (exists(select 1 from company_members cm where cm.company_id=purchases.company_id and cm.user_id=(select auth.uid())));
create policy "members manage purchase items" on purchase_items for all to authenticated
using (exists(select 1 from company_members cm where cm.company_id=purchase_items.company_id and cm.user_id=(select auth.uid())))
with check (exists(select 1 from company_members cm where cm.company_id=purchase_items.company_id and cm.user_id=(select auth.uid())));
create policy "members manage expenses" on expenses for all to authenticated
using (exists(select 1 from company_members cm where cm.company_id=expenses.company_id and cm.user_id=(select auth.uid())))
with check (exists(select 1 from company_members cm where cm.company_id=expenses.company_id and cm.user_id=(select auth.uid())));
create policy "members manage cash accounts" on cash_accounts for all to authenticated
using (exists(select 1 from company_members cm where cm.company_id=cash_accounts.company_id and cm.user_id=(select auth.uid())))
with check (exists(select 1 from company_members cm where cm.company_id=cash_accounts.company_id and cm.user_id=(select auth.uid())));
create policy "members manage cash movements" on cash_movements for all to authenticated
using (exists(select 1 from company_members cm where cm.company_id=cash_movements.company_id and cm.user_id=(select auth.uid())))
with check (exists(select 1 from company_members cm where cm.company_id=cash_movements.company_id and cm.user_id=(select auth.uid())));

grant select,insert,update,delete on suppliers,purchases,purchase_items,expenses,cash_accounts,cash_movements to authenticated;
grant usage,select on all sequences in schema public to authenticated;
