alter table public.inventory_items
  add column if not exists barcode text,
  add column if not exists qr_code text,
  add column if not exists subcategory text,
  add column if not exists brand text,
  add column if not exists model text,
  add column if not exists item_type text not null default 'MATERIAL',
  add column if not exists secondary_unit text,
  add column if not exists conversion_factor numeric(18,6) not null default 1,
  add column if not exists maximum_stock numeric(18,3) not null default 0,
  add column if not exists target_stock numeric(18,3) not null default 0,
  add column if not exists reorder_point numeric(18,3) not null default 0,
  add column if not exists safety_stock numeric(18,3) not null default 0,
  add column if not exists reserved_stock numeric(18,3) not null default 0,
  add column if not exists committed_stock numeric(18,3) not null default 0,
  add column if not exists damaged_stock numeric(18,3) not null default 0,
  add column if not exists blocked_stock numeric(18,3) not null default 0,
  add column if not exists in_transit_stock numeric(18,3) not null default 0,
  add column if not exists last_cost numeric(18,4) not null default 0,
  add column if not exists standard_cost numeric(18,4) not null default 0,
  add column if not exists replacement_cost numeric(18,4) not null default 0,
  add column if not exists supplier_id uuid references public.suppliers(id) on delete set null,
  add column if not exists warehouse_id uuid,
  add column if not exists location_id uuid,
  add column if not exists lot_tracking boolean not null default false,
  add column if not exists serial_tracking boolean not null default false,
  add column if not exists expiry_tracking boolean not null default false,
  add column if not exists abc_class text,
  add column if not exists last_movement_at timestamptz,
  add column if not exists deleted_at timestamptz;
create table if not exists public.inventory_warehouses(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,code text not null,name text not null,warehouse_type text not null default 'GENERAL',address text,responsible_name text,capacity numeric(18,3),active boolean not null default true,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,code));
create table if not exists public.inventory_locations(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,warehouse_id uuid not null references public.inventory_warehouses(id) on delete cascade,code text not null,zone text,aisle text,rack text,level text,bin text,capacity numeric(18,3),status text not null default 'AVAILABLE',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(warehouse_id,code));
alter table public.inventory_items drop constraint if exists inventory_items_warehouse_id_fkey; alter table public.inventory_items add constraint inventory_items_warehouse_id_fkey foreign key(warehouse_id) references public.inventory_warehouses(id) on delete set null;
alter table public.inventory_items drop constraint if exists inventory_items_location_id_fkey; alter table public.inventory_items add constraint inventory_items_location_id_fkey foreign key(location_id) references public.inventory_locations(id) on delete set null;
create table if not exists public.inventory_lots(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,warehouse_id uuid references public.inventory_warehouses(id) on delete set null,location_id uuid references public.inventory_locations(id) on delete set null,lot_number text not null,supplier_lot text,serial_number text,manufactured_at date,received_at date,expires_at date,quantity numeric(18,3) not null default 0,reserved_quantity numeric(18,3) not null default 0,unit_cost numeric(18,4) not null default 0,status text not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,inventory_item_id,lot_number,serial_number));
create table if not exists public.inventory_reservations(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,work_order_id uuid references public.work_orders(id) on delete cascade,warehouse_id uuid references public.inventory_warehouses(id) on delete set null,location_id uuid references public.inventory_locations(id) on delete set null,lot_id uuid references public.inventory_lots(id) on delete set null,quantity numeric(18,3) not null check(quantity>0),consumed_quantity numeric(18,3) not null default 0,status text not null default 'ACTIVE',priority text not null default 'NORMAL',expires_at timestamptz,notes text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory_counts(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,warehouse_id uuid references public.inventory_warehouses(id) on delete set null,code text not null,count_type text not null default 'CYCLE',status text not null default 'OPEN',started_at timestamptz not null default now(),completed_at timestamptz,notes text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),unique(company_id,code));
create table if not exists public.inventory_count_lines(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,inventory_count_id uuid not null references public.inventory_counts(id) on delete cascade,inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,location_id uuid references public.inventory_locations(id) on delete set null,lot_id uuid references public.inventory_lots(id) on delete set null,system_quantity numeric(18,3) not null default 0,counted_quantity numeric(18,3),difference numeric(18,3) generated always as(coalesce(counted_quantity,0)-system_quantity) stored,reason text,approved boolean not null default false,counted_at timestamptz,created_at timestamptz not null default now());
alter table public.inventory_movements add column if not exists warehouse_id uuid references public.inventory_warehouses(id) on delete set null,add column if not exists location_id uuid references public.inventory_locations(id) on delete set null,add column if not exists lot_id uuid references public.inventory_lots(id) on delete set null,add column if not exists reservation_id uuid references public.inventory_reservations(id) on delete set null,add column if not exists previous_stock numeric(18,3),add column if not exists resulting_stock numeric(18,3),add column if not exists document_type text,add column if not exists document_id uuid,add column if not exists movement_at timestamptz not null default now(),add column if not exists created_by uuid references auth.users(id) on delete set null,add column if not exists reversed_movement_id uuid references public.inventory_movements(id) on delete set null;
create index if not exists idx_inventory_items_company_stock on public.inventory_items(company_id,active,current_stock,minimum_stock); create index if not exists idx_inventory_items_company_sku on public.inventory_items(company_id,sku); create index if not exists idx_inventory_items_supplier on public.inventory_items(supplier_id); create index if not exists idx_inventory_movements_item_date on public.inventory_movements(inventory_item_id,movement_at desc); create index if not exists idx_inventory_movements_company_date on public.inventory_movements(company_id,movement_at desc); create index if not exists idx_inventory_reservations_order on public.inventory_reservations(work_order_id,status); create index if not exists idx_inventory_reservations_item on public.inventory_reservations(inventory_item_id,status); create index if not exists idx_inventory_lots_item_expiry on public.inventory_lots(inventory_item_id,expires_at,status);
alter table public.inventory_warehouses enable row level security; alter table public.inventory_locations enable row level security; alter table public.inventory_lots enable row level security; alter table public.inventory_reservations enable row level security; alter table public.inventory_counts enable row level security; alter table public.inventory_count_lines enable row level security;
do $$ declare t text; begin foreach t in array array['inventory_warehouses','inventory_locations','inventory_lots','inventory_reservations','inventory_counts','inventory_count_lines'] loop execute format('drop policy if exists %I on public.%I','company_members_manage_'||t,t); execute format('create policy %I on public.%I for all to authenticated using (public.is_company_member(company_id)) with check (public.is_company_member(company_id))','company_members_manage_'||t,t); end loop; end $$;
grant select,insert,update,delete on public.inventory_warehouses,public.inventory_locations,public.inventory_lots,public.inventory_reservations,public.inventory_counts,public.inventory_count_lines to authenticated;
create or replace function public.apply_inventory_movement() returns trigger language plpgsql set search_path='public' as $$ declare v_stock numeric(18,3);v_avg numeric(18,4);v_new_stock numeric(18,3);v_new_avg numeric(18,4);v_out boolean; begin select current_stock,average_cost into v_stock,v_avg from public.inventory_items where id=new.inventory_item_id and company_id=new.company_id for update; if not found then raise exception 'Inventory item does not belong to this company'; end if; v_out:=new.movement_type in('CONSUMPTION','ADJUST_OUT','SALE_OUT','TRANSFER_OUT','DAMAGE','LOSS','EXPIRY','SUPPLIER_RETURN','PRODUCTION_OUT','INSTALLATION_OUT'); new.previous_stock:=v_stock; if v_out then if new.quantity>v_stock then raise exception 'Insufficient stock: available %, requested %',v_stock,new.quantity; end if;v_new_stock:=v_stock-new.quantity;v_new_avg:=v_avg; else v_new_stock:=v_stock+new.quantity;if new.movement_type in('PURCHASE_IN','ADJUST_IN','RETURN','PRODUCTION_IN','TRANSFER_IN','INITIAL') and coalesce(new.unit_cost,0)>0 then v_new_avg:=case when v_new_stock>0 then((v_stock*v_avg)+(new.quantity*new.unit_cost))/v_new_stock else new.unit_cost end;else v_new_avg:=v_avg;end if;end if;new.resulting_stock:=v_new_stock;update public.inventory_items set current_stock=v_new_stock,average_cost=v_new_avg,last_cost=case when coalesce(new.unit_cost,0)>0 then new.unit_cost else last_cost end,last_movement_at=coalesce(new.movement_at,now()),updated_at=now() where id=new.inventory_item_id;return new;end;$$;
drop trigger if exists inventory_movement_apply on public.inventory_movements; drop trigger if exists apply_inventory_movement_trigger on public.inventory_movements; create trigger inventory_movement_apply before insert on public.inventory_movements for each row execute function public.apply_inventory_movement();
create or replace function public.refresh_inventory_reserved_stock(p_item uuid) returns void language sql security invoker set search_path='public' as $$ update public.inventory_items i set reserved_stock=coalesce((select sum(greatest(r.quantity-r.consumed_quantity,0)) from public.inventory_reservations r where r.inventory_item_id=i.id and r.status='ACTIVE'),0),updated_at=now() where i.id=p_item; $$;