create table if not exists deliveries (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade,
  work_order_id uuid references work_orders(id) on delete set null, client_id uuid references clients(id) on delete set null,
  number bigint generated by default as identity, status text not null default 'PENDING' check (status in ('PENDING','SCHEDULED','READY','DELIVERED','CANCELLED')),
  delivery_method text not null default 'PICKUP' check (delivery_method in ('PICKUP','DELIVERY','INSTALLATION')),
  scheduled_at timestamptz, delivered_at timestamptz, recipient_name text, recipient_document text, delivery_address text, notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists deliveries_work_order_uidx on deliveries(work_order_id) where work_order_id is not null;
create index if not exists deliveries_company_idx on deliveries(company_id,status,created_at desc);
create table if not exists accounts_receivable (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade,
  client_id uuid references clients(id) on delete set null, work_order_id uuid references work_orders(id) on delete set null, quote_id uuid references quotes(id) on delete set null,
  number bigint generated by default as identity, concept text not null, amount_total numeric(12,2) not null default 0 check (amount_total >= 0),
  amount_paid numeric(12,2) not null default 0 check (amount_paid >= 0), due_date date,
  status text not null default 'OPEN' check (status in ('OPEN','PARTIAL','PAID','OVERDUE','CANCELLED')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists ar_company_idx on accounts_receivable(company_id,status,due_date);
create unique index if not exists ar_work_order_uidx on accounts_receivable(work_order_id) where work_order_id is not null;
create table if not exists customer_payments (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade,
  receivable_id uuid not null references accounts_receivable(id) on delete cascade, client_id uuid references clients(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0), payment_method text not null default 'CASH' check (payment_method in ('CASH','TRANSFER','CARD','CHECK','OTHER')),
  reference text, paid_at timestamptz not null default now(), notes text, created_at timestamptz not null default now()
);
create index if not exists customer_payments_receivable_idx on customer_payments(receivable_id,paid_at desc);
alter table deliveries enable row level security; alter table accounts_receivable enable row level security; alter table customer_payments enable row level security;
create policy "members manage deliveries" on deliveries for all using (exists(select 1 from company_members cm where cm.company_id=deliveries.company_id and cm.user_id=auth.uid())) with check (exists(select 1 from company_members cm where cm.company_id=deliveries.company_id and cm.user_id=auth.uid()));
create policy "members manage receivables" on accounts_receivable for all using (exists(select 1 from company_members cm where cm.company_id=accounts_receivable.company_id and cm.user_id=auth.uid())) with check (exists(select 1 from company_members cm where cm.company_id=accounts_receivable.company_id and cm.user_id=auth.uid()));
create policy "members manage customer payments" on customer_payments for all using (exists(select 1 from company_members cm where cm.company_id=customer_payments.company_id and cm.user_id=auth.uid())) with check (exists(select 1 from company_members cm where cm.company_id=customer_payments.company_id and cm.user_id=auth.uid()));
create or replace function refresh_receivable_balance(target_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare v_paid numeric(12,2); v_total numeric(12,2); v_due date; begin
select coalesce(sum(amount),0) into v_paid from customer_payments where receivable_id=target_id;
select amount_total,due_date into v_total,v_due from accounts_receivable where id=target_id;
update accounts_receivable set amount_paid=v_paid,status=case when v_paid>=v_total then 'PAID' when v_paid>0 then 'PARTIAL' when v_due is not null and v_due<current_date then 'OVERDUE' else 'OPEN' end,updated_at=now() where id=target_id and status<>'CANCELLED'; end $$;
create or replace function customer_payment_refresh_trigger() returns trigger language plpgsql security definer set search_path=public as $$ begin perform refresh_receivable_balance(coalesce(new.receivable_id,old.receivable_id)); return coalesce(new,old); end $$;
drop trigger if exists trg_customer_payment_refresh on customer_payments;
create trigger trg_customer_payment_refresh after insert or update or delete on customer_payments for each row execute function customer_payment_refresh_trigger();