-- IDEALO BAR · evolución comercial: split, tips, ubicaciones, presentaciones, compras, delivery, tickets, analítica
alter table public.bar_payments add column if not exists bill_split_id uuid;
alter table public.bar_orders add column if not exists delivery_preparing_at timestamptz;
alter table public.bar_orders add column if not exists delivery_ready_at timestamptz;
alter table public.bar_orders add column if not exists delivery_out_at timestamptz;
alter table public.bar_orders add column if not exists delivery_delivered_at timestamptz;
alter table public.bar_settings add column if not exists auto_dte_on_paid boolean not null default true;
alter table public.bar_settings add column if not exists kitchen_printer_name text;
alter table public.bar_settings add column if not exists bar_printer_name text;
alter table public.bar_settings add column if not exists default_stock_location text not null default 'BAR';

create table if not exists public.bar_bill_splits(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,order_id uuid not null references public.bar_orders(id) on delete cascade,label text not null,split_type text not null default 'EQUAL' check(split_type in ('EQUAL','ITEMS','MANUAL')),amount numeric(12,2) not null check(amount>0),status text not null default 'OPEN' check(status in ('OPEN','PAID','CANCELLED')),paid_at timestamptz,created_by uuid default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists bar_bill_splits_order_idx on public.bar_bill_splits(order_id,status);
create table if not exists public.bar_bill_split_items(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,split_id uuid not null references public.bar_bill_splits(id) on delete cascade,order_item_id uuid not null references public.bar_order_items(id) on delete cascade,quantity numeric(12,3) not null check(quantity>0),amount numeric(12,2) not null check(amount>=0),created_at timestamptz not null default now(),unique(split_id,order_item_id));
create index if not exists bar_bill_split_items_item_idx on public.bar_bill_split_items(order_item_id);
alter table public.bar_payments drop constraint if exists bar_payments_bill_split_id_fkey;
alter table public.bar_payments add constraint bar_payments_bill_split_id_fkey foreign key(bill_split_id) references public.bar_bill_splits(id) on delete set null;
create index if not exists bar_payments_bill_split_idx on public.bar_payments(bill_split_id);
create table if not exists public.bar_tip_allocations(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,order_id uuid not null references public.bar_orders(id) on delete cascade,recipient_user_id uuid,source_payment_id uuid references public.bar_payments(id) on delete set null,method text not null default 'cash',amount numeric(12,2) not null check(amount>0),status text not null default 'EARNED' check(status in ('EARNED','PAID_OUT','VOID')),paid_out_at timestamptz,created_at timestamptz not null default now());
create index if not exists bar_tip_allocations_order_idx on public.bar_tip_allocations(order_id);
create index if not exists bar_tip_allocations_recipient_idx on public.bar_tip_allocations(recipient_user_id,created_at);
create table if not exists public.bar_inventory_location_stock(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,warehouse_id uuid references public.inventory_warehouses(id) on delete cascade,location_id uuid references public.inventory_locations(id) on delete cascade,location_kind text not null check(location_kind in ('WAREHOUSE','FRIDGE','BAR','OTHER')),quantity numeric(18,3) not null default 0 check(quantity>=0),updated_by uuid default auth.uid(),updated_at timestamptz not null default now(),unique(company_id,inventory_item_id,warehouse_id,location_id,location_kind));
create index if not exists bar_location_stock_item_idx on public.bar_inventory_location_stock(inventory_item_id);
create table if not exists public.bar_stock_transfers(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,inventory_item_id uuid not null references public.inventory_items(id),from_stock_id uuid not null references public.bar_inventory_location_stock(id),to_stock_id uuid not null references public.bar_inventory_location_stock(id),quantity numeric(18,3) not null check(quantity>0),reason text,created_by uuid default auth.uid(),created_at timestamptz not null default now());
create index if not exists bar_stock_transfers_item_idx on public.bar_stock_transfers(inventory_item_id,created_at);
create table if not exists public.bar_inventory_presentations(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,name text not null,code text,units_per_presentation numeric(18,3) not null check(units_per_presentation>0),purchase_cost numeric(14,4),sale_price numeric(14,4),preferred_supplier_id uuid references public.suppliers(id) on delete set null,is_purchase_default boolean not null default false,active boolean not null default true,created_by uuid default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,inventory_item_id,name));
create index if not exists bar_presentations_supplier_idx on public.bar_inventory_presentations(preferred_supplier_id);
create table if not exists public.bar_delivery_events(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,order_id uuid not null references public.bar_orders(id) on delete cascade,status text not null check(status in ('pending','preparing','ready','on_the_way','delivered','cancelled')),driver_name text,driver_phone text,notes text,created_by uuid default auth.uid(),created_at timestamptz not null default now());
create index if not exists bar_delivery_events_order_idx on public.bar_delivery_events(order_id,created_at);
create table if not exists public.bar_print_jobs(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,order_id uuid not null references public.bar_orders(id) on delete cascade,station text not null check(station in ('kitchen','bar','cashier')),ticket_type text not null default 'COMMAND' check(ticket_type in ('COMMAND','BILL','REPRINT')),payload jsonb not null,printer_name text,status text not null default 'PENDING' check(status in ('PENDING','PRINTED','FAILED','CANCELLED')),attempts integer not null default 0,printed_at timestamptz,created_by uuid default auth.uid(),created_at timestamptz not null default now());
create index if not exists bar_print_jobs_station_idx on public.bar_print_jobs(company_id,station,status,created_at);

alter table public.bar_bill_splits enable row level security; alter table public.bar_bill_split_items enable row level security; alter table public.bar_tip_allocations enable row level security; alter table public.bar_inventory_location_stock enable row level security; alter table public.bar_stock_transfers enable row level security; alter table public.bar_inventory_presentations enable row level security; alter table public.bar_delivery_events enable row level security; alter table public.bar_print_jobs enable row level security;
create policy bar_bill_splits_read on public.bar_bill_splits for select to authenticated using(public.erp_can_operate(company_id)); create policy bar_bill_splits_write on public.bar_bill_splits for all to authenticated using(public.erp_can_operate(company_id)) with check(public.erp_can_operate(company_id));
create policy bar_bill_split_items_read on public.bar_bill_split_items for select to authenticated using(public.erp_can_operate(company_id)); create policy bar_bill_split_items_write on public.bar_bill_split_items for all to authenticated using(public.erp_can_operate(company_id)) with check(public.erp_can_operate(company_id));
create policy bar_tip_allocations_read on public.bar_tip_allocations for select to authenticated using(public.erp_can_operate(company_id)); create policy bar_tip_allocations_write on public.bar_tip_allocations for all to authenticated using(public.erp_can_admin(company_id));
create policy bar_location_stock_read on public.bar_inventory_location_stock for select to authenticated using(public.erp_can_operate(company_id)); create policy bar_location_stock_write on public.bar_inventory_location_stock for all to authenticated using(public.erp_can_operate(company_id)) with check(public.erp_can_operate(company_id));
create policy bar_stock_transfers_read on public.bar_stock_transfers for select to authenticated using(public.erp_can_operate(company_id)); create policy bar_stock_transfers_write on public.bar_stock_transfers for insert to authenticated with check(public.erp_can_operate(company_id));
create policy bar_presentations_read on public.bar_inventory_presentations for select to authenticated using(public.erp_can_operate(company_id)); create policy bar_presentations_write on public.bar_inventory_presentations for all to authenticated using(public.erp_can_admin(company_id)) with check(public.erp_can_admin(company_id));
create policy bar_delivery_events_read on public.bar_delivery_events for select to authenticated using(public.erp_can_operate(company_id)); create policy bar_delivery_events_write on public.bar_delivery_events for insert to authenticated with check(public.erp_can_operate(company_id));
create policy bar_print_jobs_read on public.bar_print_jobs for select to authenticated using(public.erp_can_operate(company_id)); create policy bar_print_jobs_write on public.bar_print_jobs for all to authenticated using(public.erp_can_operate(company_id)) with check(public.erp_can_operate(company_id));
grant select,insert,update,delete on public.bar_bill_splits,public.bar_bill_split_items to authenticated; grant select,insert,update,delete on public.bar_tip_allocations to authenticated; grant select,insert,update on public.bar_inventory_location_stock to authenticated; grant select,insert on public.bar_stock_transfers to authenticated; grant select,insert,update,delete on public.bar_inventory_presentations to authenticated; grant select,insert on public.bar_delivery_events to authenticated; grant select,insert,update on public.bar_print_jobs to authenticated;

create or replace function public.bar_create_equal_splits(p_order_id uuid,p_parts integer) returns setof public.bar_bill_splits language plpgsql set search_path=public as $$ declare v_order public.bar_orders%rowtype; v_paid numeric; v_remaining numeric; v_base numeric; v_amount numeric; i int; begin select * into v_order from public.bar_orders where id=p_order_id for update; if not found then raise exception 'Pedido no encontrado.'; end if; if not public.bar_has_permission(v_order.company_id,'payment.take') and not public.bar_has_permission(v_order.company_id,'bill.request') then raise exception 'Tu rol no puede dividir cuentas.'; end if; if p_parts<2 or p_parts>50 then raise exception 'La cuenta se puede dividir entre 2 y 50 partes.'; end if; if v_order.status in ('paid','cancelled') then raise exception 'El pedido ya está cerrado.'; end if; if exists(select 1 from public.bar_bill_splits where order_id=p_order_id and status='OPEN') then raise exception 'Ya existen divisiones abiertas para este pedido.'; end if; select coalesce(sum(amount),0) into v_paid from public.bar_payments where order_id=p_order_id; v_remaining:=round(greatest(coalesce(v_order.total,0)-v_paid,0),2); if v_remaining<=0 then raise exception 'No hay saldo por dividir.'; end if; v_base:=trunc((v_remaining/p_parts)*100)/100; for i in 1..p_parts loop v_amount:=case when i=p_parts then round(v_remaining-v_base*(p_parts-1),2) else v_base end; insert into public.bar_bill_splits(company_id,order_id,label,split_type,amount) values(v_order.company_id,v_order.id,'Persona '||i,'EQUAL',v_amount); end loop; return query select * from public.bar_bill_splits where order_id=p_order_id and status='OPEN' order by created_at,id; end; $$;
create or replace function public.bar_create_item_split(p_order_id uuid,p_label text,p_allocations jsonb) returns public.bar_bill_splits language plpgsql set search_path=public as $$ declare v_order public.bar_orders%rowtype; v_entry jsonb; v_item public.bar_order_items%rowtype; v_qty numeric; v_used numeric; v_amount numeric:=0; v_split public.bar_bill_splits%rowtype; begin select * into v_order from public.bar_orders where id=p_order_id for update; if not found then raise exception 'Pedido no encontrado.'; end if; if not public.bar_has_permission(v_order.company_id,'payment.take') and not public.bar_has_permission(v_order.company_id,'bill.request') then raise exception 'Tu rol no puede dividir cuentas.'; end if; if jsonb_typeof(p_allocations)<>'array' or jsonb_array_length(p_allocations)=0 then raise exception 'Selecciona productos para la división.'; end if; for v_entry in select * from jsonb_array_elements(p_allocations) loop select * into v_item from public.bar_order_items where id=(v_entry->>'order_item_id')::uuid and order_id=p_order_id and status<>'cancelled' for update; if not found then raise exception 'Producto no válido en la división.'; end if; v_qty:=(v_entry->>'quantity')::numeric; if v_qty<=0 then raise exception 'Cantidad inválida.'; end if; select coalesce(sum(si.quantity),0) into v_used from public.bar_bill_split_items si join public.bar_bill_splits s on s.id=si.split_id where si.order_item_id=v_item.id and s.status<>'CANCELLED'; if v_used+v_qty>v_item.quantity then raise exception 'La cantidad asignada supera la cantidad del producto %.',v_item.item_name; end if; v_amount:=v_amount+round((coalesce(v_item.line_total,v_item.quantity*v_item.unit_price)/nullif(v_item.quantity,0))*v_qty,2); end loop; if v_amount<=0 then raise exception 'La división no tiene monto.'; end if; insert into public.bar_bill_splits(company_id,order_id,label,split_type,amount) values(v_order.company_id,p_order_id,coalesce(nullif(trim(p_label),''),'Cuenta parcial'),'ITEMS',v_amount) returning * into v_split; for v_entry in select * from jsonb_array_elements(p_allocations) loop select * into v_item from public.bar_order_items where id=(v_entry->>'order_item_id')::uuid; v_qty:=(v_entry->>'quantity')::numeric; insert into public.bar_bill_split_items(company_id,split_id,order_item_id,quantity,amount) values(v_order.company_id,v_split.id,v_item.id,v_qty,round((coalesce(v_item.line_total,v_item.quantity*v_item.unit_price)/nullif(v_item.quantity,0))*v_qty,2)); end loop; return v_split; end; $$;
create or replace function public.bar_take_split_payment(p_split_id uuid,p_method text,p_reference text default null) returns jsonb language plpgsql set search_path=public as $$ declare v_split public.bar_bill_splits%rowtype; v_result jsonb; v_payment uuid; begin select * into v_split from public.bar_bill_splits where id=p_split_id for update; if not found then raise exception 'División no encontrada.'; end if; if v_split.status<>'OPEN' then raise exception 'La división ya fue cerrada.'; end if; v_result:=public.bar_take_payment(v_split.order_id,p_method,v_split.amount,p_reference); v_payment:=(v_result->>'payment_id')::uuid; update public.bar_payments set bill_split_id=v_split.id where id=v_payment; update public.bar_bill_splits set status='PAID',paid_at=now(),updated_at=now() where id=v_split.id; return v_result||jsonb_build_object('split_id',v_split.id,'split_label',v_split.label); end; $$;

create or replace function public.bar_reconcile_tip_allocation() returns trigger language plpgsql security definer set search_path=public as $$ declare v_order public.bar_orders%rowtype; v_allocated numeric; v_paid_total numeric; v_target numeric; v_piece numeric; begin select * into v_order from public.bar_orders where id=new.order_id; if not found or coalesce(v_order.tip_total,0)<=0 or v_order.waiter_id is null then return new; end if; select coalesce(sum(amount),0) into v_allocated from public.bar_tip_allocations where order_id=v_order.id and status<>'VOID'; select coalesce(sum(amount),0) into v_paid_total from public.bar_payments where order_id=v_order.id; v_target:=case when coalesce(v_order.total,0)>0 then round(v_order.tip_total*least(v_paid_total/v_order.total,1),2) else 0 end; v_piece:=round(greatest(v_target-v_allocated,0),2); if v_piece>0 then insert into public.bar_tip_allocations(company_id,order_id,recipient_user_id,source_payment_id,method,amount) values(v_order.company_id,v_order.id,v_order.waiter_id,new.id,new.method,v_piece); end if; return new; end; $$;
drop trigger if exists bar_payment_tip_allocation on public.bar_payments; create trigger bar_payment_tip_allocation after insert on public.bar_payments for each row execute function public.bar_reconcile_tip_allocation();

create or replace function public.bar_initialize_location_stock(p_inventory_item_id uuid,p_warehouse_id uuid,p_location_id uuid,p_location_kind text,p_quantity numeric) returns public.bar_inventory_location_stock language plpgsql set search_path=public as $$ declare v_item public.inventory_items%rowtype; v_total numeric; v_row public.bar_inventory_location_stock%rowtype; v_kind text:=upper(trim(p_location_kind)); begin select * into v_item from public.inventory_items where id=p_inventory_item_id and active=true for update; if not found then raise exception 'Insumo no encontrado.'; end if; if not public.bar_has_permission(v_item.company_id,'inventory.manage') and not public.erp_can_admin(v_item.company_id) then raise exception 'Tu rol no puede distribuir existencias por ubicación.'; end if; if p_quantity<0 then raise exception 'Cantidad inválida.'; end if; if v_kind not in ('WAREHOUSE','FRIDGE','BAR','OTHER') then raise exception 'Tipo de ubicación inválido.'; end if; if p_warehouse_id is not null and not exists(select 1 from public.inventory_warehouses where id=p_warehouse_id and company_id=v_item.company_id and active=true) then raise exception 'Bodega inválida.'; end if; if p_location_id is not null and not exists(select 1 from public.inventory_locations where id=p_location_id and company_id=v_item.company_id and active=true) then raise exception 'Ubicación inválida.'; end if; select coalesce(sum(quantity),0) into v_total from public.bar_inventory_location_stock where company_id=v_item.company_id and inventory_item_id=v_item.id; if v_total+p_quantity>v_item.current_stock then raise exception 'La distribución por ubicaciones no puede superar el stock total (%).',v_item.current_stock; end if; insert into public.bar_inventory_location_stock(company_id,inventory_item_id,warehouse_id,location_id,location_kind,quantity) values(v_item.company_id,v_item.id,p_warehouse_id,p_location_id,v_kind,p_quantity) returning * into v_row; return v_row; end; $$;
create or replace function public.bar_transfer_location_stock(p_from_stock_id uuid,p_to_stock_id uuid,p_quantity numeric,p_reason text default null) returns uuid language plpgsql set search_path=public as $$ declare v_from public.bar_inventory_location_stock%rowtype; v_to public.bar_inventory_location_stock%rowtype; v_id uuid; begin if p_quantity<=0 then raise exception 'Cantidad inválida.'; end if; select * into v_from from public.bar_inventory_location_stock where id=p_from_stock_id for update; select * into v_to from public.bar_inventory_location_stock where id=p_to_stock_id for update; if v_from.id is null or v_to.id is null or v_from.company_id<>v_to.company_id or v_from.inventory_item_id<>v_to.inventory_item_id then raise exception 'Las ubicaciones no corresponden al mismo insumo.'; end if; if not public.bar_has_permission(v_from.company_id,'inventory.manage') and not public.erp_can_admin(v_from.company_id) then raise exception 'Tu rol no puede trasladar inventario.'; end if; if v_from.quantity<p_quantity then raise exception 'Existencia insuficiente en la ubicación origen.'; end if; update public.bar_inventory_location_stock set quantity=quantity-p_quantity,updated_by=auth.uid(),updated_at=now() where id=v_from.id; update public.bar_inventory_location_stock set quantity=quantity+p_quantity,updated_by=auth.uid(),updated_at=now() where id=v_to.id; insert into public.bar_stock_transfers(company_id,inventory_item_id,from_stock_id,to_stock_id,quantity,reason) values(v_from.company_id,v_from.inventory_item_id,v_from.id,v_to.id,p_quantity,nullif(trim(coalesce(p_reason,'')),'')) returning id into v_id; return v_id; end; $$;

create or replace function public.bar_prepare_purchase_by_presentation(p_presentation_id uuid,p_presentations numeric) returns uuid language plpgsql set search_path=public as $$ declare v_pres public.bar_inventory_presentations%rowtype; v_item public.inventory_items%rowtype; v_qty numeric; v_purchase uuid; begin select * into v_pres from public.bar_inventory_presentations where id=p_presentation_id and active=true; if not found then raise exception 'Presentación no encontrada.'; end if; select * into v_item from public.inventory_items where id=v_pres.inventory_item_id for update; if not public.bar_has_permission(v_pres.company_id,'inventory.manage') and not public.erp_can_admin(v_pres.company_id) then raise exception 'Tu rol no puede preparar compras.'; end if; if p_presentations<=0 then raise exception 'Cantidad inválida.'; end if; v_qty:=p_presentations*v_pres.units_per_presentation; if v_pres.preferred_supplier_id is not null and v_item.supplier_id is distinct from v_pres.preferred_supplier_id then update public.inventory_items set supplier_id=v_pres.preferred_supplier_id where id=v_item.id; end if; v_purchase:=public.create_replenishment_purchase(v_item.id,v_qty); update public.purchases set notes=concat_ws(' · ',notes,'IDEALO BAR: '||p_presentations||' x '||v_pres.name||' = '||v_qty||' '||v_item.unit) where id=v_purchase; return v_purchase; end; $$;

create or replace function public.bar_update_fulfillment_status(p_order_id uuid,p_status text) returns public.bar_orders language plpgsql set search_path=public as $$ declare v_order public.bar_orders%rowtype; v_status text; begin select * into v_order from public.bar_orders where id=p_order_id for update; if not found then raise exception 'Pedido no encontrado.'; end if; if not public.bar_has_permission(v_order.company_id,'delivery.manage') and not public.erp_can_admin(v_order.company_id) then raise exception 'Tu rol no puede actualizar delivery.'; end if; if v_order.order_type<>'delivery' then raise exception 'Este pedido no es delivery.'; end if; v_status:=lower(trim(coalesce(p_status,''))); if v_status not in ('pending','preparing','ready','on_the_way','delivered','cancelled') then raise exception 'Estado de delivery inválido.'; end if; update public.bar_orders set fulfillment_status=v_status,delivery_preparing_at=case when v_status='preparing' and delivery_preparing_at is null then now() else delivery_preparing_at end,delivery_ready_at=case when v_status='ready' and delivery_ready_at is null then now() else delivery_ready_at end,delivery_out_at=case when v_status='on_the_way' and delivery_out_at is null then now() else delivery_out_at end,delivery_delivered_at=case when v_status='delivered' and delivery_delivered_at is null then now() else delivery_delivered_at end where id=v_order.id returning * into v_order; insert into public.bar_delivery_events(company_id,order_id,status,driver_name,driver_phone) values(v_order.company_id,v_order.id,v_status,v_order.driver_name,v_order.driver_phone); insert into public.bar_order_events(company_id,order_id,event_type,details) values(v_order.company_id,v_order.id,'FULFILLMENT_STATUS',jsonb_build_object('status',v_status)); return v_order; end; $$;
create or replace function public.bar_queue_station_tickets(p_order_id uuid) returns integer language plpgsql set search_path=public as $$ declare v_order public.bar_orders%rowtype; v_station text; v_items jsonb; v_printer text; v_count int:=0; begin select * into v_order from public.bar_orders where id=p_order_id; if not found then raise exception 'Pedido no encontrado.'; end if; if not public.bar_has_permission(v_order.company_id,'order.send') and not public.erp_can_admin(v_order.company_id) then raise exception 'Sin permiso para generar comandas.'; end if; foreach v_station in array array['kitchen','bar'] loop select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',item_name,'quantity',quantity,'notes',notes,'seat',seat_number) order by created_at),'[]'::jsonb) into v_items from public.bar_order_items where order_id=p_order_id and station=v_station and status='sent'; if jsonb_array_length(v_items)>0 then select case when v_station='kitchen' then kitchen_printer_name else bar_printer_name end into v_printer from public.bar_settings where company_id=v_order.company_id; insert into public.bar_print_jobs(company_id,order_id,station,ticket_type,payload,printer_name) values(v_order.company_id,v_order.id,v_station,'COMMAND',jsonb_build_object('order_code',v_order.order_code,'order_type',v_order.order_type,'table_id',v_order.table_id,'customer',v_order.customer_name,'notes',v_order.notes,'items',v_items),v_printer); v_count:=v_count+1; end if; end loop; return v_count; end; $$;
create or replace function public.bar_send_order(p_order_id uuid) returns public.bar_orders language plpgsql set search_path=public as $$ declare v_order public.bar_orders%rowtype; v_rows int; begin select * into v_order from public.bar_orders where id=p_order_id for update; if not found then raise exception 'Pedido no encontrado.'; end if; if not public.bar_has_permission(v_order.company_id,'order.send') then raise exception 'Tu rol no puede enviar comandas.'; end if; if v_order.status in ('paid','cancelled') then raise exception 'El pedido ya está cerrado.'; end if; update public.bar_order_items set status='sent' where order_id=v_order.id and status='new'; get diagnostics v_rows=row_count; if v_rows=0 then raise exception 'No hay productos nuevos para enviar.'; end if; perform public.bar_queue_station_tickets(v_order.id); select * into v_order from public.bar_orders where id=p_order_id; insert into public.bar_order_events(company_id,order_id,event_type,details) values(v_order.company_id,v_order.id,'ORDER_SENT',jsonb_build_object('items_sent',v_rows)); return v_order; end; $$;
create or replace function public.bar_advanced_profitability(p_company_id uuid,p_from date default current_date,p_to date default current_date) returns jsonb language plpgsql stable set search_path=public as $$ declare v_result jsonb; begin if not public.erp_can_read_finance(p_company_id) then raise exception 'Sin acceso financiero.'; end if; select jsonb_build_object('summary',jsonb_build_object('sales',coalesce(sum(o.total),0),'discounts',coalesce(sum(o.discount_total),0),'tips',coalesce(sum(o.tip_total),0),'orders',count(*),'avg_ticket',coalesce(avg(o.total),0)),'by_hour',(select coalesce(jsonb_agg(x order by (x->>'hour')::int),'[]'::jsonb) from (select jsonb_build_object('hour',extract(hour from closed_at at time zone 'America/El_Salvador')::int,'sales',sum(total),'orders',count(*)) x from public.bar_orders where company_id=p_company_id and status='paid' and (closed_at at time zone 'America/El_Salvador')::date between p_from and p_to group by 1) q),'tips_by_waiter',(select coalesce(jsonb_agg(x order by (x->>'tips')::numeric desc),'[]'::jsonb) from (select jsonb_build_object('user_id',recipient_user_id,'tips',sum(amount),'count',count(*)) x from public.bar_tip_allocations where company_id=p_company_id and status='EARNED' and (created_at at time zone 'America/El_Salvador')::date between p_from and p_to group by recipient_user_id) q),'losses',(select coalesce(sum(estimated_cost),0) from public.bar_inventory_events where company_id=p_company_id and event_type in ('WASTE','DAMAGE') and (created_at at time zone 'America/El_Salvador')::date between p_from and p_to),'courtesies',(select coalesce(sum(estimated_cost),0) from public.bar_inventory_events where company_id=p_company_id and event_type='COURTESY' and (created_at at time zone 'America/El_Salvador')::date between p_from and p_to)) into v_result from public.bar_orders o where o.company_id=p_company_id and o.status='paid' and (o.closed_at at time zone 'America/El_Salvador')::date between p_from and p_to; return coalesce(v_result,'{}'::jsonb); end; $$;
grant execute on function public.bar_create_equal_splits(uuid,integer) to authenticated; grant execute on function public.bar_create_item_split(uuid,text,jsonb) to authenticated; grant execute on function public.bar_take_split_payment(uuid,text,text) to authenticated; grant execute on function public.bar_initialize_location_stock(uuid,uuid,uuid,text,numeric) to authenticated; grant execute on function public.bar_transfer_location_stock(uuid,uuid,numeric,text) to authenticated; grant execute on function public.bar_prepare_purchase_by_presentation(uuid,numeric) to authenticated; grant execute on function public.bar_queue_station_tickets(uuid) to authenticated; grant execute on function public.bar_advanced_profitability(uuid,date,date) to authenticated;