create table if not exists finished_products (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade,
  name text not null, category text, description text, unit text not null default 'unidad',
  sale_price numeric(12,2) not null default 0 check (sale_price >= 0), estimated_minutes integer,
  active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists finished_products_company_idx on finished_products(company_id, active, name);
create table if not exists quotes (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade,
  client_id uuid references clients(id) on delete set null, number bigint generated by default as identity,
  status text not null default 'DRAFT' check (status in ('DRAFT','SENT','APPROVED','REJECTED','EXPIRED','CONVERTED')),
  valid_until date, notes text, subtotal numeric(12,2) not null default 0, discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists quotes_company_idx on quotes(company_id, created_at desc);
create table if not exists quote_items (
  id uuid primary key default gen_random_uuid(), quote_id uuid not null references quotes(id) on delete cascade,
  product_id uuid references finished_products(id) on delete set null, description text not null,
  quantity numeric(12,2) not null default 1 check (quantity > 0), unit text not null default 'unidad',
  unit_price numeric(12,2) not null default 0, discount numeric(12,2) not null default 0, line_total numeric(12,2) not null default 0,
  sort_order integer not null default 0
);
create table if not exists work_orders (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade,
  quote_id uuid references quotes(id) on delete set null, client_id uuid references clients(id) on delete set null,
  number bigint generated by default as identity, status text not null default 'PENDING' check (status in ('PENDING','DESIGN','APPROVAL','PRODUCTION','READY','DELIVERED','CANCELLED')),
  title text not null, due_at timestamptz, production_notes text, total numeric(12,2) not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists work_order_items (
  id uuid primary key default gen_random_uuid(), work_order_id uuid not null references work_orders(id) on delete cascade,
  product_id uuid references finished_products(id) on delete set null, description text not null, quantity numeric(12,2) not null default 1,
  unit text not null default 'unidad', unit_price numeric(12,2) not null default 0, line_total numeric(12,2) not null default 0,
  specifications text, sort_order integer not null default 0
);
alter table finished_products enable row level security; alter table quotes enable row level security; alter table quote_items enable row level security; alter table work_orders enable row level security; alter table work_order_items enable row level security;
create policy "members manage finished products" on finished_products for all using (exists(select 1 from company_members cm where cm.company_id=finished_products.company_id and cm.user_id=auth.uid())) with check (exists(select 1 from company_members cm where cm.company_id=finished_products.company_id and cm.user_id=auth.uid()));
create policy "members manage quotes" on quotes for all using (exists(select 1 from company_members cm where cm.company_id=quotes.company_id and cm.user_id=auth.uid())) with check (exists(select 1 from company_members cm where cm.company_id=quotes.company_id and cm.user_id=auth.uid()));
create policy "members manage quote items" on quote_items for all using (exists(select 1 from quotes q join company_members cm on cm.company_id=q.company_id where q.id=quote_items.quote_id and cm.user_id=auth.uid())) with check (exists(select 1 from quotes q join company_members cm on cm.company_id=q.company_id where q.id=quote_items.quote_id and cm.user_id=auth.uid()));
create policy "members manage work orders" on work_orders for all using (exists(select 1 from company_members cm where cm.company_id=work_orders.company_id and cm.user_id=auth.uid())) with check (exists(select 1 from company_members cm where cm.company_id=work_orders.company_id and cm.user_id=auth.uid()));
create policy "members manage work order items" on work_order_items for all using (exists(select 1 from work_orders w join company_members cm on cm.company_id=w.company_id where w.id=work_order_items.work_order_id and cm.user_id=auth.uid())) with check (exists(select 1 from work_orders w join company_members cm on cm.company_id=w.company_id where w.id=work_order_items.work_order_id and cm.user_id=auth.uid()));