alter table public.internal_income_records
  add column if not exists receipt_no bigint generated by default as identity;

create unique index if not exists internal_income_records_receipt_no_uidx
  on public.internal_income_records(receipt_no)
  where receipt_no is not null;
