import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const read=path=>fs.readFileSync(new URL(path,import.meta.url),'utf8')
const index=read('../index.js')
const migration=read('../../../../supabase/migrations/0046_saas_atomic_billing_and_plan_requests.sql')
const gate=read('../../../../supabase/migrations/0047_saas_operational_rls_gate.sql')
const cleanup=read('../../../../supabase/migrations/0048_saas_security_advisor_cleanup.sql')
const reminderCron=read('../../../../supabase/migrations/0049_saas_commercial_reminder_cron.sql')
const payment=read('../admin/saas-payment-service.js')
const portal=read('./customer-portal-service.js')
const planChanges=read('../admin/saas-plan-change-service.js')
const safeSubscription=read('../admin/saas-subscription-admin-service.js')
const webPortal=read('../../../web/src/SaasCustomerAccountHost.jsx')
const mobilePlanGuard=read('../../../web/src/MobileSaasPlanGuard.jsx')
const mobileRuntime=read('../../../web/src/MobileRuntimeGuard.jsx')
test('cobro SaaS es atómico, idempotente y genera comprobante',()=>{assert.match(migration,/saas_record_payment_atomic/);assert.match(migration,/for update/);assert.match(migration,/idempotency_key/);assert.match(migration,/receipt_number/);assert.match(payment,/saas_record_payment_atomic/);assert.match(payment,/createHash/);assert.match(payment,/randomUUID/)})
test('pago mensual reactiva y extiende sin perder días vigentes',()=>{assert.match(migration,/greatest\(v_now,coalesce\(v_sub\.current_period_end,v_now\)\)/);assert.match(migration,/status='active'/);assert.match(migration,/current_period_end=v_start\+interval '30 days'/);assert.match(migration,/status='dismissed'/)})
test('compatibilidad del panel no duplica renovación ya aplicada por el cobro atómico',()=>{assert.match(safeSubscription,/wasJustRenewedByMonthlyPayment/);assert.match(safeSubscription,/paymentAge>30000/);assert.ok(safeSubscription.includes("String(event.metadata?.charge_type||'')!=='monthly'"));assert.match(safeSubscription,/renewal_already_applied:true/)})
test('portal del cliente expone cuenta, avisos, onboarding y cambio de plan',()=>{assert.match(index,/\/api\/saas\/account/);assert.match(index,/\/api\/saas\/plan-change/);assert.match(portal,/getCustomerSaasAccount/);assert.match(portal,/requestPlanChange/);assert.match(portal,/COMPANY_ADMIN_REQUIRED/);assert.match(portal,/saas_payment_reminders/);assert.match(portal,/onboardingSteps/);assert.match(portal,/DUE_7/);assert.match(portal,/SUSPENDED/);assert.match(webPortal,/\/mi-cuenta/);assert.match(webPortal,/Historial de pagos/);assert.match(webPortal,/Onboarding de la empresa/);assert.match(webPortal,/notifications/);assert.match(reminderCron,/saas-commercial-reminders/);assert.match(reminderCron,/saas_refresh_commercial_lifecycle/)})
test('administrador puede aprobar o rechazar cambios con control de usuarios',()=>{assert.match(index,/\/api\/admin\/saas\/plan-changes/);assert.match(planChanges,/PLAN_USER_LIMIT_CONFLICT/);assert.match(planChanges,/approved/);assert.match(planChanges,/rejected/);assert.match(migration,/uq_saas_plan_change_pending/);assert.match(index,/updateSaasSubscriptionSafely/);assert.match(safeSubscription,/PLAN_USER_LIMIT_CONFLICT/)})
test('tablas sensibles de solicitudes no quedan expuestas a usuarios normales',()=>{assert.match(migration,/enable row level security/);assert.match(migration,/revoke all on public\.saas_plan_change_requests from anon, authenticated/);assert.match(migration,/revoke all on function public\.saas_record_payment_atomic/);assert.match(migration,/grant execute on function public\.saas_record_payment_atomic[^;]+service_role,postgres/s);assert.match(cleanup,/security invoker/);assert.match(cleanup,/saas_payment_reminders_no_direct_access/);assert.match(cleanup,/saas_plan_change_requests_no_direct_access/)})
test('membresía suspendida se bloquea también en RLS del ERP',()=>{assert.match(gate,/saas_company_operational_access/);assert.match(gate,/status in \('trial','active'\)/);assert.match(gate,/status='past_due'/);assert.match(gate,/create policy saas_operational_gate/);for(const table of ['clients','finished_products','quotes','work_orders','inventory_items','suppliers','purchases','expenses','cash_accounts','customer_payments','dte_documents'])assert.ok(gate.includes(`'${table}'`),`falta gate para ${table}`)})
test('Android e iPhone quedan ligados al plan Empresarial',()=>{assert.match(mobilePlanGuard,/mobile_apps_enabled!==true/);assert.match(mobilePlanGuard,/App móvil no incluida/);assert.match(mobilePlanGuard,/\/api\/saas\/access/);assert.match(mobileRuntime,/MobileSaasPlanGuard/);assert.match(mobileRuntime,/<MobileSaasPlanGuard\/>/)})
